SaffronCity_CopycatsHouse_1F_Frlg_MapScripts::
        .byte 0


SaffronCity_CopycatsHouse_1F_Frlg_EventScript_Man::
        msgbox SaffronCity_CopycatsHouse_1F_Frlg_Text_Man, MSGBOX_NPC
        end

SaffronCity_CopycatsHouse_1F_Frlg_EventScript_Woman::
        msgbox SaffronCity_CopycatsHouse_1F_Frlg_Text_Woman, MSGBOX_NPC
        end

SaffronCity_CopycatsHouse_1F_Frlg_EventScript_Chansey::
        msgbox SaffronCity_CopycatsHouse_1F_Frlg_Text_Chansey, MSGBOX_NPC
        end


SaffronCity_CopycatsHouse_1F_Frlg_Text_Man:
        .string "Our daughter loves copying people.\p"
        .string "Don't encourage her.$"

SaffronCity_CopycatsHouse_1F_Frlg_Text_Woman:
        .string "She's upstairs if you're looking\n"
        .string "for her.$"

SaffronCity_CopycatsHouse_1F_Frlg_Text_Chansey:
        .string "CHANSEY: Chaansey!$"
