voice_group bw_main_6                                                                                        @ Num | Substitute Instrument     |  Original BW
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 43, 76, 103, 216                    @ 000 | RSE Whistle               |  voice_directsound 60, 0, DirectSoundWaveData_bw_sambawhistlec4_route2, 255, 0, 255, 171
	voice_keysplit_all voicegroup_allkeysplit_bw_drum_5                                                      @ 001 | Drum                      |  voice_keysplit_all voicegroup285 @ drums 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 002 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 003 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 004 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 128, 249, 0, 188            @ 005 | RSE Electric Piano        |  voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia2_c4_22, 255, 248, 0, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 006 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 007 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 008 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 009 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 010 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 011 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 012 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 013 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 014 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 015 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 0                              @ 016 | HGSS Synth Snare          |  voice_directsound 60, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 017 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c4_16, 255, 0, 255, 205                             @ 018 | DPPt Organ Part           |  voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c4_16, 255, 0, 255, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 019 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                       @ 020 | HGSS Sawtooth             |  voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 021 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 022 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 023 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 024 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 025 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 026 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 027 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 028 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_dp_distortion_guitar_2             @ 029 | HGSS Distortion Guitar 1  |  voice_keysplit voicegroup210, KeySplitTable21    @ distortion guitar 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 030 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 031 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 032 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 033 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 034 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 035 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 036 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 037 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 1, 255, 192                         @ 038 | HGSS Synth Bass           |  voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 1, 255, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220                         @ 039 | HGSS Synth Bass           |  voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                     @ 040 | HGSS Violin               |  voice_keysplit voicegroup256, KeySplitTable46    @ violin
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 041 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 042 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 043 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 044 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 045 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 046 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani              @ 047 | HGSS Timpani              |  voice_keysplit voicegroup216, KeySplitTable27    @ timpani 1
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                   @ 048 | HGSS Strings              |  voice_keysplit voicegroup255, KeySplitTable60    @ strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 049 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 050 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c3_16, 224, 242, 101, 220                        @ 051 | DP Timpani                |  voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c3_16, 255, 250, 0, 210
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 052 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 053 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 054 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 055 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 056 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone                           @ 057 | HGSS Trombones            |  voice_keysplit voicegroup220, KeySplitTable30    @ trombone (lowest split never used)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 058 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 059 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn                           @ 060 | HGSS French Horns         |  voice_keysplit voicegroup223, KeySplitTable9     @ french horns
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 061 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 062 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 063 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 064 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 065 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 066 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 067 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 068 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 069 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 070 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 071 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 072 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 073 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 074 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 075 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                         @ 076 | HGSS Tenor Choir          |  voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171                       @ 077 | HGSS Soprano Choir        |  voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192                         @ 078 | HGSS Whistle              |  voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 079 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                  @ 080 | ---                       |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 0, 255, 205                         @ 081 | HGSS Orchestra Hit Minor  |  voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 0, 255, 205
