voice_group dppt_main                                                                            @ Num | Type | Instrument
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16                @ 000 | Direct | DP Reverse Cymbal
	voice_keysplit_all voicegroup_allkeysplit_dppt_drum_1				                         @ 001 | Drum | DP Drum 1
	voice_keysplit voicegroup_keysplit_dp_piano_1, keysplit_dp_piano_1                           @ 002 | Direct | DP Piano 1
	voice_keysplit voicegroup_keysplit_dp_piano_2, keysplit_dp_piano_2                           @ 003 | Direct | DP (Low Ocvate)
	voice_keysplit voicegroup_keysplit_dp_electric_piano_1, keysplit_dp_electric_piano_1         @ 004 | Direct | DP Electric Piano 1
	voice_keysplit voicegroup_keysplit_dp_electric_piano_2, keysplit_dp_electric_piano_2_rhodes  @ 005 | Direct | DP Electric Piano 2
	voice_keysplit_all voicegroup_allkeysplit_dppt_drum_2				                         @ 006 | Drum | DP Drum 2
	voice_keysplit voicegroup_keysplit_dp_clavinet, keysplit_dp_clavinet                         @ 007 | Direct | DP Clavinet
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192                       @ 008 | Direct | Sampled Noise 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_glocken_c6_16, 255, 247, 0, 208              @ 009 | Direct | DP Glockenspiel
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 205                @ 010 | Direct | Sampled Square Wave 50% 1
	voice_keysplit voicegroup_keysplit_dp_vibraphone, keysplit_dp_vibraphone                     @ 011 | Direct | DP Vibraphone
	voice_keysplit voicegroup_keysplit_dp_marimba, keysplit_dp_marimba                           @ 012 | Direct | DP Marimba
	voice_keysplit voicegroup_keysplit_dp_xylophone, keysplit_dp_xylophone                       @ 013 | Direct | DP Xylophone
	voice_keysplit voicegroup_keysplit_dp_tubular_bell, keysplit_dp_tubular_bell                 @ 014 | Direct | DP Tubular Bell
	voice_keysplit voicegroup_keysplit_dp_trinity_piano, keysplit_dp_trinity_piano               @ 015 | Direct | DP Trinity Piano
	voice_keysplit_all voicegroup_allkeysplit_dppt_drum_3				                         @ 016 | Drum | DP Drum 3 (Synth Kick + Snare)
	voice_keysplit voicegroup_keysplit_dp_rotary_organ, keysplit_dp_rotary_organ                 @ 017 | Direct | DP Rotary Organ
	voice_keysplit voicegroup_keysplit_dp_straight_organ, keysplit_dp_straight_organ             @ 018 | Direct | DP Straight Organ
	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 175, 235, 171               @ 019 | Direct | DP Organ
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 200, 255, 171           @ 020 | Direct | DP Sawtooth
	voice_keysplit voicegroup_keysplit_dp_accordion, keysplit_dp_accordion                       @ 021 | Direct | DP Accordion
	voice_directsound 60, 0, DirectSoundWaveData_dp_harmonica_c3_16, 67, 247, 191, 171           @ 022 | Direct | DP Harmonica
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretnoise60, 255, 0, 255, 16                 @ 023 | Direct | DP Fret Noise
	voice_keysplit voicegroup_keysplit_dp_accoustic_guitar, keysplit_dp_accoustic_guitar         @ 024 | Direct | DP Acoustic Guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_bluesgt_a2_16, 255, 255, 227, 208            @ 025 | Direct | DP Blues Guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_eternaguitar36, 255, 253, 159, 208           @ 026 | Direct | DP Eterna Guitar
	voice_keysplit voicegroup_keysplit_dp_clean_guitar, keysplit_dp_clean_guitar                 @ 027 | Direct | DP Clean Guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32           @ 028 | Direct | DP Wind Effect (Spear Pillar)
	voice_keysplit voicegroup_keysplit_dp_distortion_guitar_1, keysplit_dp_distortion_guitar_1   @ 029 | Direct | DP Distortion Guitar 1
	voice_keysplit voicegroup_keysplit_dp_power_guitar, keysplit_dp_power_guitar                 @ 030 | Direct | DP Power Guitar
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0                  @ 031 | Direct | DP Sample Square 50% 2
	voice_keysplit voicegroup_keysplit_dp_wood_bass_1, keysplit_dp_wood_bass                     @ 032 | Direct | DP Upright Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_sting_bass_e1_16, 255, 251, 0, 208           @ 033 | Direct | DP Sting Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_pickbass_e1_16, 255, 251, 0, 208             @ 034 | Direct | DP Pick Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretlessbass_d1_16, 255, 0, 255, 196         @ 035 | Direct | DP Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_g1_16, 255, 0, 255, 222             @ 036 | Direct | DP Slap Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 216             @ 037 | Direct | DP Slap Bass 2
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 196            @ 038 | Direct | DP Synth Bass 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 222             @ 039 | Direct | DP Synth Bass 2
	voice_keysplit voicegroup_keysplit_dp_violin, keysplit_dp_violin                             @ 040 | Direct | DP Violin
	voice_directsound 60, 0, DirectSoundWaveData_dp_oct_g3_16, 255, 235, 255, 212                @ 041 | Direct | DP Guitar
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96                  @ 042 | Direct | Sampled Square Wave 50% 3
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 37, 244, 155, 226                 @ 043 | Direct | DP Wind Effect
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 37, 255, 0, 246                   @ 044 | Direct | DP Explosion Effect
	voice_keysplit voicegroup_keysplit_dp_pizzicato, keysplit_dp_pizzicato_music_box             @ 045 | Direct | DP Pizzicato
	voice_keysplit voicegroup_keysplit_dp_harp, keysplit_dp_harp                                 @ 046 | Direct | DP Harp
	voice_keysplit voicegroup_keysplit_dp_timpani_1, keysplit_dp_timpani                         @ 047 | Direct | DP Timpani 1
	voice_keysplit voicegroup_keysplit_dp_strings, keysplit_dp_strings                           @ 048 | Direct | DP Strings
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlow_cs2_16, 255, 200, 255, 196            @ 049 | Direct | DP ???
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlowbra_b2_16, 255, 200, 255, 226          @ 050 | Direct | DP ???
	voice_keysplit voicegroup_keysplit_dp_timpani_2, keysplit_dp_timpani                         @ 051 | Direct | DP Timpani 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220                 @ 052 | Direct | DP Sampled Square Wave 50% 4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171           @ 053 | Direct | DP Sampled Square Wave | shift up by 1 octave
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 150, 0, 255, 0                 @ 054 | Direct | DP Bubble Effect
	voice_directsound 60, 0, DirectSoundWaveData_dp_octhit_c2_16, 255, 200, 255, 222             @ 055 | Direct | DP Orchestral Hit
	voice_keysplit voicegroup_keysplit_dp_trumpet_1, keysplit_dp_trumpet                         @ 056 | Direct | DP Trumpets 1
	voice_keysplit voicegroup_keysplit_dp_trombone, keysplit_dp_trombone                         @ 057 | Direct | DP Trombones
	voice_keysplit voicegroup_keysplit_dp_tuba, keysplit_dp_tuba                                 @ 058 | Direct | DP Tuba
	voice_keysplit voicegroup_keysplit_dp_trumpet_2, keysplit_dp_trumpet                         @ 059 | Direct | DP Trumpets 2
	voice_keysplit voicegroup_keysplit_dp_french_horn, keysplit_dp_electric_piano_2_rhodes       @ 060 | Direct | DP French Horns
	voice_keysplit voicegroup_keysplit_dp_distortion_guitar_2, keysplit_dp_distortion_guitar_2   @ 061 | Direct | DP Distortion Guitar 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 224, 242, 101, 220               @ 062 | Direct | Sampled Square Wave 25% 1
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 224, 242, 101, 220               @ 063 | Direct | Sampled Square Wave 12.5%
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass_c1_16, 255, 42, 255, 216             @ 064 | Direct | DP Synth Bass 3
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 219, 252, 196            @ 065 | Direct | DP Alto Sax
	voice_keysplit voicegroup_keysplit_dp_wood_bass_2, keysplit_dp_wood_bass                     @ 066 | Direct | DP Upright Bass 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220               @ 067 | Direct | Sampled Square Wave 50% 5
	voice_directsound 60, 0, DirectSoundWaveData_dp_oboe_c3_16, 255, 243, 127, 216               @ 068 | Direct | DP Oboe
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 182                     @ 069 | Direct | DP Sampled Noise 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 58, 0, 101, 220                  @ 070 | Direct | DP Sampled Square Wave 25% 2
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy_clarinet_c3_16, 255, 243, 159, 216        @ 071 | Direct | DP Clarinet
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 182               @ 072 | Direct | DP Sampled Square Wave 50% 6
	voice_keysplit voicegroup_keysplit_dp_flute, keysplit_dp_flute                               @ 073 | Direct | DP Flute
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodpat_c4_16, 100, 247, 78, 136             @ 074 | Direct | DP Wood Pat
	voice_directsound 60, 0, DirectSoundWaveData_dp_basschoir36, 255, 200, 255, 171              @ 075 | Direct | DP Bass Choir
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 200, 255, 171             @ 076 | Direct | DP Tenor Choir
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 200, 255, 171           @ 077 | Direct | DP Soprano Choir
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196             @ 078 | Direct | DP Whistle              | remaining voices wrap around
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 079 | --- | ---                        | to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171           @ 080 | Direct | DP Orchestral Hit Major | have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171           @ 081 | Direct | DP Orchestral Hit Minor
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 082 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 083 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 084 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 085 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 086 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 087 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 088 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 089 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 090 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 091 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 092 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 093 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 094 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 095 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 096 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 097 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 098 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 099 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 100 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 101 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 102 | --- | 
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                      @ 103 | --- | 
@	voice_keysplit voicegroup_keysplit_dp_music_box, keysplit_dp_pizzicato_music_box             @ 104 | Direct | DP Music Box
@	voice_keysplit voicegroup_keysplit_dp_banjo, keysplit_dp_banjo                               @ 105 | Direct | DP Banjo
