voice_group hgss_main                                                                                        @ Num | Type | Instrument
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                                   @ 000 | Direct | HGSS Piano 1
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel      @ 001 | Direct | HGSS Piano 2
	voice_keysplit voicegroup_keysplit_hgss_piano_3, keysplit_hgss_piano_3                                   @ 002 | Direct | HGSS Piano 3 (Piano Octave)
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_electric_piano_2_rhodes                    @ 003 | Direct | HGSS Rhodes 1
	voice_keysplit voicegroup_keysplit_hgss_rhodes_2, keysplit_dp_electric_piano_2_rhodes                    @ 004 | Direct | HGSS Rhodes 2
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel   @ 005 | Direct | HGSS Vibraphone
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square          @ 006 | Direct | HGSS Marimba
	voice_keysplit voicegroup_keysplit_hgss_xylophone, keysplit_hgss_xylophone_trumpet                       @ 007 | Direct | HGSS Xylophone
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_pizzicato_music_box                    @ 008 | Direct | HGSS Tubular Bell
	voice_keysplit voicegroup_keysplit_hgss_glockenspiel, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 009 | Direct | HGSS Glockenspiel
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square        @ 010 | Direct | HGSS Music Box
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani        @ 011 | Direct | HGSS Drawbar Organ
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani           @ 012 | Direct | HGSS Jazz Organ
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani            @ 013 | Direct | HGSS Accordion
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                               @ 014 | Direct | HGSS Nylon Guitar
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                              @ 015 | Direct | HGSS Martin Guitar
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_dp_distortion_guitar_2             @ 016 | Direct | HGSS Distortion Guitar 1
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_2, keysplit_dp_distortion_guitar_2             @ 017 | Direct | HGSS Distortion Guitar 2
	voice_keysplit voicegroup_keysplit_hgss_clean_guitar, keysplit_hgss_guitar                               @ 018 | Direct | HGSS Clean Guitar
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                         @ 019 | Direct | HGSS Upright Bass
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass                       @ 020 | Direct | HGSS Fingered Bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                         @ 021 | Direct | HGSS Slap Bass
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass                             @ 022 | Direct | HGSS Synth Bass
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                   @ 023 | Direct | HGSS Strings
	voice_keysplit voicegroup_keysplit_hgss_violin, keysplit_hgss_violin                                     @ 024 | Direct | HGSS Violin
	voice_keysplit voicegroup_keysplit_hgss_cello, keysplit_hgss_cello_trombone                              @ 025 | Direct | HGSS Cello
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                               @ 026 | Direct | HGSS Pizzicato
	voice_keysplit voicegroup_keysplit_hgss_harp, keysplit_hgss_organ_accordion_harp_timpani                 @ 027 | Direct | HGSS Harp
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani              @ 028 | Direct | HGSS Timpani
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                         @ 029 | Direct | HGSS Trumpets
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone                           @ 030 | Direct | HGSS Trombones
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo                 @ 031 | Direct | HGSS French Horn Solo
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn                           @ 032 | Direct | HGSS French Horns
	voice_keysplit voicegroup_keysplit_hgss_oboe, keysplit_hgss_oboe                                         @ 033 | Direct | HGSS Oboe
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                                 @ 034 | Direct | HGSS Clarinet
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                                       @ 035 | Direct | HGSS Flute
	voice_keysplit voicegroup_keysplit_hgss_bassoon, keysplit_hgss_bassoon                                   @ 036 | Direct | HGSS Bassoon
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit                     @ 037 | Direct | HGSS Orchestral Hit
	voice_keysplit voicegroup_keysplit_hgss_sampled_square, keysplit_hgss_marimba_music_box_sampled_square   @ 038 | Direct | HGSS Sampled Square Wave
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum				                                         @ 039 | Drum | HGSS Drums
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum				                                 @ 040 | Drum | HGSS Taiko Drums
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 171                         @ 041 | Direct | HGSS Wood Bass
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto                                         @ 042 | Direct | HGSS Koto
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 211                            @ 043 | Direct | Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 224                             @ 044 | Direct | HGSS Wind Effect
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 67, 255, 0, 245                               @ 045 | Direct | HGSS Explosion Effect
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171                       @ 046 | Direct | Sampled Square Wave | 1 octave too low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0                             @ 047 | Direct | HGSS Bubble Effect
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0                              @ 048 | Direct | Sampled Square Wave 50% | also 066 in BATTLE4 and DUNGEON4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96                              @ 049 | Direct | Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220                             @ 050 | Direct | Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220                           @ 051 | Direct | Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 192                           @ 052 | Direct | Sampled Square Wave 50%
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192                                   @ 053 | Direct | Sampled Noise 1
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 19                                  @ 054 | Direct | Sampled Noise 2
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 246, 78, 192	                     @ 055 | Direct | DP Whistle        | remaining voices wrap around
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16                            @ 056 | Direct | DP Reverse Cymbal | to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 167, 235, 171		                     @ 057 | Direct | DP Organ          | have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_37, 80, 234, 191, 220                            @ 058 | Direct | Sampled Square Wave 37.5%
@	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 80, 234, 191, 220                            @ 059 | Direct | Sampled Square Wave 12.5%
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 197, 255, 171                       @ 060 | Direct | DP Orchestral Hit Major
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171                       @ 061 | Direct | DP Orchestral Hit Minor
@	voice_keysplit_all voicegroup_allkeysplit_hgss_drum_kick_and_snare                                       @ 062 | Drum | HGSS Synth Kick + Snare
@	voice_keysplit voicegroup_keysplit_dp_timpani, keysplit_dp_timpani                                       @ 063 | Direct | DP Timpani
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 192                        @ 064 | Direct | DP Synth Bass 1
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220                         @ 065 | Direct | DP Synth Bass 2
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                       @ 066 | Direct | DP Sawtooth
@	voice_keysplit voicegroup_keysplit_hgss_shamisen, keysplit_hgss_shamisen                                 @ 067 | Direct | HGSS Shamisen
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171                               @ 068 | Direct | HGSS Hyoshigi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171                                @ 069 | Direct | HGSS Kodaiko
@	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171                                @ 070 | Direct | HGSS Tsuzumi
@	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171                             @ 071 | Direct | HGSS Jingle Bell
@	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0                                 @ 072 | Direct | HGSS Clap (Ho-Oh)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 197, 255, 171                         @ 073 | Direct | DP Tenor Choir
@	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 197, 255, 171                       @ 074 | Direct | DP Soprano Choir
@	voice_directsound 60, 0, DirectSoundWaveData_hg_choirc5, 255, 197, 255, 171                              @ 075 | Direct | HGSS Choir | 1 octave too low
@	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 197, 255, 171                         @ 076 | Direct | DP Reverse Cymbal | 1 octave too high
@	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32                       @ 077 | Direct | DP Wind Effect (Spear Pillar)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                        @ 078 | Direct | DP Altosax
@	voice_directsound 60, 0, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 171                             @ 079 | Direct | DP Synth Snare
@	voice_keysplit voicegroup_keysplit_hgss_piano_4, keysplit_hgss_piano_4                                   @ 080 | Direct | HGSS Piano 4 (National Park)
@	voice_directsound 60, 0, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32                                 @ 081 | Direct | DP Tom
@	voice_keysplit voicegroup_keysplit_dp_trumpet_1, keysplit_dp_trumpet                                     @ 082 | Direct | DP Trumpet (Arceus)
@	voice_keysplit voicegroup_keysplit_dp_trombone, keysplit_dp_trombone                                     @ 083 | Direct | DP Trombone (Arceus)
