	.align 2
voicegroup277::
	voice_keysplit voicegroup233, KeySplitTable35                                        @ 000 | HGSS Piano |  voice_keysplit voicegroup323, KeySplitTable106   @ piano | 41 | 46 | 53 | 58
	voice_keysplit voicegroup005, KeySplitTableGBAPiano1Custom                            @ 001 | RSE Piano |  voice_keysplit voicegroup323, KeySplitTable59    @ piano (all splits)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 002 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 003 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup236, KeySplitTable9                                          @ 004 | HGSS Rhodes |  voice_keysplit voicegroup294, KeySplitTable36    @ rhodes
	voice_keysplit voicegroup234, KeySplitTable36                                         @ 005 | HGSS Piano 2 |  voice_keysplit voicegroup234, KeySplitTable36    @ piano 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 006 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 007 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 008 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 009 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup238, KeySplitTable36                                         @ 010 | HGSS Vibraphone |  voice_keysplit voicegroup297, KeySplitTable76    @ vibraphone
	voice_keysplit voicegroup239, KeySplitTable38                                         @ 011 | HGSS Marimba |  voice_keysplit voicegroup295, KeySplitTable74    @ marimba
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 012 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 013 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 014 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 015 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_hg_072musboxc5, 255, 246, 0, 205         @ 016 | HGSS Music Box |  voice_directsound 60, 0, DirectSoundWaveData_hg_072musboxc5, 255, 246, 0, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 017 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup245, KeySplitTable40                                         @ 018 | HGSS Jazz Organ |  voice_keysplit voicegroup245, KeySplitTable71    @ jazz organ
	voice_keysplit voicegroup246, KeySplitTable40                                         @ 019 | HGSS Accordion |  voice_directsound 60, 0, DirectSoundWaveData_bw_accorc3, 255, 234, 191, 192
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 020 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 021 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 022 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 023 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 024 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup252, KeySplitTable42                                         @ 025 | HGSS Upright Bass |  voice_keysplit voicegroup252, KeySplitTable42    @ upright bass
	voice_keysplit voicegroup253, KeySplitTable43                                         @ 026 | HGSS Fingered Bass |  voice_keysplit voicegroup253, KeySplitTable43    @ fingered bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216 @ 028 | RSE Unison Bass |  voice_directsound 60, 0, DirectSoundWaveData_bw_acidbassb1, 255, 1, 227, 0
	voice_keysplit voicegroup254, KeySplitTable44                                         @ 029 | HGSS Synth Bass |  voice_keysplit voicegroup254, KeySplitTable73    @ synth bass
	voice_keysplit voicegroup255, KeySplitTable45                                         @ 030 | HGSS Strings |  voice_keysplit voicegroup255, KeySplitTable79    @ strings | 66
	voice_keysplit voicegroup006, KeySplitTable2                                          @ 031 | RSE Strings |  voice_keysplit voicegroup255, KeySplitTable60    @ strings
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 032 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 033 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup258, KeySplitTable48                                         @ 034 | HGSS Pizzicato |  voice_keysplit voicegroup293, KeySplitTable107   @ pizzicato | 48 | 57 | 65
	voice_keysplit voicegroup259, KeySplitTable40                                         @ 035 | HGSS Harp |  voice_keysplit voicegroup299, KeySplitTable78    @ harp 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 036 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 038 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup261, KeySplitTable39                                         @ 039 | HGSS Trumpets |  voice_keysplit voicegroup261, KeySplitTable39    @ trumpets
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup264, KeySplitTable50                                         @ 042 | HGSS French Horns |  voice_keysplit voicegroup327, KeySplitTable41    @ french horns
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup266, KeySplitTable52                                         @ 045 | HGSS Clarinet |  voice_keysplit voicegroup266, KeySplitTable52    @ clarinet
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205       @ 046 | HGSS Timpani Part |  voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127        @ 047 | RSE Flute |  voice_directsound 60, 0, DirectSoundWaveData_bw_064flt2a5, 255, 246, 159, 205
	voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 159, 205         @ 048 | HGSS Flute Part |  voice_directsound 60, 0, DirectSoundWaveData_hg_096flt1c6, 255, 246, 159, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup262, KeySplitTable47                                         @ 051 | HGSS Trombones |  voice_directsound 60, 0, DirectSoundWaveData_bw_trombonesstaccatocs2, 255, 1, 227, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup258, KeySplitTable48                                         @ 061 | HGSS Pizzicato |  voice_directsound 60, 0, DirectSoundWaveData_bw_spiccatostringse2, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16         @ 062 | HGSS Reverse Cymbal |  voice_directsound 60, 0, DirectSoundWaveData_bw_reversecymbale2, 255, 0, 255, 236
	voice_keysplit voicegroup261, KeySplitTable39                                         @ 063 | HGSS Trumpets |  voice_directsound 60, 0, DirectSoundWaveData_bw_trumpetsstaccatogs4, 255, 0, 255, 224
	voice_keysplit voicegroup255, KeySplitTable45                                         @ 064 | HGSS Strings |  voice_directsound 60, 0, DirectSoundWaveData_bw_stringscs2, 255, 0, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204 @ 070 | RSE Shaku |  voice_directsound 60, 0, DirectSoundWaveData_bw_shakuds4, 255, 0, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 246, 159, 224    @ 071 | RSE Koto High |  voice_directsound 60, 0, DirectSoundWaveData_bw_kotods4, 255, 246, 159, 224
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 080 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171    @ 088 | HGSS Sawtooth |  voice_keysplit voicegroup306, KeySplitTable38    @ saw lead
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 7, 15, 0                                              @ 100 | GB Square-2 |  voice_square_2_alt 60, 0, 2, 0, 7, 15, 0
	voice_square_2_alt 60, 0, 2, 0, 7, 15, 6                                              @ 101 | GB Square-2 |  voice_square_2_alt 60, 0, 2, 0, 7, 15, 6
	voice_square_1_alt 60, 0, 0, 2, 0, 7, 15, 6                                           @ 102 | GB Square-1 |  voice_square_1_alt 60, 0, 0, 2, 0, 7, 15, 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_3, 0, 7, 15, 6                @ 103 | GB Wave |  voice_programmable_wave_alt 60, 0, ProgrammableWaveData_sq50half, 0, 7, 15, 6
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_noise_alt 60, 0, 0, 0, 7, 15, 1                                                 @ 122 | GB Noise |  voice_noise_alt 60, 0, 0, 0, 7, 15, 1 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup284                                                      @ 127 | Drum Split |  voice_keysplit_all voicegroup284 @ drums
