	.align 2
voicegroup280::
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 000 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox01, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 001 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox02, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 002 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox03, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 003 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox04, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 004 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox05, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 005 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox06, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 006 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox07, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 007 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox08, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 008 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox09, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 009 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox10, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 010 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox11, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 011 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox12, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 012 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox13, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 013 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox14, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 014 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox15, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 015 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox16, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 016 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox17, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 017 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox18, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 018 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox19, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 019 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox20, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 020 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox21, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 021 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox22, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 022 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox23, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 023 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox24, 255, 0, 227, 171
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 227, 171 @ 024 | --- |  voice_directsound 60, 0, DirectSoundWaveData_bw_villagebridge_vox25, 255, 0, 227, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 025 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 026 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 027 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 028 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 029 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 030 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 031 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 032 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 033 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 034 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 035 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 036 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 037 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 038 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup271, KeySplitTable56                                         @ 039 | HGSS Koto |  voice_keysplit voicegroup290, KeySplitTable70    @ harpsichord
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 040 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 041 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 042 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 043 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 044 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup247, KeySplitTable41                                         @ 045 | HGSS Nylon Guitar |  voice_keysplit voicegroup292, KeySplitTable109   @ nylon str. guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 046 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 047 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 048 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 049 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 050 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 051 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 052 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 053 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 054 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 055 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 056 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 057 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 058 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 059 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 060 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 061 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 062 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 063 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 064 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 065 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 066 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 067 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 068 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 069 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup270, KeySplitTable38                                         @ 070 | HGSS Square Wave |  voice_keysplit voicegroup270, KeySplitTable38    @ square wave (HGSS)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 071 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 072 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 073 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 074 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 075 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 076 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 077 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 078 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 079 | --- |  voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup285                                                      @ 080 | Drum Split |  voice_keysplit_all voicegroup285 @ drums
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 081 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 082 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 122 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 127 | --- |  
