Cobblecross_Museum_MapScripts::
	.byte 0

Cobblecross_Museum_EventScript_Curator::
	msgbox Cobblecross_Museum_Text_1, MSGBOX_NPC
	end

Cobblecross_Museum_Text_1::
	.string "Welcome to the Aldermoor Fossil\n"
	.string "Museum!\p"
	.string "Our lab can bring fossils back to\n"
	.string "life. Omanyte, Kabuto, even\l"
	.string "Aerodactyl!\p"
	.string "Find a fossil in Rustcave Tunnel\n"
	.string "and bring it here. (Side story:\l"
	.string "VOICES IN THE STONE)$"

