Brambleton_BeekeepersHouse_MapScripts::
	.byte 0

Brambleton_BeekeepersHouse_EventScript_Beekeeper::
	msgbox Brambleton_BeekeepersHouse_Text_1, MSGBOX_NPC
	end

Brambleton_BeekeepersHouse_Text_1::
	.string "My Ledyba swarm went missing last\n"
	.string "spring, stolen by poachers, I'd\l"
	.string "bet.\p"
	.string "Team Rust sells rare Pokémon to\n"
	.string "collectors. If you ever find their\l"
	.string "hideout...\p"
	.string "(Side story: THE STOLEN HIVE)$"

