#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H

enum FrontierMonId
{
    FRONTIER_MON_TEST_PIKACHU,
    FRONTIER_MON_TEST_ABRA,
    FRONTIER_MON_TEST_MACHOP,
    FRONTIER_MON_TEST_PIKACHU_2,
    FRONTIER_MON_TEST_BULBASAUR,

    FRONTIER_MONS_HIGH_TIER = FRONTIER_MON_TEST_ABRA, // Mons above this point can only appear > level 50

    NUM_FRONTIER_MONS = FRONTIER_MON_TEST_BULBASAUR + 1,
};

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_MONS_H
