#ifndef GUARD_CONSTANTS_BATTLE_FRONTIER_POOL_SETS_H
#define GUARD_CONSTANTS_BATTLE_FRONTIER_POOL_SETS_H

enum FrontierPoolSetId
{
    FRONTIER_POOL_TEST_LEVEL_50,
    FRONTIER_POOL_TEST_OPEN_LEVEL,

    NUM_FRONTIER_POOL_SETS,
};

#endif // GUARD_CONSTANTS_BATTLE_FRONTIER_POOL_SETS_H
