NewLittleroot_Supermarket_MapScripts::
	.byte 0


NewLittleroot_Supermarket_Employee_1::
# 6 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 7 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 8 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_1_Text_0
# 9 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 10 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen1Shop
# 11 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 12 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_2::
# 17 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 18 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 19 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_2_Text_0
# 20 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 21 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen2Shop
# 22 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 23 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_3::
# 28 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 29 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 30 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_3_Text_0
# 31 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 32 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen3Shop
# 33 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 34 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_4::
# 39 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 40 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 41 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_4_Text_0
# 42 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 43 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen4Shop
# 44 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 45 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_5::
# 50 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 51 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 52 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_5_Text_0
# 53 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 54 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen5Shop
# 55 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 56 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_6::
# 61 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 62 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 63 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_6_Text_0
# 64 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 65 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen6Shop
# 66 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 67 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_7::
# 72 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 73 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 74 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_7_Text_0
# 75 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 76 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen7Shop
# 77 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 78 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_8::
# 83 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 84 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 85 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_8_Text_0
# 86 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 87 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen8Shop
# 88 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 89 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


NewLittleroot_Supermarket_Employee_9::
# 94 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 95 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 96 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	message NewLittleroot_Supermarket_Employee_9_Text_0
# 97 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 98 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	pokemart Gen9Shop
# 99 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Employee_1_Text_1
# 100 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	release
	end


	.align 2
# 104 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen1Shop:
# 105 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 106 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 107 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_WATER_STONE
# 108 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 109 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_STONE
# 110 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 111 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_POKE_BALL
# 112 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 113 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SAFARI_BALL
# 114 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MASTER_BALL
# 115 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_NONE

	.align 2
# 119 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen2Shop:
# 120 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SUN_STONE
# 121 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEVEL_BALL
# 122 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LURE_BALL
# 123 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LOVE_BALL
# 124 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FAST_BALL
# 125 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_HEAVY_BALL
# 126 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FRIEND_BALL
# 127 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_BALL
# 128 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DRAGON_SCALE
# 129 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_METAL_COAT
# 130 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_UPGRADE
# 131 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SACRED_ASH
# 132 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LIGHT_BALL
	.2byte ITEM_NONE

	.align 2
# 136 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen3Shop:
# 137 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_TIMER_BALL
# 138 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_REPEAT_BALL
# 139 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LUXURY_BALL
# 140 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DIVE_BALL
# 141 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_NET_BALL
# 142 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_ENIGMA_BERRY
# 143 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_ACRO_BIKE
# 144 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MACH_BIKE
	.2byte ITEM_NONE

	.align 2
# 148 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen4Shop:
# 149 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_QUICK_BALL
# 150 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DUSK_BALL
# 151 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_HEAL_BALL
# 152 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DESTINY_KNOT
# 153 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_EXPERT_BELT
# 154 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 155 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_CHOICE_BAND
# 156 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_CHOICE_SCARF
# 157 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_CHOICE_SPECS
# 158 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_TOXIC_ORB
# 159 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LIFE_ORB
# 160 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FLAME_ORB
# 161 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_ELECTIRIZER
# 162 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DUBIOUS_DISC
# 163 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_REAPER_CLOTH
# 164 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_PROTECTOR
# 165 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MAGMARIZER
# 166 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RAZOR_CLAW
# 167 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RAZOR_FANG
# 168 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DUSK_STONE
# 169 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DAWN_STONE
# 170 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SHINY_STONE
# 171 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FOCUS_SASH
# 172 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_OVAL_STONE
# 173 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_HONEY
	.2byte ITEM_NONE

	.align 2
# 177 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen5Shop:
# 178 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_DREAM_BALL
# 179 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_AIR_BALLOON
# 180 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_ROCKY_HELMET
# 181 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RED_CARD
# 182 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_EJECT_BUTTON
# 183 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_EVIOLITE
# 184 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_HEALTH_WING
# 185 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MUSCLE_WING
# 186 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RESIST_WING
# 187 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GENIUS_WING
# 188 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_CLEVER_WING
# 189 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SWIFT_WING
	.2byte ITEM_NONE

	.align 2
# 193 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen6Shop:
# 194 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 195 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 196 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_WATER_STONE
# 197 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 198 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_STONE
# 199 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 200 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_POKE_BALL
# 201 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 202 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SAFARI_BALL
# 203 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MASTER_BALL
# 204 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_NONE

	.align 2
# 208 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen7Shop:
# 209 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 210 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 211 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_WATER_STONE
# 212 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 213 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_STONE
# 214 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 215 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_POKE_BALL
# 216 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 217 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SAFARI_BALL
# 218 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MASTER_BALL
# 219 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_NONE

	.align 2
# 223 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen8Shop:
# 224 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 225 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 226 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_WATER_STONE
# 227 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 228 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_STONE
# 229 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 230 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_POKE_BALL
# 231 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 232 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SAFARI_BALL
# 233 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MASTER_BALL
# 234 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_NONE

	.align 2
# 238 "data/maps/NewLittleroot_Supermarket/scripts.pory"
Gen9Shop:
# 239 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 240 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 241 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_WATER_STONE
# 242 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 243 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MOON_STONE
# 244 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_FULL_RESTORE
# 245 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_POKE_BALL
# 246 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_GREAT_BALL
# 247 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_SAFARI_BALL
# 248 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_MASTER_BALL
# 249 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.2byte ITEM_RARE_CANDY
	.2byte ITEM_NONE

Luxray_Battle_Decision::
# 254 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lock
# 255 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	faceplayer
# 256 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	playmoncry SPECIES_LUXRAY, CRY_MODE_NORMAL
# 257 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitse
# 258 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox Luxray_Battle_Decision_Text_0
# 259 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 260 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox Luxray_Battle_Decision_Text_1
# 261 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	playmoncry SPECIES_LUXRAY, CRY_MODE_NORMAL
# 262 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox Luxray_Battle_Decision_Text_2
# 263 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitse
# 264 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 265 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox Luxray_Battle_Decision_Text_3
# 266 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox Luxray_Battle_Decision_Text_4, MSGBOX_YESNO
# 268 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_eq Luxray_Battle_Decision_1
# 271 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, YES
	goto_if_ne Luxray_Battle_Decision_2
	return

Luxray_Battle_Decision_1:
# 269 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call Luxray_Battle
	end

Luxray_Battle_Decision_2:
# 272 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call RanAway
	return


Won_or_Caught::
# 277 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	fadescreen FADE_TO_BLACK
# 278 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	removeobject 15
# 279 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	fadescreen FADE_FROM_BLACK
	return


RanAway::
# 285 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	fadescreen FADE_TO_BLACK
# 286 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	delay 20
# 287 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	removeobject 15
# 288 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	fadescreen FADE_FROM_BLACK
# 289 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox RanAway_Text_0
# 290 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return


LuxrayTrigger::
# 295 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lockall
# 296 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	setflag FLAG_UNUSED_0x021
# 297 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	applymovement 15, LuxrayRun
# 298 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmovement 0
# 299 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return


# 302 "data/maps/NewLittleroot_Supermarket/scripts.pory"
LuxrayRun:
# 303 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	walk_fast_down
# 303 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	walk_fast_down
# 303 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	walk_fast_down
# 303 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	walk_fast_down
	step_end

Luxray_Battle::
# 307 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lockall
# 308 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	setflag FLAG_UNUSED_0x022
# 309 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	playmoncry SPECIES_LUXRAY, CRY_MODE_NORMAL
# 310 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	delay 40
# 311 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmoncry
# 312 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	setwildbattle SPECIES_LUXRAY, 50, ITEM_ELECTRIUM_Z
# 313 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	dowildbattle
# 314 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	specialvar VAR_RESULT, GetBattleOutcome
# 316 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_CAUGHT
	goto_if_eq Luxray_Battle_2
# 319 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_WON
	goto_if_eq Luxray_Battle_3
# 322 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_RAN
	goto_if_eq Luxray_Battle_4
# 325 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	compare VAR_RESULT, B_OUTCOME_PLAYER_TELEPORTED
	goto_if_eq Luxray_Battle_5
Luxray_Battle_1:
# 328 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	waitmessage
# 329 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return

Luxray_Battle_2:
# 317 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call Won_or_Caught
	goto Luxray_Battle_1

Luxray_Battle_3:
# 320 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call Won_or_Caught
	goto Luxray_Battle_1

Luxray_Battle_4:
# 323 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call RanAway
	goto Luxray_Battle_1

Luxray_Battle_5:
# 326 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	call RanAway
	goto Luxray_Battle_1


NewLittlerootTown_Sign::
# 333 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lockall
# 334 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittlerootTown_Sign_Text_0
# 335 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return


NewLittleroot_Supermarket_Sign::
# 339 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lockall
# 340 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox NewLittleroot_Supermarket_Sign_Text_0
# 341 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return


The_Fallen_Souls_Sign::
# 345 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	lockall
# 346 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	msgbox The_Fallen_Souls_Sign_Text_0
# 347 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	releaseall
	return


NewLittleroot_Supermarket_Employee_1_Text_0:
# 8 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen I market. How\n"
	.string "may I help you?$"

NewLittleroot_Supermarket_Employee_1_Text_1:
# 11 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Please come again.$"

NewLittleroot_Supermarket_Employee_2_Text_0:
# 19 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen II market. How\n"
	.string "may I help you?$"

NewLittleroot_Supermarket_Employee_3_Text_0:
# 30 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen III market.\n"
	.string "How may I help you?$"

NewLittleroot_Supermarket_Employee_4_Text_0:
# 41 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen IV market. How\n"
	.string "may I help you?$"

NewLittleroot_Supermarket_Employee_5_Text_0:
# 52 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen V market. How\n"
	.string "may I help you?$"

NewLittleroot_Supermarket_Employee_6_Text_0:
# 63 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen VI market. How\n"
	.string "may I help you?$"

NewLittleroot_Supermarket_Employee_7_Text_0:
# 74 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen VII market.\n"
	.string "How may I help you?$"

NewLittleroot_Supermarket_Employee_8_Text_0:
# 85 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen VIII market.\n"
	.string "How may I help you?$"

NewLittleroot_Supermarket_Employee_9_Text_0:
# 96 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Hello, welcome to the Gen IX market. How\n"
	.string "may I help you?$"

Luxray_Battle_Decision_Text_0:
# 258 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Luxray!$"

Luxray_Battle_Decision_Text_1:
# 260 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "{PLAYER}: E-Easy there kitty...$"

Luxray_Battle_Decision_Text_2:
# 262 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Luxray: Lux-RAY!$"

Luxray_Battle_Decision_Text_3:
# 265 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "The Luxray seems very hostile. It seems\n"
	.string "like it wants to battle.$"

Luxray_Battle_Decision_Text_4:
# 266 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Do you want to battle Luxray?$"

RanAway_Text_0:
# 289 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "Luxray ran away.$"

NewLittlerootTown_Sign_Text_0:
# 334 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "New Littleroot Town: A sleek expansion\n"
	.string "to Littleroot Town, developed by Team\l"
	.string "Magma under the guise of progress.\l"
	.string "Maxie rewarded the Champion for their\l"
	.string "efforts in saving the world from\l"
	.string "Groudon and Kyogre by granting them\l"
	.string "this upgraded settlement. Though\l"
	.string "modern and efficient, its origins remain\l"
	.string "a source of quiet suspicion.$"

NewLittleroot_Supermarket_Sign_Text_0:
# 340 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "New Littleroot Town Supermarket: Built\n"
	.string "alongside the expansion of New\l"
	.string "Littleroot Town, this supermarket is a\l"
	.string "symbol of modernization and\l"
	.string "convenience. Stocked with a wide range\l"
	.string "of Trainer essentials and specialty\l"
	.string "items, it serves as a hub for locals and\l"
	.string "newcomers alike. Funded in part by Team\l"
	.string "Magma, the store reflects their vision\l"
	.string "of progress though some still question\l"
	.string "the motives behind their generosity.$"

The_Fallen_Souls_Sign_Text_0:
# 346 "data/maps/NewLittleroot_Supermarket/scripts.pory"
	.string "The Fallen Souls: Legendary Pokémon\n"
	.string "who died unnaturally, their spirits\l"
	.string "trapped between worlds and dimensions.$"
