#ifndef GUARD_CONSTANTS_APRICORN_TREE_H
#define GUARD_CONSTANTS_APRICORN_TREE_H

// Apricorns
#define APRICORN_RED             0
#define APRICORN_BLUE            1
#define APRICORN_YELLOW          2
#define APRICORN_GREEN           3
#define APRICORN_PINK            4
#define APRICORN_WHITE           5
#define APRICORN_BLACK           6
#define APRICORN_BERRY_CHERI     7
#define APRICORN_BERRY_CHESTO    8
#define APRICORN_BERRY_PECHA     9
#define APRICORN_BERRY_RAWST    10
#define APRICORN_BERRY_ASPEAR   11
#define APRICORN_BERRY_LEPPA    12
#define APRICORN_BERRY_ORAN     13
#define APRICORN_BERRY_PERSIM   14
#define APRICORN_BERRY_LUM      15
#define APRICORN_BERRY_SITRUS   16
#define APRICORN_BERRY_FIGY     17
#define APRICORN_BERRY_WIKI     18
#define APRICORN_BERRY_MAGO     19
#define APRICORN_BERRY_AGUAV    20
#define APRICORN_BERRY_IAPAPA   21
#define APRICORN_BERRY_RAZZ     22
#define APRICORN_BERRY_BLUK     23
#define APRICORN_BERRY_NANAB    24
#define APRICORN_BERRY_WEPEAR   25
#define APRICORN_BERRY_PINAP    26
#define APRICORN_BERRY_POMEG    27
#define APRICORN_BERRY_KELPSY   28
#define APRICORN_BERRY_QUALOT   29
#define APRICORN_BERRY_HONDEW   30
#define APRICORN_BERRY_GREPA    31
#define APRICORN_BERRY_TAMATO   32
#define APRICORN_BERRY_CORNN    33
#define APRICORN_BERRY_MAGOST   34
#define APRICORN_BERRY_RABUTA   35
#define APRICORN_BERRY_NOMEL    36
#define APRICORN_BERRY_SPELON   37
#define APRICORN_BERRY_PAMTRE   38
#define APRICORN_BERRY_WATMEL   39
#define APRICORN_BERRY_DURIN    40
#define APRICORN_BERRY_BELUE    41
#define APRICORN_BERRY_OCCA     42
#define APRICORN_BERRY_PASSHO   43
#define APRICORN_BERRY_WACAN    44
#define APRICORN_BERRY_RINDO    45
#define APRICORN_BERRY_YACHE    46
#define APRICORN_BERRY_CHOPLE   47
#define APRICORN_BERRY_KEBIA    48
#define APRICORN_BERRY_SHUCA    49
#define APRICORN_BERRY_COBA     50
#define APRICORN_BERRY_PAYAPA   51
#define APRICORN_BERRY_TANGA    52
#define APRICORN_BERRY_CHARTI   53
#define APRICORN_BERRY_KASIB    54
#define APRICORN_BERRY_HABAN    55
#define APRICORN_BERRY_COLBUR   56
#define APRICORN_BERRY_BABIRI   57
#define APRICORN_BERRY_CHILAN   58
#define APRICORN_BERRY_LIECHI   59
#define APRICORN_BERRY_GANLON   60
#define APRICORN_BERRY_SALAC    61
#define APRICORN_BERRY_PETAYA   62
#define APRICORN_BERRY_APICOT   63
#define APRICORN_BERRY_LANSAT   64
#define APRICORN_BERRY_STARF    65
#define APRICORN_BERRY_ENIGMA   66
#define APRICORN_BERRY_MICLE    67
#define APRICORN_BERRY_CUSTAP   68
#define APRICORN_BERRY_JABOCA   69
#define APRICORN_BERRY_ROWAP    70
#define APRICORN_BERRY_ROSELI   71
#define APRICORN_BERRY_KEE      72
#define APRICORN_BERRY_MARANGA  73

// default is set to an u8, so limited to 256 by default
#define APRICORN_COUNT          74

// Trees
#define APRICORN_TREE_NONE 0

#define APRICORN_TREE_COUNT 0

#endif //GUARD_CONSTANTS_APRICORN_TREE_H
