#ifndef GUARD_BATTLE_STATUS_MENU_CONSTANTS_H
#define GUARD_BATTLE_STATUS_MENU_CONSTANTS_H

enum BattleMenuStates
{
    B_STATUS_MENU_STATE_CLEAR_PAGE,
    B_STATUS_MENU_STATE_ENTER_PAGE,
    B_STATUS_MENU_STATE_EXIT,
    B_STATUS_MENU_STATE_HANDLE_INPUT,
    B_STATUS_MENU_STATE_DONE,
};

enum BattleMenuPages
{
    BATTLE_STATUS_PAGE_OVERVIEW,
    BATTLE_STATUS_PAGE_DETAIL,
};

enum
{
    B_STATUS_TEXT_COLOR_TRANSPARENT,
    B_STATUS_TEXT_COLOR_BLACK,
    B_STATUS_TEXT_COLOR_DARK_GRAY,
    B_STATUS_TEXT_COLOR_LIGHT_GRAY,
    B_STATUS_TEXT_COLOR_WHITE,
    B_STATUS_TEXT_COLOR_LIGHT_BLUE,
    B_STATUS_TEXT_COLOR_BLUE,
    B_STATUS_TEXT_COLOR_PINK,
    B_STATUS_TEXT_COLOR_DARK_PINK,
    B_STATUS_TEXT_COLOR_GREEN,
    B_STATUS_TEXT_COLOR_LIGHT_GREEN,
    B_STATUS_TEXT_COLOR_RED,
    B_STATUS_TEXT_COLOR_LIGHT_RED,
};

#define B_STATUS_TEXT_PAL                15
#define B_STATUS_TEXT_BG                 0
#define B_STATUS_BACKDROP_BG             1
#define B_STATUS_TILEMAP_WIDTH           32
#define B_STATUS_TILEMAP_HEIGHT          32

#define B_STATUS_BG_TILE_FILL             0x01
#define B_STATUS_BG_TILE_HEADER_CORNER    0x02
#define B_STATUS_BG_TILE_HEADER_SIDE      0x03
#define B_STATUS_BG_TILE_HEADER_TOP       0x04
#define B_STATUS_BG_TILE_HEADER_FILL      0x05
#define B_STATUS_BG_TILE_CARD_INACTIVE_TL 0x06
#define B_STATUS_BG_TILE_CARD_INACTIVE_TE 0x07
#define B_STATUS_BG_TILE_CARD_INACTIVE_SE 0x08
#define B_STATUS_BG_TILE_CARD_INACTIVE_IN 0x09
#define B_STATUS_BG_TILE_CARD_INACTIVE_BL 0x0A
#define B_STATUS_BG_TILE_CARD_INACTIVE_BE 0x0B
#define B_STATUS_BG_TILE_CARD_ACTIVE_TL   0x0C
#define B_STATUS_BG_TILE_CARD_ACTIVE_TE   0x0D
#define B_STATUS_BG_TILE_CARD_ACTIVE_SE   0x0E
#define B_STATUS_BG_TILE_CARD_ACTIVE_IN   0x0F
#define B_STATUS_BG_TILE_CARD_ACTIVE_BL   0x10
#define B_STATUS_BG_TILE_CARD_ACTIVE_BE   0x11
#define B_STATUS_BG_TILE_SCROLLBAR_LANE   0x18
#define B_STATUS_BG_TILE_SCROLLBAR_TOP    0x19
#define B_STATUS_BG_TILE_SCROLLBAR_BOTTOM 0x1A

#define B_STATUS_BG_ATTR_HFLIP           BG_TILE_H_FLIP(0)
#define B_STATUS_BG_ATTR_VFLIP           BG_TILE_V_FLIP(0)

#define B_STATUS_CARD_TILE_W             8
#define B_STATUS_CARD_TILE_H             7
#define B_STATUS_CARD_W                  (B_STATUS_CARD_TILE_W * 8)
#define B_STATUS_CARD_H                  (B_STATUS_CARD_TILE_H * 8)

#define B_STATUS_ROW_Y_ENEMY             24
#define B_STATUS_ROW_Y_PLAYER            80

#define B_STATUS_SAFE_LEFT_TILE          1
#define B_STATUS_SAFE_RIGHT_TILE         30

#define B_STATUS_LABEL_TILE_H            3
#define B_STATUS_LABEL_H                 (B_STATUS_LABEL_TILE_H * 8)
#define B_STATUS_LABEL_BOTTOM_TILE_TOP   ((DISPLAY_HEIGHT / 8) - B_STATUS_LABEL_TILE_H)

#define B_STATUS_WIN_LABEL_TOP_BASE      1
#define B_STATUS_WIN_LABEL_BOTTOM_BASE   (B_STATUS_WIN_LABEL_TOP_BASE + (32 * B_STATUS_LABEL_TILE_H))
#define B_STATUS_WIN_ROW_ENEMY_BASE      (B_STATUS_WIN_LABEL_BOTTOM_BASE + (32 * B_STATUS_LABEL_TILE_H))
#define B_STATUS_WIN_ROW_PLAYER_BASE     (B_STATUS_WIN_ROW_ENEMY_BASE + (32 * B_STATUS_CARD_TILE_H))
#define B_STATUS_DETAIL_HEADER_WIN_W     15
#define B_STATUS_DETAIL_HEADER_WIN_H     12
#define B_STATUS_DETAIL_ITEM_WIN_W       9
#define B_STATUS_DETAIL_ITEM_WIN_H       8
#define B_STATUS_DETAIL_STATS_WIN_W      6
#define B_STATUS_DETAIL_STATS_WIN_H      11
#define B_STATUS_DETAIL_EFFECTS_WIN_W    13
#define B_STATUS_DETAIL_EFFECTS_WIN_H    12
#define B_STATUS_DETAIL_DESC_WIN_W       13
#define B_STATUS_DETAIL_DESC_WIN_H       8
#define B_STATUS_WIN_DETAIL_HEADER_BASE  1
#define B_STATUS_WIN_DETAIL_ITEM_BASE    (B_STATUS_WIN_DETAIL_HEADER_BASE + (B_STATUS_DETAIL_HEADER_WIN_W * B_STATUS_DETAIL_HEADER_WIN_H))
#define B_STATUS_WIN_DETAIL_STATS_BASE   (B_STATUS_WIN_DETAIL_ITEM_BASE + (B_STATUS_DETAIL_ITEM_WIN_W * B_STATUS_DETAIL_ITEM_WIN_H))
#define B_STATUS_WIN_DETAIL_EFFECTS_BASE (B_STATUS_WIN_DETAIL_STATS_BASE + (B_STATUS_DETAIL_STATS_WIN_W * B_STATUS_DETAIL_STATS_WIN_H))
#define B_STATUS_WIN_DETAIL_DESC_BASE    (B_STATUS_WIN_DETAIL_EFFECTS_BASE + (B_STATUS_DETAIL_EFFECTS_WIN_W * B_STATUS_DETAIL_EFFECTS_WIN_H))

#define B_STATUS_GENDER_W                8

#define B_STATUS_HP_BAR_TILE_TAG_BASE         0xD7C0
#define B_STATUS_HP_BAR_PAL_TAG               0xD7C4
#define B_STATUS_HP_BAR_ENDCAP_LEFT_TILE_TAG  0xD7C5
#define B_STATUS_HP_BAR_ENDCAP_RIGHT_TILE_TAG 0xD7C6
#define B_STATUS_HP_BAR_ENDCAP_PAL_TAG        0xD7C7

#define B_STATUS_HEALTHBAR_PIXELS        48
#define B_STATUS_DETAIL_HEALTHBAR_PIXELS 40
#define B_STATUS_HP_BAR_SEGMENTS         6
#define B_STATUS_DETAIL_HP_BAR_SEGMENTS  5

#define B_STATUS_UPDATE_ICON_TILE_TAG              0xD7D0
#define B_STATUS_CURSOR_TILE_TAG                   0xD7E0
#define B_STATUS_DETAIL_GIMMICK_TILE_TAG           0xD7E2
#define B_STATUS_DETAIL_HP_BAR_TILE_TAG            0xD7E3
#define B_STATUS_DETAIL_TERA_TYPE_TILE_TAG         0xD7F0
#define B_STATUS_OVERVIEW_GIMMICK_TILE_TAG_BASE    0xD7E4
#define B_STATUS_DETAIL_STAT_PIP_DOT_TILE_TAG      0xD7E8
#define B_STATUS_DETAIL_STAT_PIP_UP_TILE_TAG       0xD7E9
#define B_STATUS_DETAIL_STAT_PIP_DOWN_TILE_TAG     0xD7EA
#define B_STATUS_DETAIL_STAT_PIP_PAL_TAG           0xD7EF
#define B_STATUS_DETAIL_STAT_PIP_PAL_NUM           12
#define B_STATUS_DETAIL_EFFECTS_SCROLLBAR_TILE_TAG 0xD7EB
#define B_STATUS_MOVE_TYPES_PAL_TAG_1              0xD7ED
#define B_STATUS_MOVE_TYPES_PAL_TAG_2              0xD7EE

#define B_STATUS_DETAIL_GIMMICK_W            8
#define B_STATUS_DETAIL_GIMMICK_H            16
#define B_STATUS_DETAIL_GIMMICK_GFX_SIZE     ((B_STATUS_DETAIL_GIMMICK_W * B_STATUS_DETAIL_GIMMICK_H) / 2)
#define B_STATUS_DETAIL_STAT_ROW_COUNT       7
#define B_STATUS_DETAIL_STAT_PIPS_PER_ROW    6
#define B_STATUS_DETAIL_MAX_ACTIVE_EFFECTS   64
#define B_STATUS_DETAIL_EFFECTS_VISIBLE_ROWS 6

#define B_STATUS_DETAIL_TEXT_BUFFER_SIZE 512

#define TAG_STATUS_ICONS                1202

#define HEALTHBOX_GFX_HP_BAR_GREEN      3
#define HEALTHBOX_GFX_HP_BAR_YELLOW     50
#define HEALTHBOX_GFX_HP_BAR_RED        59

enum
{
    WIN_DETAIL_HEADER,
    WIN_DETAIL_ITEM_ABILITY,
    WIN_DETAIL_STATS,
    WIN_DETAIL_EFFECTS,
    WIN_DETAIL_DESCRIPTION,
    WIN_DETAIL_COUNT,
};

enum BattleStatus
{
    M_STATUS_NONE,
    M_STATUS_HARSH_SUNLIGHT,
    M_STATUS_RAIN,
    M_STATUS_SANDSTORM,
    M_STATUS_SNOW,
    M_STATUS_ELECTRIC_TERRAIN,
    M_STATUS_GRASSY_TERRAIN,
    M_STATUS_MISTY_TERRAIN,
    M_STATUS_PSYCHIC_TERRAIN,
    M_STATUS_TRICK_ROOM,
    M_STATUS_MAGIC_ROOM,
    M_STATUS_WONDER_ROOM,
    M_STATUS_GRAVITY,
    M_STATUS_MIST,
    M_STATUS_SAFEGUARD,
    M_STATUS_LUCKY_CHANT,
    M_STATUS_TAILWIND,
    M_STATUS_CRITICAL_HIT_BOOST,
    M_STATUS_CONFUSION,
    M_STATUS_INFATUATION,
    M_STATUS_NIGHTMARE,
    M_STATUS_DROWSY,
    M_STATUS_ENCORE,
    M_STATUS_TORMENT,
    M_STATUS_GRUDGE,
    M_STATUS_HEALING_PREVENTED,
    M_STATUS_IDENTIFIED,
    M_STATUS_MOVE_DISABLED,
    M_STATUS_CANT_ESCAPE,
    M_STATUS_LOCK_ON,
    M_STATUS_EMBARGO,
    M_STATUS_CHARGE,
    M_STATUS_TAUNT,
    M_STATUS_TELEKINESIS,
    M_STATUS_MAGNET_RISE,
    M_STATUS_WISH,
    M_STATUS_INGRAIN,
    M_STATUS_CURSE,
    M_STATUS_DESTINY_BOND,
    M_STATUS_BOUND,
    M_STATUS_BIDE,
    M_STATUS_FUTURE_ATTACK,
    M_STATUS_UPROAR,
    M_STATUS_AQUA_RING,
    M_STATUS_AUTOTOMIZE,
    M_STATUS_SMACK_DOWN,
    M_STATUS_FAIRY_LOCK,
    M_STATUS_RAINBOW,
    M_STATUS_SWAMP,
    M_STATUS_SEA_OF_FIRE,
    M_STATUS_THROAT_CHOP,
    M_STATUS_LASER_FOCUS,
    M_STATUS_TAR_SHOT,
    M_STATUS_OCTOLOCK,
    M_STATUS_FIXATED,
    M_STATUS_SPLINTERS,
    M_STATUS_OBSCURED,
    M_STATUS_PRIMED,
    M_STATUS_STANCE_SWAP,
    M_STATUS_SLOW_START,
    M_STATUS_SALT_CURE,
    M_STATUS_SYRUPY,
    M_STATUS_GOING_ALL_OUT,
    M_STATUS_HANGING_TOUGH,
    M_STATUS_POISONED,
    M_STATUS_BADLY_POISONED,
    M_STATUS_PARALYZED,
    M_STATUS_BURNED,
    M_STATUS_FROSTBITE,
    M_STATUS_STEALTH_ROCK,
    M_STATUS_SPIKES,
    M_STATUS_TOXIC_SPIKES,
    M_STATUS_STICKY_WEB,
    M_STATUS_LIGHT_SCREEN,
    M_STATUS_REFLECT,
    M_STATUS_AURORA_VEIL,
    M_STATUS_MUD_SPORT,
    M_STATUS_WATER_SPORT,
    M_STATUS_FORESTS_CURSE,
    M_STATUS_TRICK_OR_TREAT,
    M_STATUS_POWER_BOOST,
    M_STATUS_POWER_DROP,
    M_STATUS_GUARD_BOOST,
    M_STATUS_GUARD_DROP,
    M_STATUS_FOG,
    M_STATUS_EXTREMELY_HARSH_SUNLIGHT,
    M_STATUS_HEAVY_RAIN,
    M_STATUS_STRONG_WINDS,
    M_STATUS_OUTRAGE,
    M_STATUS_RAMPAGING,
    M_STATUS_PETAL_DANCE,
    M_STATUS_RAGING_FURY,
    M_STATUS_G_MAX_WILDFIRE,
    M_STATUS_G_MAX_VOLCALITH,
    M_STATUS_G_MAX_VINE_LASH,
    M_STATUS_G_MAX_CANNONADE,
    M_STATUS_WILD_MIGHT,
    M_STATUS_TERRIBLE_MIGHT,
    M_STATUS_TERRIFIC_MIGHT,
    M_STATUS_FRENZIED_MIGHT,
    M_STATUS_COUNT
};

#endif // GUARD_BATTLE_STATUS_MENU_CONSTANTS_H
