#ifndef GUARD_B_INFO_MENU_CONSTANTS_H
#define GUARD_B_INFO_MENU_CONSTANTS_H

enum BattleMenuStates
{
    B_INFO_STATE_CLEAR_PAGE,
    B_INFO_STATE_ENTER_PAGE,
    B_INFO_STATE_EXIT,
    B_INFO_STATE_HANDLE_INPUT,
    B_INFO_STATE_DONE,
};

enum BattleMenuPages
{
    B_INFO_PAGE_OVERVIEW,
    B_INFO_PAGE_DETAIL,
};

enum
{
    B_INFO_TEXT_COLOR_TRANSPARENT,
    B_INFO_TEXT_COLOR_BLACK,
    B_INFO_TEXT_COLOR_DARK_GRAY,
    B_INFO_TEXT_COLOR_LIGHT_GRAY,
    B_INFO_TEXT_COLOR_WHITE,
    B_INFO_TEXT_COLOR_LIGHT_BLUE,
    B_INFO_TEXT_COLOR_BLUE,
    B_INFO_TEXT_COLOR_PINK,
    B_INFO_TEXT_COLOR_DARK_PINK,
    B_INFO_TEXT_COLOR_GREEN,
    B_INFO_TEXT_COLOR_LIGHT_GREEN,
    B_INFO_TEXT_COLOR_RED,
    B_INFO_TEXT_COLOR_LIGHT_RED,
};

#define B_INFO_TEXT_PAL                15
#define B_INFO_TEXT_BG                 0
#define B_INFO_BACKDROP_BG             1
#define B_INFO_TILEMAP_WIDTH           32
#define B_INFO_TILEMAP_HEIGHT          32

#define B_INFO_BG_TILE_FILL             0x01
#define B_INFO_BG_TILE_HEADER_CORNER    0x02
#define B_INFO_BG_TILE_HEADER_SIDE      0x03
#define B_INFO_BG_TILE_HEADER_TOP       0x04
#define B_INFO_BG_TILE_HEADER_FILL      0x05
#define B_INFO_BG_TILE_CARD_INACTIVE_TL 0x06
#define B_INFO_BG_TILE_CARD_INACTIVE_TE 0x07
#define B_INFO_BG_TILE_CARD_INACTIVE_SE 0x08
#define B_INFO_BG_TILE_CARD_INACTIVE_IN 0x09
#define B_INFO_BG_TILE_CARD_INACTIVE_BL 0x0A
#define B_INFO_BG_TILE_CARD_INACTIVE_BE 0x0B
#define B_INFO_BG_TILE_CARD_ACTIVE_TL   0x0C
#define B_INFO_BG_TILE_CARD_ACTIVE_TE   0x0D
#define B_INFO_BG_TILE_CARD_ACTIVE_SE   0x0E
#define B_INFO_BG_TILE_CARD_ACTIVE_IN   0x0F
#define B_INFO_BG_TILE_CARD_ACTIVE_BL   0x10
#define B_INFO_BG_TILE_CARD_ACTIVE_BE   0x11
#define B_INFO_BG_TILE_SCROLLBAR_LANE   0x18
#define B_INFO_BG_TILE_SCROLLBAR_TOP    0x19
#define B_INFO_BG_TILE_SCROLLBAR_BOTTOM 0x1A

#define B_INFO_BG_ATTR_HFLIP           BG_TILE_H_FLIP(0)
#define B_INFO_BG_ATTR_VFLIP           BG_TILE_V_FLIP(0)

#define B_INFO_CARD_TILE_W             8
#define B_INFO_CARD_TILE_H             7
#define B_INFO_CARD_W                  (B_INFO_CARD_TILE_W * 8)
#define B_INFO_CARD_H                  (B_INFO_CARD_TILE_H * 8)

#define B_INFO_ROW_Y_ENEMY             24
#define B_INFO_ROW_Y_PLAYER            80

#define B_INFO_SAFE_LEFT_TILE          1
#define B_INFO_SAFE_RIGHT_TILE         30

#define B_INFO_LABEL_TILE_H            3
#define B_INFO_LABEL_H                 (B_INFO_LABEL_TILE_H * 8)
#define B_INFO_LABEL_BOTTOM_TILE_TOP   ((DISPLAY_HEIGHT / 8) - B_INFO_LABEL_TILE_H)

#define B_INFO_WIN_LABEL_TOP_BASE      1
#define B_INFO_WIN_LABEL_BOTTOM_BASE   (B_INFO_WIN_LABEL_TOP_BASE + (32 * B_INFO_LABEL_TILE_H))
#define B_INFO_WIN_ROW_ENEMY_BASE      (B_INFO_WIN_LABEL_BOTTOM_BASE + (32 * B_INFO_LABEL_TILE_H))
#define B_INFO_WIN_ROW_PLAYER_BASE     (B_INFO_WIN_ROW_ENEMY_BASE + (32 * B_INFO_CARD_TILE_H))
#define B_INFO_DETAIL_HEADER_WIN_W     15
#define B_INFO_DETAIL_HEADER_WIN_H     12
#define B_INFO_DETAIL_ITEM_WIN_W       9
#define B_INFO_DETAIL_ITEM_WIN_H       8
#define B_INFO_DETAIL_STATS_WIN_W      6
#define B_INFO_DETAIL_STATS_WIN_H      11
#define B_INFO_DETAIL_EFFECTS_WIN_W    13
#define B_INFO_DETAIL_EFFECTS_WIN_H    12
#define B_INFO_DETAIL_DESC_WIN_W       13
#define B_INFO_DETAIL_DESC_WIN_H       8
#define B_INFO_WIN_DETAIL_HEADER_BASE  1
#define B_INFO_WIN_DETAIL_ITEM_BASE    (B_INFO_WIN_DETAIL_HEADER_BASE + (B_INFO_DETAIL_HEADER_WIN_W * B_INFO_DETAIL_HEADER_WIN_H))
#define B_INFO_WIN_DETAIL_STATS_BASE   (B_INFO_WIN_DETAIL_ITEM_BASE + (B_INFO_DETAIL_ITEM_WIN_W * B_INFO_DETAIL_ITEM_WIN_H))
#define B_INFO_WIN_DETAIL_EFFECTS_BASE (B_INFO_WIN_DETAIL_STATS_BASE + (B_INFO_DETAIL_STATS_WIN_W * B_INFO_DETAIL_STATS_WIN_H))
#define B_INFO_WIN_DETAIL_DESC_BASE    (B_INFO_WIN_DETAIL_EFFECTS_BASE + (B_INFO_DETAIL_EFFECTS_WIN_W * B_INFO_DETAIL_EFFECTS_WIN_H))

#define B_INFO_GENDER_W                8

#define B_INFO_HP_BAR_TILE_TAG_BASE         0xD7C0
#define B_INFO_HP_BAR_PAL_TAG               0xD7C4
#define B_INFO_HP_BAR_ENDCAP_LEFT_TILE_TAG  0xD7C5
#define B_INFO_HP_BAR_ENDCAP_RIGHT_TILE_TAG 0xD7C6
#define B_INFO_HP_BAR_ENDCAP_PAL_TAG        0xD7C7

#define B_INFO_HEALTHBAR_PIXELS        48
#define B_INFO_DETAIL_HEALTHBAR_PIXELS 40
#define B_INFO_HP_BAR_SEGMENTS         6
#define B_INFO_DETAIL_HP_BAR_SEGMENTS  5

#define B_INFO_UPDATE_ICON_TILE_TAG              0xD7D0
#define B_INFO_CURSOR_TILE_TAG                   0xD7E0
#define B_INFO_DETAIL_GIMMICK_TILE_TAG           0xD7E2
#define B_INFO_DETAIL_HP_BAR_TILE_TAG            0xD7E3
#define B_INFO_DETAIL_TERA_TYPE_TILE_TAG         0xD7F0
#define B_INFO_OVERVIEW_GIMMICK_TILE_TAG_BASE    0xD7E4
#define B_INFO_DETAIL_STAT_PIP_DOT_TILE_TAG      0xD7E8
#define B_INFO_DETAIL_STAT_PIP_UP_TILE_TAG       0xD7E9
#define B_INFO_DETAIL_STAT_PIP_DOWN_TILE_TAG     0xD7EA
#define B_INFO_DETAIL_STAT_PIP_PAL_TAG           0xD7EF
#define B_INFO_DETAIL_STAT_PIP_PAL_NUM           12
#define B_INFO_DETAIL_EFFECTS_SCROLLBAR_TILE_TAG 0xD7EB
#define B_INFO_MOVE_TYPES_PAL_TAG_1              0xD7ED
#define B_INFO_MOVE_TYPES_PAL_TAG_2              0xD7EE

#define B_INFO_DETAIL_GIMMICK_W            8
#define B_INFO_DETAIL_GIMMICK_H            16
#define B_INFO_DETAIL_GIMMICK_GFX_SIZE     ((B_INFO_DETAIL_GIMMICK_W * B_INFO_DETAIL_GIMMICK_H) / 2)
#define B_INFO_DETAIL_STAT_ROW_COUNT       7
#define B_INFO_DETAIL_STAT_PIPS_PER_ROW    6
#define B_INFO_DETAIL_MAX_ACTIVE_EFFECTS   64
#define B_INFO_DETAIL_EFFECTS_VISIBLE_ROWS 6

#define B_INFO_DETAIL_TEXT_BUFFER_SIZE 512

#define TAG_STATUS_ICONS                1202

#define HEALTHBOX_GFX_HP_BAR_GREEN      3
#define HEALTHBOX_GFX_HP_BAR_YELLOW     50
#define HEALTHBOX_GFX_HP_BAR_RED        59

enum
{
    WIN_DETAIL_HEADER,
    WIN_DETAIL_ITEM_ABILITY,
    WIN_DETAIL_STATS,
    WIN_DETAIL_EFFECTS,
    WIN_DETAIL_DESCRIPTION,
    WIN_DETAIL_COUNT,
};

enum BattleInfoLabels
{
    INFO_NONE,
    INFO_HARSH_SUNLIGHT,
    INFO_RAIN,
    INFO_SANDSTORM,
    INFO_SNOW,
    INFO_ELECTRIC_TERRAIN,
    INFO_GRASSY_TERRAIN,
    INFO_MISTY_TERRAIN,
    INFO_PSYCHIC_TERRAIN,
    INFO_TRICK_ROOM,
    INFO_MAGIC_ROOM,
    INFO_WONDER_ROOM,
    INFO_GRAVITY,
    INFO_MIST,
    INFO_SAFEGUARD,
    INFO_LUCKY_CHANT,
    INFO_TAILWIND,
    INFO_CRITICAL_HIT_BOOST,
    INFO_CONFUSION,
    INFO_INFATUATION,
    INFO_NIGHTMARE,
    INFO_DROWSY,
    INFO_ENCORE,
    INFO_TORMENT,
    INFO_GRUDGE,
    INFO_HEALING_PREVENTED,
    INFO_IDENTIFIED,
    INFO_MOVE_DISABLED,
    INFO_CANT_ESCAPE,
    INFO_LOCK_ON,
    INFO_EMBARGO,
    INFO_CHARGE,
    INFO_TAUNT,
    INFO_TELEKINESIS,
    INFO_MAGNET_RISE,
    INFO_WISH,
    INFO_INGRAIN,
    INFO_CURSE,
    INFO_DESTINY_BOND,
    INFO_BOUND,
    INFO_BIDE,
    INFO_FUTURE_ATTACK,
    INFO_UPROAR,
    INFO_AQUA_RING,
    INFO_AUTOTOMIZE,
    INFO_SMACK_DOWN,
    INFO_FAIRY_LOCK,
    INFO_RAINBOW,
    INFO_SWAMP,
    INFO_SEA_OF_FIRE,
    INFO_THROAT_CHOP,
    INFO_LASER_FOCUS,
    INFO_TAR_SHOT,
    INFO_OCTOLOCK,
    INFO_FIXATED,
    INFO_SPLINTERS,
    INFO_OBSCURED,
    INFO_PRIMED,
    INFO_STANCE_SWAP,
    INFO_SLOW_START,
    INFO_SALT_CURE,
    INFO_SYRUPY,
    INFO_GOING_ALL_OUT,
    INFO_HANGING_TOUGH,
    INFO_POISONED,
    INFO_BADLY_POISONED,
    INFO_PARALYZED,
    INFO_BURNED,
    INFO_FROSTBITE,
    INFO_STEALTH_ROCK,
    INFO_SPIKES,
    INFO_TOXIC_SPIKES,
    INFO_STICKY_WEB,
    INFO_LIGHT_SCREEN,
    INFO_REFLECT,
    INFO_AURORA_VEIL,
    INFO_MUD_SPORT,
    INFO_WATER_SPORT,
    INFO_FORESTS_CURSE,
    INFO_TRICK_OR_TREAT,
    INFO_POWER_BOOST,
    INFO_POWER_DROP,
    INFO_GUARD_BOOST,
    INFO_GUARD_DROP,
    INFO_FOG,
    INFO_EXTREMELY_HARSH_SUNLIGHT,
    INFO_HEAVY_RAIN,
    INFO_STRONG_WINDS,
    INFO_OUTRAGE,
    INFO_RAMPAGING,
    INFO_PETAL_DANCE,
    INFO_RAGING_FURY,
    INFO_G_MAX_WILDFIRE,
    INFO_G_MAX_VOLCALITH,
    INFO_G_MAX_VINE_LASH,
    INFO_G_MAX_CANNONADE,
    INFO_WILD_MIGHT,
    INFO_TERRIBLE_MIGHT,
    INFO_TERRIFIC_MIGHT,
    INFO_FRENZIED_MIGHT,
    INFO_COUNT
};

#endif // GUARD_B_INFO_MENU_CONSTANTS_H
