#ifndef GUARD_CONSTANTS_BXPY_H
#define GUARD_CONSTANTS_BXPY_H

enum BXPYBattleTypes
{
    BXPY_BATTLE_SINGLE,
    BXPY_BATTLE_DOUBLE,
};

enum BXPYErrorCodes
{
    BXPY_ERROR_BRING_SIZE_TOO_LARGE,
    BXPY_ERROR_BRING_SIZE_NOT_ENOUGH,
    BXPY_ERROR_CLAUSE_SPECIES,
    BXPY_ERROR_CLAUSE_ITEM,
    BXPY_ERROR_CLAUSE_SPECIAL_POKEMON,
};

enum BXPYHealModes
{
    BXPY_HEAL_NEVER,
    BXPY_HEAL_BEFORE_BATTLE,
    BXPY_HEAL_AFTER_BATTLE,
    BXPY_HEAL_ALWAYS,
    BXPY_HEAL_COUNT,
};

enum BXPYTeamPreviewItemModes
{
    BXPY_ITEM_NO_VISIBILITY,
    BXPY_ITEM_SHOW_POSSESSION,
    BXPY_ITEM_SHOW_ITEM,
};

enum BXPYTeamPreviewSpeciesModes
{
    BXPY_SPECIES_HIDE,
    BXPY_SPECIES_SHOW_BASE,
    BXPY_SPECIES_SHOW_TRUE,
};

#define VAR_BXPY_PICK_SIZE                       VAR_0x8008
#define VAR_BXPY_BRING_SIZE                      VAR_0x800B
#define VAR_BXPY_PARTNER                         VAR_0x800A

#define SUMMARY_SCREEN_SPRITE_ID_TYPE_1          SPRITE_ARR_ID_TYPE
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_2          SPRITE_ARR_ID_TYPE + 1
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_TERA       SPRITE_ARR_ID_TYPE + 2
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_1     SPRITE_ARR_ID_TYPE
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_2     SPRITE_ARR_ID_TYPE + 1
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_3     SPRITE_ARR_ID_TYPE + 2
#define SUMMARY_SCREEN_SPRITE_ID_TYPE_MOVE_4     SPRITE_ARR_ID_TYPE + 3

enum BXPYBackgrounds
{
    BG0_BXPY_TEXT,
    BG1_BXPY_INFO,
    BG2_BXPY_PARTY_BG,
    BG3_BXPY_WALLPAPER,
    BG_BXPY_COUNT,
};

enum BXPYWindows
{
    WIN_BXPY_PLAYER_INFO,
    WIN_BXPY_ENEMY_NAME,
    WIN_BXPY_ENEMY_LEVELS,
    WIN_BXPY_HELP_BAR,
    WIN_BXPY_COUNT,
};

enum BXPYBgPalettes
{
    BXPY_PALETTE_BG_ID,
    BXPY_PALETTE_TEXT_ID,
};

#define BXPY_PALETTE_TEXT_SLOT BG_PLTT_ID(BXPY_PALETTE_TEXT_ID)
#define BXPY_PALETTE_BG_SLOT BG_PLTT_ID(BXPY_PALETTE_BG_ID)

enum BXPYFontColor
{
    BXPY_FONT_COLOR_BLACK,
    BXPY_FONT_COLOR_WHITE,
    BXPY_FONT_COLOR_COUNT,
};

enum BXPYSpriteIds
{
    BXPY_SPRITEID_CURSOR,
    BXPY_SPRITEID_PLAYER_MON_0,
    BXPY_SPRITEID_PLAYER_MON_1,
    BXPY_SPRITEID_PLAYER_MON_2,
    BXPY_SPRITEID_PLAYER_MON_3,
    BXPY_SPRITEID_PLAYER_MON_4,
    BXPY_SPRITEID_PLAYER_MON_5,
    BXPY_SPRITEID_PLAYER_HP_0,
    BXPY_SPRITEID_PLAYER_HP_1,
    BXPY_SPRITEID_PLAYER_HP_2,
    BXPY_SPRITEID_PLAYER_HP_3,
    BXPY_SPRITEID_PLAYER_HP_4,
    BXPY_SPRITEID_PLAYER_HP_5,
    BXPY_SPRITEID_PLAYER_SEX_0,
    BXPY_SPRITEID_PLAYER_SEX_1,
    BXPY_SPRITEID_PLAYER_SEX_2,
    BXPY_SPRITEID_PLAYER_SEX_3,
    BXPY_SPRITEID_PLAYER_SEX_4,
    BXPY_SPRITEID_PLAYER_SEX_5,
    BXPY_SPRITEID_PLAYER_SELECTED_0,
    BXPY_SPRITEID_PLAYER_SELECTED_1,
    BXPY_SPRITEID_PLAYER_SELECTED_2,
    BXPY_SPRITEID_PLAYER_SELECTED_3,
    BXPY_SPRITEID_PLAYER_SELECTED_4,
    BXPY_SPRITEID_PLAYER_SELECTED_5,
    BXPY_SPRITEID_ENEMY_MON_0,
    BXPY_SPRITEID_ENEMY_MON_1,
    BXPY_SPRITEID_ENEMY_MON_2,
    BXPY_SPRITEID_ENEMY_MON_3,
    BXPY_SPRITEID_ENEMY_MON_4,
    BXPY_SPRITEID_ENEMY_MON_5,
    BXPY_SPRITEID_ENEMY_SEX_0,
    BXPY_SPRITEID_ENEMY_SEX_1,
    BXPY_SPRITEID_ENEMY_SEX_2,
    BXPY_SPRITEID_ENEMY_SEX_3,
    BXPY_SPRITEID_ENEMY_SEX_4,
    BXPY_SPRITEID_ENEMY_SEX_5,
    BXPY_SPRITEID_COUNT,
};

enum BXPYSpriteTags
{
    BXPY_SPRITETAG_CURSOR = 6969,
    BXPY_SPRITETAG_HP,
    BXPY_SPRITETAG_SEX,
    BXPY_SPRITETAG_SELECTED,
    BXPY_SPRITETAG_COUNT,
};

enum BXPYPaletteTags
{
    BXPY_PALTAG_SPRITE = 42069,
};

#define FONT_BXPY_HELPBAR FONT_SMALL

#endif //GUARD_CONSTANTS_BXPY_H
