#ifndef GUARD_CONSTANTS_COUNTERPARTS_H
#define GUARD_CONSTANTS_COUNTERPARTS_H

#define COUNTERPART_NONE      0
#define COUNTERPART_BRENDAN   1
#define COUNTERPART_MAY       2
#define COUNTERPART_LEXY      3
#define COUNTERPART_JUSTIN    4
#define COUNTERPART_MAAM      5
#define COUNTERPART_SIR       6

#endif