#ifndef GUARD_CONSTANTS_DIALOGUE_STYLES_H
#define GUARD_CONSTANTS_DIALOGUE_STYLES_H

#define DIALOGUE_STYLE_DEFAULT   0
#define DIALOGUE_STYLE_SLOW      1
#define DIALOGUE_STYLE_FAST      2
#define DIALOGUE_STYLE_SLOW_TEXT 3
#define DIALOGUE_STYLE_FAST_TEXT 4
#define DIALOGUE_STYLE_COUNT     5

#endif // GUARD_CONSTANTS_DIALOGUE_STYLES_H
