#ifndef GUARD_FACTORY_POOLS_H
#define GUARD_FACTORY_POOLS_H

// Max total size of combined rank pools (conservative)
#define FACTORY_RANK_POOL_MAX_SIZE 512
#define MAX_SETS_PER_SPECIES 6

struct RankedSetMap {
    u16 species;
    u16 monIds[MAX_SETS_PER_SPECIES];
    u8 count;
};

extern u16 sFactoryPoolRank1[FACTORY_RANK_POOL_MAX_SIZE];
extern u16 sFactoryPoolRank2[FACTORY_RANK_POOL_MAX_SIZE];
extern u16 sFactoryPoolRank3[FACTORY_RANK_POOL_MAX_SIZE];
extern u16 sFactoryPoolRank4[FACTORY_RANK_POOL_MAX_SIZE];

extern u16 gFactoryPoolRank1Count;
extern u16 gFactoryPoolRank2Count;
extern u16 gFactoryPoolRank3Count;
extern u16 gFactoryPoolRank4Count;

void InitFactoryRankPools();

// Auto-generated Frontier Factory Pool Declarations
// BEGIN_GENERATED_FACTORY_POOLS
#define FRONTIER_FACTORY_POOL_GEN9NATIONALDEX_COUNT 710
extern const u16 gFrontierFactoryPool_GEN9NATIONALDEX[FRONTIER_FACTORY_POOL_GEN9NATIONALDEX_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9NATIONALDEXRU_COUNT 703
extern const u16 gFrontierFactoryPool_GEN9NATIONALDEXRU[FRONTIER_FACTORY_POOL_GEN9NATIONALDEXRU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9NATIONALDEXUU_COUNT 510
extern const u16 gFrontierFactoryPool_GEN9NATIONALDEXUU[FRONTIER_FACTORY_POOL_GEN9NATIONALDEXUU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9NU_COUNT 1476
extern const u16 gFrontierFactoryPool_GEN9NU[FRONTIER_FACTORY_POOL_GEN9NU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9OU_COUNT 697
extern const u16 gFrontierFactoryPool_GEN9OU[FRONTIER_FACTORY_POOL_GEN9OU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9PU_COUNT 545
extern const u16 gFrontierFactoryPool_GEN9PU[FRONTIER_FACTORY_POOL_GEN9PU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9RU_COUNT 608
extern const u16 gFrontierFactoryPool_GEN9RU[FRONTIER_FACTORY_POOL_GEN9RU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9UU_COUNT 245
extern const u16 gFrontierFactoryPool_GEN9UU[FRONTIER_FACTORY_POOL_GEN9UU_COUNT];
#define FRONTIER_FACTORY_POOL_GEN9ZU_COUNT 458
extern const u16 gFrontierFactoryPool_GEN9ZU[FRONTIER_FACTORY_POOL_GEN9ZU_COUNT];

#endif // GUARD_FACTORY_POOLS_H
