#ifndef GUARD_CONSTANTS_FACTORY_BOSS_H
#define GUARD_CONSTANTS_FACTORY_BOSS_H

#define FACTORY_BOSS_NONE    0
#define FACTORY_BOSS_STEVEN  1
#define FACTORY_BOSS_WALLY   2
#define FACTORY_BOSS_RED     3
#define FACTORY_BOSS_NORMAN  4
#define FACTORY_BOSS_COUNT   5

enum FactoryBossAcePolicy
{
    FACTORY_BOSS_ACE_NONE,
    FACTORY_BOSS_ACE_SPECIES_ANCHOR_LAST,
    FACTORY_BOSS_ACE_SPECIES_ANCHOR_FIRST,
};

#endif // GUARD_CONSTANTS_FACTORY_BOSS_H
