#ifndef GUARD_CONSTANTS_FIELD_MOVE_H
#define GUARD_CONSTANTS_FIELD_MOVE_H


enum FieldMove
{
    FIELD_MOVE_CUT,         // FLAG_BADGE01_GET
    FIELD_MOVE_FLASH,       // FLAG_BADGE02_GET
    FIELD_MOVE_ROCK_SMASH,  // FLAG_BADGE03_GET
    FIELD_MOVE_STRENGTH,    // FLAG_BADGE04_GET
    FIELD_MOVE_SURF,        // FLAG_BADGE05_GET
    FIELD_MOVE_FLY,         // FLAG_BADGE06_GET
    FIELD_MOVE_DIVE,        // FLAG_BADGE07_GET
    FIELD_MOVE_WATERFALL,   // FLAG_BADGE08_GET
    FIELD_MOVE_TELEPORT,
    FIELD_MOVE_DIG,
    FIELD_MOVE_SECRET_POWER,
    FIELD_MOVE_MILK_DRINK,
    FIELD_MOVE_SOFT_BOILED,
    FIELD_MOVE_SWEET_SCENT,
#if OW_DEFOG_FIELD_MOVE == TRUE
    FIELD_MOVE_DEFOG,
#endif
    FIELD_MOVES_COUNT
};


#endif //GUARD_CONSTANTS_FIELD_MOVE_H