#ifndef GUARD_CONSTANTS_GENERATIONAL_CHANGES_H
#define GUARD_CONSTANTS_GENERATIONAL_CHANGES_H

enum ConfigTag
{
    CONFIG_CRIT_CHANCE,
    CONFIG_CRIT_MULTIPLIER,
    CONFIG_FOCUS_ENERGY_CRIT_RATIO,
    CONFIG_PARALYSIS_SPEED,
    CONFIG_CONFUSION_SELF_DMG_CHANCE,
    CONFIG_MULTI_HIT_CHANCE,
    CONFIG_GALE_WINGS,
    CONFIG_HEAL_BELL_SOUNDPROOF,
    CONFIG_TELEPORT_BEHAVIOR,
    CONFIG_ABILITY_WEATHER,
    CONFIG_MOODY_STATS,
    CONFIG_BATTLE_BOND,
    CONFIG_ATE_MULTIPLIER,
    CONFIG_FELL_STINGER_STAT_RAISE,
    CONFIG_COUNT
};

#endif // GUARD_CONSTANTS_GENERATIONAL_CHANGES_H
