#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F + 1)
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F + 1)
    HEAL_LOCATION_PETALBURG_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_PETALBURG_CITY + 1)
    HEAL_LOCATION_SLATEPORT_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_SLATEPORT_CITY + 1)
    HEAL_LOCATION_MAUVILLE_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_MAUVILLE_CITY + 1)
    HEAL_LOCATION_RUSTBORO_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_RUSTBORO_CITY + 1)
    HEAL_LOCATION_FORTREE_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_FORTREE_CITY + 1)
    HEAL_LOCATION_LILYCOVE_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LILYCOVE_CITY + 1)
    HEAL_LOCATION_MOSSDEEP_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_MOSSDEEP_CITY + 1)
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_SOOTOPOLIS_CITY + 1)
    HEAL_LOCATION_EVER_GRANDE_CITY,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_EVER_GRANDE_CITY + 1)
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE + 1)
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE + 1)
    HEAL_LOCATION_OLDALE_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_OLDALE_TOWN + 1)
    HEAL_LOCATION_DEWFORD_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_DEWFORD_TOWN + 1)
    HEAL_LOCATION_LAVARIDGE_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_LAVARIDGE_TOWN + 1)
    HEAL_LOCATION_FALLARBOR_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_FALLARBOR_TOWN + 1)
    HEAL_LOCATION_VERDANTURF_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_VERDANTURF_TOWN + 1)
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_PACIFIDLOG_TOWN + 1)
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE + 1)
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR + 1)
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    #undef NUM_HEAL_LOCATIONS
    #define NUM_HEAL_LOCATIONS (HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST + 1)
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
