#ifndef GUARD_CONSTANTS_MOVE_DATA_IDS_H
#define GUARD_CONSTANTS_MOVE_DATA_IDS_H

enum MoveDataID
{
    MOVE_DATA_ID_EFFECT,
    MOVE_DATA_ID_POWER,
    MOVE_DATA_ID_TYPE,
    MOVE_DATA_ID_ACCURACY,
    MOVE_DATA_ID_PP,
};

#endif // GUARD_CONSTANTS_MOVE_DATA_IDS_H
