#ifndef GUARD_CONSTANTS_MOVE_RELEARNER_H
#define GUARD_CONSTANTS_MOVE_RELEARNER_H

// Max number of relearner moves shown in the list
// This number was increased to 255 to show more moves
#define MAX_RELEARNER_MOVES             0xFF

// Move Relearner menu change constants
enum MoveRelearnerStates
{
    MOVE_RELEARNER_LEVEL_UP_MOVES,
    MOVE_RELEARNER_EGG_MOVES,
    MOVE_RELEARNER_TM_MOVES,
    MOVE_RELEARNER_TUTOR_MOVES,
    MOVE_RELEARNER_COUNT,
};

enum RelearnMode
{
    RELEARN_MODE_NONE,
    RELEARN_MODE_LAVARIDGE_RELEARNER_SCRIPT,
    RELEARN_MODE_PSS_PAGE_BATTLE_MOVES,
    RELEARN_MODE_PSS_PAGE_CONTEST_MOVES,
    RELEARN_MODE_SCRIPT,
    RELEARN_MODE_PARTY_MENU,
};

#endif // GUARD_CONSTANTS_MOVE_RELEARNER_H
