#ifndef GUARD_CONSTANTS_PENTARA_TM_COMPAT_H
#define GUARD_CONSTANTS_PENTARA_TM_COMPAT_H

// Generated: legacy Emerald TM/HM names mapped onto Pentara TMs.

#define ITEM_TM_FOCUS_PUNCH ITEM_TM01
#define ITEM_TM_ROAR ITEM_TM01
#define ITEM_TM_HAIL ITEM_TM01
#define ITEM_TM_BULLET_SEED ITEM_TM01
#define ITEM_TM_HIDDEN_POWER ITEM_TM01
#define ITEM_TM_TAUNT ITEM_TM01
#define ITEM_TM_GIGA_DRAIN ITEM_TM01
#define ITEM_TM_SAFEGUARD ITEM_TM01
#define ITEM_TM_FRUSTRATION ITEM_TM01
#define ITEM_TM_IRON_TAIL ITEM_TM01
#define ITEM_TM_RETURN ITEM_TM01
#define ITEM_TM_DOUBLE_TEAM ITEM_TM01
#define ITEM_TM_TORMENT ITEM_TM01
#define ITEM_TM_FACADE ITEM_TM01
#define ITEM_TM_SECRET_POWER ITEM_TM01
#define ITEM_TM_ATTRACT ITEM_TM01
#define ITEM_TM_THIEF ITEM_TM01
#define ITEM_TM_STEEL_WING ITEM_TM01
#define ITEM_TM_SKILL_SWAP ITEM_TM01
#define ITEM_TM_SNATCH ITEM_TM01
#define ITEM_TM_OVERHEAT ITEM_TM01
#define ITEM_HM_SURF ITEM_TM_SURF

#endif
