#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

// National Pokédex order
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum NationalDexOrder
{
    NATIONAL_DEX_NONE,
    // Kanto
    NATIONAL_DEX_BULBASAUR,
    NATIONAL_DEX_IVYSAUR,
    NATIONAL_DEX_VENUSAUR,
    NATIONAL_DEX_CHARMANDER,
    NATIONAL_DEX_CHARMELEON,
    NATIONAL_DEX_CHARIZARD,
    NATIONAL_DEX_SQUIRTLE,
    NATIONAL_DEX_WARTORTLE,
    NATIONAL_DEX_BLASTOISE,
    NATIONAL_DEX_CATERPIE,
    NATIONAL_DEX_METAPOD,
    NATIONAL_DEX_BUTTERFREE,
    NATIONAL_DEX_WEEDLE,
    NATIONAL_DEX_KAKUNA,
    NATIONAL_DEX_BEEDRILL,
    NATIONAL_DEX_PIDGEY,
    NATIONAL_DEX_PIDGEOTTO,
    NATIONAL_DEX_PIDGEOT,
    NATIONAL_DEX_RATTATA,
    NATIONAL_DEX_RATICATE,
    NATIONAL_DEX_SPEAROW,
    NATIONAL_DEX_FEAROW,
    NATIONAL_DEX_EKANS,
    NATIONAL_DEX_ARBOK,
    NATIONAL_DEX_PIKACHU,
    NATIONAL_DEX_RAICHU,
    NATIONAL_DEX_SANDSHREW,
    NATIONAL_DEX_SANDSLASH,
    NATIONAL_DEX_NIDORAN_F,
    NATIONAL_DEX_NIDORINA,
    NATIONAL_DEX_NIDOQUEEN,
    NATIONAL_DEX_NIDORAN_M,
    NATIONAL_DEX_NIDORINO,
    NATIONAL_DEX_NIDOKING,
    NATIONAL_DEX_CLEFAIRY,
    NATIONAL_DEX_CLEFABLE,
    NATIONAL_DEX_VULPIX,
    NATIONAL_DEX_NINETALES,
    NATIONAL_DEX_JIGGLYPUFF,
    NATIONAL_DEX_WIGGLYTUFF,
    NATIONAL_DEX_ZUBAT,
    NATIONAL_DEX_GOLBAT,
    NATIONAL_DEX_ODDISH,
    NATIONAL_DEX_GLOOM,
    NATIONAL_DEX_VILEPLUME,
    NATIONAL_DEX_PARAS,
    NATIONAL_DEX_PARASECT,
    NATIONAL_DEX_VENONAT,
    NATIONAL_DEX_VENOMOTH,
    NATIONAL_DEX_DIGLETT,
    NATIONAL_DEX_DUGTRIO,
    NATIONAL_DEX_MEOWTH,
    NATIONAL_DEX_PERSIAN,
    NATIONAL_DEX_PSYDUCK,
    NATIONAL_DEX_GOLDUCK,
    NATIONAL_DEX_MANKEY,
    NATIONAL_DEX_PRIMEAPE,
    NATIONAL_DEX_GROWLITHE,
    NATIONAL_DEX_ARCANINE,
    NATIONAL_DEX_POLIWAG,
    NATIONAL_DEX_POLIWHIRL,
    NATIONAL_DEX_POLIWRATH,
    NATIONAL_DEX_ABRA,
    NATIONAL_DEX_KADABRA,
    NATIONAL_DEX_ALAKAZAM,
    NATIONAL_DEX_MACHOP,
    NATIONAL_DEX_MACHOKE,
    NATIONAL_DEX_MACHAMP,
    NATIONAL_DEX_BELLSPROUT,
    NATIONAL_DEX_WEEPINBELL,
    NATIONAL_DEX_VICTREEBEL,
    NATIONAL_DEX_TENTACOOL,
    NATIONAL_DEX_TENTACRUEL,
    NATIONAL_DEX_GEODUDE,
    NATIONAL_DEX_GRAVELER,
    NATIONAL_DEX_GOLEM,
    NATIONAL_DEX_PONYTA,
    NATIONAL_DEX_RAPIDASH,
    NATIONAL_DEX_SLOWPOKE,
    NATIONAL_DEX_SLOWBRO,
    NATIONAL_DEX_MAGNEMITE,
    NATIONAL_DEX_MAGNETON,
    NATIONAL_DEX_FARFETCHD,
    NATIONAL_DEX_DODUO,
    NATIONAL_DEX_DODRIO,
    NATIONAL_DEX_SEEL,
    NATIONAL_DEX_DEWGONG,
    NATIONAL_DEX_GRIMER,
    NATIONAL_DEX_MUK,
    NATIONAL_DEX_SHELLDER,
    NATIONAL_DEX_CLOYSTER,
    NATIONAL_DEX_GASTLY,
    NATIONAL_DEX_HAUNTER,
    NATIONAL_DEX_GENGAR,
    NATIONAL_DEX_ONIX,
    NATIONAL_DEX_DROWZEE,
    NATIONAL_DEX_HYPNO,
    NATIONAL_DEX_KRABBY,
    NATIONAL_DEX_KINGLER,
    NATIONAL_DEX_VOLTORB,
    NATIONAL_DEX_ELECTRODE,
    NATIONAL_DEX_EXEGGCUTE,
    NATIONAL_DEX_EXEGGUTOR,
    NATIONAL_DEX_CUBONE,
    NATIONAL_DEX_MAROWAK,
    NATIONAL_DEX_HITMONLEE,
    NATIONAL_DEX_HITMONCHAN,
    NATIONAL_DEX_LICKITUNG,
    NATIONAL_DEX_KOFFING,
    NATIONAL_DEX_WEEZING,
    NATIONAL_DEX_RHYHORN,
    NATIONAL_DEX_RHYDON,
    NATIONAL_DEX_CHANSEY,
    NATIONAL_DEX_TANGELA,
    NATIONAL_DEX_KANGASKHAN,
    NATIONAL_DEX_HORSEA,
    NATIONAL_DEX_SEADRA,
    NATIONAL_DEX_GOLDEEN,
    NATIONAL_DEX_SEAKING,
    NATIONAL_DEX_STARYU,
    NATIONAL_DEX_STARMIE,
    NATIONAL_DEX_MR_MIME,
    NATIONAL_DEX_SCYTHER,
    NATIONAL_DEX_JYNX,
    NATIONAL_DEX_ELECTABUZZ,
    NATIONAL_DEX_MAGMAR,
    NATIONAL_DEX_PINSIR,
    NATIONAL_DEX_TAUROS,
    NATIONAL_DEX_MAGIKARP,
    NATIONAL_DEX_GYARADOS,
    NATIONAL_DEX_LAPRAS,
    NATIONAL_DEX_DITTO,
    NATIONAL_DEX_EEVEE,
    NATIONAL_DEX_VAPOREON,
    NATIONAL_DEX_JOLTEON,
    NATIONAL_DEX_FLAREON,
    NATIONAL_DEX_PORYGON,
    NATIONAL_DEX_OMANYTE,
    NATIONAL_DEX_OMASTAR,
    NATIONAL_DEX_KABUTO,
    NATIONAL_DEX_KABUTOPS,
    NATIONAL_DEX_AERODACTYL,
    NATIONAL_DEX_SNORLAX,
    NATIONAL_DEX_ARTICUNO,
    NATIONAL_DEX_ZAPDOS,
    NATIONAL_DEX_MOLTRES,
    NATIONAL_DEX_DRATINI,
    NATIONAL_DEX_DRAGONAIR,
    NATIONAL_DEX_DRAGONITE,
    NATIONAL_DEX_MEWTWO,
    NATIONAL_DEX_MEW,
    // Johto
    NATIONAL_DEX_CHIKORITA,
    NATIONAL_DEX_BAYLEEF,
    NATIONAL_DEX_MEGANIUM,
    NATIONAL_DEX_CYNDAQUIL,
    NATIONAL_DEX_QUILAVA,
    NATIONAL_DEX_TYPHLOSION,
    NATIONAL_DEX_TOTODILE,
    NATIONAL_DEX_CROCONAW,
    NATIONAL_DEX_FERALIGATR,
    NATIONAL_DEX_SENTRET,
    NATIONAL_DEX_FURRET,
    NATIONAL_DEX_HOOTHOOT,
    NATIONAL_DEX_NOCTOWL,
    NATIONAL_DEX_LEDYBA,
    NATIONAL_DEX_LEDIAN,
    NATIONAL_DEX_SPINARAK,
    NATIONAL_DEX_ARIADOS,
    NATIONAL_DEX_CROBAT,
    NATIONAL_DEX_CHINCHOU,
    NATIONAL_DEX_LANTURN,
    NATIONAL_DEX_PICHU,
    NATIONAL_DEX_CLEFFA,
    NATIONAL_DEX_IGGLYBUFF,
    NATIONAL_DEX_TOGEPI,
    NATIONAL_DEX_TOGETIC,
    NATIONAL_DEX_NATU,
    NATIONAL_DEX_XATU,
    NATIONAL_DEX_MAREEP,
    NATIONAL_DEX_FLAAFFY,
    NATIONAL_DEX_AMPHAROS,
    NATIONAL_DEX_BELLOSSOM,
    NATIONAL_DEX_MARILL,
    NATIONAL_DEX_AZUMARILL,
    NATIONAL_DEX_SUDOWOODO,
    NATIONAL_DEX_POLITOED,
    NATIONAL_DEX_HOPPIP,
    NATIONAL_DEX_SKIPLOOM,
    NATIONAL_DEX_JUMPLUFF,
    NATIONAL_DEX_AIPOM,
    NATIONAL_DEX_SUNKERN,
    NATIONAL_DEX_SUNFLORA,
    NATIONAL_DEX_YANMA,
    NATIONAL_DEX_WOOPER,
    NATIONAL_DEX_QUAGSIRE,
    NATIONAL_DEX_ESPEON,
    NATIONAL_DEX_UMBREON,
    NATIONAL_DEX_MURKROW,
    NATIONAL_DEX_SLOWKING,
    NATIONAL_DEX_MISDREAVUS,
    NATIONAL_DEX_UNOWN,
    NATIONAL_DEX_WOBBUFFET,
    NATIONAL_DEX_GIRAFARIG,
    NATIONAL_DEX_PINECO,
    NATIONAL_DEX_FORRETRESS,
    NATIONAL_DEX_DUNSPARCE,
    NATIONAL_DEX_GLIGAR,
    NATIONAL_DEX_STEELIX,
    NATIONAL_DEX_SNUBBULL,
    NATIONAL_DEX_GRANBULL,
    NATIONAL_DEX_QWILFISH,
    NATIONAL_DEX_SCIZOR,
    NATIONAL_DEX_SHUCKLE,
    NATIONAL_DEX_HERACROSS,
    NATIONAL_DEX_SNEASEL,
    NATIONAL_DEX_TEDDIURSA,
    NATIONAL_DEX_URSARING,
    NATIONAL_DEX_SLUGMA,
    NATIONAL_DEX_MAGCARGO,
    NATIONAL_DEX_SWINUB,
    NATIONAL_DEX_PILOSWINE,
    NATIONAL_DEX_CORSOLA,
    NATIONAL_DEX_REMORAID,
    NATIONAL_DEX_OCTILLERY,
    NATIONAL_DEX_DELIBIRD,
    NATIONAL_DEX_MANTINE,
    NATIONAL_DEX_SKARMORY,
    NATIONAL_DEX_HOUNDOUR,
    NATIONAL_DEX_HOUNDOOM,
    NATIONAL_DEX_KINGDRA,
    NATIONAL_DEX_PHANPY,
    NATIONAL_DEX_DONPHAN,
    NATIONAL_DEX_PORYGON2,
    NATIONAL_DEX_STANTLER,
    NATIONAL_DEX_SMEARGLE,
    NATIONAL_DEX_TYROGUE,
    NATIONAL_DEX_HITMONTOP,
    NATIONAL_DEX_SMOOCHUM,
    NATIONAL_DEX_ELEKID,
    NATIONAL_DEX_MAGBY,
    NATIONAL_DEX_MILTANK,
    NATIONAL_DEX_BLISSEY,
    NATIONAL_DEX_RAIKOU,
    NATIONAL_DEX_ENTEI,
    NATIONAL_DEX_SUICUNE,
    NATIONAL_DEX_LARVITAR,
    NATIONAL_DEX_PUPITAR,
    NATIONAL_DEX_TYRANITAR,
    NATIONAL_DEX_LUGIA,
    NATIONAL_DEX_HO_OH,
    NATIONAL_DEX_CELEBI,
    // Hoenn
    NATIONAL_DEX_TREECKO,
    NATIONAL_DEX_GROVYLE,
    NATIONAL_DEX_SCEPTILE,
    NATIONAL_DEX_TORCHIC,
    NATIONAL_DEX_COMBUSKEN,
    NATIONAL_DEX_BLAZIKEN,
    NATIONAL_DEX_MUDKIP,
    NATIONAL_DEX_MARSHTOMP,
    NATIONAL_DEX_SWAMPERT,
    NATIONAL_DEX_POOCHYENA,
    NATIONAL_DEX_MIGHTYENA,
    NATIONAL_DEX_ZIGZAGOON,
    NATIONAL_DEX_LINOONE,
    NATIONAL_DEX_WURMPLE,
    NATIONAL_DEX_SILCOON,
    NATIONAL_DEX_BEAUTIFLY,
    NATIONAL_DEX_CASCOON,
    NATIONAL_DEX_DUSTOX,
    NATIONAL_DEX_LOTAD,
    NATIONAL_DEX_LOMBRE,
    NATIONAL_DEX_LUDICOLO,
    NATIONAL_DEX_SEEDOT,
    NATIONAL_DEX_NUZLEAF,
    NATIONAL_DEX_SHIFTRY,
    NATIONAL_DEX_TAILLOW,
    NATIONAL_DEX_SWELLOW,
    NATIONAL_DEX_WINGULL,
    NATIONAL_DEX_PELIPPER,
    NATIONAL_DEX_RALTS,
    NATIONAL_DEX_KIRLIA,
    NATIONAL_DEX_GARDEVOIR,
    NATIONAL_DEX_SURSKIT,
    NATIONAL_DEX_MASQUERAIN,
    NATIONAL_DEX_SHROOMISH,
    NATIONAL_DEX_BRELOOM,
    NATIONAL_DEX_SLAKOTH,
    NATIONAL_DEX_VIGOROTH,
    NATIONAL_DEX_SLAKING,
    NATIONAL_DEX_NINCADA,
    NATIONAL_DEX_NINJASK,
    NATIONAL_DEX_SHEDINJA,
    NATIONAL_DEX_WHISMUR,
    NATIONAL_DEX_LOUDRED,
    NATIONAL_DEX_EXPLOUD,
    NATIONAL_DEX_MAKUHITA,
    NATIONAL_DEX_HARIYAMA,
    NATIONAL_DEX_AZURILL,
    NATIONAL_DEX_NOSEPASS,
    NATIONAL_DEX_SKITTY,
    NATIONAL_DEX_DELCATTY,
    NATIONAL_DEX_SABLEYE,
    NATIONAL_DEX_MAWILE,
    NATIONAL_DEX_ARON,
    NATIONAL_DEX_LAIRON,
    NATIONAL_DEX_AGGRON,
    NATIONAL_DEX_MEDITITE,
    NATIONAL_DEX_MEDICHAM,
    NATIONAL_DEX_ELECTRIKE,
    NATIONAL_DEX_MANECTRIC,
    NATIONAL_DEX_PLUSLE,
    NATIONAL_DEX_MINUN,
    NATIONAL_DEX_VOLBEAT,
    NATIONAL_DEX_ILLUMISE,
    NATIONAL_DEX_ROSELIA,
    NATIONAL_DEX_GULPIN,
    NATIONAL_DEX_SWALOT,
    NATIONAL_DEX_CARVANHA,
    NATIONAL_DEX_SHARPEDO,
    NATIONAL_DEX_WAILMER,
    NATIONAL_DEX_WAILORD,
    NATIONAL_DEX_NUMEL,
    NATIONAL_DEX_CAMERUPT,
    NATIONAL_DEX_TORKOAL,
    NATIONAL_DEX_SPOINK,
    NATIONAL_DEX_GRUMPIG,
    NATIONAL_DEX_SPINDA,
    NATIONAL_DEX_TRAPINCH,
    NATIONAL_DEX_VIBRAVA,
    NATIONAL_DEX_FLYGON,
    NATIONAL_DEX_CACNEA,
    NATIONAL_DEX_CACTURNE,
    NATIONAL_DEX_SWABLU,
    NATIONAL_DEX_ALTARIA,
    NATIONAL_DEX_ZANGOOSE,
    NATIONAL_DEX_SEVIPER,
    NATIONAL_DEX_LUNATONE,
    NATIONAL_DEX_SOLROCK,
    NATIONAL_DEX_BARBOACH,
    NATIONAL_DEX_WHISCASH,
    NATIONAL_DEX_CORPHISH,
    NATIONAL_DEX_CRAWDAUNT,
    NATIONAL_DEX_BALTOY,
    NATIONAL_DEX_CLAYDOL,
    NATIONAL_DEX_LILEEP,
    NATIONAL_DEX_CRADILY,
    NATIONAL_DEX_ANORITH,
    NATIONAL_DEX_ARMALDO,
    NATIONAL_DEX_FEEBAS,
    NATIONAL_DEX_MILOTIC,
    NATIONAL_DEX_CASTFORM,
    NATIONAL_DEX_KECLEON,
    NATIONAL_DEX_SHUPPET,
    NATIONAL_DEX_BANETTE,
    NATIONAL_DEX_DUSKULL,
    NATIONAL_DEX_DUSCLOPS,
    NATIONAL_DEX_TROPIUS,
    NATIONAL_DEX_CHIMECHO,
    NATIONAL_DEX_ABSOL,
    NATIONAL_DEX_WYNAUT,
    NATIONAL_DEX_SNORUNT,
    NATIONAL_DEX_GLALIE,
    NATIONAL_DEX_SPHEAL,
    NATIONAL_DEX_SEALEO,
    NATIONAL_DEX_WALREIN,
    NATIONAL_DEX_CLAMPERL,
    NATIONAL_DEX_HUNTAIL,
    NATIONAL_DEX_GOREBYSS,
    NATIONAL_DEX_RELICANTH,
    NATIONAL_DEX_LUVDISC,
    NATIONAL_DEX_BAGON,
    NATIONAL_DEX_SHELGON,
    NATIONAL_DEX_SALAMENCE,
    NATIONAL_DEX_BELDUM,
    NATIONAL_DEX_METANG,
    NATIONAL_DEX_METAGROSS,
    NATIONAL_DEX_REGIROCK,
    NATIONAL_DEX_REGICE,
    NATIONAL_DEX_REGISTEEL,
    NATIONAL_DEX_LATIAS,
    NATIONAL_DEX_LATIOS,
    NATIONAL_DEX_KYOGRE,
    NATIONAL_DEX_GROUDON,
    NATIONAL_DEX_RAYQUAZA,
    NATIONAL_DEX_JIRACHI,
    NATIONAL_DEX_DEOXYS,
    // Sinnoh
    NATIONAL_DEX_TURTWIG,
    NATIONAL_DEX_GROTLE,
    NATIONAL_DEX_TORTERRA,
    NATIONAL_DEX_CHIMCHAR,
    NATIONAL_DEX_MONFERNO,
    NATIONAL_DEX_INFERNAPE,
    NATIONAL_DEX_PIPLUP,
    NATIONAL_DEX_PRINPLUP,
    NATIONAL_DEX_EMPOLEON,
    NATIONAL_DEX_STARLY,
    NATIONAL_DEX_STARAVIA,
    NATIONAL_DEX_STARAPTOR,
    NATIONAL_DEX_BIDOOF,
    NATIONAL_DEX_BIBAREL,
    NATIONAL_DEX_KRICKETOT,
    NATIONAL_DEX_KRICKETUNE,
    NATIONAL_DEX_SHINX,
    NATIONAL_DEX_LUXIO,
    NATIONAL_DEX_LUXRAY,
    NATIONAL_DEX_BUDEW,
    NATIONAL_DEX_ROSERADE,
    NATIONAL_DEX_CRANIDOS,
    NATIONAL_DEX_RAMPARDOS,
    NATIONAL_DEX_SHIELDON,
    NATIONAL_DEX_BASTIODON,
    NATIONAL_DEX_BURMY,
    NATIONAL_DEX_WORMADAM,
    NATIONAL_DEX_MOTHIM,
    NATIONAL_DEX_COMBEE,
    NATIONAL_DEX_VESPIQUEN,
    NATIONAL_DEX_PACHIRISU,
    NATIONAL_DEX_BUIZEL,
    NATIONAL_DEX_FLOATZEL,
    NATIONAL_DEX_CHERUBI,
    NATIONAL_DEX_CHERRIM,
    NATIONAL_DEX_SHELLOS,
    NATIONAL_DEX_GASTRODON,
    NATIONAL_DEX_AMBIPOM,
    NATIONAL_DEX_DRIFLOON,
    NATIONAL_DEX_DRIFBLIM,
    NATIONAL_DEX_BUNEARY,
    NATIONAL_DEX_LOPUNNY,
    NATIONAL_DEX_MISMAGIUS,
    NATIONAL_DEX_HONCHKROW,
    NATIONAL_DEX_GLAMEOW,
    NATIONAL_DEX_PURUGLY,
    NATIONAL_DEX_CHINGLING,
    NATIONAL_DEX_STUNKY,
    NATIONAL_DEX_SKUNTANK,
    NATIONAL_DEX_BRONZOR,
    NATIONAL_DEX_BRONZONG,
    NATIONAL_DEX_BONSLY,
    NATIONAL_DEX_MIME_JR,
    NATIONAL_DEX_HAPPINY,
    NATIONAL_DEX_CHATOT,
    NATIONAL_DEX_SPIRITOMB,
    NATIONAL_DEX_GIBLE,
    NATIONAL_DEX_GABITE,
    NATIONAL_DEX_GARCHOMP,
    NATIONAL_DEX_MUNCHLAX,
    NATIONAL_DEX_RIOLU,
    NATIONAL_DEX_LUCARIO,
    NATIONAL_DEX_HIPPOPOTAS,
    NATIONAL_DEX_HIPPOWDON,
    NATIONAL_DEX_SKORUPI,
    NATIONAL_DEX_DRAPION,
    NATIONAL_DEX_CROAGUNK,
    NATIONAL_DEX_TOXICROAK,
    NATIONAL_DEX_CARNIVINE,
    NATIONAL_DEX_FINNEON,
    NATIONAL_DEX_LUMINEON,
    NATIONAL_DEX_MANTYKE,
    NATIONAL_DEX_SNOVER,
    NATIONAL_DEX_ABOMASNOW,
    NATIONAL_DEX_WEAVILE,
    NATIONAL_DEX_MAGNEZONE,
    NATIONAL_DEX_LICKILICKY,
    NATIONAL_DEX_RHYPERIOR,
    NATIONAL_DEX_TANGROWTH,
    NATIONAL_DEX_ELECTIVIRE,
    NATIONAL_DEX_MAGMORTAR,
    NATIONAL_DEX_TOGEKISS,
    NATIONAL_DEX_YANMEGA,
    NATIONAL_DEX_LEAFEON,
    NATIONAL_DEX_GLACEON,
    NATIONAL_DEX_GLISCOR,
    NATIONAL_DEX_MAMOSWINE,
    NATIONAL_DEX_PORYGON_Z,
    NATIONAL_DEX_GALLADE,
    NATIONAL_DEX_PROBOPASS,
    NATIONAL_DEX_DUSKNOIR,
    NATIONAL_DEX_FROSLASS,
    NATIONAL_DEX_ROTOM,
    NATIONAL_DEX_UXIE,
    NATIONAL_DEX_MESPRIT,
    NATIONAL_DEX_AZELF,
    NATIONAL_DEX_DIALGA,
    NATIONAL_DEX_PALKIA,
    NATIONAL_DEX_HEATRAN,
    NATIONAL_DEX_REGIGIGAS,
    NATIONAL_DEX_GIRATINA,
    NATIONAL_DEX_CRESSELIA,
    NATIONAL_DEX_PHIONE,
    NATIONAL_DEX_MANAPHY,
    NATIONAL_DEX_DARKRAI,
    NATIONAL_DEX_SHAYMIN,
    NATIONAL_DEX_ARCEUS,
    // Unova
    NATIONAL_DEX_VICTINI,
    NATIONAL_DEX_SNIVY,
    NATIONAL_DEX_SERVINE,
    NATIONAL_DEX_SERPERIOR,
    NATIONAL_DEX_TEPIG,
    NATIONAL_DEX_PIGNITE,
    NATIONAL_DEX_EMBOAR,
    NATIONAL_DEX_OSHAWOTT,
    NATIONAL_DEX_DEWOTT,
    NATIONAL_DEX_SAMUROTT,
    NATIONAL_DEX_PATRAT,
    NATIONAL_DEX_WATCHOG,
    NATIONAL_DEX_LILLIPUP,
    NATIONAL_DEX_HERDIER,
    NATIONAL_DEX_STOUTLAND,
    NATIONAL_DEX_PURRLOIN,
    NATIONAL_DEX_LIEPARD,
    NATIONAL_DEX_PANSAGE,
    NATIONAL_DEX_SIMISAGE,
    NATIONAL_DEX_PANSEAR,
    NATIONAL_DEX_SIMISEAR,
    NATIONAL_DEX_PANPOUR,
    NATIONAL_DEX_SIMIPOUR,
    NATIONAL_DEX_MUNNA,
    NATIONAL_DEX_MUSHARNA,
    NATIONAL_DEX_PIDOVE,
    NATIONAL_DEX_TRANQUILL,
    NATIONAL_DEX_UNFEZANT,
    NATIONAL_DEX_BLITZLE,
    NATIONAL_DEX_ZEBSTRIKA,
    NATIONAL_DEX_ROGGENROLA,
    NATIONAL_DEX_BOLDORE,
    NATIONAL_DEX_GIGALITH,
    NATIONAL_DEX_WOOBAT,
    NATIONAL_DEX_SWOOBAT,
    NATIONAL_DEX_DRILBUR,
    NATIONAL_DEX_EXCADRILL,
    NATIONAL_DEX_AUDINO,
    NATIONAL_DEX_TIMBURR,
    NATIONAL_DEX_GURDURR,
    NATIONAL_DEX_CONKELDURR,
    NATIONAL_DEX_TYMPOLE,
    NATIONAL_DEX_PALPITOAD,
    NATIONAL_DEX_SEISMITOAD,
    NATIONAL_DEX_THROH,
    NATIONAL_DEX_SAWK,
    NATIONAL_DEX_SEWADDLE,
    NATIONAL_DEX_SWADLOON,
    NATIONAL_DEX_LEAVANNY,
    NATIONAL_DEX_VENIPEDE,
    NATIONAL_DEX_WHIRLIPEDE,
    NATIONAL_DEX_SCOLIPEDE,
    NATIONAL_DEX_COTTONEE,
    NATIONAL_DEX_WHIMSICOTT,
    NATIONAL_DEX_PETILIL,
    NATIONAL_DEX_LILLIGANT,
    NATIONAL_DEX_BASCULIN,
    NATIONAL_DEX_SANDILE,
    NATIONAL_DEX_KROKOROK,
    NATIONAL_DEX_KROOKODILE,
    NATIONAL_DEX_DARUMAKA,
    NATIONAL_DEX_DARMANITAN,
    NATIONAL_DEX_MARACTUS,
    NATIONAL_DEX_DWEBBLE,
    NATIONAL_DEX_CRUSTLE,
    NATIONAL_DEX_SCRAGGY,
    NATIONAL_DEX_SCRAFTY,
    NATIONAL_DEX_SIGILYPH,
    NATIONAL_DEX_YAMASK,
    NATIONAL_DEX_COFAGRIGUS,
    NATIONAL_DEX_TIRTOUGA,
    NATIONAL_DEX_CARRACOSTA,
    NATIONAL_DEX_ARCHEN,
    NATIONAL_DEX_ARCHEOPS,
    NATIONAL_DEX_TRUBBISH,
    NATIONAL_DEX_GARBODOR,
    NATIONAL_DEX_ZORUA,
    NATIONAL_DEX_ZOROARK,
    NATIONAL_DEX_MINCCINO,
    NATIONAL_DEX_CINCCINO,
    NATIONAL_DEX_GOTHITA,
    NATIONAL_DEX_GOTHORITA,
    NATIONAL_DEX_GOTHITELLE,
    NATIONAL_DEX_SOLOSIS,
    NATIONAL_DEX_DUOSION,
    NATIONAL_DEX_REUNICLUS,
    NATIONAL_DEX_DUCKLETT,
    NATIONAL_DEX_SWANNA,
    NATIONAL_DEX_VANILLITE,
    NATIONAL_DEX_VANILLISH,
    NATIONAL_DEX_VANILLUXE,
    NATIONAL_DEX_DEERLING,
    NATIONAL_DEX_SAWSBUCK,
    NATIONAL_DEX_EMOLGA,
    NATIONAL_DEX_KARRABLAST,
    NATIONAL_DEX_ESCAVALIER,
    NATIONAL_DEX_FOONGUS,
    NATIONAL_DEX_AMOONGUSS,
    NATIONAL_DEX_FRILLISH,
    NATIONAL_DEX_JELLICENT,
    NATIONAL_DEX_ALOMOMOLA,
    NATIONAL_DEX_JOLTIK,
    NATIONAL_DEX_GALVANTULA,
    NATIONAL_DEX_FERROSEED,
    NATIONAL_DEX_FERROTHORN,
    NATIONAL_DEX_KLINK,
    NATIONAL_DEX_KLANG,
    NATIONAL_DEX_KLINKLANG,
    NATIONAL_DEX_TYNAMO,
    NATIONAL_DEX_EELEKTRIK,
    NATIONAL_DEX_EELEKTROSS,
    NATIONAL_DEX_ELGYEM,
    NATIONAL_DEX_BEHEEYEM,
    NATIONAL_DEX_LITWICK,
    NATIONAL_DEX_LAMPENT,
    NATIONAL_DEX_CHANDELURE,
    NATIONAL_DEX_AXEW,
    NATIONAL_DEX_FRAXURE,
    NATIONAL_DEX_HAXORUS,
    NATIONAL_DEX_CUBCHOO,
    NATIONAL_DEX_BEARTIC,
    NATIONAL_DEX_CRYOGONAL,
    NATIONAL_DEX_SHELMET,
    NATIONAL_DEX_ACCELGOR,
    NATIONAL_DEX_STUNFISK,
    NATIONAL_DEX_MIENFOO,
    NATIONAL_DEX_MIENSHAO,
    NATIONAL_DEX_DRUDDIGON,
    NATIONAL_DEX_GOLETT,
    NATIONAL_DEX_GOLURK,
    NATIONAL_DEX_PAWNIARD,
    NATIONAL_DEX_BISHARP,
    NATIONAL_DEX_BOUFFALANT,
    NATIONAL_DEX_RUFFLET,
    NATIONAL_DEX_BRAVIARY,
    NATIONAL_DEX_VULLABY,
    NATIONAL_DEX_MANDIBUZZ,
    NATIONAL_DEX_HEATMOR,
    NATIONAL_DEX_DURANT,
    NATIONAL_DEX_DEINO,
    NATIONAL_DEX_ZWEILOUS,
    NATIONAL_DEX_HYDREIGON,
    NATIONAL_DEX_LARVESTA,
    NATIONAL_DEX_VOLCARONA,
    NATIONAL_DEX_COBALION,
    NATIONAL_DEX_TERRAKION,
    NATIONAL_DEX_VIRIZION,
    NATIONAL_DEX_TORNADUS,
    NATIONAL_DEX_THUNDURUS,
    NATIONAL_DEX_RESHIRAM,
    NATIONAL_DEX_ZEKROM,
    NATIONAL_DEX_LANDORUS,
    NATIONAL_DEX_KYUREM,
    NATIONAL_DEX_KELDEO,
    NATIONAL_DEX_MELOETTA,
    NATIONAL_DEX_GENESECT,
    // Kalos
    NATIONAL_DEX_CHESPIN,
    NATIONAL_DEX_QUILLADIN,
    NATIONAL_DEX_CHESNAUGHT,
    NATIONAL_DEX_FENNEKIN,
    NATIONAL_DEX_BRAIXEN,
    NATIONAL_DEX_DELPHOX,
    NATIONAL_DEX_FROAKIE,
    NATIONAL_DEX_FROGADIER,
    NATIONAL_DEX_GRENINJA,
    NATIONAL_DEX_BUNNELBY,
    NATIONAL_DEX_DIGGERSBY,
    NATIONAL_DEX_FLETCHLING,
    NATIONAL_DEX_FLETCHINDER,
    NATIONAL_DEX_TALONFLAME,
    NATIONAL_DEX_SCATTERBUG,
    NATIONAL_DEX_SPEWPA,
    NATIONAL_DEX_VIVILLON,
    NATIONAL_DEX_LITLEO,
    NATIONAL_DEX_PYROAR,
    NATIONAL_DEX_FLABEBE,
    NATIONAL_DEX_FLOETTE,
    NATIONAL_DEX_FLORGES,
    NATIONAL_DEX_SKIDDO,
    NATIONAL_DEX_GOGOAT,
    NATIONAL_DEX_PANCHAM,
    NATIONAL_DEX_PANGORO,
    NATIONAL_DEX_FURFROU,
    NATIONAL_DEX_ESPURR,
    NATIONAL_DEX_MEOWSTIC,
    NATIONAL_DEX_HONEDGE,
    NATIONAL_DEX_DOUBLADE,
    NATIONAL_DEX_AEGISLASH,
    NATIONAL_DEX_SPRITZEE,
    NATIONAL_DEX_AROMATISSE,
    NATIONAL_DEX_SWIRLIX,
    NATIONAL_DEX_SLURPUFF,
    NATIONAL_DEX_INKAY,
    NATIONAL_DEX_MALAMAR,
    NATIONAL_DEX_BINACLE,
    NATIONAL_DEX_BARBARACLE,
    NATIONAL_DEX_SKRELP,
    NATIONAL_DEX_DRAGALGE,
    NATIONAL_DEX_CLAUNCHER,
    NATIONAL_DEX_CLAWITZER,
    NATIONAL_DEX_HELIOPTILE,
    NATIONAL_DEX_HELIOLISK,
    NATIONAL_DEX_TYRUNT,
    NATIONAL_DEX_TYRANTRUM,
    NATIONAL_DEX_AMAURA,
    NATIONAL_DEX_AURORUS,
    NATIONAL_DEX_SYLVEON,
    NATIONAL_DEX_HAWLUCHA,
    NATIONAL_DEX_DEDENNE,
    NATIONAL_DEX_CARBINK,
    NATIONAL_DEX_GOOMY,
    NATIONAL_DEX_SLIGGOO,
    NATIONAL_DEX_GOODRA,
    NATIONAL_DEX_KLEFKI,
    NATIONAL_DEX_PHANTUMP,
    NATIONAL_DEX_TREVENANT,
    NATIONAL_DEX_PUMPKABOO,
    NATIONAL_DEX_GOURGEIST,
    NATIONAL_DEX_BERGMITE,
    NATIONAL_DEX_AVALUGG,
    NATIONAL_DEX_NOIBAT,
    NATIONAL_DEX_NOIVERN,
    NATIONAL_DEX_XERNEAS,
    NATIONAL_DEX_YVELTAL,
    NATIONAL_DEX_ZYGARDE,
    NATIONAL_DEX_DIANCIE,
    NATIONAL_DEX_HOOPA,
    NATIONAL_DEX_VOLCANION,
    // Alola
    NATIONAL_DEX_ROWLET,
    NATIONAL_DEX_DARTRIX,
    NATIONAL_DEX_DECIDUEYE,
    NATIONAL_DEX_LITTEN,
    NATIONAL_DEX_TORRACAT,
    NATIONAL_DEX_INCINEROAR,
    NATIONAL_DEX_POPPLIO,
    NATIONAL_DEX_BRIONNE,
    NATIONAL_DEX_PRIMARINA,
    NATIONAL_DEX_PIKIPEK,
    NATIONAL_DEX_TRUMBEAK,
    NATIONAL_DEX_TOUCANNON,
    NATIONAL_DEX_YUNGOOS,
    NATIONAL_DEX_GUMSHOOS,
    NATIONAL_DEX_GRUBBIN,
    NATIONAL_DEX_CHARJABUG,
    NATIONAL_DEX_VIKAVOLT,
    NATIONAL_DEX_CRABRAWLER,
    NATIONAL_DEX_CRABOMINABLE,
    NATIONAL_DEX_ORICORIO,
    NATIONAL_DEX_CUTIEFLY,
    NATIONAL_DEX_RIBOMBEE,
    NATIONAL_DEX_ROCKRUFF,
    NATIONAL_DEX_LYCANROC,
    NATIONAL_DEX_WISHIWASHI,
    NATIONAL_DEX_MAREANIE,
    NATIONAL_DEX_TOXAPEX,
    NATIONAL_DEX_MUDBRAY,
    NATIONAL_DEX_MUDSDALE,
    NATIONAL_DEX_DEWPIDER,
    NATIONAL_DEX_ARAQUANID,
    NATIONAL_DEX_FOMANTIS,
    NATIONAL_DEX_LURANTIS,
    NATIONAL_DEX_MORELULL,
    NATIONAL_DEX_SHIINOTIC,
    NATIONAL_DEX_SALANDIT,
    NATIONAL_DEX_SALAZZLE,
    NATIONAL_DEX_STUFFUL,
    NATIONAL_DEX_BEWEAR,
    NATIONAL_DEX_BOUNSWEET,
    NATIONAL_DEX_STEENEE,
    NATIONAL_DEX_TSAREENA,
    NATIONAL_DEX_COMFEY,
    NATIONAL_DEX_ORANGURU,
    NATIONAL_DEX_PASSIMIAN,
    NATIONAL_DEX_WIMPOD,
    NATIONAL_DEX_GOLISOPOD,
    NATIONAL_DEX_SANDYGAST,
    NATIONAL_DEX_PALOSSAND,
    NATIONAL_DEX_PYUKUMUKU,
    NATIONAL_DEX_TYPE_NULL,
    NATIONAL_DEX_SILVALLY,
    NATIONAL_DEX_MINIOR,
    NATIONAL_DEX_KOMALA,
    NATIONAL_DEX_TURTONATOR,
    NATIONAL_DEX_TOGEDEMARU,
    NATIONAL_DEX_MIMIKYU,
    NATIONAL_DEX_BRUXISH,
    NATIONAL_DEX_DRAMPA,
    NATIONAL_DEX_DHELMISE,
    NATIONAL_DEX_JANGMO_O,
    NATIONAL_DEX_HAKAMO_O,
    NATIONAL_DEX_KOMMO_O,
    NATIONAL_DEX_TAPU_KOKO,
    NATIONAL_DEX_TAPU_LELE,
    NATIONAL_DEX_TAPU_BULU,
    NATIONAL_DEX_TAPU_FINI,
    NATIONAL_DEX_COSMOG,
    NATIONAL_DEX_COSMOEM,
    NATIONAL_DEX_SOLGALEO,
    NATIONAL_DEX_LUNALA,
    NATIONAL_DEX_NIHILEGO,
    NATIONAL_DEX_BUZZWOLE,
    NATIONAL_DEX_PHEROMOSA,
    NATIONAL_DEX_XURKITREE,
    NATIONAL_DEX_CELESTEELA,
    NATIONAL_DEX_KARTANA,
    NATIONAL_DEX_GUZZLORD,
    NATIONAL_DEX_NECROZMA,
    NATIONAL_DEX_MAGEARNA,
    NATIONAL_DEX_MARSHADOW,
    NATIONAL_DEX_POIPOLE,
    NATIONAL_DEX_NAGANADEL,
    NATIONAL_DEX_STAKATAKA,
    NATIONAL_DEX_BLACEPHALON,
    NATIONAL_DEX_ZERAORA,
    // Unknown
    NATIONAL_DEX_MELTAN,
    NATIONAL_DEX_MELMETAL,
    // Galar
    NATIONAL_DEX_GROOKEY,
    NATIONAL_DEX_THWACKEY,
    NATIONAL_DEX_RILLABOOM,
    NATIONAL_DEX_SCORBUNNY,
    NATIONAL_DEX_RABOOT,
    NATIONAL_DEX_CINDERACE,
    NATIONAL_DEX_SOBBLE,
    NATIONAL_DEX_DRIZZILE,
    NATIONAL_DEX_INTELEON,
    NATIONAL_DEX_SKWOVET,
    NATIONAL_DEX_GREEDENT,
    NATIONAL_DEX_ROOKIDEE,
    NATIONAL_DEX_CORVISQUIRE,
    NATIONAL_DEX_CORVIKNIGHT,
    NATIONAL_DEX_BLIPBUG,
    NATIONAL_DEX_DOTTLER,
    NATIONAL_DEX_ORBEETLE,
    NATIONAL_DEX_NICKIT,
    NATIONAL_DEX_THIEVUL,
    NATIONAL_DEX_GOSSIFLEUR,
    NATIONAL_DEX_ELDEGOSS,
    NATIONAL_DEX_WOOLOO,
    NATIONAL_DEX_DUBWOOL,
    NATIONAL_DEX_CHEWTLE,
    NATIONAL_DEX_DREDNAW,
    NATIONAL_DEX_YAMPER,
    NATIONAL_DEX_BOLTUND,
    NATIONAL_DEX_ROLYCOLY,
    NATIONAL_DEX_CARKOL,
    NATIONAL_DEX_COALOSSAL,
    NATIONAL_DEX_APPLIN,
    NATIONAL_DEX_FLAPPLE,
    NATIONAL_DEX_APPLETUN,
    NATIONAL_DEX_SILICOBRA,
    NATIONAL_DEX_SANDACONDA,
    NATIONAL_DEX_CRAMORANT,
    NATIONAL_DEX_ARROKUDA,
    NATIONAL_DEX_BARRASKEWDA,
    NATIONAL_DEX_TOXEL,
    NATIONAL_DEX_TOXTRICITY,
    NATIONAL_DEX_SIZZLIPEDE,
    NATIONAL_DEX_CENTISKORCH,
    NATIONAL_DEX_CLOBBOPUS,
    NATIONAL_DEX_GRAPPLOCT,
    NATIONAL_DEX_SINISTEA,
    NATIONAL_DEX_POLTEAGEIST,
    NATIONAL_DEX_HATENNA,
    NATIONAL_DEX_HATTREM,
    NATIONAL_DEX_HATTERENE,
    NATIONAL_DEX_IMPIDIMP,
    NATIONAL_DEX_MORGREM,
    NATIONAL_DEX_GRIMMSNARL,
    NATIONAL_DEX_OBSTAGOON,
    NATIONAL_DEX_PERRSERKER,
    NATIONAL_DEX_CURSOLA,
    NATIONAL_DEX_SIRFETCHD,
    NATIONAL_DEX_MR_RIME,
    NATIONAL_DEX_RUNERIGUS,
    NATIONAL_DEX_MILCERY,
    NATIONAL_DEX_ALCREMIE,
    NATIONAL_DEX_FALINKS,
    NATIONAL_DEX_PINCURCHIN,
    NATIONAL_DEX_SNOM,
    NATIONAL_DEX_FROSMOTH,
    NATIONAL_DEX_STONJOURNER,
    NATIONAL_DEX_EISCUE,
    NATIONAL_DEX_INDEEDEE,
    NATIONAL_DEX_MORPEKO,
    NATIONAL_DEX_CUFANT,
    NATIONAL_DEX_COPPERAJAH,
    NATIONAL_DEX_DRACOZOLT,
    NATIONAL_DEX_ARCTOZOLT,
    NATIONAL_DEX_DRACOVISH,
    NATIONAL_DEX_ARCTOVISH,
    NATIONAL_DEX_DURALUDON,
    NATIONAL_DEX_DREEPY,
    NATIONAL_DEX_DRAKLOAK,
    NATIONAL_DEX_DRAGAPULT,
    NATIONAL_DEX_ZACIAN,
    NATIONAL_DEX_ZAMAZENTA,
    NATIONAL_DEX_ETERNATUS,
    NATIONAL_DEX_KUBFU,
    NATIONAL_DEX_URSHIFU,
    NATIONAL_DEX_ZARUDE,
    NATIONAL_DEX_REGIELEKI,
    NATIONAL_DEX_REGIDRAGO,
    NATIONAL_DEX_GLASTRIER,
    NATIONAL_DEX_SPECTRIER,
    NATIONAL_DEX_CALYREX,
    NATIONAL_DEX_WYRDEER,
    NATIONAL_DEX_KLEAVOR,
    NATIONAL_DEX_URSALUNA,
    NATIONAL_DEX_BASCULEGION,
    NATIONAL_DEX_SNEASLER,
    NATIONAL_DEX_OVERQWIL,
    NATIONAL_DEX_ENAMORUS,
    NATIONAL_DEX_SPRIGATITO,
    NATIONAL_DEX_FLORAGATO,
    NATIONAL_DEX_MEOWSCARADA,
    NATIONAL_DEX_FUECOCO,
    NATIONAL_DEX_CROCALOR,
    NATIONAL_DEX_SKELEDIRGE,
    NATIONAL_DEX_QUAXLY,
    NATIONAL_DEX_QUAXWELL,
    NATIONAL_DEX_QUAQUAVAL,
    NATIONAL_DEX_LECHONK,
    NATIONAL_DEX_OINKOLOGNE,
    NATIONAL_DEX_TAROUNTULA,
    NATIONAL_DEX_SPIDOPS,
    NATIONAL_DEX_NYMBLE,
    NATIONAL_DEX_LOKIX,
    NATIONAL_DEX_PAWMI,
    NATIONAL_DEX_PAWMO,
    NATIONAL_DEX_PAWMOT,
    NATIONAL_DEX_TANDEMAUS,
    NATIONAL_DEX_MAUSHOLD,
    NATIONAL_DEX_FIDOUGH,
    NATIONAL_DEX_DACHSBUN,
    NATIONAL_DEX_SMOLIV,
    NATIONAL_DEX_DOLLIV,
    NATIONAL_DEX_ARBOLIVA,
    NATIONAL_DEX_SQUAWKABILLY,
    NATIONAL_DEX_NACLI,
    NATIONAL_DEX_NACLSTACK,
    NATIONAL_DEX_GARGANACL,
    NATIONAL_DEX_CHARCADET,
    NATIONAL_DEX_ARMAROUGE,
    NATIONAL_DEX_CERULEDGE,
    NATIONAL_DEX_TADBULB,
    NATIONAL_DEX_BELLIBOLT,
    NATIONAL_DEX_WATTREL,
    NATIONAL_DEX_KILOWATTREL,
    NATIONAL_DEX_MASCHIFF,
    NATIONAL_DEX_MABOSSTIFF,
    NATIONAL_DEX_SHROODLE,
    NATIONAL_DEX_GRAFAIAI,
    NATIONAL_DEX_BRAMBLIN,
    NATIONAL_DEX_BRAMBLEGHAST,
    NATIONAL_DEX_TOEDSCOOL,
    NATIONAL_DEX_TOEDSCRUEL,
    NATIONAL_DEX_KLAWF,
    NATIONAL_DEX_CAPSAKID,
    NATIONAL_DEX_SCOVILLAIN,
    NATIONAL_DEX_RELLOR,
    NATIONAL_DEX_RABSCA,
    NATIONAL_DEX_FLITTLE,
    NATIONAL_DEX_ESPATHRA,
    NATIONAL_DEX_TINKATINK,
    NATIONAL_DEX_TINKATUFF,
    NATIONAL_DEX_TINKATON,
    NATIONAL_DEX_WIGLETT,
    NATIONAL_DEX_WUGTRIO,
    NATIONAL_DEX_BOMBIRDIER,
    NATIONAL_DEX_FINIZEN,
    NATIONAL_DEX_PALAFIN,
    NATIONAL_DEX_VAROOM,
    NATIONAL_DEX_REVAVROOM,
    NATIONAL_DEX_CYCLIZAR,
    NATIONAL_DEX_ORTHWORM,
    NATIONAL_DEX_GLIMMET,
    NATIONAL_DEX_GLIMMORA,
    NATIONAL_DEX_GREAVARD,
    NATIONAL_DEX_HOUNDSTONE,
    NATIONAL_DEX_FLAMIGO,
    NATIONAL_DEX_CETODDLE,
    NATIONAL_DEX_CETITAN,
    NATIONAL_DEX_VELUZA,
    NATIONAL_DEX_DONDOZO,
    NATIONAL_DEX_TATSUGIRI,
    NATIONAL_DEX_ANNIHILAPE,
    NATIONAL_DEX_CLODSIRE,
    NATIONAL_DEX_FARIGIRAF,
    NATIONAL_DEX_DUDUNSPARCE,
    NATIONAL_DEX_KINGAMBIT,
    NATIONAL_DEX_GREAT_TUSK,
    NATIONAL_DEX_SCREAM_TAIL,
    NATIONAL_DEX_BRUTE_BONNET,
    NATIONAL_DEX_FLUTTER_MANE,
    NATIONAL_DEX_SLITHER_WING,
    NATIONAL_DEX_SANDY_SHOCKS,
    NATIONAL_DEX_IRON_TREADS,
    NATIONAL_DEX_IRON_BUNDLE,
    NATIONAL_DEX_IRON_HANDS,
    NATIONAL_DEX_IRON_JUGULIS,
    NATIONAL_DEX_IRON_MOTH,
    NATIONAL_DEX_IRON_THORNS,
    NATIONAL_DEX_FRIGIBAX,
    NATIONAL_DEX_ARCTIBAX,
    NATIONAL_DEX_BAXCALIBUR,
    NATIONAL_DEX_GIMMIGHOUL,
    NATIONAL_DEX_GHOLDENGO,
    NATIONAL_DEX_WO_CHIEN,
    NATIONAL_DEX_CHIEN_PAO,
    NATIONAL_DEX_TING_LU,
    NATIONAL_DEX_CHI_YU,
    NATIONAL_DEX_ROARING_MOON,
    NATIONAL_DEX_IRON_VALIANT,
    NATIONAL_DEX_KORAIDON,
    NATIONAL_DEX_MIRAIDON,
    NATIONAL_DEX_WALKING_WAKE,
    NATIONAL_DEX_IRON_LEAVES,
    NATIONAL_DEX_DIPPLIN,
    NATIONAL_DEX_POLTCHAGEIST,
    NATIONAL_DEX_SINISTCHA,
    NATIONAL_DEX_OKIDOGI,
    NATIONAL_DEX_MUNKIDORI,
    NATIONAL_DEX_FEZANDIPITI,
    NATIONAL_DEX_OGERPON,
    NATIONAL_DEX_ARCHALUDON,
    NATIONAL_DEX_HYDRAPPLE,
    NATIONAL_DEX_GOUGING_FIRE,
    NATIONAL_DEX_RAGING_BOLT, 
    NATIONAL_DEX_IRON_BOULDER,
    NATIONAL_DEX_IRON_CROWN,
    NATIONAL_DEX_TERAPAGOS,
    NATIONAL_DEX_PECHARUNT,
    NATIONAL_DEX_ILLUSION_MAGICIAN,
    NATIONAL_DEX_DARK_MAGICIAN,
    NATIONAL_DEX_DARK_SAGE,
    NATIONAL_DEX_BLACK_DRAGONS_CHICK,
    NATIONAL_DEX_RED_EYES_BLACK_DRAGON,
    NATIONAL_DEX_RED_EYES_BLACK_METAL_DRAGON,
    NATIONAL_DEX_PALADIN_OF_WHITE_DRAGON,
    NATIONAL_DEX_BLUE_EYES_WHITE_DRAGON,
    NATIONAL_DEX_BLUE_EYES_ULTIMATE_DRAGON,
    NATIONAL_DEX_MAN_EATER_BUG,
    NATIONAL_DEX_NOBLEMAN_EATER_BUG,
    NATIONAL_DEX_PETIT_MOTH,
    NATIONAL_DEX_LARVAE_MOTH,
    NATIONAL_DEX_COCOON_OF_EVOLUTION,
    NATIONAL_DEX_GREAT_MOTH,
    NATIONAL_DEX_PERFECTLY_ULTIMATE_GREAT_MOTH,
    NATIONAL_DEX_PARASITE_CATERPILLAR,
    NATIONAL_DEX_POISON_BUTTERFLY,
    NATIONAL_DEX_BEAVER_WARRIOR,
    NATIONAL_DEX_KURIBOH,
    NATIONAL_DEX_WINGED_KURIBOH,
    NATIONAL_DEX_WINGED_KURIBOH_LEVEL10,
    NATIONAL_DEX_KURIBABYLON,
    NATIONAL_DEX_LINKURIBOH,
    NATIONAL_DEX_KURIBON,
    NATIONAL_DEX_SPHERE_KURIBOH,
    NATIONAL_DEX_JUNKURIBOH,
    NATIONAL_DEX_LITTLE_WINGUARD,
    NATIONAL_DEX_ROCKET_WARRIOR,
    NATIONAL_DEX_SWORDSMAN_OF_LANDSTAR,
    NATIONAL_DEX_GILFORD_THE_LIGHTNING,
    NATIONAL_DEX_HAPPY_LOVER,
    NATIONAL_DEX_SHINING_FRIENDSHIP,
    NATIONAL_DEX_SPEED_WARRIOR,
    NATIONAL_DEX_JUNK_SPEEDER,
    NATIONAL_DEX_FLAME_MANIPULATOR,
    NATIONAL_DEX_FLAME_SWORDSMAN,
    NATIONAL_DEX_DARK_FLARE_KNIGHT,
    NATIONAL_DEX_FERAL_IMP,
    NATIONAL_DEX_DES_FERAL_IMP,
    NATIONAL_DEX_KING_OF_THE_FERAL_IMPS,
    NATIONAL_DEX_BABY_DRAGON,
    NATIONAL_DEX_THOUSAND_DRAGON,
    NATIONAL_DEX_JERRY_BEANS_MAN,
    NATIONAL_DEX_WITCH_OF_THE_BLACK_FOREST,
    NATIONAL_DEX_SANGAN,
    NATIONAL_DEX_SANWITCH,
    NATIONAL_DEX_INJECTION_FAIRY_LILY,
    NATIONAL_DEX_BETA_THE_MAGNET_WARRIOR,
    NATIONAL_DEX_VALKYRION,
    NATIONAL_DEX_ALPHA_THE_MAGNET_WARRIOR,
    NATIONAL_DEX_BERSERKION,
    NATIONAL_DEX_GOKIBORE,
    NATIONAL_DEX_GOKIPOLE,
    NATIONAL_DEX_BERFORMET,
    NATIONAL_DEX_CHIMERA_THE_FLYING_MYTHICAL_BEAST,
    NATIONAL_DEX_CHIMAERA_THE_MASTER_OF_BEASTS,
    NATIONAL_DEX_SWAMP_BATTLEGUARD,
    NATIONAL_DEX_LAVA_BATTLEGUARD,
    NATIONAL_DEX_KILLER_NEEDLE,
    NATIONAL_DEX_ARMORED_BEE,
    NATIONAL_DEX_POKI_DRACO,
    NATIONAL_DEX_DORA_DRACO,
    NATIONAL_DEX_MUKA_MUKA,
    NATIONAL_DEX_ENRAGED_MUKA_MUKA,
    NATIONAL_DEX_QUILLBOLT_HEDGEHOG,
    NATIONAL_DEX_ANCHORBOLT_HEDGEHOG,
    NATIONAL_DEX_FROG_THE_JAM,
    NATIONAL_DEX_TOADALLY_AWESOME,
    NATIONAL_DEX_TREEBORN_FROG,
    NATIONAL_DEX_TRADETOAD,
    NATIONAL_DEX_SUBSTITOAD,
    NATIONAL_DEX_DES_FROG,
    NATIONAL_DEX_D3S_FROG,
    NATIONAL_DEX_TADPOLE,
    NATIONAL_DEX_BEELZE_FROG,
    NATIONAL_DEX_SWAP_FROG,
    NATIONAL_DEX_RONINTOADIN,
    NATIONAL_DEX_DUPE_FROG,
    NATIONAL_DEX_LUSTER_DRAGON,
    NATIONAL_DEX_LUSTER_DRAGON_TWO,
    NATIONAL_DEX_DIAMOND_HEAD_DRAGON,
    NATIONAL_DEX_LITTLE_D,
    NATIONAL_DEX_URABY,
    NATIONAL_DEX_BLACK_TYRANNO,
    NATIONAL_DEX_BASIC_INSECT,
    NATIONAL_DEX_ARMOURED_BASIC_INSECT,
    NATIONAL_DEX_INSECT_PRINCESS,
    NATIONAL_DEX_INSECT_QUEEN,
    NATIONAL_DEX_TWIN_HEADED_REX,
    NATIONAL_DEX_CELTIC_GUARDIAN,
    NATIONAL_DEX_OBNOXIOUS_CELTIC_GUARDIAN,
    NATIONAL_DEX_CELTIC_GUARDIAN_OF_NOBLE_ARMS,
    NATIONAL_DEX_RYU_KISHIN,
    NATIONAL_DEX_RYU_KISHIN_POWERED,
    NATIONAL_DEX_WATAPON,
    NATIONAL_DEX_MARSHMALLON,
    NATIONAL_DEX_SPORE,
    NATIONAL_DEX_SPORE_THE_FAIRY_SEED,
    NATIONAL_DEX_OJAMA_YELLOW,
    NATIONAL_DEX_OJAMA_KNIGHT,
    NATIONAL_DEX_OJAMA_KING,
    NATIONAL_DEX_MYSTICAL_ELF,
    NATIONAL_DEX_FLAME_CEREBRUS,
    NATIONAL_DEX_ALLIGATOR_SWORD,
    NATIONAL_DEX_CYBERTECH_ALLIGATOR,
    NATIONAL_DEX_ALLIGATOR_SWORD_DRAGON,
    NATIONAL_DEX_AXE_RAIDER,
    NATIONAL_DEX_VORSE_RAIDER,
    NATIONAL_DEX_WILDHEART,
    NATIONAL_DEX_WILD_WINGMAN,
    NATIONAL_DEX_WINGED_DRAGON_GUARDIAN_OF_THE_FORTRESS,
    NATIONAL_DEX_DARK_MAGICIAN_GIRL,
    NATIONAL_DEX_DARK_MAGICIAN_GIRL_THE_DRAGON_KNIGHT,
    NATIONAL_DEX_KAIRYU_SHIN,
    NATIONAL_DEX_OCEAN_DRAGON_LORD_KAIRYU_SHIN,
    NATIONAL_DEX_BLACKWING_GALE_THE_WHIRLWIND,
    NATIONAL_DEX_BLACKWING_ARMOR_MASTER,
    NATIONAL_DEX_COCKROACH_KNIGHT,
    NATIONAL_DEX_INSECT_KNIGHT,
    NATIONAL_DEX_ULTIMATE_BASEBALL_KID,
    NATIONAL_DEX_HARPIE_LADY,
    NATIONAL_DEX_HARPIE_LADY_SISTERS,
    NATIONAL_DEX_CYBER_HARPIE_LADY,
    NATIONAL_DEX_CYBER_SLASH_HARPIE_LADY,
    NATIONAL_DEX_HARPIE_QUEEN,
    NATIONAL_DEX_HARPIE_BROTHER,
    NATIONAL_DEX_HARPIES_PET_DRAGON,
    NATIONAL_DEX_AMAZONESS_BABY_TIGER,
    NATIONAL_DEX_AMAZONESS_TIGER,
    NATIONAL_DEX_AMAZONESS_PRINCESS,
    NATIONAL_DEX_AMAZONESS_QUEEN,
    NATIONAL_DEX_REVIVAL_ROSE,
    NATIONAL_DEX_REGENERATING_ROSE,
    NATIONAL_DEX_ROSE_TENTACLES,
    NATIONAL_DEX_DARK_RESONATOR,
    NATIONAL_DEX_CRIMSON_RESONATOR,
    NATIONAL_DEX_SMALL_PIECE_GOLEM,
    NATIONAL_DEX_MEDIUM_PIECE_GOLEM,
    NATIONAL_DEX_BIG_PIECE_GOLEM,
    NATIONAL_DEX_SUMMONED_SKULL,
    NATIONAL_DEX_BLACK_SKULL_DRAGON,
    NATIONAL_DEX_ARCHFIENDS_ZOMBIE_SKULL,
    NATIONAL_DEX_CURSE_OF_DRAGON,
    NATIONAL_DEX_GAIA_THE_DRAGON_CHAMPION,
    NATIONAL_DEX_QUEENS_KNIGHT,
    NATIONAL_DEX_KINGS_KNIGHT,
    NATIONAL_DEX_JACKS_KNIGHT,
    NATIONAL_DEX_INFERNITY_ARCHFIEND,
    NATIONAL_DEX_INFERNITY_DOOM_ARCHFIEND,
    NATIONAL_DEX_RED_ARCHERY_GIRL,
    NATIONAL_DEX_SAGGI,
    NATIONAL_DEX_PETEN,
    NATIONAL_DEX_AGIDO,
    NATIONAL_DEX_AGIDO_THE_ANCIENT_SENTINEL,
    NATIONAL_DEX_KELDO,
    NATIONAL_DEX_KELDO_THE_SACRED_PROTECTOR,
    NATIONAL_DEX_BLACK_PTERA,
    NATIONAL_DEX_OVERTEX_QOATLUS,
    NATIONAL_DEX_LORD_OF_D,
    NATIONAL_DEX_KING_OF_D,
    NATIONAL_DEX_GEARFRIED_THE_IRON_KNIGHT,
    NATIONAL_DEX_GEARFRIED_THE_SWORDMASTER,
    NATIONAL_DEX_GIANT_SOLDIER_OF_STONE,
    NATIONAL_DEX_GIANT_SOLDIER_OF_STEEL,
    NATIONAL_DEX_CRAB_TURTLE,
    NATIONAL_DEX_LEGENDARY_FISHERMAN,
    NATIONAL_DEX_LEGENDARY_FISHERMAN_TWO,
    NATIONAL_DEX_KOUMORI_DRAGON,
    NATIONAL_DEX_SERPENT_NIGHT_DRAGON,
    NATIONAL_DEX_JUNK_SYNCHRON,
    NATIONAL_DEX_JUNK_WARRIOR,
    NATIONAL_DEX_JUNK_DESTROYER,
    NATIONAL_DEX_JUNK_ARCHER,
    NATIONAL_DEX_NITRO_SYNCHRON,
    NATIONAL_DEX_NITRO_WARRIOR,
    NATIONAL_DEX_TURBO_SYNCHRON,
    NATIONAL_DEX_TURBO_WARRIOR,
    NATIONAL_DEX_ROAD_SYNCHRON,
    NATIONAL_DEX_ROAD_WARRIOR,
    NATIONAL_DEX_QUICKDRAW_SYNCHRON,
    NATIONAL_DEX_LEVEL_EATER,
    NATIONAL_DEX_OUTSTANDING_DOG_MARRON,
    NATIONAL_DEX_SKULL_DOG_MARRON,
    NATIONAL_DEX_MAD_DOG_OF_DARKNESS,
    NATIONAL_DEX_BEHEMOTH_KING_OF_ALL_ANIMALS,
    NATIONAL_DEX_INPACHI,
    NATIONAL_DEX_BLAZING_INPACHI,
    NATIONAL_DEX_CHARCOAL_INPACHI,
    NATIONAL_DEX_GAIA_THE_FIERCE_KNIGHT,
    NATIONAL_DEX_GAIA_KNIGHT_THE_FORCE_OF_EARTH,
    NATIONAL_DEX_DARK_CAVALRY,
    NATIONAL_DEX_AVIAN,
    NATIONAL_DEX_FLAME_WINGMAN,
    NATIONAL_DEX_SHINING_FLARE_WINGMAN,
    NATIONAL_DEX_CYBER_PETIT_ANGEL,
    NATIONAL_DEX_CYBER_ANGEL_BENTEN,
    NATIONAL_DEX_CYBER_ANGEL_DAKINI,
    NATIONAL_DEX_WARRIOR_OF_ZERA,
    NATIONAL_DEX_ZERA_THE_MANT,
    NATIONAL_DEX_MEGAZOWLER,
    NATIONAL_DEX_ILLUSIONIST_FACELESS_MAGE,
    NATIONAL_DEX_ILLUSIONIST_FACELESS_MAGICIAN,
    NATIONAL_DEX_PARROT_DRAGON,
    NATIONAL_DEX_TRI_HORNED_DRAGON,
    NATIONAL_DEX_MYSTIC_TOMATO,
    NATIONAL_DEX_HUNGRY_BURGER,
    NATIONAL_DEX_THUNDER_DRAGON,
    NATIONAL_DEX_TWIN_HEADED_THUNDER_DRAGON,
    NATIONAL_DEX_THUNDER_DRAGON_TITAN,
    NATIONAL_DEX_THUNDER_DRAGON_COLOSSUS,
    NATIONAL_DEX_PANTHER_WARRIOR,
    NATIONAL_DEX_SOLITAIRE_MAGICIAN,
    NATIONAL_DEX_FORTUNE_LADY_EVERY,
    NATIONAL_DEX_MUSICIAN_KING,
    NATIONAL_DEX_HEAVY_METAL_KING,
    NATIONAL_DEX_SLOT_MACHINE,
    NATIONAL_DEX_BATTLE_OX,
    NATIONAL_DEX_RABID_HORSEMAN,
    NATIONAL_DEX_JIRAI_GUMO,
    NATIONAL_DEX_LAUNCHER_SPIDER,
    NATIONAL_DEX_VAMPIRE_BAT,
    NATIONAL_DEX_VAMPIRE_LORD,
    NATIONAL_DEX_VAMPIRE_GENESIS,
    NATIONAL_DEX_VAMPIRE_LADY,
    NATIONAL_DEX_VAMPIRE_GRACE,
    NATIONAL_DEX_CLAYMAN,
    NATIONAL_DEX_MUDBALLMAN,
    NATIONAL_DEX_GRACEFUL_DICE,
    NATIONAL_DEX_SKULL_DICE,
    NATIONAL_DEX_ORGOTH_THE_RELENTLESS,
    NATIONAL_DEX_LA_JINN,
    NATIONAL_DEX_LORD_POISON,
    NATIONAL_DEX_LAVA_GOLEM,
    NATIONAL_DEX_REVIVAL_JAM,
    NATIONAL_DEX_HUMANOID_SLIME,
    NATIONAL_DEX_HUMANOID_WORM_DRAKE,
    NATIONAL_DEX_EGYPTIAN_GOD_SLIME,
    NATIONAL_DEX_PENDULUM_MACHINE,
    NATIONAL_DEX_SPEAR_DRAGON,
    NATIONAL_DEX_SILENT_MAGICIAN_LEVEL4,
    NATIONAL_DEX_SILENT_MAGICIAN_LEVEL8,
    NATIONAL_DEX_SILENT_SWORDSMAN_LEVEL3,
    NATIONAL_DEX_SILENT_SWORDSMAN_LEVEL7,
    NATIONAL_DEX_GANDORA,
    NATIONAL_DEX_REAPER_OF_THE_CARDS,
    NATIONAL_DEX_KING_OF_YAMIMAKAI,
    NATIONAL_DEX_RESCURE_RABBIT,
    NATIONAL_DEX_RESCUE_CAT,
    NATIONAL_DEX_WARM_WORM,
    NATIONAL_DEX_NEEDLE_WORM,
    NATIONAL_DEX_DUNGEON_WORM,
    NATIONAL_DEX_KARATE_MAN,
    NATIONAL_DEX_DES_KANGAROO,
    NATIONAL_DEX_MASTER_OF_OZ,
    NATIONAL_DEX_BERSERK_GORILLA,
    NATIONAL_DEX_SINISTER_SERPENT,
    NATIONAL_DEX_THIRTEENTH_GRAVE,
    NATIONAL_DEX_SKULL_SERVANT,
    NATIONAL_DEX_KING_OF_THE_SKULL_SERVANTS,
    NATIONAL_DEX_CATAPULT_TURTLE,
    NATIONAL_DEX_ELECTROMAGNETIC_TURTLE,
    NATIONAL_DEX_BLOCK_DRAGON,
    NATIONAL_DEX_BUSTER_BLADER,
    NATIONAL_DEX_DARK_PALADIN,
    NATIONAL_DEX_X_CANNON,
    NATIONAL_DEX_XY_DRAGON,
    NATIONAL_DEX_XYZ_DRAGON_CANNON,
    NATIONAL_DEX_JINZO_RETURNER,
    NATIONAL_DEX_JINZO,
    NATIONAL_DEX_RYU_RAN,
    NATIONAL_DEX_MANGA_RYU_RAN,
    NATIONAL_DEX_BLUE_EYES_TOON_DRAGON,
    NATIONAL_DEX_TOON_ALLIGATOR,
    NATIONAL_DEX_TOON_GEMINI_ELF,
    NATIONAL_DEX_TOON_DARK_MAGICIAN_GIRL,
    NATIONAL_DEX_TOON_SUMMONED_SKULL,
    NATIONAL_DEX_TOON_ANCIENT_GEAR_GOLEM,
    NATIONAL_DEX_RED_EYES_TOON_DRAGON,
    NATIONAL_DEX_TOON_DARK_MAGICIAN,
    NATIONAL_DEX_BIG_SHIELD_GARDNA,
    NATIONAL_DEX_POT_OF_GREED,
    NATIONAL_DEX_AVATAR_OF_THE_POT,
    NATIONAL_DEX_PUMPKING,
    NATIONAL_DEX_GUARDIAN_EATOS,
    NATIONAL_DEX_HYOZANRYU,
    NATIONAL_DEX_DARK_NECROFEAR,
    NATIONAL_DEX_METEOR_DRAGON,
    NATIONAL_DEX_METEOR_BLACK_DRAGON,
    NATIONAL_DEX_YATA_GARASU,
    NATIONAL_DEX_BLACK_LUSTER_SOLDIER,
    NATIONAL_DEX_CHAOS_EMPEROR_DRAGON,
    NATIONAL_DEX_DRAGON_MASTER_KNIGHT,
    NATIONAL_DEX_NEOS,
    NATIONAL_DEX_AQUA_NEOS,
    NATIONAL_DEX_FLARE_NEOS,
    NATIONAL_DEX_GLOW_NEOS,
    NATIONAL_DEX_AIR_NEOS,
    NATIONAL_DEX_GRAND_NEOS,
    NATIONAL_DEX_DARK_NEOS,
    NATIONAL_DEX_HONEST_NEOS,
    NATIONAL_DEX_THOUSAND_EYES_IDOL,
    NATIONAL_DEX_RELINQUISHED,
    NATIONAL_DEX_THOUSAND_EYES_RESTRICT,
    NATIONAL_DEX_THE_GREAT_LEVIATHAN,
    NATIONAL_DEX_FIVE_GOD_DRAGON,
    NATIONAL_DEX_HAMON,
    NATIONAL_DEX_RAVIEL,
    NATIONAL_DEX_URIA,
    NATIONAL_DEX_OBELISK_THE_TORMENTOR,
    NATIONAL_DEX_WINGED_DRAGON_OF_RA,
    NATIONAL_DEX_SLIFER_THE_SKY_DRAGON,
    NATIONAL_DEX_HORUS_LEVEL_FOUR,
    NATIONAL_DEX_HORUS_LEVEL_SIX,
    NATIONAL_DEX_HORUS_LEVEL_EIGHT,
    NATIONAL_DEX_CYBERDARK_HORN,
    NATIONAL_DEX_CYBERDARK_DRAGON,
    NATIONAL_DEX_CYBER_DRAGON,
    NATIONAL_DEX_CYBER_TWIN_DRAGON,
    NATIONAL_DEX_CYBER_END_DRAGON,
    NATIONAL_DEX_CHIMERATECH_OVERDRAGON,
    NATIONAL_DEX_EXODIA_THE_FORBIDDEN_ONE,
    NATIONAL_DEX_EXODIA_NECROSS,
    NATIONAL_DEX_ARMED_DRAGON_LEVEL3,
    NATIONAL_DEX_ARMED_DRAGON_LEVEL5,
    NATIONAL_DEX_ARMED_DRAGON_LEVEL7,
    NATIONAL_DEX_ARMED_DRAGON_LEVEL10,
    NATIONAL_DEX_MOBIUS,
    NATIONAL_DEX_MOKEY_MOKEY,
    NATIONAL_DEX_MOKEY_KING,
    NATIONAL_DEX_VOLCANIC_SHELL,
    NATIONAL_DEX_VOLCANIC_SLICER,
    NATIONAL_DEX_VOLCANIC_SCATTERSHOT,
    NATIONAL_DEX_VOLCANIC_HAMMERER,
    NATIONAL_DEX_VOLCANIC_DOOMFIRE,
    NATIONAL_DEX_VOLCANIC_QUEEN,
    NATIONAL_DEX_TIME_WIZARD,
    NATIONAL_DEX_SNOW_DRAGON,
    NATIONAL_DEX_SNOWDUST_DRAGON,
    NATIONAL_DEX_WHITE_NIGHT_DRAGON,
    NATIONAL_DEX_STEAMROID,
    NATIONAL_DEX_STEAM_GYROID,
    NATIONAL_DEX_DRILLROID,
    NATIONAL_DEX_SUPER_VEHICROID_JUMBO_DRAGON,
    NATIONAL_DEX_AMBULANCEROID,
    NATIONAL_DEX_AMBULANCE_RESCUEROID,
    NATIONAL_DEX_NECROSHADE,
    NATIONAL_DEX_NECROID_SHAMAN,
    NATIONAL_DEX_SANGA_OF_THE_THUNDER,
    NATIONAL_DEX_GATE_GUARDIAN_THUNDER_WIND,
    NATIONAL_DEX_GATE_GUARDIAN,
    NATIONAL_DEX_SEVEN_COLOURED_FISH,
    NATIONAL_DEX_BURSTINATRIX,
    NATIONAL_DEX_RAMPART_BLASTER,
    NATIONAL_DEX_INFERNO_WING,
    NATIONAL_DEX_FORTRESS_WHALE,
    NATIONAL_DEX_SEIYARYU,
    NATIONAL_DEX_STARRY_NIGHT_STARRY_DRAGON,
    NATIONAL_DEX_BREAKER_THE_MAGICAL_WARRIOR,
    NATIONAL_DEX_AQUA_MADOR,
    NATIONAL_DEX_NEO_AQUA_MADOR,
    NATIONAL_DEX_ANCIENT_GEAR_SOLDIER,
    NATIONAL_DEX_ANCIENT_GEAR_GOLEM,
    NATIONAL_DEX_ULTIMATE_ANCIENT_GEAR_GOLEM,
    NATIONAL_DEX_WALL_SHADOW,
    NATIONAL_DEX_FIREWALL_DRAGON,
    NATIONAL_DEX_PREDAPLANT_VERTE_ANACONDA,
    NATIONAL_DEX_BLOWBACK_DRAGON,
    NATIONAL_DEX_BARREL_DRAGON,
    NATIONAL_DEX_BLADE_SKATER,
    NATIONAL_DEX_CYBER_BLADER,
    NATIONAL_DEX_HELIOS_THE_PRIMORDIAL_SUN,
    NATIONAL_DEX_HELIOS_DUO_MEGISTUS,
    NATIONAL_DEX_HELIOS_TRICE_MEGISTUS,
    NATIONAL_DEX_STAR_BOY,
    NATIONAL_DEX_MISTAR_BOY,
    NATIONAL_DEX_DARK_RULER_HA_DES,
    NATIONAL_DEX_DARK_KING_OF_THE_ABYSS,
    NATIONAL_DEX_SUNLIGHT_UNICORN,
    NATIONAL_DEX_FIEND_KRAKEN,
    NATIONAL_DEX_DOOM_KRAKEN,
    NATIONAL_DEX_MONTAGE_DRAGON,
    NATIONAL_DEX_BLADEDGE,
    NATIONAL_DEX_PLASMA_VICE,
    NATIONAL_DEX_EMBODIMENT_OF_APOPHIS,
    NATIONAL_DEX_FORMULA_SYNCHRON,
    NATIONAL_DEX_MAMMOTH_GRAVEYARD,
    NATIONAL_DEX_GREAT_MAMMOTH_OF_GOLDFINE,
    NATIONAL_DEX_LAUNDRY_DRAGONMAID,
    NATIONAL_DEX_HITOTSU_ME_GIANT,
    NATIONAL_DEX_CYBERNETIC_CYCLOPEAN,
    NATIONAL_DEX_SONIC_BIRD,
    NATIONAL_DEX_ALECTOR,
    NATIONAL_DEX_RUBY_CARBUNCLE,
    NATIONAL_DEX_CRYSTAL_BEAST_SAPHIRE_PEGASUS,
    NATIONAL_DEX_PENGUIN_SOLDIER,
    NATIONAL_DEX_EMPEROR_PENGUIN,
    NATIONAL_DEX_NIGHTMARE_PENGUIN,
    NATIONAL_DEX_SWORDSTALKER,
    NATIONAL_DEX_TOON_MERMAID,
    NATIONAL_DEX_GEMINI_ELF,
    NATIONAL_DEX_DARK_JEROID,
    NATIONAL_DEX_SPARKMAN,
    NATIONAL_DEX_THUNDERGIANT,
    NATIONAL_DEX_CHANGE_OF_HEART,
    NATIONAL_DEX_MIMICAT,
    NATIONAL_DEX_ARCHFIENDS_MIRROR,
    NATIONAL_DEX_NIWATORI,
    NATIONAL_DEX_THUNDER_KID,
    NATIONAL_DEX_SPACE_MAMBO,
    NATIONAL_DEX_MUSHROOM_MAN,
    NATIONAL_DEX_MEDA_BAT,
    NATIONAL_DEX_BUBBLEMAN,
    NATIONAL_DEX_STEAM_HEALER,
    NATIONAL_DEX_MELCHID_THE_FOUR_FACE_BEAST,
    NATIONAL_DEX_MASKED_BEAST_DES_GARDIUS,
    NATIONAL_DEX_GRAND_TIKI_ELDER,
    NATIONAL_DEX_MASKED_BEAST,
    NATIONAL_DEX_CLOUDIAN_NIMBUSMAN,
    NATIONAL_DEX_CLOUDIAN_EYE_OF_THE_TYPHOON,
    NATIONAL_DEX_CLEAR_VICE_DRAGON,
    NATIONAL_DEX_HONEST,
    NATIONAL_DEX_MAGICIAN_OF_BLACK_CHAOS,
    NATIONAL_DEX_RAINBOW_DRAGON,
    NATIONAL_DEX_RAINBOW_NEOS,
    NATIONAL_DEX_GHOSTRICK_WITCH,
    NATIONAL_DEX_GAMECIEL,
    NATIONAL_DEX_MYSTICAL_BEAST_OF_SERKET,
    NATIONAL_DEX_JUDGE_MAN,
    NATIONAL_DEX_JUDGMENT_DRAGON,
    NATIONAL_DEX_ELDLICH,
    NATIONAL_DEX_DESTINY_HERO_PLASMA,
    NATIONAL_DEX_DESTINY_HERO_DREADMASTER,
    NATIONAL_DEX_DIVINE_SERPENT_GEH,
    NATIONAL_DEX_FROST_AND_FLAME_DRAGON,
    NATIONAL_DEX_REPTILIANNE_SERVANT,
    NATIONAL_DEX_DRAGON_QUEEN_OF_TRAGIC_ENDING,
    NATIONAL_DEX_ZOA,
    NATIONAL_DEX_METALZOA,
    NATIONAL_DEX_KYUOTORA,
    NATIONAL_DEX_SHUNOROS,
    NATIONAL_DEX_TYRANT_DRAGON,
    NATIONAL_DEX_DAEDALUS,
    NATIONAL_DEX_DANDYLION,
    NATIONAL_DEX_GIANT_REX,
    NATIONAL_DEX_SNOWMAN_EATER,
    NATIONAL_DEX_VENOM_BOA,
    NATIONAL_DEX_VENNOMINON,
    NATIONAL_DEX_VENNOMINAGA,
    NATIONAL_DEX_ARCANA_FORCE_THE_FIEND,
    NATIONAL_DEX_ARCANA_FORCE_THE_DARK_RULER,
    NATIONAL_DEX_ARCANA_FORCE_THE_LIGHT_RULER,
    NATIONAL_DEX_ARCANA_FORCE_THE_WORLD,
    NATIONAL_DEX_SAMSARAS_LOTUS,
    NATIONAL_DEX_YUBEL,
    NATIONAL_DEX_YUBEL_TERROR_INCARNATE,
    NATIONAL_DEX_YUBEL_ULTIMATE_KNIGHTMARE,
    NATIONAL_DEX_DARK_DIVINER,
    NATIONAL_DEX_UNDERGROUND_ARACHNID,
    NATIONAL_DEX_FROZEN_FITZGERALD,
    NATIONAL_DEX_ZEMAN_THE_APE_KING,
    NATIONAL_DEX_DARK_FLATTOP,
    NATIONAL_DEX_HUNDRED_EYES_DRAGON,
    NATIONAL_DEX_SUPAY,
    NATIONAL_DEX_MOON_DRAGON_QUILLA,
    NATIONAL_DEX_SUN_DRAGON_INTI,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_CCAPAC_APU,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_CUSILLU,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_CCARAYHUA,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_URU,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_CHACU_CHALLHUA,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_ASLLA_PISCU,
    NATIONAL_DEX_EARTHBOUND_IMMORTAL_WIRAQOCHA_RASCA,
    NATIONAL_DEX_DEBRIS_DRAGON,
    NATIONAL_DEX_STARDUST_DRAGON,
    NATIONAL_DEX_SHOOTING_STAR_DRAGON,
    NATIONAL_DEX_RED_RISING_DRAGON,
    NATIONAL_DEX_RED_DRAGON_ARCHFIEND,
    NATIONAL_DEX_RED_NOVA_DRAGON,
    NATIONAL_DEX_RED_ROSE_DRAGON,
    NATIONAL_DEX_BLACK_ROSE_DRAGON,
    NATIONAL_DEX_RUDDY_ROSE_DRAGON,
    NATIONAL_DEX_BLACKWING_GHIBLI,
    NATIONAL_DEX_BLACKWING_DRAGON,
    NATIONAL_DEX_BLACKWING_ASSAULT_DRAGON,
    NATIONAL_DEX_FAIRY_DRAGON,
    NATIONAL_DEX_ANCIENT_FAIRY_DRAGON,
    NATIONAL_DEX_ANCIENT_PIXIE_DRAGON,
    NATIONAL_DEX_REVOLUTION_SYNCHRON,
    NATIONAL_DEX_POWER_TOOL_DRAGON,
    NATIONAL_DEX_LIFE_STREAM_DRAGON,
    NATIONAL_DEX_MAJESTIC_DRAGON,
    NATIONAL_DEX_MAJESTIC_STAR_DRAGON,
    NATIONAL_DEX_MAJESTIC_RED_DRAGON,
    NATIONAL_DEX_SHOOTING_QUASAR_DRAGON,
    NATIONAL_DEX_CRIMSON_DRAGON,
    NATIONAL_DEX_NIBIRU,
    NATIONAL_DEX_VICTORY_DRAGON,
    NATIONAL_DEX_CRITIAS,
    NATIONAL_DEX_TIMAEUS,
    NATIONAL_DEX_HERMOS,

};

#define JOHTO_DEX_COUNT     NATIONAL_DEX_CELEBI

#if P_GEN_9_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_PECHARUNT
#elif P_GEN_9_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_HYDRAPPLE
#elif P_PALDEAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_CLODSIRE

#elif P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ENAMORUS
#elif P_HISUIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_OVERQWIL
#elif P_GEN_8_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_URSALUNA
#elif P_GALARIAN_FORMS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_RUNERIGUS

#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_MELMETAL

#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_VOLCANION
#elif P_GEN_6_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_SYLVEON

#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_GENESECT

#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_ARCEUS
#elif P_GEN_4_CROSS_EVOS == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_FROSLASS

#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

#if P_NEW_EVOS_IN_REGIONAL_DEX
#define HOENN_DEX_IF(config, ...) CAT(HOENN_DEX_IF_, config)(__VA_ARGS__)
#define HOENN_DEX_IF_0(...)
#define HOENN_DEX_IF_1(...) __VA_ARGS__
#else
#define HOENN_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_HOENN_DEX_ORDER(F) \
    F(TREECKO) \
    F(GROVYLE) \
    F(SCEPTILE) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(MUDKIP) \
    F(MARSHTOMP) \
    F(SWAMPERT) \
    F(POOCHYENA) \
    F(MIGHTYENA) \
    F(ZIGZAGOON) \
    F(LINOONE) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(OBSTAGOON)) \
    F(WURMPLE) \
    F(SILCOON) \
    F(BEAUTIFLY) \
    F(CASCOON) \
    F(DUSTOX) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(TAILLOW) \
    F(SWELLOW) \
    F(WINGULL) \
    F(PELIPPER) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(GALLADE)) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(SLAKOTH) \
    F(VIGOROTH) \
    F(SLAKING) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(NINCADA) \
    F(NINJASK) \
    F(SHEDINJA) \
    F(WHISMUR) \
    F(LOUDRED) \
    F(EXPLOUD) \
    F(MAKUHITA) \
    F(HARIYAMA) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(AZURILL) \
    F(MARILL) \
    F(AZUMARILL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(NOSEPASS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(PROBOPASS)) \
    F(SKITTY) \
    F(DELCATTY) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(CROBAT) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(SABLEYE) \
    F(MAWILE) \
    F(ARON) \
    F(LAIRON) \
    F(AGGRON) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(MEDITITE) \
    F(MEDICHAM) \
    F(ELECTRIKE) \
    F(MANECTRIC) \
    F(PLUSLE) \
    F(MINUN) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(VOLBEAT) \
    F(ILLUMISE) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    F(BELLOSSOM) \
    F(DODUO) \
    F(DODRIO) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(BUDEW)) \
    F(ROSELIA) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(ROSERADE)) \
    F(GULPIN) \
    F(SWALOT) \
    F(CARVANHA) \
    F(SHARPEDO) \
    F(WAILMER) \
    F(WAILORD) \
    F(NUMEL) \
    F(CAMERUPT) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(TORKOAL) \
    F(GRIMER) \
    F(MUK) \
    F(KOFFING) \
    F(WEEZING) \
    F(SPOINK) \
    F(GRUMPIG) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(SPINDA) \
    F(SKARMORY) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(SWABLU) \
    F(ALTARIA) \
    F(ZANGOOSE) \
    F(SEVIPER) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BARBOACH) \
    F(WHISCASH) \
    F(CORPHISH) \
    F(CRAWDAUNT) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(LILEEP) \
    F(CRADILY) \
    F(ANORITH) \
    F(ARMALDO) \
    F(IGGLYBUFF) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(STARYU) \
    F(STARMIE) \
    F(KECLEON) \
    F(SHUPPET) \
    F(BANETTE) \
    F(DUSKULL) \
    F(DUSCLOPS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(DUSKNOIR)) \
    F(TROPIUS) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(CHINGLING)) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(VULPIX) \
    F(NINETALES) \
    F(PICHU) \
    F(PIKACHU) \
    F(RAICHU) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(WYNAUT) \
    F(WOBBUFFET) \
    F(NATU) \
    F(XATU) \
    F(GIRAFARIG) \
    HOENN_DEX_IF(P_GEN_9_CROSS_EVOS, F(FARIGIRAF)) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PINSIR) \
    F(HERACROSS) \
    F(RHYHORN) \
    F(RHYDON) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    F(SNORUNT) \
    F(GLALIE) \
    HOENN_DEX_IF(P_GEN_4_CROSS_EVOS, F(FROSLASS)) \
    F(SPHEAL) \
    F(SEALEO) \
    F(WALREIN) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(RELICANTH) \
    F(CORSOLA) \
    HOENN_DEX_IF(P_GALARIAN_FORMS, F(CURSOLA)) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(LUVDISC) \
    F(HORSEA) \
    F(SEADRA) \
    F(KINGDRA) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(LATIAS) \
    F(LATIOS) \
    F(KYOGRE) \
    F(GROUDON) \
    F(RAYQUAZA) \
    F(JIRACHI) \
    F(DEOXYS)

// Hoenn Pokédex order
enum HoennDexOrder
{
    HOENN_DEX_NONE,
    #define HOENN_DEX_ENUM(name) HOENN_DEX_ ##name,
    FOREACH_SPECIES_IN_HOENN_DEX_ORDER(HOENN_DEX_ENUM)
    #undef HOENN_DEX_ENUM
};



#if P_NEW_EVOS_IN_REGIONAL_DEX
#define KANTO_DEX_IF(config, ...) CAT(KANTO_DEX_IF_, config)(__VA_ARGS__)
#define KANTO_DEX_IF_0(...)
#define KANTO_DEX_IF_1(...) __VA_ARGS__
#else
#define KANTO_DEX_IF(config, ...)
#endif

#define FOREACH_SPECIES_IN_KANTO_DEX_ORDER(F) \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(CHARMANDER) \
    F(CHARMELEON) \
    F(CHARIZARD) \
    F(SQUIRTLE) \
    F(WARTORTLE) \
    F(BLASTOISE) \
    F(CATERPIE) \
    F(METAPOD) \
    F(BUTTERFREE) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(PIDGEY) \
    F(PIDGEOTTO) \
    F(PIDGEOT) \
    F(RATTATA) \
    F(RATICATE) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PICHU)) \
    F(PIKACHU) \
    F(RAICHU) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(NIDORAN_F) \
    F(NIDORINA) \
    F(NIDOQUEEN) \
    F(NIDORAN_M) \
    F(NIDORINO) \
    F(NIDOKING) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CLEFFA)) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(IGGLYBUFF)) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(CROBAT)) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BELLOSSOM)) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(DIGLETT) \
    F(DUGTRIO) \
    F(MEOWTH) \
    F(PERSIAN) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(PERRSERKER)) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(MANKEY) \
    F(PRIMEAPE) \
    KANTO_DEX_IF(P_GEN_9_CROSS_EVOS, F(ANNIHILAPE)) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(POLIWAG) \
    F(POLIWHIRL) \
    F(POLIWRATH) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(POLITOED)) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(BELLSPROUT) \
    F(WEEPINBELL) \
    F(VICTREEBEL) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SLOWKING)) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGNEZONE)) \
    F(FARFETCHD) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(SIRFETCHD)) \
    F(DODUO) \
    F(DODRIO) \
    F(SEEL) \
    F(DEWGONG) \
    F(GRIMER) \
    F(MUK) \
    F(SHELLDER) \
    F(CLOYSTER) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(ONIX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(STEELIX)) \
    F(DROWZEE) \
    F(HYPNO) \
    F(KRABBY) \
    F(KINGLER) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(EXEGGCUTE) \
    F(EXEGGUTOR) \
    F(CUBONE) \
    F(MAROWAK) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(TYROGUE)) \
    F(HITMONLEE) \
    F(HITMONCHAN) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(HITMONTOP)) \
    F(LICKITUNG) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LICKILICKY)) \
    F(KOFFING) \
    F(WEEZING) \
    F(RHYHORN) \
    F(RHYDON) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(RHYPERIOR)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(HAPPINY)) \
    F(CHANSEY) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(BLISSEY)) \
    F(TANGELA) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(TANGROWTH)) \
    F(KANGASKHAN) \
    F(HORSEA) \
    F(SEADRA) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(KINGDRA)) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MIME_JR)) \
    F(MR_MIME) \
    KANTO_DEX_IF(P_GALARIAN_FORMS, F(MR_RIME)) \
    F(SCYTHER) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SCIZOR)) \
    KANTO_DEX_IF(P_GEN_8_CROSS_EVOS, F(KLEAVOR)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(SMOOCHUM)) \
    F(JYNX) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ELEKID)) \
    F(ELECTABUZZ) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(ELECTIVIRE)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(MAGBY)) \
    F(MAGMAR) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MAGMORTAR)) \
    F(PINSIR) \
    F(TAUROS) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(DITTO) \
    F(EEVEE) \
    F(VAPOREON) \
    F(JOLTEON) \
    F(FLAREON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(ESPEON)) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(UMBREON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(LEAFEON)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(GLACEON)) \
    KANTO_DEX_IF(P_GEN_6_CROSS_EVOS, F(SYLVEON)) \
    F(PORYGON) \
    KANTO_DEX_IF(P_GEN_2_CROSS_EVOS, F(PORYGON2)) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(PORYGON_Z)) \
    F(OMANYTE) \
    F(OMASTAR) \
    F(KABUTO) \
    F(KABUTOPS) \
    F(AERODACTYL) \
    KANTO_DEX_IF(P_GEN_4_CROSS_EVOS, F(MUNCHLAX)) \
    F(SNORLAX) \
    F(ARTICUNO) \
    F(ZAPDOS) \
    F(MOLTRES) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEWTWO) \
    F(ILLUSION_MAGICIAN) \
    F(DARK_MAGICIAN) \
    F(DARK_SAGE) \
    F(BLACK_DRAGONS_CHICK) \
    F(RED_EYES_BLACK_DRAGON) \
    F(RED_EYES_BLACK_METAL_DRAGON) \
    F(PALADIN_OF_WHITE_DRAGON) \
    F(BLUE_EYES_WHITE_DRAGON) \
    F(BLUE_EYES_ULTIMATE_DRAGON) \
    F(MAN_EATER_BUG) \
    F(NOBLEMAN_EATER_BUG) \
    F(PETIT_MOTH) \
    F(LARVAE_MOTH) \
    F(COCOON_OF_EVOLUTION) \
    F(GREAT_MOTH) \
    F(PERFECTLY_ULTIMATE_GREAT_MOTH) \
    F(PARASITE_CATERPILLAR) \
    F(POISON_BUTTERFLY) \
    F(BEAVER_WARRIOR) \
    F(KURIBOH) \
    F(WINGED_KURIBOH) \
    F(WINGED_KURIBOH_LEVEL10) \
    F(KURIBABYLON) \
    F(LINKURIBOH) \
    F(KURIBON) \
    F(SPHERE_KURIBOH) \
    F(JUNKURIBOH) \
    F(LITTLE_WINGUARD) \
    F(ROCKET_WARRIOR) \
    F(SWORDSMAN_OF_LANDSTAR) \
    F(GILFORD_THE_LIGHTNING) \
    F(HAPPY_LOVER) \
    F(SHINING_FRIENDSHIP) \
    F(SPEED_WARRIOR) \
    F(JUNK_SPEEDER) \
    F(FLAME_MANIPULATOR) \
    F(FLAME_SWORDSMAN) \
    F(DARK_FLARE_KNIGHT) \
    F(FERAL_IMP) \
    F(DES_FERAL_IMP) \
    F(KING_OF_THE_FERAL_IMPS) \
    F(BABY_DRAGON) \
    F(THOUSAND_DRAGON) \
    F(JERRY_BEANS_MAN) \
    F(WITCH_OF_THE_BLACK_FOREST) \
    F(SANGAN) \
    F(SANWITCH) \
    F(INJECTION_FAIRY_LILY) \
    F(BETA_THE_MAGNET_WARRIOR) \
    F(VALKYRION) \
    F(ALPHA_THE_MAGNET_WARRIOR) \
    F(BERSERKION) \
    F(GOKIBORE) \
    F(GOKIPOLE) \
    F(BERFORMET) \
    F(CHIMERA_THE_FLYING_MYTHICAL_BEAST) \
    F(CHIMAERA_THE_MASTER_OF_BEASTS) \
    F(SWAMP_BATTLEGUARD) \
    F(LAVA_BATTLEGUARD) \
    F(KILLER_NEEDLE) \
    F(ARMORED_BEE) \
    F(POKI_DRACO) \
    F(DORA_DRACO) \
    F(MUKA_MUKA) \
    F(ENRAGED_MUKA_MUKA) \
    F(QUILLBOLT_HEDGEHOG) \
    F(ANCHORBOLT_HEDGEHOG) \
    F(FROG_THE_JAM) \
    F(TOADALLY_AWESOME) \
    F(TREEBORN_FROG) \
    F(TRADETOAD) \
    F(SUBSTITOAD) \
    F(DES_FROG) \
    F(D3S_FROG) \
    F(TADPOLE) \
    F(BEELZE_FROG) \
    F(SWAP_FROG) \
    F(RONINTOADIN) \
    F(DUPE_FROG) \
    F(LUSTER_DRAGON) \
    F(LUSTER_DRAGON_TWO) \
    F(DIAMOND_HEAD_DRAGON) \
    F(LITTLE_D) \
    F(URABY) \
    F(BLACK_TYRANNO) \
    F(BASIC_INSECT) \
    F(ARMOURED_BASIC_INSECT) \
    F(INSECT_PRINCESS) \
    F(INSECT_QUEEN) \
    F(TWIN_HEADED_REX) \
    F(CELTIC_GUARDIAN) \
    F(OBNOXIOUS_CELTIC_GUARDIAN) \
    F(CELTIC_GUARDIAN_OF_NOBLE_ARMS) \
    F(RYU_KISHIN) \
    F(RYU_KISHIN_POWERED) \
    F(WATAPON) \
    F(MARSHMALLON) \
    F(SPORE) \
    F(SPORE_THE_FAIRY_SEED) \
    F(OJAMA_YELLOW) \
    F(OJAMA_KNIGHT) \
    F(OJAMA_KING) \
    F(MYSTICAL_ELF) \
    F(FLAME_CEREBRUS) \
    F(ALLIGATOR_SWORD) \
    F(CYBERTECH_ALLIGATOR) \
    F(ALLIGATOR_SWORD_DRAGON) \
    F(AXE_RAIDER) \
    F(VORSE_RAIDER) \
    F(WILDHEART) \
    F(WILD_WINGMAN) \
    F(WINGED_DRAGON_GUARDIAN_OF_THE_FORTRESS) \
    F(DARK_MAGICIAN_GIRL) \
    F(DARK_MAGICIAN_GIRL_THE_DRAGON_KNIGHT) \
    F(KAIRYU_SHIN) \
    F(OCEAN_DRAGON_LORD_KAIRYU_SHIN) \
    F(BLACKWING_GALE_THE_WHIRLWIND) \
    F(BLACKWING_ARMOR_MASTER) \
    F(COCKROACH_KNIGHT) \
    F(INSECT_KNIGHT) \
    F(ULTIMATE_BASEBALL_KID) \
    F(HARPIE_LADY) \
    F(HARPIE_LADY_SISTERS) \
    F(CYBER_HARPIE_LADY) \
    F(CYBER_SLASH_HARPIE_LADY) \
    F(HARPIE_QUEEN) \
    F(HARPIE_BROTHER) \
    F(HARPIES_PET_DRAGON) \
    F(AMAZONESS_BABY_TIGER) \
    F(AMAZONESS_TIGER) \
    F(AMAZONESS_PRINCESS) \
    F(AMAZONESS_QUEEN) \
    F(REVIVAL_ROSE) \
    F(REGENERATING_ROSE) \
    F(ROSE_TENTACLES) \
    F(DARK_RESONATOR) \
    F(CRIMSON_RESONATOR) \
    F(SMALL_PIECE_GOLEM) \
    F(MEDIUM_PIECE_GOLEM) \
    F(BIG_PIECE_GOLEM) \
    F(SUMMONED_SKULL) \
    F(BLACK_SKULL_DRAGON) \
    F(ARCHFIENDS_ZOMBIE_SKULL) \
    F(CURSE_OF_DRAGON) \
    F(GAIA_THE_DRAGON_CHAMPION) \
    F(QUEENS_KNIGHT) \
    F(KINGS_KNIGHT) \
    F(JACKS_KNIGHT) \
    F(INFERNITY_ARCHFIEND) \
    F(INFERNITY_DOOM_ARCHFIEND) \
    F(RED_ARCHERY_GIRL) \
    F(SAGGI) \
    F(PETEN) \
    F(AGIDO) \
    F(AGIDO_THE_ANCIENT_SENTINEL) \
    F(KELDO) \
    F(KELDO_THE_SACRED_PROTECTOR) \
    F(BLACK_PTERA) \
    F(OVERTEX_QOATLUS) \
    F(LORD_OF_D) \
    F(KING_OF_D) \
    F(GEARFRIED_THE_IRON_KNIGHT) \
    F(GEARFRIED_THE_SWORDMASTER) \
    F(GIANT_SOLDIER_OF_STONE) \
    F(GIANT_SOLDIER_OF_STEEL) \
    F(CRAB_TURTLE) \
    F(LEGENDARY_FISHERMAN) \
    F(LEGENDARY_FISHERMAN_TWO) \
    F(KOUMORI_DRAGON) \
    F(SERPENT_NIGHT_DRAGON) \
    F(JUNK_SYNCHRON) \
    F(JUNK_WARRIOR) \
    F(JUNK_DESTROYER) \
    F(JUNK_ARCHER) \
    F(NITRO_SYNCHRON) \
    F(NITRO_WARRIOR) \
    F(TURBO_SYNCHRON) \
    F(TURBO_WARRIOR) \
    F(ROAD_SYNCHRON) \
    F(ROAD_WARRIOR) \
    F(QUICKDRAW_SYNCHRON) \
    F(LEVEL_EATER) \
    F(OUTSTANDING_DOG_MARRON) \
    F(SKULL_DOG_MARRON) \
    F(MAD_DOG_OF_DARKNESS) \
    F(BEHEMOTH_KING_OF_ALL_ANIMALS) \
    F(INPACHI) \
    F(BLAZING_INPACHI) \
    F(CHARCOAL_INPACHI) \
    F(GAIA_THE_FIERCE_KNIGHT) \
    F(GAIA_KNIGHT_THE_FORCE_OF_EARTH) \
    F(DARK_CAVALRY) \
    F(AVIAN) \
    F(FLAME_WINGMAN) \
    F(SHINING_FLARE_WINGMAN) \
    F(CYBER_PETIT_ANGEL) \
    F(CYBER_ANGEL_BENTEN) \
    F(CYBER_ANGEL_DAKINI) \
    F(WARRIOR_OF_ZERA) \
    F(ZERA_THE_MANT) \
    F(MEGAZOWLER) \
    F(ILLUSIONIST_FACELESS_MAGE) \
    F(ILLUSIONIST_FACELESS_MAGICIAN) \
    F(PARROT_DRAGON) \
    F(TRI_HORNED_DRAGON) \
    F(MYSTIC_TOMATO) \
    F(HUNGRY_BURGER) \
    F(THUNDER_DRAGON) \
    F(TWIN_HEADED_THUNDER_DRAGON) \
    F(THUNDER_DRAGON_TITAN) \
    F(THUNDER_DRAGON_COLOSSUS) \
    F(PANTHER_WARRIOR) \
    F(SOLITAIRE_MAGICIAN) \
    F(FORTUNE_LADY_EVERY) \
    F(MUSICIAN_KING) \
    F(HEAVY_METAL_KING) \
    F(SLOT_MACHINE) \
    F(BATTLE_OX) \
    F(RABID_HORSEMAN) \
    F(JIRAI_GUMO) \
    F(LAUNCHER_SPIDER) \
    F(VAMPIRE_BAT) \
    F(VAMPIRE_LORD) \
    F(VAMPIRE_GENESIS) \
    F(VAMPIRE_LADY) \
    F(VAMPIRE_GRACE) \
    F(CLAYMAN) \
    F(MUDBALLMAN) \
    F(GRACEFUL_DICE) \
    F(SKULL_DICE) \
    F(ORGOTH_THE_RELENTLESS) \
    F(LA_JINN) \
    F(LORD_POISON) \
    F(LAVA_GOLEM) \
    F(REVIVAL_JAM) \
    F(HUMANOID_SLIME) \
    F(HUMANOID_WORM_DRAKE) \
    F(EGYPTIAN_GOD_SLIME) \
    F(PENDULUM_MACHINE) \
    F(SPEAR_DRAGON) \
    F(SILENT_MAGICIAN_LEVEL4) \
    F(SILENT_MAGICIAN_LEVEL8) \
    F(SILENT_SWORDSMAN_LEVEL3) \
    F(SILENT_SWORDSMAN_LEVEL7) \
    F(GANDORA) \
    F(REAPER_OF_THE_CARDS) \
    F(KING_OF_YAMIMAKAI) \
    F(RESCURE_RABBIT) \
    F(RESCUE_CAT) \
    F(WARM_WORM) \
    F(NEEDLE_WORM) \
    F(DUNGEON_WORM) \
    F(KARATE_MAN) \
    F(DES_KANGAROO) \
    F(MASTER_OF_OZ) \
    F(BERSERK_GORILLA) \
    F(SINISTER_SERPENT) \
    F(THIRTEENTH_GRAVE) \
    F(SKULL_SERVANT) \
    F(KING_OF_THE_SKULL_SERVANTS) \
    F(CATAPULT_TURTLE) \
    F(ELECTROMAGNETIC_TURTLE) \
    F(BLOCK_DRAGON) \
    F(BUSTER_BLADER) \
    F(DARK_PALADIN) \
    F(X_CANNON) \
    F(XY_DRAGON) \
    F(XYZ_DRAGON_CANNON) \
    F(JINZO_RETURNER) \
    F(JINZO) \
    F(RYU_RAN) \
    F(MANGA_RYU_RAN) \
    F(BLUE_EYES_TOON_DRAGON) \
    F(TOON_ALLIGATOR) \
    F(TOON_GEMINI_ELF) \
    F(TOON_DARK_MAGICIAN_GIRL) \
    F(TOON_SUMMONED_SKULL) \
    F(TOON_ANCIENT_GEAR_GOLEM) \
    F(RED_EYES_TOON_DRAGON) \
    F(TOON_DARK_MAGICIAN) \
    F(BIG_SHIELD_GARDNA) \
    F(POT_OF_GREED) \
    F(AVATAR_OF_THE_POT) \
    F(PUMPKING) \
    F(GUARDIAN_EATOS) \
    F(HYOZANRYU) \
    F(DARK_NECROFEAR) \
    F(METEOR_DRAGON) \
    F(METEOR_BLACK_DRAGON) \
    F(YATA_GARASU) \
    F(BLACK_LUSTER_SOLDIER) \
    F(CHAOS_EMPEROR_DRAGON) \
    F(DRAGON_MASTER_KNIGHT) \
    F(NEOS) \
    F(AQUA_NEOS) \
    F(FLARE_NEOS) \
    F(GLOW_NEOS) \
    F(AIR_NEOS) \
    F(GRAND_NEOS) \
    F(DARK_NEOS) \
    F(HONEST_NEOS) \
    F(THOUSAND_EYES_IDOL) \
    F(RELINQUISHED) \
    F(THOUSAND_EYES_RESTRICT) \
    F(THE_GREAT_LEVIATHAN) \
    F(FIVE_GOD_DRAGON) \
    F(HAMON) \
    F(RAVIEL) \
    F(URIA) \
    F(OBELISK_THE_TORMENTOR) \
    F(WINGED_DRAGON_OF_RA) \
    F(SLIFER_THE_SKY_DRAGON) \
    F(HORUS_LEVEL_FOUR) \
    F(HORUS_LEVEL_SIX) \
    F(HORUS_LEVEL_EIGHT) \
    F(CYBERDARK_HORN) \
    F(CYBERDARK_DRAGON) \
    F(CYBER_DRAGON) \
    F(CYBER_TWIN_DRAGON) \
    F(CYBER_END_DRAGON) \
    F(CHIMERATECH_OVERDRAGON) \
    F(EXODIA_THE_FORBIDDEN_ONE) \
    F(EXODIA_NECROSS) \
    F(ARMED_DRAGON_LEVEL3) \
    F(ARMED_DRAGON_LEVEL5) \
    F(ARMED_DRAGON_LEVEL7) \
    F(ARMED_DRAGON_LEVEL10) \
    F(MOBIUS) \
    F(MOKEY_MOKEY) \
    F(MOKEY_KING) \
    F(VOLCANIC_SHELL) \
    F(VOLCANIC_SLICER) \
    F(VOLCANIC_SCATTERSHOT) \
    F(VOLCANIC_HAMMERER) \
    F(VOLCANIC_DOOMFIRE) \
    F(VOLCANIC_QUEEN) \
    F(TIME_WIZARD) \
    F(SNOW_DRAGON) \
    F(SNOWDUST_DRAGON) \
    F(WHITE_NIGHT_DRAGON) \
    F(STEAMROID) \
    F(STEAM_GYROID) \
    F(DRILLROID) \
    F(SUPER_VEHICROID_JUMBO_DRAGON) \
    F(AMBULANCEROID) \
    F(AMBULANCE_RESCUEROID) \
    F(NECROSHADE) \
    F(NECROID_SHAMAN) \
    F(SANGA_OF_THE_THUNDER) \
    F(GATE_GUARDIAN_THUNDER_WIND) \
    F(GATE_GUARDIAN) \
    F(SEVEN_COLOURED_FISH) \
    F(BURSTINATRIX) \
    F(RAMPART_BLASTER) \
    F(INFERNO_WING) \
    F(FORTRESS_WHALE) \
    F(SEIYARYU) \
    F(STARRY_NIGHT_STARRY_DRAGON) \
    F(BREAKER_THE_MAGICAL_WARRIOR) \
    F(AQUA_MADOR) \
    F(NEO_AQUA_MADOR) \
    F(ANCIENT_GEAR_SOLDIER) \
    F(ANCIENT_GEAR_GOLEM) \
    F(ULTIMATE_ANCIENT_GEAR_GOLEM) \
    F(WALL_SHADOW) \
    F(FIREWALL_DRAGON) \
    F(PREDAPLANT_VERTE_ANACONDA) \
    F(BLOWBACK_DRAGON) \
    F(BARREL_DRAGON) \
    F(BLADE_SKATER) \
    F(CYBER_BLADER) \
    F(HELIOS_THE_PRIMORDIAL_SUN) \
    F(HELIOS_DUO_MEGISTUS) \
    F(HELIOS_TRICE_MEGISTUS) \
    F(STAR_BOY) \
    F(MISTAR_BOY) \
    F(DARK_RULER_HA_DES) \
    F(DARK_KING_OF_THE_ABYSS) \
    F(SUNLIGHT_UNICORN) \
    F(FIEND_KRAKEN) \
    F(DOOM_KRAKEN) \
    F(MONTAGE_DRAGON) \
    F(BLADEDGE) \
    F(PLASMA_VICE) \
    F(EMBODIMENT_OF_APOPHIS) \
    F(FORMULA_SYNCHRON) \
    F(MAMMOTH_GRAVEYARD) \
    F(GREAT_MAMMOTH_OF_GOLDFINE) \
    F(LAUNDRY_DRAGONMAID) \
    F(HITOTSU_ME_GIANT) \
    F(CYBERNETIC_CYCLOPEAN) \
    F(SONIC_BIRD) \
    F(ALECTOR) \
    F(RUBY_CARBUNCLE) \
    F(CRYSTAL_BEAST_SAPHIRE_PEGASUS) \
    F(PENGUIN_SOLDIER) \
    F(EMPEROR_PENGUIN) \
    F(NIGHTMARE_PENGUIN) \
    F(SWORDSTALKER) \
    F(TOON_MERMAID) \
    F(GEMINI_ELF) \
    F(DARK_JEROID) \
    F(SPARKMAN) \
    F(THUNDERGIANT) \
    F(CHANGE_OF_HEART) \
    F(MIMICAT) \
    F(ARCHFIENDS_MIRROR) \
    F(NIWATORI) \
    F(THUNDER_KID) \
    F(SPACE_MAMBO) \
    F(MUSHROOM_MAN) \
    F(MEDA_BAT) \
    F(BUBBLEMAN) \
    F(STEAM_HEALER) \
    F(MELCHID_THE_FOUR_FACE_BEAST) \
    F(MASKED_BEAST_DES_GARDIUS) \
    F(GRAND_TIKI_ELDER) \
    F(MASKED_BEAST) \
    F(CLOUDIAN_NIMBUSMAN) \
    F(CLOUDIAN_EYE_OF_THE_TYPHOON) \
    F(CLEAR_VICE_DRAGON) \
    F(HONEST) \
    F(MAGICIAN_OF_BLACK_CHAOS) \
    F(RAINBOW_DRAGON) \
    F(RAINBOW_NEOS) \
    F(GHOSTRICK_WITCH) \
    F(GAMECIEL) \
    F(MYSTICAL_BEAST_OF_SERKET) \
    F(JUDGE_MAN) \
    F(JUDGMENT_DRAGON) \
    F(ELDLICH) \
    F(DESTINY_HERO_PLASMA) \
    F(DESTINY_HERO_DREADMASTER) \
    F(DIVINE_SERPENT_GEH) \
    F(FROST_AND_FLAME_DRAGON) \
    F(REPTILIANNE_SERVANT) \
    F(DRAGON_QUEEN_OF_TRAGIC_ENDING) \
    F(ZOA) \
    F(METALZOA) \
    F(KYUOTORA) \
    F(SHUNOROS) \
    F(TYRANT_DRAGON) \
    F(DAEDALUS) \
    F(DANDYLION) \
    F(GIANT_REX) \
    F(SNOWMAN_EATER) \
    F(VENOM_BOA) \
    F(VENNOMINON) \
    F(VENNOMINAGA) \
    F(ARCANA_FORCE_THE_FIEND) \
    F(ARCANA_FORCE_THE_DARK_RULER) \
    F(ARCANA_FORCE_THE_LIGHT_RULER) \
    F(ARCANA_FORCE_THE_WORLD) \
    F(SAMSARAS_LOTUS) \
    F(YUBEL) \
    F(YUBEL_TERROR_INCARNATE) \
    F(YUBEL_ULTIMATE_KNIGHTMARE) \
    F(DARK_DIVINER) \
    F(UNDERGROUND_ARACHNID) \
    F(FROZEN_FITZGERALD) \
    F(ZEMAN_THE_APE_KING) \
    F(DARK_FLATTOP) \
    F(HUNDRED_EYES_DRAGON) \
    F(SUPAY) \
    F(MOON_DRAGON_QUILLA) \
    F(SUN_DRAGON_INTI) \
    F(EARTHBOUND_IMMORTAL_CCAPAC_APU) \
    F(EARTHBOUND_IMMORTAL_CUSILLU) \
    F(EARTHBOUND_IMMORTAL_CCARAYHUA) \
    F(EARTHBOUND_IMMORTAL_URU) \
    F(EARTHBOUND_IMMORTAL_CHACU_CHALLHUA) \
    F(EARTHBOUND_IMMORTAL_ASLLA_PISCU) \
    F(EARTHBOUND_IMMORTAL_WIRAQOCHA_RASCA) \
    F(DEBRIS_DRAGON) \
    F(STARDUST_DRAGON) \
    F(SHOOTING_STAR_DRAGON) \
    F(RED_RISING_DRAGON) \
    F(RED_DRAGON_ARCHFIEND) \
    F(RED_NOVA_DRAGON) \
    F(RED_ROSE_DRAGON) \
    F(BLACK_ROSE_DRAGON) \
    F(RUDDY_ROSE_DRAGON) \
    F(BLACKWING_GHIBLI) \
    F(BLACKWING_DRAGON) \
    F(BLACKWING_ASSAULT_DRAGON) \
    F(FAIRY_DRAGON) \
    F(ANCIENT_FAIRY_DRAGON) \
    F(ANCIENT_PIXIE_DRAGON) \
    F(REVOLUTION_SYNCHRON) \
    F(POWER_TOOL_DRAGON) \
    F(LIFE_STREAM_DRAGON) \
    F(MAJESTIC_DRAGON) \
    F(MAJESTIC_STAR_DRAGON) \
    F(MAJESTIC_RED_DRAGON) \
    F(SHOOTING_QUASAR_DRAGON) \
    F(CRIMSON_DRAGON) \
    F(NIBIRU) \
    F(VICTORY_DRAGON) \
    F(CRITIAS) \
    F(TIMAEUS) \
    F(HERMOS) \
    F(MEW)

// Kanto Pokedex order
enum KantoDexOrder
{
    KANTO_DEX_NONE,
    #define KANTO_DEX_ENUM(name) KANTO_DEX_ ##name,
    FOREACH_SPECIES_IN_KANTO_DEX_ORDER(KANTO_DEX_ENUM)
    #undef KANTO_DEX_ENUM
};

#define KANTO_DEX_COUNT (KANTO_DEX_MEW + 1)
#define HOENN_DEX_COUNT (HOENN_DEX_DEOXYS + 1)

#define REGIONAL_DEX_COUNT (IS_FRLG ? KANTO_DEX_COUNT : HOENN_DEX_COUNT)

#define DECAGRAMS_IN_POUND             453592
#define CM_PER_INCH                    2.54
#define CM_PER_INCH_FACTOR             (CM_PER_INCH * 100)
#define INCHES_IN_FOOT                 12
#define INCHES_IN_ONE_AND_HALF_FOOT    (INCHES_IN_FOOT * 1.5)
#define INCHES_IN_FOOT_FACTOR          (INCHES_IN_FOOT * 10)

#define WEIGHT_HEIGHT_STR_LEN          16
#define WEIGHT_HEIGHT_STR_MEM          (WEIGHT_HEIGHT_STR_LEN * sizeof(u8))

#define DEX_HEADER_X                   96
#define DEX_Y_TOP                      57
#define DEX_Y_BOTTOM                   73
#define DEX_MEASUREMENT_X              129

#define DEX_HGSS_HEADER_X_PADDING      59
#define DEX_HGSS_Y_TOP_PADDING         7
#define DEX_HGSS_Y_BOTTOM_PADDING      4
#define DEX_HGSS_MEASUREMENT_X_PADDING 51

enum
{
    DEX_MODE_HOENN,
    DEX_MODE_NATIONAL
};

enum
{
    FLAG_GET_SEEN,
    FLAG_GET_CAUGHT,
    FLAG_SET_SEEN,
    FLAG_SET_CAUGHT
};

#endif // GUARD_CONSTANTS_POKEDEX_H
