#ifndef GUARD_CONSTANTS_POSTLINK_H
#define GUARD_CONSTANTS_POSTLINK_H

#define POSTLINK_TYPE_SYMTAB 0
#define POSTLINK_TYPE_ENUMTAB 1

#define POSTLINK_SYMTAB_ADD_SYMBOL (1 << 0)
#define POSTLINK_SYMTAB_ADD_REFERRERS (1 << 1)
#define POSTLINK_SYMTAB_ADD_REFERENCES (1 << 2)
#define POSTLINK_SYMTAB_IF_FUNCTION (1 << 3)

#endif
