#ifndef GUARD_CONSTANTS_REGIONS_H
#define GUARD_CONSTANTS_REGIONS_H

// Core-series regions
enum Region
{
    REGION_NONE,
    REGION_KANTO,
    REGION_JOHTO,
    REGION_HOENN,
    REGION_SINNOH,
    REGION_UNOVA,
    REGION_KALOS,
    REGION_ALOLA,
    REGION_GALAR,
    REGION_HISUI,
    REGION_PALDEA,
    REGIONS_COUNT,
};

enum KantoSubRegion
{
    KANTO_SUB_KANTO,
    KANTO_SUB_SEVII123,
    KANTO_SUB_SEVII45,
    KANTO_SUB_SEVII67
};

#endif  // GUARD_CONSTANTS_REGIONS_H
