#ifndef GUARD_CONSTANTS_REGIONS_H
#define GUARD_CONSTANTS_REGIONS_H

// Core-series regions
enum PokemonRegion
{
    POKEMON_REGION_NONE,
    POKEMON_REGION_KANTO,
    POKEMON_REGION_JOHTO,
    POKEMON_REGION_HOENN,
    POKEMON_REGION_SINNOH,
    POKEMON_REGION_UNOVA,
    POKEMON_REGION_KALOS,
    POKEMON_REGION_ALOLA,
    POKEMON_REGION_GALAR,
    POKEMON_REGION_HISUI,
    POKEMON_REGION_PALDEA,
    POKEMON_REGIONS_COUNT,
};

enum RegionMapId
{
    REGION_MAP_UNKNOWN,
    REGION_MAP_HOENN,
    REGION_MAP_KANTO,
    REGION_MAP_SEVII123,
    REGION_MAP_SEVII45,
    REGION_MAP_SEVII67,
    REGION_MAP_COUNT,
};

#endif  // GUARD_CONSTANTS_REGIONS_H