#ifndef GUARD_CONSTANTS_RELATIONSHIPS_H
#define GUARD_CONSTANTS_RELATIONSHIPS_H


// Counterpart Relationship
enum
{
    RELATIONSHIP_UNKNOWN,
    RELATIONSHIP_COMPANION,
    RELATIONSHIP_RIVAL,
    RELATIONSHIP_MENTOR,
    RELATIONSHIP_FOIL,
};

#endif // GUARD_CONSTANTS_RELATIONSHIPS_H