#ifndef GUARD_CONSTANTS_SAFARIS_H
#define GUARD_CONSTANTS_SAFARIS_H

enum SafariEvents {
    SAFARI_EVENT_NONE,
    SAFARI_EVENT_HOENN,
    SAFARI_EVENT_KANTO,
    SAFARI_EVENT_COUNT
};

// VAR_SAFARI_ZONE_STATE
#define ENTERING_SAFARI_ZONE                    1
#define SAFARI_ZONE_NO_STEP_LEFT                2
#define SAFARI_ZONE_NO_BALLS_LEFT               3
#define SAFARI_ZONE_NO_BALLS_MID_BATTLE         4
#define SAFARI_ZONE_RETIRING                    5
#define SAFARI_ZONE_WHITEOUT                    6

#endif // GUARD_CONSTANTS_SAFARIS_H
