#ifndef GUARD_CONSTANTS_SONGS_H
#define GUARD_CONSTANTS_SONGS_H

// Original JP names listed on right, along with any additional notes

enum SongId
{
    MUS_DUMMY                  = 0, // MUS_DUMMY

    #define START_SE           SE_USE_ITEM
    SE_USE_ITEM                = 1, // SE_KAIFUKU
    SE_PC_LOGIN                = 2, // SE_PC_LOGIN
    SE_PC_OFF                  = 3, // SE_PC_OFF
    SE_PC_ON                   = 4, // SE_PC_ON
    SE_SELECT                  = 5, // SE_SELECT
    SE_WIN_OPEN                = 6, // SE_WIN_OPEN
    SE_WALL_HIT                = 7, // SE_WALL_HIT
    SE_DOOR                    = 8, // SE_DOOR
    SE_EXIT                    = 9, // SE_KAIDAN
    SE_LEDGE                   = 10, // SE_DANSA
    SE_BIKE_BELL               = 11, // SE_JITENSYA
    SE_NOT_EFFECTIVE           = 12, // SE_KOUKA_L
    SE_EFFECTIVE               = 13, // SE_KOUKA_M
    SE_SUPER_EFFECTIVE         = 14, // SE_KOUKA_H
    SE_BALL_OPEN               = 15, // SE_BOWA2
    SE_FAINT                   = 16, // SE_POKE_DEAD
    SE_FLEE                    = 17, // SE_NIGERU
    SE_SLIDING_DOOR            = 18, // SE_JIDO_DOA
    SE_SHIP                    = 19, // SE_NAMINORI
    SE_BANG                    = 20, // SE_BAN
    SE_PIN                     = 21, // SE_PIN (General "good", commonly for "!")
    SE_BOO                     = 22, // SE_BOO (General "bad")
    SE_BALL                    = 23, // SE_BOWA (Giving Poké Ball to nurse, Poké Ball shake, etc)
    SE_CONTEST_PLACE           = 24, // SE_JYUNI
    SE_A                       = 25, // SE_A (Bard sounds)
    SE_I                       = 26, // SE_I
    SE_U                       = 27, // SE_U
    SE_E                       = 28, // SE_E
    SE_O                       = 29, // SE_O
    SE_N                       = 30, // SE_N
    SE_SUCCESS                 = 31, // SE_SEIKAI
    SE_FAILURE                 = 32, // SE_HAZURE
    SE_EXP                     = 33, // SE_EXP
    SE_BIKE_HOP                = 34, // SE_JITE_PYOKO
    SE_SWITCH                  = 35, // SE_MU_PACHI
    SE_CLICK                   = 36, // SE_TK_KASYA
    SE_FU_ZAKU                 = 37, // SE_FU_ZAKU (Unknown purpose, unused)
    SE_CONTEST_CONDITION_LOSE  = 38, // SE_FU_ZAKU2
    SE_LAVARIDGE_FALL_WARP     = 39, // SE_FU_ZUZUZU
    SE_ICE_STAIRS              = 40, // SE_RU_GASHIN
    SE_ICE_BREAK               = 41, // SE_RU_GASYAN
    SE_ICE_CRACK               = 42, // SE_RU_BARI
    SE_FALL                    = 43, // SE_RU_HYUU
    SE_UNLOCK                  = 44, // SE_KI_GASYAN
    SE_WARP_IN                 = 45, // SE_TK_WARPIN
    SE_WARP_OUT                = 46, // SE_TK_WARPOUT
    SE_REPEL                   = 47, // SE_TU_SAA
    SE_ROTATING_GATE           = 48, // SE_HI_TURUN
    SE_TRUCK_MOVE              = 49, // SE_TRACK_MOVE
    SE_TRUCK_STOP              = 50, // SE_TRACK_STOP
    SE_TRUCK_UNLOAD            = 51, // SE_TRACK_HAIKI
    SE_TRUCK_DOOR              = 52, // SE_TRACK_DOOR
    SE_BERRY_BLENDER           = 53, // SE_MOTER
    SE_CARD                    = 54, // SE_CARD (Unused, different from the RS card SE)
    SE_SAVE                    = 55, // SE_SAVE
    SE_BALL_BOUNCE_1           = 56, // SE_KON
    SE_BALL_BOUNCE_2           = 57, // SE_KON2
    SE_BALL_BOUNCE_3           = 58, // SE_KON3
    SE_BALL_BOUNCE_4           = 59, // SE_KON4
    SE_BALL_TRADE              = 60, // SE_SUIKOMU
    SE_BALL_THROW              = 61, // SE_NAGERU
    SE_NOTE_C                  = 62, // SE_TOY_C
    SE_NOTE_D                  = 63, // SE_TOY_D
    SE_NOTE_E                  = 64, // SE_TOY_E
    SE_NOTE_F                  = 65, // SE_TOY_F
    SE_NOTE_G                  = 66, // SE_TOY_G
    SE_NOTE_A                  = 67, // SE_TOY_A
    SE_NOTE_B                  = 68, // SE_TOY_B
    SE_NOTE_C_HIGH             = 69, // SE_TOY_C1
    SE_PUDDLE                  = 70, // SE_MIZU
    SE_BRIDGE_WALK             = 71, // SE_HASHI
    SE_ITEMFINDER              = 72, // SE_DAUGI
    SE_DING_DONG               = 73, // SE_PINPON
    SE_BALLOON_RED             = 74, // SE_FUUSEN1
    SE_BALLOON_BLUE            = 75, // SE_FUUSEN2
    SE_BALLOON_YELLOW          = 76, // SE_FUUSEN3
    SE_BREAKABLE_DOOR          = 77, // SE_TOY_KABE
    SE_MUD_BALL                = 78, // SE_TOY_DANGO
    SE_FIELD_POISON            = 79, // SE_DOKU
    SE_ESCALATOR               = 80, // SE_ESUKA
    SE_THUNDERSTORM            = 81, // SE_T_AME
    SE_THUNDERSTORM_STOP       = 82, // SE_T_AME_E
    SE_DOWNPOUR                = 83, // SE_T_OOAME
    SE_DOWNPOUR_STOP           = 84, // SE_T_OOAME_E
    SE_RAIN                    = 85, // SE_T_KOAME
    SE_RAIN_STOP               = 86, // SE_T_KOAME_E
    SE_THUNDER                 = 87, // SE_T_KAMI
    SE_THUNDER2                = 88, // SE_T_KAMI2
    SE_ELEVATOR                = 89, // SE_ELEBETA
    SE_LOW_HEALTH              = 90, // SE_HINSI
    SE_EXP_MAX                 = 91, // SE_EXPMAX
    SE_ROULETTE_BALL           = 92, // SE_TAMAKORO
    SE_ROULETTE_BALL2          = 93, // SE_TAMAKORO_E
    SE_TAILLOW_WING_FLAP       = 94, // SE_BASABASA
    SE_SHOP                    = 95, // SE_REGI
    SE_CONTEST_HEART           = 96, // SE_C_GAJI
    SE_CONTEST_CURTAIN_RISE    = 97, // SE_C_MAKU_U
    SE_CONTEST_CURTAIN_FALL    = 98, // SE_C_MAKU_D
    SE_CONTEST_ICON_CHANGE     = 99, // SE_C_PASI
    SE_CONTEST_ICON_CLEAR      = 100, // SE_C_SYU
    SE_CONTEST_MONS_TURN       = 101, // SE_C_PIKON
    SE_SHINY                   = 102, // SE_REAPOKE
    SE_INTRO_BLAST             = 103, // SE_OP_BASYU
    SE_MUGSHOT                 = 104, // SE_BT_START
    SE_APPLAUSE                = 105, // SE_DENDOU
    SE_VEND                    = 106, // SE_JIHANKI
    SE_ORB                     = 107, // SE_TAMA
    SE_DEX_SCROLL              = 108, // SE_Z_SCROLL
    SE_DEX_PAGE                = 109, // SE_Z_PAGE
    SE_POKENAV_ON              = 110, // SE_PN_ON
    SE_POKENAV_OFF             = 111, // SE_PN_OFF
    SE_DEX_SEARCH              = 112, // SE_Z_SEARCH
    SE_EGG_HATCH               = 113, // SE_TAMAGO
    SE_BALL_TRAY_ENTER         = 114, // SE_TB_START
    SE_BALL_TRAY_BALL          = 115, // SE_TB_KON
    SE_BALL_TRAY_EXIT          = 116, // SE_TB_KARA
    SE_GLASS_FLUTE             = 117, // SE_BIDORO
// Move SFX
    SE_M_THUNDERBOLT           = 118, // SE_W085
    SE_M_THUNDERBOLT2          = 119, // SE_W085B
    SE_M_HARDEN                = 120, // SE_W231
    SE_M_NIGHTMARE             = 121, // SE_W171
    SE_M_VITAL_THROW           = 122, // SE_W233
    SE_M_VITAL_THROW2          = 123, // SE_W233B
    SE_M_BUBBLE                = 124, // SE_W145
    SE_M_BUBBLE2               = 125, // SE_W145B
    SE_M_BUBBLE3               = 126, // SE_W145C
    SE_M_RAIN_DANCE            = 127, // SE_W240
    SE_M_CUT                   = 128, // SE_W015
    SE_M_STRING_SHOT           = 129, // SE_W081
    SE_M_STRING_SHOT2          = 130, // SE_W081B
    SE_M_ROCK_THROW            = 131, // SE_W088
    SE_M_GUST                  = 132, // SE_W016
    SE_M_GUST2                 = 133, // SE_W016B
    SE_M_DOUBLE_SLAP           = 134, // SE_W003
    SE_M_DOUBLE_TEAM           = 135, // SE_W104
    SE_M_RAZOR_WIND            = 136, // SE_W013
    SE_M_ICY_WIND              = 137, // SE_W196
    SE_M_THUNDER_WAVE          = 138, // SE_W086
    SE_M_COMET_PUNCH           = 139, // SE_W004
    SE_M_MEGA_KICK             = 140, // SE_W025
    SE_M_MEGA_KICK2            = 141, // SE_W025B
    SE_M_CRABHAMMER            = 142, // SE_W152
    SE_M_JUMP_KICK             = 143, // SE_W026
    SE_M_FLAME_WHEEL           = 144, // SE_W172
    SE_M_FLAME_WHEEL2          = 145, // SE_W172B
    SE_M_FLAMETHROWER          = 146, // SE_W053
    SE_M_FIRE_PUNCH            = 147, // SE_W007
    SE_M_TOXIC                 = 148, // SE_W092
    SE_M_SACRED_FIRE           = 149, // SE_W221
    SE_M_SACRED_FIRE2          = 150, // SE_W221B
    SE_M_EMBER                 = 151, // SE_W052
    SE_M_TAKE_DOWN             = 152, // SE_W036
    SE_M_BLIZZARD              = 153, // SE_W059
    SE_M_BLIZZARD2             = 154, // SE_W059B
    SE_M_SCRATCH               = 155, // SE_W010
    SE_M_VICEGRIP              = 156, // SE_W011
    SE_M_WING_ATTACK           = 157, // SE_W017
    SE_M_FLY                   = 158, // SE_W019
    SE_M_SAND_ATTACK           = 159, // SE_W028
    SE_M_RAZOR_WIND2           = 160, // SE_W013B
    SE_M_BITE                  = 161, // SE_W044
    SE_M_HEADBUTT              = 162, // SE_W029
    SE_M_SURF                  = 163, // SE_W057
    SE_M_HYDRO_PUMP            = 164, // SE_W056
    SE_M_WHIRLPOOL             = 165, // SE_W250
    SE_M_HORN_ATTACK           = 166, // SE_W030
    SE_M_TAIL_WHIP             = 167, // SE_W039
    SE_M_MIST                  = 168, // SE_W054
    SE_M_POISON_POWDER         = 169, // SE_W077
    SE_M_BIND                  = 170, // SE_W020
    SE_M_DRAGON_RAGE           = 171, // SE_W082
    SE_M_SING                  = 172, // SE_W047
    SE_M_PERISH_SONG           = 173, // SE_W195
    SE_M_PAY_DAY               = 174, // SE_W006
    SE_M_DIG                   = 175, // SE_W091
    SE_M_DIZZY_PUNCH           = 176, // SE_W146
    SE_M_SELF_DESTRUCT         = 177, // SE_W120
    SE_M_EXPLOSION             = 178, // SE_W153
    SE_M_ABSORB_2              = 179, // SE_W071B
    SE_M_ABSORB                = 180, // SE_W071
    SE_M_SCREECH               = 181, // SE_W103
    SE_M_BUBBLE_BEAM           = 182, // SE_W062
    SE_M_BUBBLE_BEAM2          = 183, // SE_W062B
    SE_M_SUPERSONIC            = 184, // SE_W048
    SE_M_BELLY_DRUM            = 185, // SE_W187
    SE_M_METRONOME             = 186, // SE_W118
    SE_M_BONEMERANG            = 187, // SE_W155
    SE_M_LICK                  = 188, // SE_W122
    SE_M_PSYBEAM               = 189, // SE_W060
    SE_M_FAINT_ATTACK          = 190, // SE_W185
    SE_M_SWORDS_DANCE          = 191, // SE_W014
    SE_M_LEER                  = 192, // SE_W043
    SE_M_SWAGGER               = 193, // SE_W207
    SE_M_SWAGGER2              = 194, // SE_W207B
    SE_M_HEAL_BELL             = 195, // SE_W215
    SE_M_CONFUSE_RAY           = 196, // SE_W109
    SE_M_SNORE                 = 197, // SE_W173
    SE_M_BRICK_BREAK           = 198, // SE_W280
    SE_M_GIGA_DRAIN            = 199, // SE_W202
    SE_M_PSYBEAM2              = 200, // SE_W060B
    SE_M_SOLAR_BEAM            = 201, // SE_W076
    SE_M_PETAL_DANCE           = 202, // SE_W080
    SE_M_TELEPORT              = 203, // SE_W100
    SE_M_MINIMIZE              = 204, // SE_W107
    SE_M_SKETCH                = 205, // SE_W166
    SE_M_SWIFT                 = 206, // SE_W129
    SE_M_REFLECT               = 207, // SE_W115
    SE_M_BARRIER               = 208, // SE_W112
    SE_M_DETECT                = 209, // SE_W197
    SE_M_LOCK_ON               = 210, // SE_W199
    SE_M_MOONLIGHT             = 211, // SE_W236
    SE_M_CHARM                 = 212, // SE_W204
    SE_M_CHARGE                = 213, // SE_W268
    SE_M_STRENGTH              = 214, // SE_W070
    SE_M_HYPER_BEAM            = 215, // SE_W063
    SE_M_WATERFALL             = 216, // SE_W127
    SE_M_REVERSAL              = 217, // SE_W179
    SE_M_ACID_ARMOR            = 218, // SE_W151
    SE_M_SANDSTORM             = 219, // SE_W201
    SE_M_TRI_ATTACK            = 220, // SE_W161
    SE_M_TRI_ATTACK2           = 221, // SE_W161B
    SE_M_ENCORE                = 222, // SE_W227
    SE_M_ENCORE2               = 223, // SE_W227B
    SE_M_BATON_PASS            = 224, // SE_W226
    SE_M_MILK_DRINK            = 225, // SE_W208
    SE_M_ATTRACT               = 226, // SE_W213
    SE_M_ATTRACT2              = 227, // SE_W213B
    SE_M_MORNING_SUN           = 228, // SE_W234
    SE_M_FLATTER               = 229, // SE_W260
    SE_M_SAND_TOMB             = 230, // SE_W328
    SE_M_GRASSWHISTLE          = 231, // SE_W320
    SE_M_SPIT_UP               = 232, // SE_W255
    SE_M_DIVE                  = 233, // SE_W291
    SE_M_EARTHQUAKE            = 234, // SE_W089
    SE_M_TWISTER               = 235, // SE_W239
    SE_M_SWEET_SCENT           = 236, // SE_W230
    SE_M_YAWN                  = 237, // SE_W281
    SE_M_SKY_UPPERCUT          = 238, // SE_W327
    SE_M_STAT_INCREASE         = 239, // SE_W287
    SE_M_HEAT_WAVE             = 240, // SE_W257
    SE_M_UPROAR                = 241, // SE_W253
    SE_M_HAIL                  = 242, // SE_W258
    SE_M_COSMIC_POWER          = 243, // SE_W322
    SE_M_TEETER_DANCE          = 244, // SE_W298
    SE_M_STAT_DECREASE         = 245, // SE_W287B
    SE_M_HAZE                  = 246, // SE_W114
    SE_M_HYPER_BEAM2           = 247, // SE_W063B
// FRLG SFX
    SE_RG_DOOR                 = 248, // SE_RG_W_DOOR
    SE_RG_CARD_FLIP            = 249, // SE_RG_CARD1
    SE_RG_CARD_FLIPPING        = 250, // SE_RG_CARD2
    SE_RG_CARD_OPEN            = 251, // SE_RG_CARD3
    SE_RG_BAG_CURSOR           = 252, // SE_RG_BAG1
    SE_RG_BAG_POCKET           = 253, // SE_RG_BAG2
    SE_RG_BALL_CLICK           = 254, // SE_RG_GETTING
    SE_RG_SHOP                 = 255, // SE_RG_SHOP
    SE_RG_SS_ANNE_HORN         = 256, // SE_RG_KITEKI
    SE_RG_HELP_OPEN            = 257, // SE_RG_HELP_OP
    SE_RG_HELP_CLOSE           = 258, // SE_RG_HELP_CL
    SE_RG_HELP_ERROR           = 259, // SE_RG_HELP_NG
    SE_RG_DEOXYS_MOVE          = 260, // SE_RG_DEOMOV
    SE_RG_POKE_JUMP_SUCCESS    = 261, // SE_RG_EXCELLENT
    SE_RG_POKE_JUMP_FAILURE    = 262, // SE_RG_NAWAMISS
    SE_POKENAV_CALL            = 263, // SE_TOREEYE
    SE_POKENAV_HANG_UP         = 264, // SE_TOREOFF
    SE_ARENA_TIMEUP1           = 265, // SE_HANTEI1
    SE_ARENA_TIMEUP2           = 266, // SE_HANTEI2
    SE_PIKE_CURTAIN_CLOSE      = 267, // SE_CURTAIN
    SE_PIKE_CURTAIN_OPEN       = 268, // SE_CURTAIN1
    SE_SUDOWOODO_SHAKE         = 269, // SE_USSOKI
    #define END_SE             SE_SUDOWOODO_SHAKE

    // Music
    #define START_MUS          MUS_LITTLEROOT_TEST
    MUS_LITTLEROOT_TEST        = 350, // MUS_TETSUJI          // Unused, likely a test track.
    MUS_GSC_ROUTE38            = 351, // MUS_FIELD13          // Unused, likely a test track.
    MUS_CAUGHT                 = 352, // MUS_KACHI22
    MUS_VICTORY_WILD           = 353, // MUS_KACHI2
    MUS_VICTORY_GYM_LEADER     = 354, // MUS_KACHI3           // Also used in Frontier Brain victories.
    MUS_VICTORY_LEAGUE         = 355, // MUS_KACHI5
    MUS_C_COMM_CENTER          = 356, // MUS_PCC              // Unused, likely a test track.
    MUS_GSC_PEWTER             = 357, // MUS_NIBI             // Used in unused Contest Halls.
    MUS_C_VS_LEGEND_BEAST      = 358, // MUS_SUIKUN           // Unused, likely a test track.
    MUS_ROUTE101               = 359, // MUS_DOORO1           // Also used in Routes 102 and 103.
    MUS_ROUTE110               = 360, // MUS_DOORO_X1         // Also used in Routes 112, 114, 117, 111's non-desert section and 118's west half.
    MUS_ROUTE120               = 361, // MUS_DOORO_X3         // Also used in Routes 121, 124, 125, 126, 127 and 128.
    MUS_PETALBURG              = 362, // MUS_MACHI_S2         // Also used in Mr. Briney's House and Pretty Petal Flower Shop.
    MUS_OLDALE                 = 363, // MUS_MACHI_S4         // Also used in Lavaridge Town.
    MUS_GYM                    = 364, // MUS_GIM
    MUS_SURF                   = 365, // MUS_NAMINORI
    MUS_PETALBURG_WOODS        = 366, // MUS_DAN01            // Also used in Artisan Cave, Fiery Path, Granite Cave, Jagged Pass, Marine Cave, Rusturf Tunnel, Scorched Slab and Terra Cave.
    MUS_LEVEL_UP               = 367, // MUS_FANFA1
    MUS_HEAL                   = 368, // MUS_ME_ASA
    MUS_OBTAIN_BADGE           = 369, // MUS_ME_BACHI
    MUS_OBTAIN_ITEM            = 370, // MUS_FANFA4
    MUS_EVOLVED                = 371, // MUS_FANFA5           // Also used in egg hatching, trades and upon catching.
    MUS_OBTAIN_TMHM            = 372, // MUS_ME_WAZA
    MUS_LILYCOVE_MUSEUM        = 373, // MUS_BIJYUTU          // Also used in the Battle Frontier's Ranking Hall.
    MUS_ROUTE122               = 374, // MUS_DOORO_X4         // Also used in Route 123 and Birch's intro speech.
    MUS_OCEANIC_MUSEUM         = 375, // MUS_FUNE_KAN
    MUS_EVOLUTION_INTRO        = 376, // MUS_ME_SHINKA        // Also used in egg hatching.
    MUS_EVOLUTION              = 377, // MUS_SHINKA           // Also used in egg hatching and trades.
    MUS_MOVE_DELETED           = 378, // MUS_ME_WASURE
    MUS_ENCOUNTER_GIRL         = 379, // MUS_SYOUJOEYE
    MUS_ENCOUNTER_MALE         = 380, // MUS_BOYEYE
    MUS_ABANDONED_SHIP         = 381, // MUS_DAN02            // Also used in Faraway and Southern Islands.
    MUS_FORTREE                = 382, // MUS_MACHI_S3         // Also used in Secret Bases and the Safari Zone's entrance.
    MUS_BIRCH_LAB              = 383, // MUS_ODAMAKI
    MUS_B_TOWER_RS             = 384, // MUS_B_TOWER          // Used in Battle Tents, Trainer Hill and Battle Frontier's lounges and Exchange Service Corner.
    MUS_ENCOUNTER_SWIMMER      = 385, // MUS_SWIMEYE
    MUS_CAVE_OF_ORIGIN         = 386, // MUS_DAN03            // Also used in Meteor Falls.
    MUS_OBTAIN_BERRY           = 387, // MUS_ME_KINOMI
    MUS_AWAKEN_LEGEND          = 388, // MUS_ME_TAMA
    MUS_SLOTS_JACKPOT          = 389, // MUS_ME_B_BIG         // Also used in the Roulette.
    MUS_SLOTS_WIN              = 390, // MUS_ME_B_SMALL       // Also used in the Roulette.
    MUS_TOO_BAD                = 391, // MUS_ME_ZANNEN
    MUS_ROULETTE               = 392, // MUS_BD_TIME
    MUS_LINK_CONTEST_P1        = 393, // MUS_TEST1
    MUS_LINK_CONTEST_P2        = 394, // MUS_TEST2
    MUS_LINK_CONTEST_P3        = 395, // MUS_TEST3
    MUS_LINK_CONTEST_P4        = 396, // MUS_TEST4
    MUS_ENCOUNTER_RICH         = 397, // MUS_TEST
    MUS_VERDANTURF             = 398, // MUS_GOMACHI0
    MUS_RUSTBORO               = 399, // MUS_GOTOWN           // Also used in Mauville City, Mossdeep City, Daycare, Weather Institute and several Route houses.
    MUS_POKE_CENTER            = 400, // MUS_POKECEN          // Also used in the Pokémon League's lobby.
    MUS_ROUTE104               = 401, // MUS_NEXTROAD         // Also used in Routes 105, 106, 107, 108, 109, 115 and 116.
    MUS_ROUTE119               = 402, // MUS_GRANROAD         // Also used in Routes 129, 130, 131, 132, 133, 134 and 118's east half.
    MUS_CYCLING                = 403, // MUS_CYCLING
    MUS_POKE_MART              = 404, // MUS_FRIENDLY         // Also used in Lilycove's Department Store.
    MUS_LITTLEROOT             = 405, // MUS_MISHIRO
    MUS_MT_CHIMNEY             = 406, // MUS_TOZAN            // Also used in Desert Underpass, Mirage Tower, Seafloor Cavern and Sky Pillar.
    MUS_ENCOUNTER_FEMALE       = 407, // MUS_GIRLEYE
    MUS_LILYCOVE               = 408, // MUS_MINAMO           // Also used in Pacifidlog Town and the Diving Treasure Hunter's house.
    MUS_DESERT                 = 409, // MUS_ASHROAD
    MUS_HELP                   = 410, // MUS_EVENT0
    MUS_UNDERWATER             = 411, // MUS_DEEPDEEP
    MUS_VICTORY_TRAINER        = 412, // MUS_KACHI1
    MUS_TITLE                  = 413, // MUS_TITLE3
    MUS_INTRO                  = 414, // MUS_DEMO1
    MUS_ENCOUNTER_MAY          = 415, // MUS_GIRL_SUP
    MUS_ENCOUNTER_INTENSE      = 416, // MUS_HAGESHII
    MUS_ENCOUNTER_COOL         = 417, // MUS_KAKKOII
    MUS_ROUTE113               = 418, // MUS_KAZANBAI
    MUS_ENCOUNTER_AQUA         = 419, // MUS_AQA_0
    MUS_FOLLOW_ME              = 420, // MUS_TSURETEK
    MUS_ENCOUNTER_BRENDAN      = 421, // MUS_BOY_SUP
    MUS_EVER_GRANDE            = 422, // MUS_RAINBOW          // Also used in link rooms.
    MUS_ENCOUNTER_SUSPICIOUS   = 423, // MUS_AYASII
    MUS_VICTORY_AQUA_MAGMA     = 424, // MUS_KACHI4
    MUS_CABLE_CAR              = 425, // MUS_ROPEWAY
    MUS_GAME_CORNER            = 426, // MUS_CASINO
    MUS_DEWFORD                = 427, // MUS_HIGHTOWN         // Also used in Route 109's Seashore house.
    MUS_SAFARI_ZONE            = 428, // MUS_SAFARI
    MUS_VICTORY_ROAD           = 429, // MUS_C_ROAD           // Also used in Pokémon League's E4/Champion rooms and halls.
    MUS_AQUA_MAGMA_HIDEOUT     = 430, // MUS_AJITO
    MUS_SAILING                = 431, // MUS_M_BOAT
    MUS_MT_PYRE                = 432, // MUS_M_DUNGON         // Also used in New Mauville and Shoal Cave.
    MUS_SLATEPORT              = 433, // MUS_FINECITY         // Also used in Cycling Road's entrances.
    MUS_MT_PYRE_EXTERIOR       = 434, // MUS_MACHUPI
    MUS_SCHOOL                 = 435, // MUS_P_SCHOOL
    MUS_HALL_OF_FAME           = 436, // MUS_DENDOU
    MUS_FALLARBOR              = 437, // MUS_TONEKUSA         // Also used in Route 114's houses.
    MUS_SEALED_CHAMBER         = 438, // MUS_MABOROSI         // Also used in Ancient Tomb, Desert Ruins and Island Cave.
    MUS_CONTEST_WINNER         = 439, // MUS_CON_FAN
    MUS_CONTEST                = 440, // MUS_CONTEST0
    MUS_ENCOUNTER_MAGMA        = 441, // MUS_MGM0
    MUS_INTRO_BATTLE           = 442, // MUS_T_BATTLE
    MUS_ABNORMAL_WEATHER       = 443, // MUS_OOAME            // Replaces MUS_WEATHER_KYOGRE from R/S.
    MUS_WEATHER_GROUDON        = 444, // MUS_HIDERI           // Unused, from R/S.
    MUS_SOOTOPOLIS             = 445, // MUS_RUNECITY
    MUS_CONTEST_RESULTS        = 446, // MUS_CON_K
    MUS_HALL_OF_FAME_ROOM      = 447, // MUS_EIKOU_R
    MUS_TRICK_HOUSE            = 448, // MUS_KARAKURI
    MUS_ENCOUNTER_TWINS        = 449, // MUS_HUTAGO
    MUS_ENCOUNTER_ELITE_FOUR   = 450, // MUS_SITENNOU
    MUS_ENCOUNTER_HIKER        = 451, // MUS_YAMA_EYE
    MUS_CONTEST_LOBBY          = 452, // MUS_CONLOBBY
    MUS_ENCOUNTER_INTERVIEWER  = 453, // MUS_INTER_V          // Also used during Petalburg City report at the beginning of the game.
    MUS_ENCOUNTER_CHAMPION     = 454, // MUS_DAIGO
    MUS_CREDITS                = 455, // MUS_THANKFOR
    MUS_END                    = 456, // MUS_END
    MUS_B_FRONTIER             = 457, // MUS_B_FRONTIER
    MUS_B_ARENA                = 458, // MUS_B_ARENA
    MUS_OBTAIN_B_POINTS        = 459, // MUS_ME_POINTGET
    MUS_REGISTER_MATCH_CALL    = 460, // MUS_ME_TORE_EYE
    MUS_B_PYRAMID              = 461, // MUS_PYRAMID
    MUS_B_PYRAMID_TOP          = 462, // MUS_PYRAMID_TOP
    MUS_B_PALACE               = 463, // MUS_B_PALACE
    MUS_RAYQUAZA_APPEARS       = 464, // MUS_REKKUU_KOURIN
    MUS_B_TOWER                = 465, // MUS_SATTOWER
    MUS_OBTAIN_SYMBOL          = 466, // MUS_ME_SYMBOLGET
    MUS_B_DOME                 = 467, // MUS_B_DOME
    MUS_B_PIKE                 = 468, // MUS_B_TUBE
    MUS_B_FACTORY              = 469, // MUS_B_FACTORY
    MUS_VS_RAYQUAZA            = 470, // MUS_VS_REKKU         // Identical to MUS_VS_KYOGRE_GROUDON.
    MUS_VS_FRONTIER_BRAIN      = 471, // MUS_VS_FRONT
    MUS_VS_MEW                 = 472, // MUS_VS_MEW
    MUS_B_DOME_LOBBY           = 473, // MUS_B_DOME1
    MUS_VS_WILD                = 474, // MUS_BATTLE27
    MUS_VS_AQUA_MAGMA          = 475, // MUS_BATTLE31
    MUS_VS_TRAINER             = 476, // MUS_BATTLE20
    MUS_VS_GYM_LEADER          = 477, // MUS_BATTLE32
    MUS_VS_CHAMPION            = 478, // MUS_BATTLE33
    MUS_VS_REGI                = 479, // MUS_BATTLE36
    MUS_VS_KYOGRE_GROUDON      = 480, // MUS_BATTLE34
    MUS_VS_RIVAL               = 481, // MUS_BATTLE35
    MUS_VS_ELITE_FOUR          = 482, // MUS_BATTLE38
    MUS_VS_AQUA_MAGMA_LEADER   = 483, // MUS_BATTLE30
// FRLG Music
    MUS_RG_FOLLOW_ME           = 484, // MUS_RG_ANNAI
    MUS_RG_GAME_CORNER         = 485, // MUS_RG_SLOT
    MUS_RG_ROCKET_HIDEOUT      = 486, // MUS_RG_AJITO
    MUS_RG_GYM                 = 487, // MUS_RG_GYM
    MUS_RG_JIGGLYPUFF          = 488, // MUS_RG_PURIN
    MUS_RG_INTRO_FIGHT         = 489, // MUS_RG_DEMO
    MUS_RG_TITLE               = 490, // MUS_RG_TITLE
    MUS_RG_CINNABAR            = 491, // MUS_RG_GUREN
    MUS_RG_LAVENDER            = 492, // MUS_RG_SHION
    MUS_RG_HEAL                = 493, // MUS_RG_KAIHUKU
    MUS_RG_CYCLING             = 494, // MUS_RG_CYCLING
    MUS_RG_ENCOUNTER_ROCKET    = 495, // MUS_RG_ROCKET
    MUS_RG_ENCOUNTER_GIRL      = 496, // MUS_RG_SHOUJO
    MUS_RG_ENCOUNTER_BOY       = 497, // MUS_RG_SHOUNEN
    MUS_RG_HALL_OF_FAME        = 498, // MUS_RG_DENDOU
    MUS_RG_VIRIDIAN_FOREST     = 499, // MUS_RG_T_MORI
    MUS_RG_MT_MOON             = 500, // MUS_RG_OTSUKIMI
    MUS_RG_POKE_MANSION        = 501, // MUS_RG_POKEYASHI
    MUS_RG_CREDITS             = 502, // MUS_RG_ENDING
    MUS_RG_ROUTE1              = 503, // MUS_RG_LOAD01
    MUS_RG_ROUTE24             = 504, // MUS_RG_OPENING
    MUS_RG_ROUTE3              = 505, // MUS_RG_LOAD02
    MUS_RG_ROUTE11             = 506, // MUS_RG_LOAD03
    MUS_RG_VICTORY_ROAD        = 507, // MUS_RG_CHAMP_R
    MUS_RG_VS_GYM_LEADER       = 508, // MUS_RG_VS_GYM
    MUS_RG_VS_TRAINER          = 509, // MUS_RG_VS_TORE
    MUS_RG_VS_WILD             = 510, // MUS_RG_VS_YASEI
    MUS_RG_VS_CHAMPION         = 511, // MUS_RG_VS_LAST
    MUS_RG_PALLET              = 512, // MUS_RG_MASARA
    MUS_RG_OAK_LAB             = 513, // MUS_RG_KENKYU
    MUS_RG_OAK                 = 514, // MUS_RG_OHKIDO
    MUS_RG_POKE_CENTER         = 515, // MUS_RG_POKECEN
    MUS_RG_SS_ANNE             = 516, // MUS_RG_SANTOAN
    MUS_RG_SURF                = 517, // MUS_RG_NAMINORI
    MUS_RG_POKE_TOWER          = 518, // MUS_RG_P_TOWER
    MUS_RG_SILPH               = 519, // MUS_RG_SHIRUHU
    MUS_RG_FUCHSIA             = 520, // MUS_RG_HANADA
    MUS_RG_CELADON             = 521, // MUS_RG_TAMAMUSI
    MUS_RG_VICTORY_TRAINER     = 522, // MUS_RG_WIN_TRE       // Identical to MUS_VICTORY_TRAINER.
    MUS_RG_VICTORY_WILD        = 523, // MUS_RG_WIN_YASEI     // Identical to MUS_VICTORY_WILD.
    MUS_RG_VICTORY_GYM_LEADER  = 524, // MUS_RG_WIN_GYM       // Identical to MUS_VICTORY_GYM_LEADER.
    MUS_RG_VERMILLION          = 525, // MUS_RG_KUCHIBA
    MUS_RG_PEWTER              = 526, // MUS_RG_NIBI
    MUS_RG_ENCOUNTER_RIVAL     = 527, // MUS_RG_RIVAL1
    MUS_RG_RIVAL_EXIT          = 528, // MUS_RG_RIVAL2
    MUS_RG_DEX_RATING          = 529, // MUS_RG_FAN2
    MUS_RG_OBTAIN_KEY_ITEM     = 530, // MUS_RG_FAN5
    MUS_RG_CAUGHT_INTRO        = 531, // MUS_RG_FAN6
    MUS_RG_PHOTO               = 532, // MUS_ME_RG_PHOTO
    MUS_RG_GAME_FREAK          = 533, // MUS_RG_TITLEROG
    MUS_RG_CAUGHT              = 534, // MUS_RG_GET_YASEI
    MUS_RG_NEW_GAME_INSTRUCT   = 535, // MUS_RG_SOUSA
    MUS_RG_NEW_GAME_INTRO      = 536, // MUS_RG_SEKAIKAN
    MUS_RG_NEW_GAME_EXIT       = 537, // MUS_RG_SEIBETU
    MUS_RG_POKE_JUMP           = 538, // MUS_RG_JUMP
    MUS_RG_UNION_ROOM          = 539, // MUS_RG_UNION
    MUS_RG_NET_CENTER          = 540, // MUS_RG_NETWORK
    MUS_RG_MYSTERY_GIFT        = 541, // MUS_RG_OKURIMONO
    MUS_RG_BERRY_PICK          = 542, // MUS_RG_KINOMIKUI
    MUS_RG_SEVII_CAVE          = 543, // MUS_RG_NANADUNGEON   // Identical to MUS_RG_MT_MOON.
    MUS_RG_TEACHY_TV_SHOW      = 544, // MUS_RG_OSHIE_TV      // Identical to MUS_RG_FOLLOW_ME.
    MUS_RG_SEVII_ROUTE         = 545, // MUS_RG_NANASHIMA
    MUS_RG_SEVII_DUNGEON       = 546, // MUS_RG_NANAISEKI     // Identical to MUS_RG_VIRIDIAN_FOREST.
    MUS_RG_SEVII_123           = 547, // MUS_RG_NANA123       // Identical to MUS_RG_PEWTER
    MUS_RG_SEVII_45            = 548, // MUS_RG_NANA45
    MUS_RG_SEVII_67            = 549, // MUS_RG_NANA67
    MUS_RG_POKE_FLUTE          = 550, // MUS_RG_POKEFUE
    MUS_RG_VS_DEOXYS           = 551, // MUS_RG_VS_DEO
    MUS_RG_VS_MEWTWO           = 552, // MUS_RG_VS_MYU2
    MUS_RG_VS_LEGEND           = 553, // MUS_RG_VS_DEN
    MUS_RG_ENCOUNTER_GYM_LEADER= 554, // MUS_RG_EXEYE
    MUS_RG_ENCOUNTER_DEOXYS    = 555, // MUS_RG_DEOEYE
    MUS_RG_TRAINER_TOWER       = 556, // MUS_RG_T_TOWER
    MUS_RG_SLOW_PALLET         = 557, // MUS_RG_SLOWMASARA
    MUS_RG_TEACHY_TV_MENU      = 558, // MUS_RG_TVNOIZE
    #define END_MUS            MUS_RG_TEACHY_TV_MENU

    // These PH_* constants are phoneme sounds used by the "bard" NPC (see src/bard_music.c and src/mauville_old_man.c).
    // Each comes in a triplet of PH_*_BLEND, PH_*_HELD, and PH_*_SOLO, and the name of each triplet incorporates the English phonetic sound it represents.
    PH_TRAP_BLEND              = 559,
    PH_TRAP_HELD               = 560,
    PH_TRAP_SOLO               = 561,
    PH_FACE_BLEND              = 562,
    PH_FACE_HELD               = 563,
    PH_FACE_SOLO               = 564,
    PH_CLOTH_BLEND             = 565,
    PH_CLOTH_HELD              = 566,
    PH_CLOTH_SOLO              = 567,
    PH_DRESS_BLEND             = 568,
    PH_DRESS_HELD              = 569,
    PH_DRESS_SOLO              = 570,
    PH_FLEECE_BLEND            = 571,
    PH_FLEECE_HELD             = 572,
    PH_FLEECE_SOLO             = 573,
    PH_KIT_BLEND               = 574,
    PH_KIT_HELD                = 575,
    PH_KIT_SOLO                = 576,
    PH_PRICE_BLEND             = 577,
    PH_PRICE_HELD              = 578,
    PH_PRICE_SOLO              = 579,
    PH_LOT_BLEND               = 580,
    PH_LOT_HELD                = 581,
    PH_LOT_SOLO                = 582,
    PH_GOAT_BLEND              = 583,
    PH_GOAT_HELD               = 584,
    PH_GOAT_SOLO               = 585,
    PH_THOUGHT_BLEND           = 586,
    PH_THOUGHT_HELD            = 587,
    PH_THOUGHT_SOLO            = 588,
    PH_CHOICE_BLEND            = 589,
    PH_CHOICE_HELD             = 590,
    PH_CHOICE_SOLO             = 591,
    PH_MOUTH_BLEND             = 592,
    PH_MOUTH_HELD              = 593,
    PH_MOUTH_SOLO              = 594,
    PH_FOOT_BLEND              = 595,
    PH_FOOT_HELD               = 596,
    PH_FOOT_SOLO               = 597,
    PH_GOOSE_BLEND             = 598,
    PH_GOOSE_HELD              = 599,
    PH_GOOSE_SOLO              = 600,
    PH_STRUT_BLEND             = 601,
    PH_STRUT_HELD              = 602,
    PH_STRUT_SOLO              = 603,
    PH_CURE_BLEND              = 604,
    PH_CURE_HELD               = 605,
    PH_CURE_SOLO               = 606,
    PH_NURSE_BLEND             = 607,
    PH_NURSE_HELD              = 608,
    PH_NURSE_SOLO              = 609,

    MUS_ROUTE118               = 0x7FFF, // Map is split into 2 music sections. controlled by GetCurrLocationDefaultMusic().

    MUS_NONE                   = 0xFFFF,
};

#define FIRST_PHONEME_SONG PH_TRAP_BLEND
#define LAST_PHONEME_SONG  PH_NURSE_SOLO
#define NUM_PHONEME_SONGS  (LAST_PHONEME_SONG - FIRST_PHONEME_SONG + 1)
#define PHONEME_ID(song)   ((song) - FIRST_PHONEME_SONG)
#define PHONEME_ID_NONE    0xFF

#endif // GUARD_CONSTANTS_SONGS_H
