#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(TAKE_DOWN) \
    F(MUD_SLAP) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(LOW_KICK) \
    F(ACID_SPRAY) \
    F(ACROBATICS) \
    F(DRAINING_KISS) \
    F(DAZZLING_GLEAM) \
    F(POWER_GEM) \
    F(LIQUIDATION) \
    F(REVERSAL) \
    F(PHANTOM_FORCE) \
    F(BUG_BUZZ) \
    F(GYRO_BALL) \
    F(PETAL_BLIZZARD) \
    F(LASH_OUT) \
    F(DRACO_METEOR) \
    F(VOLT_SWITCH) \
    F(ZEN_HEADBUTT) \
    F(HYPER_VOICE) \
    F(GUNK_SHOT) \
    F(ROCK_BLAST) \
    F(AIR_SLASH) \
    F(HEX) \
    F(SCALD) \
    F(ICY_WIND) \
    F(DRAGON_TAIL) \
    F(BULLDOZE) \
    F(STEEL_BEAM) \
    F(DARK_PULSE) \
    F(AURA_SPHERE) \
    F(HEAT_WAVE) \
    F(ENERGY_BALL) \
    F(PLAY_ROUGH) \
    F(U_TURN) \
    F(FAKE_TEARS) \
    F(DRAGON_DANCE) \
    F(CHARM) \
    F(NASTY_PLOT) \
    F(TAILWIND) \
    F(CURSE) \
    F(SPIKES) \
    F(HAZE) \
    F(ENDURE) \
    F(STEALTH_ROCK) \
    F(PAIN_SPLIT) \
    F(AGILITY) \
    F(SWORDS_DANCE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
