#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

// Generated by pentara/tools/gen_learnsets.py from pentara/design/tms.py

#define FOREACH_TM(F) \
    F(PROTECT) \
    F(REST) \
    F(TOXIC) \
    F(THUNDER_WAVE) \
    F(WILL_O_WISP) \
    F(REFLECT) \
    F(LIGHT_SCREEN) \
    F(SUNNY_DAY) \
    F(RAIN_DANCE) \
    F(SANDSTORM) \
    F(SNOWSCAPE) \
    F(SWORDS_DANCE) \
    F(CALM_MIND) \
    F(BULK_UP) \
    F(WATER_PULSE) \
    F(FLAME_CHARGE) \
    F(MAGICAL_LEAF) \
    F(SHOCK_WAVE) \
    F(ICY_WIND) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(BRICK_BREAK) \
    F(BULLDOZE) \
    F(VENOSHOCK) \
    F(BUG_BITE) \
    F(SHADOW_CLAW) \
    F(DRAGON_BREATH) \
    F(PSYBEAM) \
    F(DRAINING_KISS) \
    F(METAL_CLAW) \
    F(FLAMETHROWER) \
    F(SURF) \
    F(ICE_BEAM) \
    F(THUNDERBOLT) \
    F(PSYCHIC) \
    F(ENERGY_BALL) \
    F(SLUDGE_BOMB) \
    F(EARTH_POWER) \
    F(DIG) \
    F(X_SCISSOR) \
    F(POISON_JAB) \
    F(ZEN_HEADBUTT) \
    F(IRON_HEAD) \
    F(FLASH_CANNON) \
    F(DAZZLING_GLEAM) \
    F(DRAGON_CLAW) \
    F(DRAGON_PULSE) \
    F(SHADOW_BALL) \
    F(DARK_PULSE) \
    F(CRUNCH) \
    F(AURA_SPHERE) \
    F(AIR_SLASH) \
    F(ROCK_SLIDE) \
    F(BODY_SLAM) \
    F(U_TURN) \
    F(KNOCK_OFF) \
    F(ROOST) \
    F(NASTY_PLOT) \
    F(STEALTH_ROCK) \
    F(TAILWIND) \
    F(FIRE_BLAST) \
    F(BLIZZARD) \
    F(THUNDER) \
    F(HYDRO_PUMP) \
    F(SOLAR_BEAM) \
    F(EARTHQUAKE) \
    F(STONE_EDGE) \
    F(CLOSE_COMBAT) \
    F(FOCUS_BLAST) \
    F(BRAVE_BIRD) \
    F(HURRICANE) \
    F(MEGAHORN) \
    F(GUNK_SHOT) \
    F(OUTRAGE) \
    F(PLAY_ROUGH) \
    F(MOONBLAST) \
    F(HEAT_WAVE) \
    F(LEAF_STORM) \
    F(WILD_CHARGE) \
    F(LIQUIDATION) \
    F(DRACO_METEOR) \
    F(FLARE_BLITZ) \
    F(SUPERPOWER) \
    F(HYPER_BEAM) \
    F(GIGA_IMPACT) \
    F(DRAGON_DANCE) \
    F(TRICK_ROOM) \
    F(SPIKES) \
    F(SCALD) \
    F(PHANTOM_FORCE) \
    F(STEEL_BEAM) \
    F(METEOR_BEAM) \
    F(EXPLOSION) \
    F(HIGH_HORSEPOWER) \
    F(POLTERGEIST) \
    F(BLEAKWIND_STORM) \
    F(SANDSEAR_STORM) \
    F(WILDBOLT_STORM) \
    F(SPRINGTIDE_STORM) \
    F(LUMINA_CRASH)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
