#ifndef GUARD_TRAINERS_H
#define GUARD_TRAINERS_H

#include "constants/opponents.h"
#include "constants/battle_frontier_trainers.h"

// Special Trainer Ids.
//      0-299 are frontier trainers
#define TRAINER_RECORD_MIXING_FRIEND        FRONTIER_TRAINERS_COUNT
#define TRAINER_RECORD_MIXING_APPRENTICE    400
#define TRAINER_EREADER                     500
#define TRAINER_FRONTIER_BRAIN              1022
#define TRAINER_PLAYER                      1023
#define TRAINER_SECRET_BASE                 1024
#define TRAINER_LINK_OPPONENT               2048
#define TRAINER_UNION_ROOM                  3072

#define TRAINER_PIC_HIKER                  0
#define TRAINER_PIC_AQUA_GRUNT_M           1
#define TRAINER_PIC_POKEMON_BREEDER_F      2
#define TRAINER_PIC_COOLTRAINER_M          3
#define TRAINER_PIC_BIRD_KEEPER            4
#define TRAINER_PIC_COLLECTOR              5
#define TRAINER_PIC_AQUA_GRUNT_F           6
#define TRAINER_PIC_SWIMMER_M              7
#define TRAINER_PIC_MAGMA_GRUNT_M          8
#define TRAINER_PIC_EXPERT_M               9
#define TRAINER_PIC_AQUA_ADMIN_M          10
#define TRAINER_PIC_BLACK_BELT            11
#define TRAINER_PIC_AQUA_ADMIN_F          12
#define TRAINER_PIC_AQUA_LEADER_ARCHIE    13
#define TRAINER_PIC_HEX_MANIAC            14
#define TRAINER_PIC_AROMA_LADY            15
#define TRAINER_PIC_RUIN_MANIAC           16
#define TRAINER_PIC_INTERVIEWER           17
#define TRAINER_PIC_TUBER_F               18
#define TRAINER_PIC_TUBER_M               19
#define TRAINER_PIC_COOLTRAINER_F         20
#define TRAINER_PIC_LADY                  21
#define TRAINER_PIC_BEAUTY                22
#define TRAINER_PIC_RICH_BOY              23
#define TRAINER_PIC_EXPERT_F              24
#define TRAINER_PIC_POKEMANIAC            25
#define TRAINER_PIC_MAGMA_GRUNT_F         26
#define TRAINER_PIC_GUITARIST             27
#define TRAINER_PIC_KINDLER               28
#define TRAINER_PIC_CAMPER                29
#define TRAINER_PIC_PICNICKER             30
#define TRAINER_PIC_BUG_MANIAC            31
#define TRAINER_PIC_POKEMON_BREEDER_M     32
#define TRAINER_PIC_PSYCHIC_M             33
#define TRAINER_PIC_PSYCHIC_F             34
#define TRAINER_PIC_GENTLEMAN             35
#define TRAINER_PIC_ELITE_FOUR_SIDNEY     36
#define TRAINER_PIC_ELITE_FOUR_PHOEBE     37
#define TRAINER_PIC_ELITE_FOUR_GLACIA     38
#define TRAINER_PIC_ELITE_FOUR_DRAKE      39
#define TRAINER_PIC_LEADER_ROXANNE        40
#define TRAINER_PIC_LEADER_BRAWLY         41
#define TRAINER_PIC_LEADER_WATTSON        42
#define TRAINER_PIC_LEADER_FLANNERY       43
#define TRAINER_PIC_LEADER_NORMAN         44
#define TRAINER_PIC_LEADER_WINONA         45
#define TRAINER_PIC_LEADER_TATE_AND_LIZA  46
#define TRAINER_PIC_LEADER_JUAN           47
#define TRAINER_PIC_SCHOOL_KID_M          48
#define TRAINER_PIC_SCHOOL_KID_F          49
#define TRAINER_PIC_SR_AND_JR             50
#define TRAINER_PIC_POKEFAN_M             51
#define TRAINER_PIC_POKEFAN_F             52
#define TRAINER_PIC_YOUNGSTER             53
#define TRAINER_PIC_CHAMPION_WALLACE      54
#define TRAINER_PIC_FISHERMAN             55
#define TRAINER_PIC_CYCLING_TRIATHLETE_M  56
#define TRAINER_PIC_CYCLING_TRIATHLETE_F  57
#define TRAINER_PIC_RUNNING_TRIATHLETE_M  58
#define TRAINER_PIC_RUNNING_TRIATHLETE_F  59
#define TRAINER_PIC_SWIMMING_TRIATHLETE_M 60
#define TRAINER_PIC_SWIMMING_TRIATHLETE_F 61
#define TRAINER_PIC_DRAGON_TAMER          62
#define TRAINER_PIC_NINJA_BOY             63
#define TRAINER_PIC_BATTLE_GIRL           64
#define TRAINER_PIC_PARASOL_LADY          65
#define TRAINER_PIC_SWIMMER_F             66
#define TRAINER_PIC_TWINS                 67
#define TRAINER_PIC_SAILOR                68
#define TRAINER_PIC_MAGMA_ADMIN           69
#define TRAINER_PIC_WALLY                 70
#define TRAINER_PIC_BRENDAN               71
#define TRAINER_PIC_MAY                   72
#define TRAINER_PIC_BUG_CATCHER           73
#define TRAINER_PIC_POKEMON_RANGER_M      74
#define TRAINER_PIC_POKEMON_RANGER_F      75
#define TRAINER_PIC_MAGMA_LEADER_MAXIE    76
#define TRAINER_PIC_LASS                  77
#define TRAINER_PIC_YOUNG_COUPLE          78
#define TRAINER_PIC_OLD_COUPLE            79
#define TRAINER_PIC_SIS_AND_BRO           80
#define TRAINER_PIC_STEVEN                81
#define TRAINER_PIC_SALON_MAIDEN_ANABEL   82
#define TRAINER_PIC_DOME_ACE_TUCKER       83
#define TRAINER_PIC_PALACE_MAVEN_SPENSER  84
#define TRAINER_PIC_ARENA_TYCOON_GRETA    85
#define TRAINER_PIC_FACTORY_HEAD_NOLAND   86
#define TRAINER_PIC_PIKE_QUEEN_LUCY       87
#define TRAINER_PIC_PYRAMID_KING_BRANDON  88
#define TRAINER_PIC_RED                   89
#define TRAINER_PIC_LEAF                  90
#define TRAINER_PIC_RS_BRENDAN            91
#define TRAINER_PIC_RS_MAY                92
#define TRAINER_PIC_COUNT                 93

// #define TRAINER_PIC_AQUA_LEADER_ARCHIE      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_AQUA_GRUNT_M            TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_AQUA_GRUNT_F            TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_AROMA_LADY           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_RUIN_MANIAC          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_INTERVIEWER             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_TUBER_F              TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_TUBER_M              TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_COOLTRAINER_M        TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_COOLTRAINER_F        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_HEX_MANIAC             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_LADY                TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BEAUTY              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RICH_BOY               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_POKEMANIAC          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_SWIMMER_M           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BLACK_BELT          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_GUITARIST              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_KINDLER                TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_CAMPER              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BUG_MANIAC             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_PSYCHIC_M           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_PSYCHIC_F           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_GENTLEMAN           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_ELITE_FOUR_SIDNEY      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_ELITE_FOUR_PHOEBE      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_ROXANNE         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_BRAWLY          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_TATE_AND_LIZA   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SCHOOL_KID_M           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SCHOOL_KID_F           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SR_AND_JR              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_POKEFAN_M              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_POKEFAN_F              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_EXPERT_M               TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_EXPERT_F               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_YOUNGSTER           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CHAMPION_STEVEN        TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_FISHERMAN           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_CYCLING_TRIATHLETE_M   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_CYCLING_TRIATHLETE_F   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RUNNING_TRIATHLETE_M   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RUNNING_TRIATHLETE_F   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SWIMMING_TRIATHLETE_M  TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SWIMMING_TRIATHLETE_F  TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_DRAGON_TAMER           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BIRD_KEEPER         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_NINJA_BOY              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BATTLE_GIRL            TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_PARASOL_LADY           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_SWIMMER_F           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_PICNICKER           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_TWINS               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_SAILOR              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_COLLECTOR              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_WALLY                  TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BRENDAN_1           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_MAY_1               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_POKEMON_BREEDER_M   TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_POKEMON_BREEDER_F   TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_POKEMON_RANGER_M    TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_POKEMON_RANGER_F    TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_MAGMA_LEADER_MAXIE     TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_MAGMA_GRUNT_M          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_MAGMA_GRUNT_F          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_LASS                TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BUG_CATCHER         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RS_HIKER               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_YOUNG_COUPLE        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_OLD_COUPLE             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_SIS_AND_BRO         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_AQUA_ADMIN_M           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_AQUA_ADMIN_F           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_MAGMA_ADMIN_M          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_MAGMA_ADMIN_F          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_WATTSON         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_FLANNERY        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_NORMAN          TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEADER_WINONA          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_WALLACE         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_ELITE_FOUR_GLACIA      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_ELITE_FOUR_DRAKE       TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_YOUNGSTER              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BUG_CATCHER            TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LASS                   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SAILOR                 TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_CAMPER                 TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_PICNICKER              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_POKEMANIAC             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_SUPER_NERD             TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_HIKER                  TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_BIKER                  TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_BURGLAR                TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ENGINEER               TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_FISHERMAN              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SWIMMER_M              TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CUE_BALL               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_GAMER                  TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BEAUTY                 TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SWIMMER_F              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_PSYCHIC_M             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ROCKER                TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_JUGGLER               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_TAMER                 TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BIRD_KEEPER           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_BLACK_BELT            TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RIVAL_EARLY           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_SCIENTIST             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_GIOVANNI       TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ROCKET_GRUNT_M        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_COOLTRAINER_M         TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_COOLTRAINER_F         TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ELITE_FOUR_LORELEI    TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ELITE_FOUR_BRUNO      TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ELITE_FOUR_AGATHA     TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ELITE_FOUR_LANCE      TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_BROCK          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_MISTY          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_LT_SURGE       TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_ERIKA          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_KOGA           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_BLAINE         TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_LEADER_SABRINA        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_GENTLEMAN             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RIVAL_LATE            TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CHAMPION_RIVAL        TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CHANNELER             TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_TWINS                 TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_COOL_COUPLE           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_YOUNG_COUPLE          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CRUSH_KIN             TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_SIS_AND_BRO           TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_PROFESSOR_OAK         TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_BRENDAN_2          TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_RS_MAY_2              TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RED                   TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LEAF                  TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_ROCKET_GRUNT_F        TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_PSYCHIC_F             TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_CRUSH_GIRL            TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_TUBER_F               TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_POKEMON_BREEDER       TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_POKEMON_RANGER_M      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_POKEMON_RANGER_F      TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_AROMA_LADY            TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_RUIN_MANIAC           TRAINER_PIC_BUG_MANIAC
// #define TRAINER_PIC_LADY                  TRAINER_PIC_BUG_MANIAC
#define TRAINER_PIC_PAINTER               TRAINER_PIC_BUG_MANIAC

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_BRENDAN                0
#define TRAINER_BACK_PIC_MAY                    1
#define TRAINER_BACK_PIC_RED                    2
#define TRAINER_BACK_PIC_LEAF                   3
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN  4
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY      5
#define TRAINER_BACK_PIC_WALLY                  6
#define TRAINER_BACK_PIC_STEVEN                 7
#define TRAINER_BACK_PIC_OLD_MAN                TRAINER_BACK_PIC_RED // TODO: 8

#define FACILITY_CLASS_HIKER                 0x0
#define FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define FACILITY_CLASS_PKMN_BREEDER_F        0x2
#define FACILITY_CLASS_COOLTRAINER_M         0x3
#define FACILITY_CLASS_BIRD_KEEPER           0x4
#define FACILITY_CLASS_COLLECTOR             0x5
#define FACILITY_CLASS_AQUA_GRUNT_F          0x6
#define FACILITY_CLASS_SWIMMER_M             0x7
#define FACILITY_CLASS_MAGMA_GRUNT_M         0x8
#define FACILITY_CLASS_EXPERT_M              0x9
#define FACILITY_CLASS_BLACK_BELT            0xa
#define FACILITY_CLASS_AQUA_LEADER_ARCHIE    0xb
#define FACILITY_CLASS_HEX_MANIAC            0xc
#define FACILITY_CLASS_AROMA_LADY            0xd
#define FACILITY_CLASS_RUIN_MANIAC           0xe
#define FACILITY_CLASS_INTERVIEWER           0xf
#define FACILITY_CLASS_TUBER_F               0x10
#define FACILITY_CLASS_TUBER_M               0x11
#define FACILITY_CLASS_COOLTRAINER_F         0x12
#define FACILITY_CLASS_LADY                  0x13
#define FACILITY_CLASS_BEAUTY                0x14
#define FACILITY_CLASS_RICH_BOY              0x15
#define FACILITY_CLASS_EXPERT_F              0x16
#define FACILITY_CLASS_POKEMANIAC            0x17
#define FACILITY_CLASS_MAGMA_GRUNT_F         0x18
#define FACILITY_CLASS_GUITARIST             0x19
#define FACILITY_CLASS_KINDLER               0x1a
#define FACILITY_CLASS_CAMPER                0x1b
#define FACILITY_CLASS_PICNICKER             0x1c
#define FACILITY_CLASS_BUG_MANIAC            0x1d
#define FACILITY_CLASS_PSYCHIC_M             0x1e
#define FACILITY_CLASS_PSYCHIC_F             0x1f
#define FACILITY_CLASS_GENTLEMAN             0x20
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY     0x21
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE     0x22
#define FACILITY_CLASS_LEADER_ROXANNE        0x23
#define FACILITY_CLASS_LEADER_BRAWLY         0x24
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA  0x25
#define FACILITY_CLASS_SCHOOL_KID_M          0x26
#define FACILITY_CLASS_SCHOOL_KID_F          0x27
#define FACILITY_CLASS_SR_AND_JR             0x28
#define FACILITY_CLASS_POKEFAN_M             0x29
#define FACILITY_CLASS_POKEFAN_F             0x2a
#define FACILITY_CLASS_YOUNGSTER             0x2b
#define FACILITY_CLASS_CHAMPION_WALLACE      0x2c
#define FACILITY_CLASS_FISHERMAN             0x2d
#define FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x2e
#define FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x2f
#define FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x30
#define FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x31
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x32
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x33
#define FACILITY_CLASS_DRAGON_TAMER          0x34
#define FACILITY_CLASS_NINJA_BOY             0x35
#define FACILITY_CLASS_BATTLE_GIRL           0x36
#define FACILITY_CLASS_PARASOL_LADY          0x37
#define FACILITY_CLASS_SWIMMER_F             0x38
#define FACILITY_CLASS_TWINS                 0x39
#define FACILITY_CLASS_SAILOR                0x3a
#define FACILITY_CLASS_WALLY                 0x3b
#define FACILITY_CLASS_BRENDAN               0x3c
#define FACILITY_CLASS_BRENDAN_2             0x3d
#define FACILITY_CLASS_BRENDAN_3             0x3e
#define FACILITY_CLASS_MAY                   0x3f
#define FACILITY_CLASS_MAY_2                 0x40
#define FACILITY_CLASS_MAY_3                 0x41
#define FACILITY_CLASS_PKMN_BREEDER_M        0x42
#define FACILITY_CLASS_BUG_CATCHER           0x43
#define FACILITY_CLASS_PKMN_RANGER_M         0x44
#define FACILITY_CLASS_PKMN_RANGER_F         0x45
#define FACILITY_CLASS_MAGMA_LEADER_MAXIE    0x46
#define FACILITY_CLASS_LASS                  0x47
#define FACILITY_CLASS_YOUNG_COUPLE          0x48
#define FACILITY_CLASS_OLD_COUPLE            0x49
#define FACILITY_CLASS_SIS_AND_BRO           0x4a
#define FACILITY_CLASS_STEVEN                0x4b
#define FACILITY_CLASS_SALON_MAIDEN_ANABEL   0x4c
#define FACILITY_CLASS_DOME_ACE_TUCKER       0x4d
#define FACILITY_CLASS_RED                   0x4e
#define FACILITY_CLASS_LEAF                  0x4f
#define FACILITY_CLASS_RS_BRENDAN            0x50
#define FACILITY_CLASS_RS_MAY                0x51

#define FACILITY_CLASSES_COUNT               0x52

#define RS_FACILITY_CLASS_AQUA_LEADER_ARCHIE    0x0
#define RS_FACILITY_CLASS_AQUA_GRUNT_M          0x1
#define RS_FACILITY_CLASS_AQUA_GRUNT_F          0x2
#define RS_FACILITY_CLASS_AROMA_LADY            0x3
#define RS_FACILITY_CLASS_RUIN_MANIAC           0x4
#define RS_FACILITY_CLASS_INTERVIEWER           0x5
#define RS_FACILITY_CLASS_TUBER_F               0x6
#define RS_FACILITY_CLASS_TUBER_M               0x7
#define RS_FACILITY_CLASS_COOLTRAINER_M         0x8
#define RS_FACILITY_CLASS_COOLTRAINER_F         0x9
#define RS_FACILITY_CLASS_HEX_MANIAC            0xA
#define RS_FACILITY_CLASS_LADY                  0xB
#define RS_FACILITY_CLASS_BEAUTY                0xC
#define RS_FACILITY_CLASS_RICH_BOY              0xD
#define RS_FACILITY_CLASS_POKEMANIAC            0xE
#define RS_FACILITY_CLASS_SWIMMER_M             0xF
#define RS_FACILITY_CLASS_BLACK_BELT            0x10
#define RS_FACILITY_CLASS_GUITARIST             0x11
#define RS_FACILITY_CLASS_KINDLER               0x12
#define RS_FACILITY_CLASS_CAMPER                0x13
#define RS_FACILITY_CLASS_BUG_MANIAC            0x14
#define RS_FACILITY_CLASS_PSYCHIC_M             0x15
#define RS_FACILITY_CLASS_PSYCHIC_F             0x16
#define RS_FACILITY_CLASS_GENTLEMAN             0x17
#define RS_FACILITY_CLASS_ELITE_FOUR_M          0x18
#define RS_FACILITY_CLASS_ELITE_FOUR_F          0x19
#define RS_FACILITY_CLASS_LEADER_F              0x1A
#define RS_FACILITY_CLASS_LEADER_M              0x1B
#define RS_FACILITY_CLASS_LEADER_MF             0x1C
#define RS_FACILITY_CLASS_SCHOOL_KID_M          0x1D
#define RS_FACILITY_CLASS_SCHOOL_KID_F          0x1E
#define RS_FACILITY_CLASS_SR_AND_JR             0x1F
#define RS_FACILITY_CLASS_POKEFAN_M             0x20
#define RS_FACILITY_CLASS_POKEFAN_F             0x21
#define RS_FACILITY_CLASS_EXPERT_M              0x22
#define RS_FACILITY_CLASS_EXPERT_F              0x23
#define RS_FACILITY_CLASS_YOUNGSTER             0x24
#define RS_FACILITY_CLASS_CHAMPION              0x25
#define RS_FACILITY_CLASS_FISHERMAN             0x26
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_M  0x27
#define RS_FACILITY_CLASS_CYCLING_TRIATHLETE_F  0x28
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_M  0x29
#define RS_FACILITY_CLASS_RUNNING_TRIATHLETE_F  0x2A
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_M 0x2B
#define RS_FACILITY_CLASS_SWIMMING_TRIATHLETE_F 0x2C
#define RS_FACILITY_CLASS_DRAGON_TAMER          0x2D
#define RS_FACILITY_CLASS_BIRD_KEEPER           0x2E
#define RS_FACILITY_CLASS_NINJA_BOY             0x2F
#define RS_FACILITY_CLASS_BATTLE_GIRL           0x30
#define RS_FACILITY_CLASS_PARASOL_LADY          0x31
#define RS_FACILITY_CLASS_SWIMMER_F             0x32
#define RS_FACILITY_CLASS_PICNICKER             0x33
#define RS_FACILITY_CLASS_TWINS                 0x34
#define RS_FACILITY_CLASS_SAILOR                0x35
#define RS_FACILITY_CLASS_BOARDER_1             0x36
#define RS_FACILITY_CLASS_BOARDER_2             0x37
#define RS_FACILITY_CLASS_COLLECTOR             0x38
#define RS_FACILITY_CLASS_WALLY                 0x39
#define RS_FACILITY_CLASS_BRENDAN_1             0x3A
#define RS_FACILITY_CLASS_BRENDAN_2             0x3B
#define RS_FACILITY_CLASS_BRENDAN_3             0x3C
#define RS_FACILITY_CLASS_MAY_1                 0x3D
#define RS_FACILITY_CLASS_MAY_2                 0x3E
#define RS_FACILITY_CLASS_MAY_3                 0x3F
#define RS_FACILITY_CLASS_PKMN_BREEDER_M        0x40
#define RS_FACILITY_CLASS_PKMN_BREEDER_F        0x41
#define RS_FACILITY_CLASS_PKMN_RANGER_M         0x42
#define RS_FACILITY_CLASS_PKMN_RANGER_F         0x43
#define RS_FACILITY_CLASS_MAGMA_LEADER          0x44
#define RS_FACILITY_CLASS_MAGMA_GRUNT_M         0x45
#define RS_FACILITY_CLASS_MAGMA_GRUNT_F         0x46
#define RS_FACILITY_CLASS_LASS                  0x47
#define RS_FACILITY_CLASS_BUG_CATCHER           0x48
#define RS_FACILITY_CLASS_HIKER                 0x49
#define RS_FACILITY_CLASS_YOUNG_COUPLE          0x4A
#define RS_FACILITY_CLASS_OLD_COUPLE            0x4B
#define RS_FACILITY_CLASS_SIS_AND_BRO           0x4C

#define RS_FACILITY_CLASSES_COUNT               0x4D

enum TrainerClassID
{
    TRAINER_CLASS_PKMN_TRAINER_1, // Unused
    TRAINER_CLASS_PKMN_TRAINER_2, // Unused
    TRAINER_CLASS_HIKER,
    TRAINER_CLASS_TEAM_AQUA,
    TRAINER_CLASS_PKMN_BREEDER,
    TRAINER_CLASS_COOLTRAINER,
    TRAINER_CLASS_BIRD_KEEPER,
    TRAINER_CLASS_COLLECTOR,
    TRAINER_CLASS_SWIMMER_M,
    TRAINER_CLASS_TEAM_MAGMA,
    TRAINER_CLASS_EXPERT,
    TRAINER_CLASS_AQUA_ADMIN,
    TRAINER_CLASS_BLACK_BELT,
    TRAINER_CLASS_AQUA_LEADER,
    TRAINER_CLASS_HEX_MANIAC,
    TRAINER_CLASS_AROMA_LADY,
    TRAINER_CLASS_RUIN_MANIAC,
    TRAINER_CLASS_INTERVIEWER,
    TRAINER_CLASS_TUBER_F,
    TRAINER_CLASS_TUBER_M,
    TRAINER_CLASS_LADY,
    TRAINER_CLASS_BEAUTY,
    TRAINER_CLASS_RICH_BOY,
    TRAINER_CLASS_POKEMANIAC,
    TRAINER_CLASS_GUITARIST,
    TRAINER_CLASS_KINDLER,
    TRAINER_CLASS_CAMPER,
    TRAINER_CLASS_PICNICKER,
    TRAINER_CLASS_BUG_MANIAC,
    TRAINER_CLASS_PSYCHIC,
    TRAINER_CLASS_GENTLEMAN,
    TRAINER_CLASS_ELITE_FOUR,
    TRAINER_CLASS_LEADER,
    TRAINER_CLASS_SCHOOL_KID,
    TRAINER_CLASS_SR_AND_JR,
    TRAINER_CLASS_WINSTRATE,
    TRAINER_CLASS_POKEFAN,
    TRAINER_CLASS_YOUNGSTER,
    TRAINER_CLASS_CHAMPION,
    TRAINER_CLASS_FISHERMAN,
    TRAINER_CLASS_TRIATHLETE,
    TRAINER_CLASS_DRAGON_TAMER,
    TRAINER_CLASS_NINJA_BOY,
    TRAINER_CLASS_BATTLE_GIRL,
    TRAINER_CLASS_PARASOL_LADY,
    TRAINER_CLASS_SWIMMER_F,
    TRAINER_CLASS_TWINS,
    TRAINER_CLASS_SAILOR,
    TRAINER_CLASS_COOLTRAINER_2, // Used for only one trainer.
    TRAINER_CLASS_MAGMA_ADMIN,
    TRAINER_CLASS_RIVAL,
    TRAINER_CLASS_BUG_CATCHER,
    TRAINER_CLASS_PKMN_RANGER,
    TRAINER_CLASS_MAGMA_LEADER,
    TRAINER_CLASS_LASS,
    TRAINER_CLASS_YOUNG_COUPLE,
    TRAINER_CLASS_OLD_COUPLE,
    TRAINER_CLASS_SIS_AND_BRO,
    TRAINER_CLASS_SALON_MAIDEN,
    TRAINER_CLASS_DOME_ACE,
    TRAINER_CLASS_PALACE_MAVEN,
    TRAINER_CLASS_ARENA_TYCOON,
    TRAINER_CLASS_FACTORY_HEAD,
    TRAINER_CLASS_PIKE_QUEEN,
    TRAINER_CLASS_PYRAMID_KING,
    TRAINER_CLASS_RS_PROTAG,
    TRAINER_CLASS_COUNT,
};

#define TRAINER_CLASS_SUPER_NERD  TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_BIKER       TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_BURGLAR     TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_ENGINEER    TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_CUE_BALL    TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_GAMER       TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_ROCKER      TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_JUGGLER     TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_TAMER       TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_RIVAL_EARLY TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_SCIENTIST   TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_BOSS        TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_TEAM_ROCKET TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_RIVAL_LATE  TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_CHANNELER   TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_COOL_COUPLE TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_CRUSH_KIN   TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_PKMN_PROF   TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_PLAYER      TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_CRUSH_GIRL  TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_TUBER       TRAINER_CLASS_BUG_CATCHER
#define TRAINER_CLASS_PAINTER     TRAINER_CLASS_BUG_CATCHER

#define FACILITY_CLASS_RS_AROMA_LADY            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_RUIN_MANIAC           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_TUBER_F               FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_TUBER_M               FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_COOLTRAINER_M         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_COOLTRAINER_F         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_LADY                  FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_BEAUTY                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_POKEMANIAC            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_SWIMMER_M             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_BLACK_BELT            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_CAMPER                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PSYCHIC_M             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PSYCHIC_F             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_GENTLEMAN             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_YOUNGSTER             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_FISHERMAN             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_BIRD_KEEPER           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_SWIMMER_F             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PICNICKER             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_SAILOR                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PKMN_BREEDER_M        FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PKMN_BREEDER_F        FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PKMN_RANGER_M         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_PKMN_RANGER_F         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_LASS                  FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_BUG_CATCHER           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_HIKER                 FACILITY_CLASS_HIKER
#define FACILITY_CLASS_SUPER_NERD               FACILITY_CLASS_HIKER
#define FACILITY_CLASS_BIKER                    FACILITY_CLASS_HIKER
#define FACILITY_CLASS_BURGLAR                  FACILITY_CLASS_HIKER
#define FACILITY_CLASS_ENGINEER                 FACILITY_CLASS_HIKER
#define FACILITY_CLASS_CUE_BALL                 FACILITY_CLASS_HIKER
#define FACILITY_CLASS_GAMER                    FACILITY_CLASS_HIKER
#define FACILITY_CLASS_ROCKER                   FACILITY_CLASS_HIKER
#define FACILITY_CLASS_JUGGLER                  FACILITY_CLASS_HIKER
#define FACILITY_CLASS_TAMER                    FACILITY_CLASS_HIKER
#define FACILITY_CLASS_SCIENTIST                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_CHANNELER                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_CRUSH_GIRL               FACILITY_CLASS_HIKER
#define FACILITY_CLASS_TUBER                    FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_BREEDER             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PAINTER                  FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_TWINS                 FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_YOUNG_COUPLE          FACILITY_CLASS_HIKER
#define FACILITY_CLASS_RS_SIS_AND_BRO           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_COOL_COUPLE              FACILITY_CLASS_HIKER
#define FACILITY_CLASS_CRUSH_KIN                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_MAGMA_ADMIN_F            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_LEADER_FLANNERY          FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_MAY         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_2   FACILITY_CLASS_HIKER
#define FACILITY_CLASS_AQUA_ADMIN_F             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN     FACILITY_CLASS_HIKER
#define FACILITY_CLASS_CHAMPION_STEVEN          FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_MAY_2       FACILITY_CLASS_HIKER
#define FACILITY_CLASS_LEADER_WATTSON           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_LEADER_WALLACE           FACILITY_CLASS_HIKER
#define FACILITY_CLASS_LEADER_NORMAN            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_ELITE_FOUR_DRAKE         FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_WALLY       FACILITY_CLASS_HIKER
#define FACILITY_CLASS_MAGMA_ADMIN_M            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_BOARDER_M                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_LEADER_WINONA            FACILITY_CLASS_HIKER
#define FACILITY_CLASS_AQUA_ADMIN_M             FACILITY_CLASS_HIKER
#define FACILITY_CLASS_BOARDER_F                FACILITY_CLASS_HIKER
#define FACILITY_CLASS_ELITE_FOUR_GLACIA        FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_3   FACILITY_CLASS_HIKER
#define FACILITY_CLASS_PKMN_TRAINER_MAY_3       FACILITY_CLASS_HIKER

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define F_TRAINER_FEMALE (1 << 7)

// Trainer party defines
#define TRAINER_MON_MALE          1
#define TRAINER_MON_FEMALE        2
#define TRAINER_MON_RANDOM_GENDER 3

#endif  // GUARD_TRAINERS_H
