#ifndef GUARD_CONSTANTS_TRAINER_SLIDE_H
#define GUARD_CONSTANTS_TRAINER_SLIDE_H

enum ComparisonOperators
{
    LESS_THAN,
    EQUAL,
    GREATER_THAN,
    LESS_THAN_OR_EQUAL,
    GREATER_THAN_OR_EQUAL,
    NOT_EQUAL,
};

enum TrainerSlideType
{
    TRAINER_SLIDE_NONE,
    TRAINER_SLIDE_BEFORE_FIRST_TURN,
    TRAINER_SLIDE_PLAYER_LANDS_FIRST_CRITICAL_HIT,
    TRAINER_SLIDE_ENEMY_LANDS_FIRST_CRITICAL_HIT,
    TRAINER_SLIDE_PLAYER_LANDS_FIRST_SUPER_EFFECTIVE_HIT,
    TRAINER_SLIDE_PLAYER_LANDS_FIRST_STAB_MOVE,
    TRAINER_SLIDE_PLAYER_LANDS_FIRST_DOWN,
    TRAINER_SLIDE_ENEMY_MON_UNAFFECTED,
    TRAINER_SLIDE_ENEMY_LAST_SWITCHIN,
    TRAINER_SLIDE_ENEMY_LAST_HALF_HP,
    TRAINER_SLIDE_ENEMY_LAST_LOW_HP,
    TRAINER_SLIDE_ENEMY_MEGA_EVOLUTION,
    TRAINER_SLIDE_ENEMY_Z_MOVE,
    TRAINER_SLIDE_ENEMY_DYNAMAX,
    TRAINER_SLIDE_ENEMY_TERA,
    TRAINER_SLIDE_ENEMY_LANDS_FIRST_SUPER_EFFECTIVE_HIT,
    TRAINER_SLIDE_ENEMY_LANDS_FIRST_STAB_MOVE,
    TRAINER_SLIDE_ENEMY_LANDS_FIRST_DOWN,
    TRAINER_SLIDE_PLAYER_MON_UNAFFECTED,
    TRAINER_SLIDE_PLAYER_LAST_SWITCHIN,
    TRAINER_SLIDE_PLAYER_LAST_HALF_HP,
    TRAINER_SLIDE_PLAYER_LAST_LOW_HP,
    TRAINER_SLIDE_PLAYER_MEGA_EVOLUTION,
    TRAINER_SLIDE_PLAYER_Z_MOVE,
    TRAINER_SLIDE_PLAYER_DYNAMAX,
    TRAINER_SLIDE_PLAYER_TERA,
    TRAINER_SLIDE_PLAYER_USES_MON_AND_MOVE,
    TRAINER_SLIDE_ENEMY_USES_MON_AND_MOVE,
    TRAINER_SLIDE_PLAYER_SWITCHES_CERTAIN_MON,
    TRAINER_SLIDE_ENEMY_SWITCHES_CERTAIN_MON,
    TRAINER_SLIDE_PLAYER_CERTAIN_MON_FORM_CHANGE,
    TRAINER_SLIDE_ENEMY_CERTAIN_MON_FORM_CHANGE,
    TRAINER_SLIDE_COUNT,
};

#define TRAINER_SLIDES_PER_ARRAY 8
#define TRAINER_SLIDE_ARRAY_SIZE ((TRAINER_SLIDE_COUNT + TRAINER_SLIDES_PER_ARRAY - 1) / TRAINER_SLIDES_PER_ARRAY)

enum TrainerSlideTargets
{
    TRAINER_SLIDE_TARGET_NONE,
    TRAINER_SLIDE_TARGET_TRAINER_A,
    TRAINER_SLIDE_TARGET_TRAINER_B,
    TRAINER_SLIDE_TARGET_TRAINER_PARTNER,
};

#endif // GUARD_CONSTANTS_TRAINER_SLIDE_H
