gText_Birch_Welcome::
	.string "Welcome to your computer science \p"
	.string "studies at DHBW Cooperative\p"
	.string "State University.\p"
	.string "My name is PROFESSOR FARMER\n"
	.string "and I'm your Course Director.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "To progress, you must find various ”\p"
	.string "flags. These will test your knowledge \n"
	.string "and thinking skills. \p"
	.string "$"

gText_Birch_MainSpeech::
	.string "To pass a semester, you must enter \n"
	.string "the flag into this terminal.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So, what about you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to an\n"
	.string "apartment in JUNGBUSCH.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Computer Science where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "$"
