gText_Birch_Welcome::
	.string "My name is BIRCH.\p"
	.string "But everyone calls me DADDY.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Welcome to the world of Improved Emerald.\n"
	.string "The goal is to be tougher than RR\l"
	.string "and RnB.\p"
	.string "Never heard? Too bad. Good luck!\p"
	.string "Don't forget, women have tougher\n"
	.string "battles they need to fight.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "I get it now!\p"
	.string "You like pain!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Take courage, and leap into the\n"
	.string "world of hell...\l"
	.string "- I mean, Improved Emerald...\p"
	.string "Oops. My mistake.\p"
	.string "Hurry on over to Route 101.\p"
	.string "$"
