@ Crystal-accurate phone dialogue for HnS rematch trainers

@ Joey - Youngster, Route 30
MatchCall_HNS_Joey_General::
	.string "How are your POKéMON doing?\p"
	.string "My {STR_VAR_3}'s raring to go,\n"
	.string "just like always.\p"
	.string "It's the only one I have.\n"
	.string "I'm going to become a great\l"
	.string "trainer with it!$"

MatchCall_HNS_Joey_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Wade - Bug Catcher, Route 31
MatchCall_HNS_Wade_General::
	.string "How are your POKéMON doing?\p"
	.string "My POKéMON have too much\n"
	.string "energy to burn.\p"
	.string "It gets to be a problem.\p"
	.string "Of all my POKéMON,\n"
	.string "{STR_VAR_3} is the hardest\l"
	.string "to handle.\p"
	.string "Working with it is\n"
	.string "exhausting.$"

MatchCall_HNS_Wade_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Ralph - Fisher, Route 32
MatchCall_HNS_Ralph_General::
	.string "Are you taking good care of\n"
	.string "your POKéMON?\p"
	.string "You have to be good to\n"
	.string "your partners!$"

MatchCall_HNS_Ralph_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Liz - Picnicker, Route 32
MatchCall_HNS_Liz_General::
	.string "I had some time, so I\n"
	.string "called you.\p"
	.string "So anyway, how are your\n"
	.string "POKéMON?\p"
	.string "Me, I take my {STR_VAR_3}\n"
	.string "to the POKéMON CENTER in\l"
	.string "VIOLET every day,\p"
	.string "so it's doing just\n"
	.string "fantastic!\p"
	.string "I'm friends with the\n"
	.string "receptionist!$"

MatchCall_HNS_Liz_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Anthony - Hiker, Route 33
MatchCall_HNS_Anthony_General::
	.string "Are your POKéMON as feisty\n"
	.string "as ever?\p"
	.string "My {STR_VAR_3} and me--we\n"
	.string "have energy to burn.\p"
	.string "We hike up mountains every\n"
	.string "day to work out all our\l"
	.string "energy.$"

MatchCall_HNS_Anthony_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Todd - Camper, Route 34
MatchCall_HNS_Todd_General::
	.string "How do you raise your\n"
	.string "POKéMON?\p"
	.string "I do all sorts of things,\n"
	.string "like leaving them in\l"
	.string "DAY-CARE and\p"
	.string "toughening them up with\n"
	.string "items.$"

MatchCall_HNS_Todd_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Gina - Picnicker, Route 34
MatchCall_HNS_Gina_General::
	.string "Are your POKéMON still\n"
	.string "tough?\p"
	.string "I train every day\n"
	.string "with {STR_VAR_3}.$"

MatchCall_HNS_Gina_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Irwin - Juggler, Route 35
MatchCall_HNS_Irwin_General::
	.string "I saw the most amazing\n"
	.string "battle the other day!\p"
	.string "I wish I could battle\n"
	.string "like that.\p"
	.string "Oh wait, I can! I just\n"
	.string "need someone to battle!$"

MatchCall_HNS_Irwin_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Arnie - Bug Catcher, Route 35
MatchCall_HNS_Arnie_General::
	.string "I bet your POKéMON are a\n"
	.string "lot stronger than before.$"

MatchCall_HNS_Arnie_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Alan - Schoolboy, Route 36
MatchCall_HNS_Alan_General::
	.string "{PLAYER}, are you raising\n"
	.string "your POKéMON properly?\p"
	.string "I read in a book that you\n"
	.string "should raise any POKéMON\l"
	.string "you catch with love and\l"
	.string "care.$"

MatchCall_HNS_Alan_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Dana - Lass, Route 38
MatchCall_HNS_Dana_General::
	.string "My {STR_VAR_3} is so full\n"
	.string "of energy, it's a little\l"
	.string "scary.\p"
	.string "How are your POKéMON\n"
	.string "doing?$"

MatchCall_HNS_Dana_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Chad - Schoolboy, Route 38
MatchCall_HNS_Chad_General::
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "You know PROF. OAK, so of\n"
	.string "course your POKéMON are\l"
	.string "fine!\p"
	.string "My POKéMON are doing well\n"
	.string "too.\p"
	.string "But then, I am trying to\n"
	.string "become a POKéMON\l"
	.string "professor.$"

MatchCall_HNS_Chad_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Derek - Pokefan M, Route 39
MatchCall_HNS_Derek_General::
	.string "You have to hear this!\p"
	.string "My lovable {STR_VAR_3}\n"
	.string "looked at me and grinned!\p"
	.string "It must be because our\n"
	.string "hearts beat together as\l"
	.string "one!$"

MatchCall_HNS_Derek_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Tully - Fisher, Route 42
MatchCall_HNS_Tully_General::
	.string "How's your trip coming\n"
	.string "along?\p"
	.string "I can't complain about\n"
	.string "my fishing!$"

MatchCall_HNS_Tully_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Brent - Pokemaniac, Route 43
MatchCall_HNS_Brent_General::
	.string "Oh yeah, I saw you coming\n"
	.string "out of a POKéMON CENTER\l"
	.string "the other day.\p"
	.string "You heal your POKéMON\n"
	.string "regularly, don't you?\l"
	.string "I'm impressed.\p"
	.string "Heh, my {STR_VAR_3} is\n"
	.string "so tough, it doesn't need\l"
	.string "to go to POKéMON CENTERS\l"
	.string "often. Heheh!$"

MatchCall_HNS_Brent_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Tiffany - Picnicker, Route 43
MatchCall_HNS_Tiffany_General::
	.string "Are your POKéMON doing\n"
	.string "well?\p"
	.string "I hope you take them to a\n"
	.string "POKéMON CENTER every day.\p"
	.string "Don't push them too hard.\p"
	.string "My {STR_VAR_3} is cute and\n"
	.string "lively precisely because I\l"
	.string "take it to a POKéMON\l"
	.string "CENTER every day.$"

MatchCall_HNS_Tiffany_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Vance - Bird Keeper, Route 44
MatchCall_HNS_Vance_General::
	.string "Are you and your POKéMON\n"
	.string "fine?\p"
	.string "My {STR_VAR_3} looks like\n"
	.string "it will get tough enough\p"
	.string "to face and beat the\n"
	.string "legendary bird POKéMON!$"

MatchCall_HNS_Vance_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Wilton - Fisher, Route 44
MatchCall_HNS_Wilton_General::
	.string "Have your POKéMON grown\n"
	.string "any?\p"
	.string "My {STR_VAR_3} has grown\n"
	.string "quite a bit.$"

MatchCall_HNS_Wilton_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Kenji - Blackbelt, Route 45
MatchCall_HNS_Kenji_General::
	.string "{PLAYER}! Beautiful\n"
	.string "weather, hey?$"

MatchCall_HNS_Kenji_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Parry - Hiker, Route 45
MatchCall_HNS_Parry_General::
	.string "Are your POKéMON looking\n"
	.string "good?\p"
	.string "My {STR_VAR_3} and me--\n"
	.string "we're looking mighty\l"
	.string "dandy! Hahahah!$"

MatchCall_HNS_Parry_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Erin - Picnicker, Route 46
MatchCall_HNS_Erin_General::
	.string "Are you raising your\n"
	.string "POKéMON?\p"
	.string "My {STR_VAR_3} is looking\n"
	.string "good!$"

MatchCall_HNS_Erin_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Jack - Schoolboy, National Park
MatchCall_HNS_Jack_General::
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "My {STR_VAR_3} is so\n"
	.string "curious, it's a problem.\p"
	.string "Maybe it's like me…$"

MatchCall_HNS_Jack_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Beverly - Pokefan F, National Park
MatchCall_HNS_Beverly_General::
	.string "Keeping your POKéMON\n"
	.string "happy?\p"
	.string "My {STR_VAR_3} is healthy.\n"
	.string "It eats a lot every day.$"

MatchCall_HNS_Beverly_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Huey - Sailor, Olivine Lighthouse
MatchCall_HNS_Huey_General::
	.string "Yo, {PLAYER}!\p"
	.string "How's it going?$"

MatchCall_HNS_Huey_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Gaven - Cooltrainer M, Route 26
MatchCall_HNS_Gaven_General::
	.string "How are your POKéMON\n"
	.string "doing?\p"
	.string "My {STR_VAR_3}'s doing as\n"
	.string "great as ever.\p"
	.string "Let's keep at it and\n"
	.string "become POKéMON CHAMPS!$"

MatchCall_HNS_Gaven_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Beth - Cooltrainer F, Route 26
MatchCall_HNS_Beth_General::
	.string "Are you the kind of person\n"
	.string "who goes to POKéMON\l"
	.string "CENTERS often?\p"
	.string "I go every day. Watching\n"
	.string "out for the health of your\l"
	.string "POKéMON is a basic part of\l"
	.string "being a POKéMON trainer.$"

MatchCall_HNS_Beth_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Jose - Bird Keeper, Route 27
MatchCall_HNS_Jose_General::
	.string "Are your POKéMON still\n"
	.string "cooking?\p"
	.string "My {STR_VAR_3} has too\n"
	.string "much energy.\p"
	.string "Once it takes off, it\n"
	.string "won't come back for a\l"
	.string "while.$"

MatchCall_HNS_Jose_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"

@ Reena - Cooltrainer F, Route 27
MatchCall_HNS_Reena_General::
	.string "Hey, how are your POKéMON\n"
	.string "doing?\p"
	.string "What? Great? I see…\p"
	.string "What? My POKéMON?\p"
	.string "Of course they're doing\n"
	.string "great! What kind of a\l"
	.string "question is that?$"

MatchCall_HNS_Reena_Battle::
	.string "I was waiting for you.\n"
	.string "Let's battle!$"
