MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hi, I'm the Move Relearner.\n"
	.string "Would you like to learn new moves?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level Up Moves$"

MoveRelearner_Text_EggMoves:
	.string "Egg Moves$"

MoveRelearner_Text_TMmoveMoves:
	.string "TM Moves$"

MoveRelearner_Text_TutormoveMoves:
	.string "Tutor Moves$"

MoveRelearner_Text_SeeYa:
	.string "See ya!$"

MoveRelearner_Text_AnythingElse:
	.string "Is there anything else I may do for you?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Please choose your Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Sorry…\n"
	.string "But an Egg can't learn moves.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Sorry…\p"
	.string "It doesn't appear as if I have any move\n"
	.string "I can teach that Pokémon.$"

MoveRelearner_Text_eggmove:
	.string "egg move$"

MoveRelearner_Text_TMmove:
	.string "TM move$"

MoveRelearner_Text_tutormove:
	.string "tutor move$"

MoveRelearner_Text_levelupmove:
	.string "level up move$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Which {STR_VAR_3} should I teach?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Thank you for using our services.\n"
	.string "Please come again!$"
