gText_Noland_Welcome::
.string "Hey there, challenger!\p"
.string "Welcome to the BATTLE FACTORY!\p"
.string "The name’s NOLAND.\p"
.string "I’m the FACTORY HEAD -- the one who\n"
.string "keeps this place running.\p"
.string "$"

gText_Noland_ExplainFactory::
.string "Here, we do things differently.\p"
.string "No need to bring your own team.\n"
.string "We battle with rental POKéMON!\p"
.string "\n"
.string "$"

gText_Noland_MainSpeech::
.string "In this facility, strategy rules all.\n"
.string "It’s about skill, not strength.\p"
.string "Every POKéMON has its role,\n"
.string "and it's up to you to make 'em shine.\p"
.string "Reading your opponent,\n"
.string "making the right calls... that's the key.\p"
.string "Wanna win? Then adapt, improvise,\n"
.string "and outthink the other guy.\p"
.string "I’ve seen all kinds of tactics,\n"
.string "but there’s always more to learn.\p"
.string "That's why I stick around...\n"
.string "to study and battle the best.\p"
.string "$"

gText_Noland_AndYouAre::
.string "Now then... who am I up against?$"

gText_Noland_BoyOrGirl::
.string "You a boy?\n"
.string "Or a girl?$"

gText_Noland_WhatsYourName::
.string "Okay, hotshot.\n"
.string "What do they call you?$"

gText_Noland_SoItsPlayer::
.string "So it’s {PLAYER}{KUN}, huh?$"

gText_Noland_YourePlayer::
.string "All right!\p"
.string "You're {PLAYER}{KUN}, stepping up to\n"
.string "the BATTLE FACTORY.\l"
.string "I like your guts!\p"
.string "$"

gText_Noland_AreYouReady::
.string "Ready to throw down?\p"
.string "Your tactical trial is about to begin!\p"
.string "Take your pick, plan your plays,\n"
.string "and make every move count!\p"
.string "I’ll be waiting down the line...\n"
.string "Let's see what you've got!\p"
.string "$"
