	.align 2
gText_ConfirmSave::
	.string "Would you like to save the game?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentSaveFile::
	.string "WARNING!\n"
	.string "A different game file was found.\p"
	.string "If you save now, the other file's\n"
	.string "progress will be entirely lost.\p"
	.string "Are you sure you want to save\n"
	.string "and overwrite the last adventure?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
