WonderTrade_Text_WonderTradeIntro:
    .string "Hey there! Would you like to try a new,\n"
    .string "wonderful way to trade pokemon?\p"
    .string "It's called wonder trading! Just trade\n"
    .string "away your pokemon, and receive one in\l"
    .string "return from a stranger!\p"
    .string "Would you like to give it a shot?$"

WonderTrade_Text_WhichPokemonSend:
    .string "Which pokemon would you like to send?$"

WonderTrade_Text_AreYouSure:
    .string "Are you sure you want to send it?$"

WonderTrade_Text_Wonderful:
    .string "Wonderful! Here we go!$"

WonderTrade_Text_Decline:
    .string "No worries! See me again if you want\n"
    .string "to wonder trade!$"

WonderTrade_Text_Complete:
    .string "Congratulations! Enjoy your new partner\n"
    .string "and come see me again to trade more!$"
