#ifndef GUARD_CONFIG_SPECIES_ENABLED_H
#define GUARD_CONFIG_SPECIES_ENABLED_H

// Modifying the latest generation WILL change the saveblock due to Dex flags and will require a new save file.
// Generations of Pokémon are defined by the first member introduced,
// so Pikachu depends on the Gen 1 setting despite Pichu being the lowest member of the evolution tree.
// Eg: If P_GEN_2_POKEMON is set to FALSE, all members of the Sneasel Family will be disabled
// (Sneasel + Hisuian, Weavile and Sneasler).
#define P_GEN_1_POKEMON                  FALSE // Generation 1 Pokémon (RGBY)
#define P_GEN_2_POKEMON                  FALSE // Generation 2 Pokémon (GSC)
#define P_GEN_3_POKEMON                  FALSE // Generation 3 Pokémon (RSE, FRLG)
#define P_GEN_4_POKEMON                  FALSE // Generation 4 Pokémon (DPPt, HGSS)
#define P_GEN_5_POKEMON                  FALSE // Generation 5 Pokémon (BW, B2W2)
#define P_GEN_6_POKEMON                  FALSE // Generation 6 Pokémon (XY, ORAS)
#define P_GEN_7_POKEMON                  FALSE // Generation 7 Pokémon (SM, USUM, LGPE)
#define P_GEN_8_POKEMON                  FALSE // Generation 8 Pokémon (SwSh, BDSP, LA)
#define P_GEN_9_POKEMON                  FALSE // Generation 9 Pokémon (SV)

// Setting this to TRUE will add the new evolutions to the Regional Dex.
#define P_NEW_EVOS_IN_REGIONAL_DEX       TRUE

// Battle gimmick specific Forms.
#define P_MEGA_EVOLUTIONS                TRUE
#define P_PRIMAL_REVERSIONS              TRUE // Groudon and Kyogre only.
#define P_ULTRA_BURST_FORMS              TRUE // Ultra Necrozma only.
#define P_GIGANTAMAX_FORMS               TRUE
#define P_TERA_FORMS                     TRUE

#define P_GEN_9_MEGA_EVOLUTIONS          P_MEGA_EVOLUTIONS // Mega Evolutions introduced in Z-A and its DLC

// Fusion forms
#define P_FUSION_FORMS                   TRUE

// Regional Forms. Includes Regional Form evolutions, like Sirfetch'd.
#define P_REGIONAL_FORMS                 TRUE
#define P_ALOLAN_FORMS                   P_REGIONAL_FORMS
#define P_GALARIAN_FORMS                 P_REGIONAL_FORMS
#define P_HISUIAN_FORMS                  P_REGIONAL_FORMS
#define P_PALDEAN_FORMS                  P_REGIONAL_FORMS

// Big groups of forms that aren't always desired when choosing families.
#define P_PIKACHU_EXTRA_FORMS            TRUE
#define P_COSPLAY_PIKACHU_FORMS          P_PIKACHU_EXTRA_FORMS
#define P_CAP_PIKACHU_FORMS              P_PIKACHU_EXTRA_FORMS

// Cross-generation evolutions. Includes pre-evolutions.
#define P_CROSS_GENERATION_EVOS          TRUE
#define P_GEN_2_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_3_CROSS_EVOS               P_CROSS_GENERATION_EVOS
#define P_GEN_4_CROSS_EVOS               P_CROSS_GENERATION_EVOS
//#define P_GEN_5_CROSS_EVOS             // Gen 5 didn't introduce any cross-gen evos.
#define P_GEN_6_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Just Sylveon.
//#define P_GEN_7_CROSS_EVOS             // Alolan evolutions handled by P_ALOLAN_FORMS.
#define P_GEN_8_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Regional evolutions handled by P_GALARIAN_FORMS and P_HISUIAN_FORMS.
#define P_GEN_9_CROSS_EVOS               P_CROSS_GENERATION_EVOS // Clodsire handled by P_PALDEAN_FORMS.

// To disable specific families, replace P_GEN_x_POKEMON with FALSE.
#define P_FAMILY_BULBASAUR               FALSE
#define P_FAMILY_CHARMANDER              TRUE
#define P_FAMILY_SQUIRTLE                FALSE
#define P_FAMILY_CATERPIE                FALSE
#define P_FAMILY_WEEDLE                  FALSE
#define P_FAMILY_PIDGEY                  FALSE
#define P_FAMILY_RATTATA                 FALSE
#define P_FAMILY_SPEAROW                 FALSE
#define P_FAMILY_EKANS                   FALSE
#define P_FAMILY_PIKACHU                 TRUE
#define P_FAMILY_SANDSHREW               TRUE
#define P_FAMILY_NIDORAN                 FALSE
#define P_FAMILY_CLEFAIRY                TRUE
#define P_FAMILY_VULPIX                  TRUE
#define P_FAMILY_JIGGLYPUFF              FALSE
#define P_FAMILY_ZUBAT                   TRUE
#define P_FAMILY_ODDISH                  TRUE
#define P_FAMILY_PARAS                   FALSE
#define P_FAMILY_VENONAT                 FALSE
#define P_FAMILY_DIGLETT                 FALSE
#define P_FAMILY_MEOWTH                  FALSE
#define P_FAMILY_PSYDUCK                 FALSE
#define P_FAMILY_MANKEY                  TRUE
#define P_FAMILY_GROWLITHE               FALSE
#define P_FAMILY_POLIWAG                 TRUE
#define P_FAMILY_ABRA                    FALSE
#define P_FAMILY_MACHOP                  FALSE
#define P_FAMILY_BELLSPROUT              FALSE
#define P_FAMILY_TENTACOOL               FALSE
#define P_FAMILY_GEODUDE                 TRUE
#define P_FAMILY_PONYTA                  FALSE
#define P_FAMILY_SLOWPOKE                TRUE
#define P_FAMILY_MAGNEMITE               TRUE
#define P_FAMILY_FARFETCHD               TRUE
#define P_FAMILY_DODUO                   FALSE
#define P_FAMILY_SEEL                    FALSE
#define P_FAMILY_GRIMER                  TRUE
#define P_FAMILY_SHELLDER                TRUE
#define P_FAMILY_GASTLY                  TRUE
#define P_FAMILY_ONIX                    FALSE
#define P_FAMILY_DROWZEE                 FALSE
#define P_FAMILY_KRABBY                  TRUE
#define P_FAMILY_VOLTORB                 TRUE
#define P_FAMILY_EXEGGCUTE               TRUE
#define P_FAMILY_CUBONE                  FALSE
#define P_FAMILY_HITMONS                 FALSE
#define P_FAMILY_LICKITUNG               FALSE
#define P_FAMILY_KOFFING                 TRUE
#define P_FAMILY_RHYHORN                 FALSE
#define P_FAMILY_CHANSEY                 TRUE
#define P_FAMILY_TANGELA                 TRUE
#define P_FAMILY_KANGASKHAN              FALSE
#define P_FAMILY_HORSEA                  TRUE
#define P_FAMILY_GOLDEEN                 FALSE
#define P_FAMILY_STARYU                  TRUE
#define P_FAMILY_MR_MIME                 TRUE
#define P_FAMILY_SCYTHER                 TRUE
#define P_FAMILY_JYNX                    FALSE
#define P_FAMILY_ELECTABUZZ              TRUE
#define P_FAMILY_MAGMAR                  FALSE
#define P_FAMILY_PINSIR                  FALSE
#define P_FAMILY_TAUROS                  TRUE
#define P_FAMILY_MAGIKARP                TRUE
#define P_FAMILY_LAPRAS                  TRUE
#define P_FAMILY_DITTO                   FALSE
#define P_FAMILY_EEVEE                   TRUE
#define P_FAMILY_PORYGON                 TRUE
#define P_FAMILY_OMANYTE                 FALSE
#define P_FAMILY_KABUTO                  TRUE
#define P_FAMILY_AERODACTYL              FALSE
#define P_FAMILY_SNORLAX                 TRUE
#define P_FAMILY_ARTICUNO                TRUE
#define P_FAMILY_ZAPDOS                  TRUE
#define P_FAMILY_MOLTRES                 TRUE
#define P_FAMILY_DRATINI                 TRUE
#define P_FAMILY_MEWTWO                  FALSE
#define P_FAMILY_MEW                     FALSE

#define P_FAMILY_CHIKORITA               FALSE
#define P_FAMILY_CYNDAQUIL               FALSE
#define P_FAMILY_TOTODILE                FALSE
#define P_FAMILY_SENTRET                 TRUE
#define P_FAMILY_HOOTHOOT                FALSE
#define P_FAMILY_LEDYBA                  FALSE
#define P_FAMILY_SPINARAK                FALSE
#define P_FAMILY_CHINCHOU                FALSE
#define P_FAMILY_TOGEPI                  FALSE
#define P_FAMILY_NATU                    FALSE
#define P_FAMILY_MAREEP                  FALSE
#define P_FAMILY_MARILL                  FALSE
#define P_FAMILY_SUDOWOODO               FALSE
#define P_FAMILY_HOPPIP                  TRUE
#define P_FAMILY_AIPOM                   FALSE
#define P_FAMILY_SUNKERN                 TRUE
#define P_FAMILY_YANMA                   TRUE
#define P_FAMILY_WOOPER                  TRUE
#define P_FAMILY_MURKROW                 TRUE
#define P_FAMILY_MISDREAVUS              TRUE
#define P_FAMILY_UNOWN                   FALSE
#define P_FAMILY_WOBBUFFET               FALSE
#define P_FAMILY_GIRAFARIG               FALSE
#define P_FAMILY_PINECO                  TRUE
#define P_FAMILY_DUNSPARCE               FALSE
#define P_FAMILY_GLIGAR                  TRUE
#define P_FAMILY_SNUBBULL                FALSE
#define P_FAMILY_QWILFISH                FALSE
#define P_FAMILY_SHUCKLE                 TRUE
#define P_FAMILY_HERACROSS               TRUE
#define P_FAMILY_SNEASEL                 TRUE
#define P_FAMILY_TEDDIURSA               FALSE
#define P_FAMILY_SLUGMA                  TRUE
#define P_FAMILY_SWINUB                  TRUE
#define P_FAMILY_CORSOLA                 TRUE
#define P_FAMILY_REMORAID                FALSE
#define P_FAMILY_DELIBIRD                FALSE
#define P_FAMILY_MANTINE                 FALSE
#define P_FAMILY_SKARMORY                TRUE
#define P_FAMILY_HOUNDOUR                TRUE
#define P_FAMILY_PHANPY                  TRUE
#define P_FAMILY_STANTLER                FALSE
#define P_FAMILY_SMEARGLE                TRUE
#define P_FAMILY_MILTANK                 TRUE
#define P_FAMILY_RAIKOU                  FALSE
#define P_FAMILY_ENTEI                   FALSE
#define P_FAMILY_SUICUNE                 FALSE
#define P_FAMILY_LARVITAR                TRUE
#define P_FAMILY_LUGIA                   FALSE
#define P_FAMILY_HO_OH                   FALSE
#define P_FAMILY_CELEBI                  FALSE

#define P_FAMILY_TREECKO                 FALSE
#define P_FAMILY_TORCHIC                 FALSE
#define P_FAMILY_MUDKIP                  FALSE
#define P_FAMILY_POOCHYENA               FALSE
#define P_FAMILY_ZIGZAGOON               TRUE
#define P_FAMILY_WURMPLE                 FALSE
#define P_FAMILY_LOTAD                   TRUE
#define P_FAMILY_SEEDOT                  FALSE
#define P_FAMILY_TAILLOW                 FALSE
#define P_FAMILY_WINGULL                 TRUE
#define P_FAMILY_RALTS                   TRUE
#define P_FAMILY_SURSKIT                 FALSE
#define P_FAMILY_SHROOMISH               TRUE
#define P_FAMILY_SLAKOTH                 FALSE
#define P_FAMILY_NINCADA                 TRUE
#define P_FAMILY_WHISMUR                 TRUE
#define P_FAMILY_MAKUHITA                TRUE
#define P_FAMILY_NOSEPASS                TRUE
#define P_FAMILY_SKITTY                  FALSE
#define P_FAMILY_SABLEYE                 TRUE
#define P_FAMILY_MAWILE                  FALSE
#define P_FAMILY_ARON                    FALSE
#define P_FAMILY_MEDITITE                FALSE
#define P_FAMILY_ELECTRIKE               TRUE
#define P_FAMILY_PLUSLE                  FALSE
#define P_FAMILY_MINUN                   FALSE
#define P_FAMILY_VOLBEAT_ILLUMISE        FALSE
#define P_FAMILY_ROSELIA                 TRUE
#define P_FAMILY_GULPIN                  FALSE
#define P_FAMILY_CARVANHA                FALSE
#define P_FAMILY_WAILMER                 FALSE
#define P_FAMILY_NUMEL                   FALSE
#define P_FAMILY_TORKOAL                 TRUE
#define P_FAMILY_SPOINK                  FALSE
#define P_FAMILY_SPINDA                  FALSE
#define P_FAMILY_TRAPINCH                FALSE
#define P_FAMILY_CACNEA                  TRUE
#define P_FAMILY_SWABLU                  FALSE
#define P_FAMILY_ZANGOOSE                FALSE
#define P_FAMILY_SEVIPER                 FALSE
#define P_FAMILY_LUNATONE                FALSE
#define P_FAMILY_SOLROCK                 FALSE
#define P_FAMILY_BARBOACH                FALSE
#define P_FAMILY_CORPHISH                TRUE
#define P_FAMILY_BALTOY                  TRUE
#define P_FAMILY_LILEEP                  FALSE
#define P_FAMILY_ANORITH                 FALSE
#define P_FAMILY_FEEBAS                  FALSE
#define P_FAMILY_CASTFORM                TRUE
#define P_FAMILY_KECLEON                 TRUE
#define P_FAMILY_SHUPPET                 TRUE
#define P_FAMILY_DUSKULL                 FALSE
#define P_FAMILY_TROPIUS                 FALSE
#define P_FAMILY_CHIMECHO                FALSE
#define P_FAMILY_ABSOL                   TRUE
#define P_FAMILY_SNORUNT                 TRUE
#define P_FAMILY_SPHEAL                  FALSE
#define P_FAMILY_CLAMPERL                FALSE
#define P_FAMILY_RELICANTH               FALSE
#define P_FAMILY_LUVDISC                 FALSE
#define P_FAMILY_BAGON                   FALSE
#define P_FAMILY_BELDUM                  TRUE
#define P_FAMILY_REGIROCK                FALSE
#define P_FAMILY_REGICE                  FALSE
#define P_FAMILY_REGISTEEL               FALSE
#define P_FAMILY_LATIAS                  FALSE
#define P_FAMILY_LATIOS                  FALSE
#define P_FAMILY_KYOGRE                  FALSE
#define P_FAMILY_GROUDON                 FALSE
#define P_FAMILY_RAYQUAZA                FALSE
#define P_FAMILY_JIRACHI                 FALSE
#define P_FAMILY_DEOXYS                  TRUE

#define P_FAMILY_TURTWIG                 FALSE
#define P_FAMILY_CHIMCHAR                TRUE
#define P_FAMILY_PIPLUP                  FALSE
#define P_FAMILY_STARLY                  FALSE
#define P_FAMILY_BIDOOF                  TRUE
#define P_FAMILY_KRICKETOT               FALSE
#define P_FAMILY_SHINX                   FALSE
#define P_FAMILY_CRANIDOS                FALSE
#define P_FAMILY_SHIELDON                FALSE
#define P_FAMILY_BURMY                   FALSE
#define P_FAMILY_COMBEE                  TRUE
#define P_FAMILY_PACHIRISU               FALSE
#define P_FAMILY_BUIZEL                  TRUE
#define P_FAMILY_CHERUBI                 TRUE
#define P_FAMILY_SHELLOS                 FALSE
#define P_FAMILY_DRIFLOON                FALSE
#define P_FAMILY_BUNEARY                 FALSE
#define P_FAMILY_GLAMEOW                 FALSE
#define P_FAMILY_STUNKY                  TRUE
#define P_FAMILY_BRONZOR                 TRUE
#define P_FAMILY_CHATOT                  FALSE
#define P_FAMILY_SPIRITOMB               TRUE
#define P_FAMILY_GIBLE                   TRUE
#define P_FAMILY_RIOLU                   TRUE
#define P_FAMILY_HIPPOPOTAS              TRUE
#define P_FAMILY_SKORUPI                 TRUE
#define P_FAMILY_CROAGUNK                TRUE
#define P_FAMILY_CARNIVINE               TRUE
#define P_FAMILY_FINNEON                 FALSE
#define P_FAMILY_SNOVER                  TRUE
#define P_FAMILY_ROTOM                   TRUE
#define P_FAMILY_UXIE                    FALSE
#define P_FAMILY_MESPRIT                 FALSE
#define P_FAMILY_AZELF                   FALSE
#define P_FAMILY_DIALGA                  FALSE
#define P_FAMILY_PALKIA                  FALSE
#define P_FAMILY_HEATRAN                 FALSE
#define P_FAMILY_REGIGIGAS               FALSE
#define P_FAMILY_GIRATINA                FALSE
#define P_FAMILY_CRESSELIA               FALSE
#define P_FAMILY_MANAPHY                 FALSE
#define P_FAMILY_DARKRAI                 FALSE
#define P_FAMILY_SHAYMIN                 FALSE
#define P_FAMILY_ARCEUS                  FALSE

#define P_FAMILY_VICTINI                 FALSE
#define P_FAMILY_SNIVY                   FALSE
#define P_FAMILY_TEPIG                   FALSE
#define P_FAMILY_OSHAWOTT                FALSE
#define P_FAMILY_PATRAT                  FALSE
#define P_FAMILY_LILLIPUP                TRUE
#define P_FAMILY_PURRLOIN                FALSE
#define P_FAMILY_PANSAGE                 FALSE
#define P_FAMILY_PANSEAR                 FALSE
#define P_FAMILY_PANPOUR                 FALSE
#define P_FAMILY_MUNNA                   FALSE
#define P_FAMILY_PIDOVE                  FALSE
#define P_FAMILY_BLITZLE                 FALSE
#define P_FAMILY_ROGGENROLA              TRUE
#define P_FAMILY_WOOBAT                  FALSE
#define P_FAMILY_DRILBUR                 TRUE
#define P_FAMILY_AUDINO                  FALSE
#define P_FAMILY_TIMBURR                 TRUE
#define P_FAMILY_TYMPOLE                 TRUE
#define P_FAMILY_THROH                   FALSE
#define P_FAMILY_SAWK                    FALSE
#define P_FAMILY_SEWADDLE                FALSE
#define P_FAMILY_VENIPEDE                FALSE
#define P_FAMILY_COTTONEE                TRUE
#define P_FAMILY_PETILIL                 TRUE
#define P_FAMILY_BASCULIN                FALSE
#define P_FAMILY_SANDILE                 TRUE
#define P_FAMILY_DARUMAKA                FALSE
#define P_FAMILY_MARACTUS                TRUE
#define P_FAMILY_DWEBBLE                 FALSE
#define P_FAMILY_SCRAGGY                 FALSE
#define P_FAMILY_SIGILYPH                TRUE
#define P_FAMILY_YAMASK                  TRUE
#define P_FAMILY_TIRTOUGA                FALSE
#define P_FAMILY_ARCHEN                  FALSE
#define P_FAMILY_TRUBBISH                FALSE
#define P_FAMILY_ZORUA                   TRUE
#define P_FAMILY_MINCCINO                FALSE
#define P_FAMILY_GOTHITA                 TRUE
#define P_FAMILY_SOLOSIS                 TRUE
#define P_FAMILY_DUCKLETT                FALSE
#define P_FAMILY_VANILLITE               TRUE
#define P_FAMILY_DEERLING                FALSE
#define P_FAMILY_EMOLGA                  FALSE
#define P_FAMILY_KARRABLAST              FALSE
#define P_FAMILY_FOONGUS                 TRUE
#define P_FAMILY_FRILLISH                FALSE
#define P_FAMILY_ALOMOMOLA               FALSE
#define P_FAMILY_JOLTIK                  FALSE
#define P_FAMILY_FERROSEED               TRUE
#define P_FAMILY_KLINK                   TRUE
#define P_FAMILY_TYNAMO                  FALSE
#define P_FAMILY_ELGYEM                  TRUE
#define P_FAMILY_LITWICK                 FALSE
#define P_FAMILY_AXEW                    FALSE
#define P_FAMILY_CUBCHOO                 TRUE
#define P_FAMILY_CRYOGONAL               FALSE
#define P_FAMILY_SHELMET                 TRUE
#define P_FAMILY_STUNFISK                FALSE
#define P_FAMILY_MIENFOO                 TRUE
#define P_FAMILY_DRUDDIGON               FALSE
#define P_FAMILY_GOLETT                  TRUE
#define P_FAMILY_PAWNIARD                TRUE
#define P_FAMILY_BOUFFALANT              FALSE
#define P_FAMILY_RUFFLET                 FALSE
#define P_FAMILY_VULLABY                 TRUE
#define P_FAMILY_HEATMOR                 FALSE
#define P_FAMILY_DURANT                  FALSE
#define P_FAMILY_DEINO                   FALSE
#define P_FAMILY_LARVESTA                TRUE
#define P_FAMILY_COBALION                FALSE
#define P_FAMILY_TERRAKION               FALSE
#define P_FAMILY_VIRIZION                FALSE
#define P_FAMILY_TORNADUS                TRUE
#define P_FAMILY_THUNDURUS               TRUE
#define P_FAMILY_RESHIRAM                FALSE
#define P_FAMILY_ZEKROM                  FALSE
#define P_FAMILY_LANDORUS                TRUE
#define P_FAMILY_KYUREM                  FALSE
#define P_FAMILY_KELDEO                  FALSE
#define P_FAMILY_MELOETTA                FALSE
#define P_FAMILY_GENESECT                TRUE

#define P_FAMILY_CHESPIN                 FALSE
#define P_FAMILY_FENNEKIN                FALSE
#define P_FAMILY_FROAKIE                 TRUE
#define P_FAMILY_BUNNELBY                FALSE
#define P_FAMILY_FLETCHLING              FALSE
#define P_FAMILY_SCATTERBUG              TRUE
#define P_FAMILY_LITLEO                  FALSE
#define P_FAMILY_FLABEBE                 TRUE
#define P_FAMILY_SKIDDO                  TRUE
#define P_FAMILY_PANCHAM                 FALSE
#define P_FAMILY_FURFROU                 FALSE
#define P_FAMILY_ESPURR                  FALSE
#define P_FAMILY_HONEDGE                 TRUE
#define P_FAMILY_SPRITZEE                FALSE
#define P_FAMILY_SWIRLIX                 TRUE
#define P_FAMILY_INKAY                   FALSE
#define P_FAMILY_BINACLE                 FALSE
#define P_FAMILY_SKRELP                  FALSE
#define P_FAMILY_CLAUNCHER               FALSE
#define P_FAMILY_HELIOPTILE              TRUE
#define P_FAMILY_TYRUNT                  FALSE
#define P_FAMILY_AMAURA                  FALSE
#define P_FAMILY_HAWLUCHA                TRUE
#define P_FAMILY_DEDENNE                 FALSE
#define P_FAMILY_CARBINK                 FALSE
#define P_FAMILY_GOOMY                   TRUE
#define P_FAMILY_KLEFKI                  TRUE
#define P_FAMILY_PHANTUMP                TRUE
#define P_FAMILY_PUMPKABOO               FALSE
#define P_FAMILY_BERGMITE                TRUE
#define P_FAMILY_NOIBAT                  FALSE
#define P_FAMILY_XERNEAS                 FALSE
#define P_FAMILY_YVELTAL                 FALSE
#define P_FAMILY_ZYGARDE                 FALSE
#define P_FAMILY_DIANCIE                 FALSE
#define P_FAMILY_HOOPA                   FALSE
#define P_FAMILY_VOLCANION               TRUE

#define P_FAMILY_ROWLET                  FALSE
#define P_FAMILY_LITTEN                  FALSE
#define P_FAMILY_POPPLIO                 TRUE
#define P_FAMILY_PIKIPEK                 FALSE
#define P_FAMILY_YUNGOOS                 FALSE
#define P_FAMILY_GRUBBIN                 TRUE
#define P_FAMILY_CRABRAWLER              TRUE
#define P_FAMILY_ORICORIO                TRUE
#define P_FAMILY_CUTIEFLY                TRUE
#define P_FAMILY_ROCKRUFF                FALSE
#define P_FAMILY_WISHIWASHI              FALSE
#define P_FAMILY_MAREANIE                TRUE
#define P_FAMILY_MUDBRAY                 TRUE
#define P_FAMILY_DEWPIDER                FALSE
#define P_FAMILY_FOMANTIS                FALSE
#define P_FAMILY_MORELULL                FALSE
#define P_FAMILY_SALANDIT                FALSE
#define P_FAMILY_STUFFUL                 FALSE
#define P_FAMILY_BOUNSWEET               FALSE
#define P_FAMILY_COMFEY                  TRUE
#define P_FAMILY_ORANGURU                FALSE
#define P_FAMILY_PASSIMIAN               FALSE
#define P_FAMILY_WIMPOD                  FALSE
#define P_FAMILY_SANDYGAST               FALSE
#define P_FAMILY_PYUKUMUKU               FALSE
#define P_FAMILY_TYPE_NULL               TRUE
#define P_FAMILY_MINIOR                  TRUE
#define P_FAMILY_KOMALA                  FALSE
#define P_FAMILY_TURTONATOR              FALSE
#define P_FAMILY_TOGEDEMARU              FALSE
#define P_FAMILY_MIMIKYU                 TRUE
#define P_FAMILY_BRUXISH                 FALSE
#define P_FAMILY_DRAMPA                  FALSE
#define P_FAMILY_DHELMISE                FALSE
#define P_FAMILY_JANGMO_O                TRUE
#define P_FAMILY_TAPU_KOKO               FALSE
#define P_FAMILY_TAPU_LELE               FALSE
#define P_FAMILY_TAPU_BULU               FALSE
#define P_FAMILY_TAPU_FINI               FALSE
#define P_FAMILY_COSMOG                  FALSE
#define P_FAMILY_NIHILEGO                FALSE
#define P_FAMILY_BUZZWOLE                FALSE
#define P_FAMILY_PHEROMOSA               FALSE
#define P_FAMILY_XURKITREE               FALSE
#define P_FAMILY_CELESTEELA              FALSE
#define P_FAMILY_KARTANA                 FALSE
#define P_FAMILY_GUZZLORD                FALSE
#define P_FAMILY_NECROZMA                FALSE
#define P_FAMILY_MAGEARNA                TRUE
#define P_FAMILY_MARSHADOW               FALSE
#define P_FAMILY_POIPOLE                 FALSE
#define P_FAMILY_STAKATAKA               FALSE
#define P_FAMILY_BLACEPHALON             FALSE
#define P_FAMILY_ZERAORA                 FALSE
#define P_FAMILY_MELTAN                  FALSE

#define P_FAMILY_GROOKEY                 TRUE
#define P_FAMILY_SCORBUNNY               FALSE
#define P_FAMILY_SOBBLE                  FALSE
#define P_FAMILY_SKWOVET                 FALSE
#define P_FAMILY_ROOKIDEE                FALSE
#define P_FAMILY_BLIPBUG                 FALSE
#define P_FAMILY_NICKIT                  FALSE
#define P_FAMILY_GOSSIFLEUR              FALSE
#define P_FAMILY_WOOLOO                  FALSE
#define P_FAMILY_CHEWTLE                 TRUE
#define P_FAMILY_YAMPER                  FALSE
#define P_FAMILY_ROLYCOLY                TRUE
#define P_FAMILY_APPLIN                  FALSE
#define P_FAMILY_SILICOBRA               TRUE
#define P_FAMILY_CRAMORANT               FALSE
#define P_FAMILY_ARROKUDA                TRUE
#define P_FAMILY_TOXEL                   TRUE
#define P_FAMILY_SIZZLIPEDE              FALSE
#define P_FAMILY_CLOBBOPUS               FALSE
#define P_FAMILY_SINISTEA                FALSE
#define P_FAMILY_HATENNA                 TRUE
#define P_FAMILY_IMPIDIMP                FALSE
#define P_FAMILY_MILCERY                 TRUE
#define P_FAMILY_FALINKS                 FALSE
#define P_FAMILY_PINCURCHIN              TRUE
#define P_FAMILY_SNOM                    TRUE
#define P_FAMILY_STONJOURNER             FALSE
#define P_FAMILY_EISCUE                  FALSE
#define P_FAMILY_INDEEDEE                TRUE
#define P_FAMILY_MORPEKO                 FALSE
#define P_FAMILY_CUFANT                  FALSE
#define P_FAMILY_DRACOZOLT               TRUE
#define P_FAMILY_ARCTOZOLT               TRUE
#define P_FAMILY_DRACOVISH               TRUE
#define P_FAMILY_ARCTOVISH               TRUE
#define P_FAMILY_DURALUDON               TRUE
#define P_FAMILY_DREEPY                  TRUE
#define P_FAMILY_ZACIAN                  FALSE
#define P_FAMILY_ZAMAZENTA               FALSE
#define P_FAMILY_ETERNATUS               FALSE
#define P_FAMILY_KUBFU                   TRUE
#define P_FAMILY_ZARUDE                  TRUE
#define P_FAMILY_REGIELEKI               FALSE
#define P_FAMILY_REGIDRAGO               FALSE
#define P_FAMILY_GLASTRIER               FALSE
#define P_FAMILY_SPECTRIER               FALSE
#define P_FAMILY_CALYREX                 FALSE
#define P_FAMILY_ENAMORUS                FALSE

#define P_FAMILY_SPRIGATITO              TRUE
#define P_FAMILY_FUECOCO                 FALSE
#define P_FAMILY_QUAXLY                  FALSE
#define P_FAMILY_LECHONK                 FALSE
#define P_FAMILY_TAROUNTULA              FALSE
#define P_FAMILY_NYMBLE                  TRUE
#define P_FAMILY_PAWMI                   TRUE
#define P_FAMILY_TANDEMAUS               FALSE
#define P_FAMILY_FIDOUGH                 TRUE
#define P_FAMILY_SMOLIV                  FALSE
#define P_FAMILY_SQUAWKABILLY            FALSE
#define P_FAMILY_NACLI                   TRUE
#define P_FAMILY_CHARCADET               FALSE
#define P_FAMILY_TADBULB                 TRUE
#define P_FAMILY_WATTREL                 TRUE
#define P_FAMILY_MASCHIFF                FALSE
#define P_FAMILY_SHROODLE                TRUE
#define P_FAMILY_BRAMBLIN                FALSE
#define P_FAMILY_TOEDSCOOL               FALSE
#define P_FAMILY_KLAWF                   FALSE
#define P_FAMILY_CAPSAKID                FALSE
#define P_FAMILY_RELLOR                  FALSE
#define P_FAMILY_FLITTLE                 FALSE
#define P_FAMILY_TINKATINK               FALSE
#define P_FAMILY_WIGLETT                 FALSE
#define P_FAMILY_BOMBIRDIER              FALSE
#define P_FAMILY_FINIZEN                 FALSE
#define P_FAMILY_VAROOM                  FALSE
#define P_FAMILY_CYCLIZAR                FALSE
#define P_FAMILY_ORTHWORM                FALSE
#define P_FAMILY_GLIMMET                 TRUE
#define P_FAMILY_GREAVARD                TRUE
#define P_FAMILY_FLAMIGO                 FALSE
#define P_FAMILY_CETODDLE                TRUE
#define P_FAMILY_VELUZA                  FALSE
#define P_FAMILY_DONDOZO                 FALSE
#define P_FAMILY_TATSUGIRI               FALSE
#define P_FAMILY_GREAT_TUSK              FALSE
#define P_FAMILY_SCREAM_TAIL             FALSE
#define P_FAMILY_BRUTE_BONNET            FALSE
#define P_FAMILY_FLUTTER_MANE            FALSE
#define P_FAMILY_SLITHER_WING            FALSE
#define P_FAMILY_SANDY_SHOCKS            FALSE
#define P_FAMILY_IRON_TREADS             FALSE
#define P_FAMILY_IRON_BUNDLE             FALSE
#define P_FAMILY_IRON_HANDS              FALSE
#define P_FAMILY_IRON_JUGULIS            FALSE
#define P_FAMILY_IRON_MOTH               FALSE
#define P_FAMILY_IRON_THORNS             FALSE
#define P_FAMILY_FRIGIBAX                FALSE
#define P_FAMILY_GIMMIGHOUL              FALSE
#define P_FAMILY_WO_CHIEN                FALSE
#define P_FAMILY_CHIEN_PAO               FALSE
#define P_FAMILY_TING_LU                 FALSE
#define P_FAMILY_CHI_YU                  FALSE
#define P_FAMILY_ROARING_MOON            FALSE
#define P_FAMILY_IRON_VALIANT            FALSE
#define P_FAMILY_KORAIDON                FALSE
#define P_FAMILY_MIRAIDON                FALSE
#define P_FAMILY_WALKING_WAKE            FALSE
#define P_FAMILY_IRON_LEAVES             FALSE
#define P_FAMILY_POLTCHAGEIST            FALSE
#define P_FAMILY_SINISTCHA               FALSE
#define P_FAMILY_OKIDOGI                 FALSE
#define P_FAMILY_MUNKIDORI               FALSE
#define P_FAMILY_FEZANDIPITI             FALSE
#define P_FAMILY_OGERPON                 FALSE
#define P_FAMILY_GOUGING_FIRE            FALSE
#define P_FAMILY_RAGING_BOLT             FALSE
#define P_FAMILY_IRON_BOULDER            FALSE
#define P_FAMILY_IRON_CROWN              FALSE
#define P_FAMILY_TERAPAGOS               FALSE
#define P_FAMILY_PECHARUNT               FALSE

#endif // GUARD_CONFIG_SPECIES_ENABLED_H
