#ifndef GUARD_CONFIG_SWSH_ITEM_MENU_H
#define GUARD_CONFIG_SWSH_ITEM_MENU_H

#define SWSH_ITEM_MENU                    TRUE
#define SWSH_ITEM_MENU_SCROLLING_BG       TRUE
#define SWSH_ITEM_MENU_TMHM_CONTEST_INFO  TRUE
#define SWSH_ITEM_MENU_BERRY_INFO         TRUE
#define SWSH_ITEM_MENU_CHECK_BERRY_TAG    FALSE

#endif // GUARD_CONFIG_SWSH_ITEM_MENU_H
