#ifndef GUARD_CONFIG_SWSH_ITEM_MENU_H
#define GUARD_CONFIG_SWSH_ITEM_MENU_H

#define SWSH_ITEM_MENU              TRUE
#define SWSH_ITEM_MENU_SCROLLING_BG TRUE

#endif // GUARD_CONFIG_SWSH_ITEM_MENU_H
