SaffronCity_CopycatsHouse_2F_Frlg_MapScripts::
        .byte 0


SaffronCity_CopycatsHouse_2F_Frlg_EventScript_Doduo::
        msgbox SaffronCity_CopycatsHouse_2F_Frlg_Text_Doduo, MSGBOX_NPC
        end

SaffronCity_CopycatsHouse_2F_Frlg_EventScript_Pikachu::
        msgbox SaffronCity_CopycatsHouse_2F_Frlg_Text_Pikachu, MSGBOX_NPC
        end

SaffronCity_CopycatsHouse_2F_Frlg_EventScript_Jigglypuff::
        msgbox SaffronCity_CopycatsHouse_2F_Frlg_Text_Jigglypuff, MSGBOX_NPC
        end

SaffronCity_CopycatsHouse_2F_Frlg_EventScript_Copycat::
        msgbox SaffronCity_CopycatsHouse_2F_Frlg_Text_Copycat, MSGBOX_NPC
        end


SaffronCity_CopycatsHouse_2F_Frlg_Text_Doduo:
        .string "DODUO: Do! Duo!$"

SaffronCity_CopycatsHouse_2F_Frlg_Text_Pikachu:
        .string "PIKACHU: Pika pika!$"

SaffronCity_CopycatsHouse_2F_Frlg_Text_Jigglypuff:
        .string "JIGGLYPUFF: Jiggly!$"

SaffronCity_CopycatsHouse_2F_Frlg_Text_Copycat:
        .string "COPYCAT: Oh! A visitor!\p"
        .string "A visitor!\p"
        .string "...See? I'm good at this.$"
