voice_group allkeysplit_bw_drum_6
	voice_directsound 61, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 000 | --- | voice_directsound 61, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 62, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 001 | --- | voice_directsound 62, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 63, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 002 | --- | voice_directsound 63, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 64, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 003 | --- | voice_directsound 64, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 65, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 004 | --- | voice_directsound 65, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 66, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 005 | --- | voice_directsound 66, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 67, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171      @ 006 | --- | voice_directsound 67, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 171
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 171      @ 007 | --- | voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 171
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171           @ 008 | --- | voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171           @ 009 | --- | voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 58, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171           @ 010 | --- | voice_directsound 58, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 59, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171           @ 011 | --- | voice_directsound 59, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 171
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 012 | --- | voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 61, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 013 | --- | voice_directsound 61, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 62, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 014 | --- | voice_directsound 62, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 63, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 015 | --- | voice_directsound 63, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 64, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 016 | --- | voice_directsound 64, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 65, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 017 | --- | voice_directsound 65, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 66, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 018 | --- | voice_directsound 66, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 67, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 019 | --- | voice_directsound 67, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 68, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 020 | --- | voice_directsound 68, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 69, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 021 | --- | voice_directsound 69, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 70, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 022 | --- | voice_directsound 70, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 71, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 023 | --- | voice_directsound 71, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 72, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171       @ 024 | --- | voice_directsound 72, 26, DirectSoundWaveData_dp_cabassa_16, 255, 242, 127, 171
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 197, 0, 1          @ 025 | --- | voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 197, 0, 1
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 248, 0, 192        @ 026 | --- | voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 248, 0, 192
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 171          @ 027 | --- | voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 171
	voice_directsound 61, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 171          @ 028 | --- | voice_directsound 61, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_rim1_roop, 255, 0, 227, 205          @ 029 | --- | voice_directsound 60, 64, DirectSoundWaveData_bw_159rim, 255, 0, 227, 205
	voice_directsound 61, 64, DirectSoundWaveData_dp_rim1_roop, 255, 0, 227, 205          @ 030 | --- | voice_directsound 61, 64, DirectSoundWaveData_bw_159rim, 255, 0, 227, 205
	voice_directsound 62, 64, DirectSoundWaveData_dp_rim1_roop, 255, 0, 227, 205          @ 031 | --- | voice_directsound 62, 64, DirectSoundWaveData_bw_159rim, 255, 0, 227, 205
	voice_directsound 63, 64, DirectSoundWaveData_dp_rim1_roop, 255, 0, 227, 205          @ 032 | --- | voice_directsound 63, 64, DirectSoundWaveData_bw_159rim, 255, 0, 227, 205
	voice_directsound 64, 64, DirectSoundWaveData_dp_rim1_roop, 255, 0, 227, 205          @ 033 | --- | voice_directsound 64, 64, DirectSoundWaveData_bw_159rim, 255, 0, 227, 205
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 034 | --- | voice_directsound 60, 64, DirectSoundWaveData_bw_011kick, 255, 0, 227, 205
	voice_directsound 61, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 035 | --- | voice_directsound 61, 64, DirectSoundWaveData_bw_011kick, 255, 0, 227, 205
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 036 | --- | voice_directsound 60, 64, DirectSoundWaveData_bw_109kick, 255, 0, 227, 205
	voice_directsound 61, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 037 | --- | voice_directsound 61, 64, DirectSoundWaveData_bw_109kick, 255, 0, 227, 205
	voice_directsound 62, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 038 | --- | voice_directsound 62, 64, DirectSoundWaveData_bw_109kick, 255, 0, 227, 205
	voice_directsound 63, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 227, 205          @ 039 | --- | voice_directsound 63, 64, DirectSoundWaveData_bw_109kick, 255, 0, 227, 205
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 205         @ 040 | --- | voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 205
	voice_directsound 60, 30, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171             @ 041 | --- | voice_directsound 60, 30, DirectSoundWaveData_hg_135tom, 255, 0, 255, 171
	voice_directsound 60, 80, DirectSoundWaveData_hg_062chh, 255, 78, 0, 205              @ 042 | --- | voice_directsound 60, 80, DirectSoundWaveData_hg_062chh, 255, 78, 0, 205
	voice_directsound 60, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171             @ 043 | --- | voice_directsound 60, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171
	voice_directsound 61, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171             @ 044 | --- | voice_directsound 61, 40, DirectSoundWaveData_hg_137tom, 255, 0, 255, 171
	voice_directsound 60, 50, DirectSoundWaveData_hg_138tom, 255, 0, 255, 171             @ 045 | --- | voice_directsound 60, 50, DirectSoundWaveData_hg_138tom, 255, 0, 255, 171
	voice_directsound 60, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 205             @ 046 | --- | voice_directsound 60, 80, DirectSoundWaveData_hg_063ohh, 255, 241, 0, 205
	voice_directsound 60, 100, DirectSoundWaveData_hg_136tom, 255, 0, 255, 171            @ 047 | --- | voice_directsound 60, 100, DirectSoundWaveData_hg_136tom, 255, 0, 255, 171
	voice_directsound 61, 100, DirectSoundWaveData_hg_136tom, 255, 0, 255, 171            @ 048 | --- | voice_directsound 61, 100, DirectSoundWaveData_hg_136tom, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 049 | --- | voice_directsound 60, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 61, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 050 | --- | voice_directsound 61, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 62, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 051 | --- | voice_directsound 62, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 63, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 052 | --- | voice_directsound 63, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 64, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 053 | --- | voice_directsound 64, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 65, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 054 | --- | voice_directsound 65, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 66, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 055 | --- | voice_directsound 66, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 67, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 056 | --- | voice_directsound 67, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 68, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 057 | --- | voice_directsound 68, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 69, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 058 | --- | voice_directsound 69, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 70, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 059 | --- | voice_directsound 70, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 71, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 060 | --- | voice_directsound 71, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 72, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 061 | --- | voice_directsound 72, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 73, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 062 | --- | voice_directsound 73, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 74, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 063 | --- | voice_directsound 74, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 75, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 064 | --- | voice_directsound 75, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 76, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 065 | --- | voice_directsound 76, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 77, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 066 | --- | voice_directsound 77, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 78, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 067 | --- | voice_directsound 78, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 79, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 068 | --- | voice_directsound 79, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 80, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 069 | --- | voice_directsound 80, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 81, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 070 | --- | voice_directsound 81, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 82, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 071 | --- | voice_directsound 82, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 83, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 072 | --- | voice_directsound 83, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 84, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 073 | --- | voice_directsound 84, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 85, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 074 | --- | voice_directsound 85, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 86, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 075 | --- | voice_directsound 86, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 87, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 076 | --- | voice_directsound 87, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 88, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 077 | --- | voice_directsound 88, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 89, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 078 | --- | voice_directsound 89, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 90, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 079 | --- | voice_directsound 90, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 91, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 080 | --- | voice_directsound 91, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 92, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214           @ 081 | --- | voice_directsound 92, 64, DirectSoundWaveData_hg_032crash, 255, 246, 0, 214
	voice_directsound 60, 30, DirectSoundWaveData_dp_tambourine_16, 255, 224, 227, 205    @ 082 | --- | voice_directsound 60, 30, DirectSoundWaveData_bw_201tamb, 255, 224, 227, 205
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 083 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 084 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 085 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 086 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 087 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 088 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 089 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 090 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 091 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 092 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 093 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 094 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 095 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 096 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 097 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 098 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 099 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 100 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 101 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 102 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 103 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 104 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 105 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 106 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 107 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 108 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 109 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 110 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 111 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 112 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 113 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 114 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 115 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 116 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 117 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 118 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 119 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 120 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 121 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 122 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 123 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 124 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 125 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 126 | --- |  
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                               @ 127 | --- |  
