@ Starting from here, these movements are considered
@ 'safe' (won't put follower into a Pokeball)
Common_Movement_FollowerSafeStart::
Common_Movement_QuestionMark:
	emote_question_mark
	step_end

Common_Movement_ExclamationMark:
	emote_exclamation_mark
	step_end

Common_Movement_Delay48:
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:
	face_player
	step_end

Common_Movement_FaceAwayPlayer:
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft:
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp:
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight:
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown:
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight::
	face_right
	step_end

Common_Movement_FaceLeft::
	face_left
	step_end

Common_Movement_FaceDown::
	face_down
	step_end

Common_Movement_FaceUp::
	face_up
	step_end

Common_Movement_WalkInPlaceDown:
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft:
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight:
	walk_in_place_right
	step_end

@ End of follower-safe movements
Common_Movement_FollowerSafeEnd::
	step_end

Common_Movement_WalkUp6:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp:
	walk_up
	step_end

@ Unused
Common_Movement_WalkUp2::
	walk_up
	walk_up
	step_end

@ Follower NPC
Common_Movement_WalkUpHideSlow::
    walk_slow_up
    set_invisible
    step_end

Common_Movement_WalkDownHideSlow::
    walk_slow_down
    set_invisible
    step_end

Common_Movement_WalkRightHideSlow::
    walk_slow_right
    set_invisible
    step_end

Common_Movement_WalkLeftHideSlow::
    walk_slow_left
    set_invisible
    step_end

Common_Movement_WalkUpHide::
    walk_up
    set_invisible
    step_end

Common_Movement_WalkDownHide::
    walk_down
    set_invisible
    step_end

Common_Movement_WalkRightHide::
    walk_right
    set_invisible
    step_end

Common_Movement_WalkLeftHide::
    walk_left
    set_invisible
    step_end

Common_Movement_WalkUpHideFast::
    walk_fast_up
    set_invisible
    step_end

Common_Movement_WalkDownHideFast::
    walk_fast_down
    set_invisible
    step_end

Common_Movement_WalkRightHideFast::
    walk_fast_right
    set_invisible
    step_end

Common_Movement_WalkLeftHideFast::
    walk_fast_left
    set_invisible
    step_end

Common_Movement_WalkUpHideFaster::
    walk_faster_up
    set_invisible
    step_end

Common_Movement_WalkDownHideFaster::
    walk_faster_down
    set_invisible
    step_end

Common_Movement_WalkRightHideFaster::
    walk_faster_right
    set_invisible
    step_end

Common_Movement_WalkLeftHideFaster::
    walk_faster_left
    set_invisible
    step_end
