#!/usr/bin/env python3
"""Generate FRLG classic movepool tables for S30 from porymoves frlg.json.

Writes:
  src/data/mf_classic_level_up_learnsets.h
  src/data/mf_classic_teachable_learnsets.h
  src/data/mf_classic_egg_moves.h

Modern (GEN_LATEST) learnsets stay in gSpeciesInfo. Re-run after refreshing
tools/learnset_helpers/porymoves_files/frlg.json:
  python3 tools/mf/gen_classic_movepools.py
"""

from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
FRLG_JSON = ROOT / "tools/learnset_helpers/porymoves_files/frlg.json"
SPECIES_H = ROOT / "include/constants/species.h"
OUT_LEVEL = ROOT / "src/data/mf_classic_level_up_learnsets.h"
OUT_TEACH = ROOT / "src/data/mf_classic_teachable_learnsets.h"
OUT_EGG = ROOT / "src/data/mf_classic_egg_moves.h"


def camel(species_key: str) -> str:
    """BULBASAUR -> Bulbasaur; MR_MIME -> MrMime; HO_OH -> HoOh; NIDORAN_F -> NidoranF."""
    parts = species_key.split("_")
    return "".join(p[:1].upper() + p[1:].lower() for p in parts)


def load_species_ids() -> dict[str, int]:
    """Map SPECIES_FOO -> numeric id (follows aliases to a numeric assignee)."""
    text = SPECIES_H.read_text()
    numeric: dict[str, int] = {}
    aliases: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip().rstrip(",")
        m = re.match(r"(SPECIES_\w+)\s*=\s*(\d+)\b", line)
        if m:
            numeric[m.group(1)] = int(m.group(2))
            continue
        m = re.match(r"(SPECIES_\w+)\s*=\s*(SPECIES_\w+)\b", line)
        if m:
            aliases[m.group(1)] = m.group(2)

    # Resolve aliases (one or two hops is enough for this header).
    for name, target in aliases.items():
        seen = set()
        cur = target
        while cur in aliases and cur not in seen:
            seen.add(cur)
            cur = aliases[cur]
        if cur in numeric:
            numeric[name] = numeric[cur]
    return numeric


def write_level_up(ordered_keys: list[str], data: dict) -> None:
    lines: list[str] = [
        "/* Autogenerated FRLG classic level-up learnsets for S30.",
        " * Source: tools/learnset_helpers/porymoves_files/frlg.json",
        f" * {len(ordered_keys)} species. Sorted by species id for binary search.",
        " * Regenerate: python3 tools/mf/gen_classic_movepools.py",
        " */",
        "",
        "#define LEVEL_UP_MOVE(lvl, moveLearned) {.move = moveLearned, .level = lvl}",
        "#define LEVEL_UP_END {.move = LEVEL_UP_MOVE_END, .level = 0}",
        "",
    ]
    entries: list[tuple[str, str]] = []
    for key in ordered_keys:
        name = camel(key)
        arr = f"sMfClassic{name}LevelUpLearnset"
        lines.append(f"static const struct LevelUpMove {arr}[] = {{")
        for entry in data[key]["LevelMoves"]:
            lines.append(f"    LEVEL_UP_MOVE({entry['Level']:2d}, {entry['Move']}),")
        lines.append("    LEVEL_UP_END")
        lines.append("};")
        lines.append("")
        entries.append((f"SPECIES_{key}", arr))

    lines.append("static const struct MfClassicLevelUpPtr sClassicLevelUpLearnsets[] = {")
    for species, arr in entries:
        lines.append(f"    {{ {species}, {arr} }},")
    lines.append("};")
    lines.append("")
    lines.append("#undef LEVEL_UP_MOVE")
    lines.append("#undef LEVEL_UP_END")
    lines.append("")
    OUT_LEVEL.write_text("\n".join(lines))


def write_u16_table(
    path: pathlib.Path,
    title: str,
    ordered_keys: list[str],
    data: dict,
    move_lists: dict[str, list[str]],
    array_suffix: str,
    table_name: str,
) -> None:
    lines: list[str] = [
        f"/* Autogenerated FRLG classic {title} for S30.",
        " * Source: tools/learnset_helpers/porymoves_files/frlg.json",
        f" * {len(ordered_keys)} species. Sorted by species id for binary search.",
        " * Regenerate: python3 tools/mf/gen_classic_movepools.py",
        " */",
        "",
    ]
    entries: list[tuple[str, str]] = []
    for key in ordered_keys:
        name = camel(key)
        arr = f"sMfClassic{name}{array_suffix}"
        lines.append(f"static const u16 {arr}[] = {{")
        for move in move_lists[key]:
            lines.append(f"    {move},")
        lines.append("    MOVE_UNAVAILABLE,")
        lines.append("};")
        lines.append("")
        entries.append((f"SPECIES_{key}", arr))

    lines.append(f"static const struct MfClassicU16LearnsetPtr {table_name}[] = {{")
    for species, arr in entries:
        lines.append(f"    {{ {species}, {arr} }},")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines))


def main() -> int:
    data = json.loads(FRLG_JSON.read_text())
    species_ids = load_species_ids()

    missing = [k for k in data if f"SPECIES_{k}" not in species_ids]
    if missing:
        print(f"error: missing SPECIES ids for {missing}", file=sys.stderr)
        return 1

    ordered_keys = sorted(data.keys(), key=lambda k: species_ids[f"SPECIES_{k}"])

    write_level_up(ordered_keys, data)

    teach_lists = {
        k: list(dict.fromkeys(data[k]["TMMoves"] + data[k]["TutorMoves"]))
        for k in ordered_keys
    }
    write_u16_table(
        OUT_TEACH,
        "teachable learnsets (TM/HM + tutor)",
        ordered_keys,
        data,
        teach_lists,
        "TeachableLearnset",
        "sClassicTeachableLearnsets",
    )

    egg_lists = {k: list(data[k]["EggMoves"]) for k in ordered_keys}
    write_u16_table(
        OUT_EGG,
        "egg move learnsets",
        ordered_keys,
        data,
        egg_lists,
        "EggMoveLearnset",
        "sClassicEggMoveLearnsets",
    )

    print(f"wrote {OUT_LEVEL.relative_to(ROOT)} ({len(ordered_keys)} species)")
    print(f"wrote {OUT_TEACH.relative_to(ROOT)}")
    print(f"wrote {OUT_EGG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
