SaffronCity_PokemonCenter_1F_Frlg_MapScripts::
        .byte 0


SaffronCity_PokemonCenter_1F_Frlg_EventScript_Nurse::
        msgbox SaffronCity_PokemonCenter_1F_Frlg_Text_Nurse, MSGBOX_NPC
        end

SaffronCity_PokemonCenter_1F_Frlg_EventScript_Gentleman::
        msgbox SaffronCity_PokemonCenter_1F_Frlg_Text_Gentleman, MSGBOX_NPC
        end

SaffronCity_PokemonCenter_1F_Frlg_EventScript_Woman::
        msgbox SaffronCity_PokemonCenter_1F_Frlg_Text_Woman, MSGBOX_NPC
        end

SaffronCity_PokemonCenter_1F_Frlg_EventScript_Youngster::
        msgbox SaffronCity_PokemonCenter_1F_Frlg_Text_Youngster, MSGBOX_NPC
        end


SaffronCity_PokemonCenter_1F_Frlg_Text_Nurse:
        .string "Welcome to the POKEMON CENTER.$"

SaffronCity_PokemonCenter_1F_Frlg_Text_Gentleman:
        .string "Saffron sits right in the middle\n"
        .string "of everything.\p"
        .string "Makes traveling easy.$"

SaffronCity_PokemonCenter_1F_Frlg_Text_Woman:
        .string "I stop here whenever I'm in town.\p"
        .string "It's usually busy.$"

SaffronCity_PokemonCenter_1F_Frlg_Text_Youngster:
        .string "My POKEMON likes resting here.\p"
        .string "Honestly, so do I.$"
