Town_Spragholt_MapScripts::
	.byte 0


Town_Spragholt_EventScript_FireMan::
# 4 "data/maps/Town_Spragholt/scripts.pory"
	lock
# 5 "data/maps/Town_Spragholt/scripts.pory"
	faceplayer
# 6 "data/maps/Town_Spragholt/scripts.pory"
	msgbox Town_Spragholt_EventScript_FireMan_Text_0
# 7 "data/maps/Town_Spragholt/scripts.pory"
	release
	end


Town_Spragholt_EventScript_FireMan_Text_0:
# 6 "data/maps/Town_Spragholt/scripts.pory"
	.string "Cool cave dwellers can make fire. But\n"
	.string "REALLY cool cave dwellers dare to jump\l"
	.string "over it!\p"
	.string "Have you tried it?$"
