// DO NOT MODIFY THIS FILE
// This file was auto-generate by tools/config_splitter/split_config.py
// Modify the files in the include/config/ directory instead

#ifndef GUARD_CONFIG_OVERWORLD_H
#define GUARD_CONFIG_OVERWORLD_H
#define OW_RUNNING_INDOORS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define SLOW_MOVEMENT_ON_STAIRS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POISON_DAMAGE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_DOUBLE_APPROACH_WITH_ONE_MON FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_HIDE_REPEAT_MAP_POPUP FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_WHITEOUT_CUTSCENE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_DEFOG_FIELD_MOVE FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ROCK_CLIMB_FIELD_MOVE FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ITEM_DESCRIPTIONS_OFF 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ITEM_DESCRIPTIONS_FIRST_TIME 1 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ITEM_DESCRIPTIONS_ALWAYS 2 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_SHOW_ITEM_DESCRIPTIONS OW_ITEM_DESCRIPTIONS_OFF // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define GEN_6_XY GEN_6 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define GEN_6_ORAS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PC_PRESS_B GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PC_JAPAN_WALDA_ICONS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PC_HEAL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PC_MOVE_ORDER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PC_RELEASE_ITEM GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_MUTATIONS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_MUTATION_CHANCE 25 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_MOISTURE FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_ALWAYS_WATERABLE FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_MULCH_USAGE FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_WEEDS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_PESTS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_SIX_STAGES FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_GROWTH_RATE GEN_3 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_YIELD_RATE GEN_3 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_DRAIN_RATE GEN_6_ORAS // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BERRY_IMMORTAL FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POKEMON_OBJECT_EVENTS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_SUBSTITUTE_PLACEHOLDER TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_LARGE_OW_SUPPORT TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_PKMN_OBJECTS_SHARE_PALETTES FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_GFX_COMPRESS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_MON_WANDER_WALK TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_ENABLED FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_BOBBING TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_POKEBALLS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_WEATHER_FORMS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_COPY_WILD_PKMN FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_BATTLE_ONLY_FORMS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define B_FLAG_FOLLOWERS_DISABLED 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FOLLOWERS_SCRIPT_MOVEMENT TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_SYNCHRONIZE_NATURE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_SUPER_LUCK GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_INFILTRATOR GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_HARVEST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_LIGHTNING_ROD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_STORM_DRAIN GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLASH_FIRE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define GEN_8_PLA GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define TIME_DEBUG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_TIMES_OF_DAY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_USE_FAKE_RTC FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ALTERED_TIME_RATIO GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_TIME_OF_DAY_ENCOUNTERS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_TIME_OF_DAY_DISABLE_FALLBACK FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_TIME_OF_DAY_FALLBACK TIME_MORNING // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_SHADOW_INTENSITY 4 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_OBJECT_SUBPRIORITY 148 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_ENABLE_DNS TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_OBJECT_VANILLA_SHADOWS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_PAUSE_TIME 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_NO_ENCOUNTER 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_NO_TRAINER_SEE 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_NO_COLLISION 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_POKE_RIDER 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_SUPPRESS_NAME_BOX 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define BATTLE_PYRAMID_RANDOM_ENCOUNTERS FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_GENERATION GEN_3 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_TIME_NONE 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_TIME_12_HR 1 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_TIME_24_HR 2 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_COLOR_BLACK 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_COLOR_WHITE 1 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_COLOR OW_POPUP_BW_COLOR_BLACK // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_TIME_MODE OW_POPUP_BW_TIME_NONE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_POPUP_BW_ALPHA_BLEND FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_IGNORE_EGGS_ON_HEAL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_UNION_DISABLE_CHECK FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_FLAG_MOVE_UNION_ROOM_CHECK 0 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define BERRY_BLENDER_THROW_ALL_BERRIES_AT_ONCE TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_USE_DYNAMIC_WIDTH TRUE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_NPC_TRAINER FALSE // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_DEFAULT_WIDTH 8 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_DEFAULT_HEIGHT 2 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_FOREGROUND_COLOR 1 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#define OW_NAME_BOX_SHADOW_COLOR 2 // DO NOT MODIFY THIS LINE, change include/config/overworld.h instead
#endif
