// DO NOT MODIFY THIS FILE
// This file was auto-generate by tools/config_splitter/split_config.py
// Modify the files in the include/config/ directory instead

#ifndef GUARD_CONFIG_BATTLE_H
#define GUARD_CONFIG_BATTLE_H
#define B_CRIT_CHANCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CRIT_MULTIPLIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PARALYSIS_SPEED GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CONFUSION_SELF_DMG_CHANCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MULTI_HIT_CHANCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WHITEOUT_MONEY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LIGHT_BALL_ATTACK_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_EXP_CATCH GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRAINER_EXP_MULTIPLIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SPLIT_EXP GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SCALED_EXP GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UNEVOLVED_EXP_MULTIPLIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LEVEL_UP_NOTIFICATION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BADGE_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FRIENDSHIP_BOOST FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MAX_LEVEL_EV_GAINS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RECALCULATE_STATS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BURN_DAMAGE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BURN_FACADE_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BINDING_DAMAGE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PSYWAVE_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PAYBACK_SWITCH_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HIDDEN_POWER_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ROUGH_SKIN_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_KNOCK_OFF_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SPORT_DMG_REDUCTION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_EXPLOSION_DEFENSE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PARENTAL_BOND_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MULTIPLE_TARGETS_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_GHOSTS_ESCAPE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PARALYZE_ELECTRIC GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POWDER_GRASS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_TYPE_MATCHUPS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PRANKSTER_DARK_TYPES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHEER_COLD_IMMUNITY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ROOST_PURE_FLYING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_STATUS_TYPE_IMMUNITY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BINDING_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPROAR_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPROAR_IGNORE_SOUNDPROOF GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DISABLE_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TAILWIND_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SLEEP_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TAUNT_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SPORT_TURNS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MEGA_EVO_TURN_ORDER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RECALC_TURN_AFTER_ACTIONS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FAINT_SWITCH_IN GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_MOVE_DATA GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_MOVE_TYPES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_MOVE_FLAGS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PHYSICAL_SPECIAL_SPLIT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RECOIL_IF_MISS_DMG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_KLUTZ_FLING_INTERACTION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_CONVERSION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_CONVERSION_2 GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PP_REDUCED_BY_SPITE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_EXTRAPOLATED_MOVE_FLAGS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_ABILITY_DATA GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TOXIC_NEVER_MISS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MINIMIZE_DMG_ACC GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BLIZZARD_HAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHEER_COLD_ACC GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FELL_STINGER_STAT_RAISE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_KINGS_SHIELD_LOWER_ATK GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SPEED_BUFFING_RAPID_SPIN GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CHARGE_SPDEF_RAISE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MINIMIZE_EVASION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_GROWTH_STAT_RAISE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FOCUS_ENERGY_CRIT_RATIO GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_INCINERATE_GEMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CAN_SPITE_FAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CRASH_IF_TARGET_IMMUNE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MEMENTO_FAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_GLARE_GHOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SKILL_SWAP GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BRICK_BREAK GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WISH_HP_SOURCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RAMPAGE_CANCELLING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HEAL_BLOCKING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ROOTED_GROUNDING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_METRONOME_MOVES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TELEPORT_BEHAVIOR GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BEAT_UP GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DARK_VOID_FAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BURN_HIT_THAW GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HEALING_WISH_SWITCH GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DEFOG_EFFECT_CLEARING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_STOCKPILE_RAISES_DEFS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRANSFORM_SHINY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRANSFORM_FORM_CHANGES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WIDE_GUARD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_QUICK_GUARD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_IMPRISON GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ALLY_SWITCH_FAIL_CHANCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SKETCH_BANS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_KNOCK_OFF_REMOVAL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HEAL_BELL_SOUNDPROOF GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CHARGE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POWDER_RAIN GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_AFTER_YOU_TURN_ORDER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_QUASH_TURN_ORDER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DESTINY_BOND_FAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PURSUIT_TARGET GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SKIP_RECHARGE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ENCORE_TARGET GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TIME_OF_DAY_HEALING_MOVES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DREAM_EATER_LIQUID_OOZE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_GALE_WINGS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_STANCE_CHANGE_FAIL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHADOW_TAG_ESCAPE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MOODY_ACC_EVASION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLASH_FIRE_FROZEN GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SYNCHRONIZE_TOXIC GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_UPDATED_INTIMIDATE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_OBLIVIOUS_TAUNT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_STURDY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PLUS_MINUS_INTERACTION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WEATHER_FORMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SYMBIOSIS_GEMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ABSORBING_ABILITY_STRING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_REDIRECT_ABILITY_IMMUNITY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_REDIRECT_ABILITY_ALLIES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LEAF_GUARD_PREVENTS_REST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRANSISTOR_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ILLUMINATE_EFFECT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WEAK_ARMOR_SPEED GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PROTEAN_LIBERO GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_INTREPID_SWORD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DAUNTLESS_SHIELD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DISGUISE_HP_LOSS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ABILITY_TRIGGER_CHANCE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PICKUP_WILD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MAGIC_GUARD GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_BATTLE_BOND GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ATE_MULTIPLIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DEFIANT_STICKY_WEB GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CONFUSE_BERRIES_HEAL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_X_ITEMS_BUFF GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MENTAL_HERB GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRAINERS_KNOCK_OFF_ITEMS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RETURN_STOLEN_NPC_ITEMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_STEAL_WILD_ITEMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RESTORE_HELD_BATTLE_ITEMS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SOUL_DEW_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NET_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DIVE_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEST_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_REPEAT_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TIMER_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DUSK_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_QUICK_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LURE_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HEAVY_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DREAM_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SPORT_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SAFARI_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FRIEND_BALL_MODIFIER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SERENE_GRACE_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_IRON_BALL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_BADGE_BOOST_ATTACK FLAG_BADGE01_GET // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_BADGE_BOOST_DEFENSE FLAG_BADGE05_GET // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_BADGE_BOOST_SPEED FLAG_BADGE03_GET // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_BADGE_BOOST_SPATK FLAG_BADGE07_GET // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_BADGE_BOOST_SPDEF FLAG_BADGE07_GET // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_INVERSE_BATTLE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_FORCE_DOUBLE_WILD 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SMART_WILD_AI_FLAG 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_NO_CATCHING 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_NO_RUNNING 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_AI_VS_AI_BATTLE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_DYNAMAX_BATTLE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_TERA_ORB_CHARGED 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_TERA_ORB_NO_COST 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_SLEEP_CLAUSE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_NO_WHITEOUT 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_STARTING_STATUS 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_STARTING_STATUS_TIMER 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_WILD_AI_FLAGS 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_DIFFICULTY 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define NO_BAG_RESTRICTION 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define NO_BAG_AGAINST_TRAINER 1 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define NO_BAG_IN_BATTLE 2 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_NO_BAG_USE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FLAG_SKY_BATTLE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_VAR_SKY_BATTLE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SKY_BATTLE_STRICT_ELIGIBILITY FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RESET_FLAGS_VARS_AFTER_WHITEOUT TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_PARTNER_TARGET FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_MOVE_DESCRIPTION TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ICE_WEATHER_BOTH 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ICE_WEATHER_HAIL 1 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ICE_WEATHER_SNOW 2 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ABILITY_WEATHER GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SANDSTORM_SPDEF_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_OVERWORLD_FOG GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_OVERWORLD_SNOW GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SNOW_WARNING GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PREFERRED_ICE_WEATHER B_ICE_WEATHER_BOTH // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TERRAIN_BG_CHANGE TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_THUNDERSTORM_TERRAIN TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TERRAIN_TYPE_BOOST GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SECRET_POWER_EFFECT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SECRET_POWER_ANIMATION GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NATURE_POWER_MOVES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CAMOUFLAGE_TYPES GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_TERRAIN_BACKGROUNDS FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FAST_INTRO_PKMN_TEXT TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FAST_INTRO_NO_SLIDE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FAST_HP_DRAIN TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_FAST_EXP_GROW TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_TARGETS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_CATEGORY_ICON TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_HIDE_HEALTHBOX_IN_ANIMS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WAIT_TIME_MULTIPLIER 16 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_QUICK_MOVE_CURSOR_TO_RUN FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_RUN_TRAINER_BATTLE TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MOVE_DESCRIPTION_BUTTON L_BUTTON // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_USELESS_Z_MOVE_INFO FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ANIMATE_MON_AFTER_KO TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ANIMATE_MON_AFTER_FAILED_POKEBALL TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_DYNAMAX_MESSAGE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SEMI_INVULNERABLE_CATCH GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CATCHING_CHARM_BOOST 100 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CRITICAL_CAPTURE TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CRITICAL_CAPTURE_LOCAL_DEX TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CRITICAL_CAPTURE_IF_OWNED GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LAST_USED_BALL TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LAST_USED_BALL_BUTTON R_BUTTON // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_LAST_USED_BALL_CYCLE TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CATCH_SWAP_INTO_PARTY GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_CATCH_SWAP_CHECK_HMS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DOUBLE_WILD_CHANCE 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_DOUBLE_WILD_REQUIRE_2_MONS FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MULTI_BATTLE_WHITEOUT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_EVOLUTION_AFTER_WHITEOUT GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_WILD_NATURAL_ENEMIES TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_AFFECTION_MECHANICS TRUE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRAINER_CLASS_POKE_BALLS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRAINER_MON_RANDOM_ABILITY FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_OBEDIENCE_MECHANICS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_USE_FROSTBITE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TOXIC_REVERSAL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_TRY_CATCH_TRAINER_BALL GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SLEEP_CLAUSE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PARTNER_MONS_MARKED_SEEN FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define NUM_BEEPS_GEN_LATEST 4 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define NUM_BEEPS_OFF 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NUM_LOW_HEALTH_BEEPS NUM_BEEPS_GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_SWORD_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_LEECH_SEED_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_HORN_ATTACK_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_ROCKS_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_LEAF_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_EMBER_PARTICLES FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_MEAN_LOOK_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_TEETH_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_HANDS_FEET_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_SPIKES_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_FLY_BUBBLE_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_CURSE_NAIL_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_BATON_PASS_BALL_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_MORNING_SUN_STAR_PARTICLE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_IMPACT_PALETTE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_NEW_SURF_PARTICLE_PALETTE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ENEMY_THROW_BALLS GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ENEMY_THROW_BALLS_SOUND GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_PLAYER_THROW_BALLS_SOUND GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_TYPES_NEVER 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_TYPES_ALWAYS 1 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_TYPES_CAUGHT 2 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_TYPES_SEEN 3 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_TYPES SHOW_TYPES_NEVER // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_EFFECTIVENESS_NEVER 0 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_EFFECTIVENESS_ALWAYS 1 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_EFFECTIVENESS_CAUGHT 2 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define SHOW_EFFECTIVENESS_SEEN 3 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_SHOW_EFFECTIVENESS SHOW_EFFECTIVENESS_SEEN // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_ENEMY_MON_SHADOW_STYLE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_MOVE_REARRANGEMENT_IN_BATTLE GEN_LATEST // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_SETTING_CONSISTENT_RNG FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_SETTING_USE_FIXED_SEED FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_SETTING_FIXED_SEED 0x1D4127 // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULE_SPECIES_CLAUSE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULE_EXCLUDE_FORMS FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULE_ITEM_CLAUSE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULES_USE_ITEM_EXCLUSIONS FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULE_MEGA_STONE_CLAUSE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#define B_POOL_RULE_Z_CRYSTAL_CLAUSE FALSE // DO NOT MODIFY THIS LINE, change include/config/battle.h instead
#endif
