#ifndef GUARD_METATILE_BEHAVIOUR_H
#define GUARD_METATILE_BEHAVIOUR_H

// Return values for MetatileBehaviour_GetBridgeType
enum {
    BRIDGE_TYPE_OCEAN, // For log bridges over 'ocean' style water (Routes 110/119 use this).
    BRIDGE_TYPE_POND_LOW,
    BRIDGE_TYPE_POND_MED,
    BRIDGE_TYPE_POND_HIGH,
};

bool8 MetatileBehaviour_IsATile(u8);
bool8 MetatileBehaviour_IsEncounterTile(u8);
bool8 MetatileBehaviour_IsJumpEast(u8);
bool8 MetatileBehaviour_IsJumpWest(u8);
bool8 MetatileBehaviour_IsJumpNorth(u8);
bool8 MetatileBehaviour_IsJumpSouth(u8);
bool8 MetatileBehaviour_IsPokeGrass(u8);
bool8 MetatileBehaviour_IsSandOrDeepSand(u8);
bool8 MetatileBehaviour_IsDeepSand(u8);
bool8 MetatileBehaviour_IsReflective(u8);
bool8 MetatileBehaviour_IsIce(u8);
bool8 MetatileBehaviour_IsWarpDoor(u8);
bool8 MetatileBehaviour_IsDoor(u8);
bool8 MetatileBehaviour_IsEscalator(u8);
bool8 MetatileBehaviour_IsLadder(u8);
bool8 MetatileBehaviour_IsNonAnimDoor(u8);
bool8 MetatileBehaviour_IsDeepSouthWarp(u8);
bool8 MetatileBehaviour_IsSurfableWaterOrUnderwater(u8);
bool8 MetatileBehaviour_IsEastArrowWarp(u8);
bool8 MetatileBehaviour_IsWestArrowWarp(u8);
bool8 MetatileBehaviour_IsNorthArrowWarp(u8);
bool8 MetatileBehaviour_IsSouthArrowWarp(u8);
bool8 MetatileBehaviour_IsArrowWarp(u8);
bool8 MetatileBehaviour_IsForcedMovementTile(u8);
bool8 MetatileBehaviour_IsIce_2(u8);
bool8 MetatileBehaviour_IsTrickHouseSlipperyFloor(u8);
bool8 MetatileBehaviour_IsWalkNorth(u8);
bool8 MetatileBehaviour_IsWalkSouth(u8);
bool8 MetatileBehaviour_IsWalkWest(u8);
bool8 MetatileBehaviour_IsWalkEast(u8);
bool8 MetatileBehaviour_IsNorthwardCurrent(u8);
bool8 MetatileBehaviour_IsSouthwardCurrent(u8);
bool8 MetatileBehaviour_IsWestwardCurrent(u8);
bool8 MetatileBehaviour_IsEastwardCurrent(u8);
bool8 MetatileBehaviour_IsSlideNorth(u8);
bool8 MetatileBehaviour_IsSlideSouth(u8);
bool8 MetatileBehaviour_IsSlideWest(u8);
bool8 MetatileBehaviour_IsSlideEast(u8);
bool8 MetatileBehaviour_IsCounter(u8);
bool8 MetatileBehaviour_IsPlayerFacingTVScreen(u8 tile, u8 playerDir);
bool8 MetatileBehaviour_IsPC(u8);
bool8 MetatileBehaviour_IsCableBoxResults1(u8);
bool8 MetatileBehaviour_IsOpenSecretBaseDoor(u8);
bool8 MetatileBehaviour_IsSecretBaseCave(u8);
bool8 MetatileBehaviour_IsSecretBaseTree(u8);
bool8 MetatileBehaviour_IsSecretBaseShrub(u8);
bool8 MetatileBehaviour_IsSecretBasePC(u8);
bool8 MetatileBehaviour_IsRecordMixingSecretBasePC(u8);
bool8 MetatileBehaviour_IsSecretBaseTrainerSpot(u8);
bool8 MetatileBehaviour_IsSecretBaseImpassable(u8);
bool8 MetatileBehaviour_IsSecretBaseDecorationBase(u8);
bool8 MetatileBehaviour_IsSecretBasePoster(u8);
bool8 MetatileBehaviour_IsNormal(u8);
bool8 MetatileBehaviour_IsSecretBaseNorthWall(u8);
bool8 MetatileBehaviour_HoldsSmallDecoration(u8);
bool8 MetatileBehaviour_HoldsLargeDecoration(u8);
bool8 MetatileBehaviour_IsSecretBaseHole(u8);
bool8 MetatileBehaviour_IsSecretBaseBalloon(u8);
bool8 MetatileBehaviour_IsSecretBaseBreakableDoor(u8);
bool8 MetatileBehaviour_IsSecretBaseSoundMat(u8);
bool8 MetatileBehaviour_IsSecretBaseGlitterMat(u8);
bool8 MetatileBehaviour_IsSecretBaseSandOrnament(u8);
bool8 MetatileBehaviour_IsSecretBaseShieldOrToyTV(u8);
bool8 MetatileBehaviour_IsPlayerRoomPCOn(u8);
bool8 MetatileBehaviour_HasRipples(u8);
bool8 MetatileBehaviour_IsPuddle(u8);
bool8 MetatileBehaviour_IsTallGrass(u8);
bool8 MetatileBehaviour_IsLongGrass(u8);
bool8 MetatileBehaviour_IsBerryTreeSoil(u8);
bool8 MetatileBehaviour_IsAshGrass(u8);
bool8 MetatileBehaviour_IsFootprints(u8);
bool8 MetatileBehaviour_IsBridgeOverWater(u8);
u8 MetatileBehaviour_GetBridgeType(u8);
bool8 MetatileBehaviour_IsBridgeOverWaterNoEdge(u8);
bool8 MetatileBehaviour_IsLandWildEncounter(u8);
bool8 MetatileBehaviour_IsWaterWildEncounter(u8);
bool8 MetatileBehaviour_IsIndoorEncounter(u8);
bool8 MetatileBehaviour_IsMountain(u8);
bool8 MetatileBehaviour_IsDiveable(u8);
bool8 MetatileBehaviour_IsUnableToEmerge(u8);
bool8 MetatileBehaviour_IsShallowFlowingWater(u8);
bool8 MetatileBehaviour_IsThinIce(u8);
bool8 MetatileBehaviour_IsCrackedIce(u8);
bool8 MetatileBehaviour_IsDeepOrOceanWater(u8);
bool8 MetatileBehaviour_IsSurfableAndNotWaterfall(u8);
bool8 MetatileBehaviour_IsEastBlocked(u8);
bool8 MetatileBehaviour_IsWestBlocked(u8);
bool8 MetatileBehaviour_IsNorthBlocked(u8);
bool8 MetatileBehaviour_IsSouthBlocked(u8);
bool8 MetatileBehaviour_IsShortGrass(u8);
bool8 MetatileBehaviour_IsHotSprings(u8);
bool8 MetatileBehaviour_IsWaterfall(u8);
bool8 MetatileBehaviour_IsFortreeBridge(u8);
bool8 MetatileBehaviour_IsPacifidlogVerticalLogTop(u8);
bool8 MetatileBehaviour_IsPacifidlogVerticalLogBottom(u8);
bool8 MetatileBehaviour_IsPacifidlogHorizontalLogLeft(u8);
bool8 MetatileBehaviour_IsPacifidlogHorizontalLogRight(u8);
bool8 MetatileBehaviour_IsPacifidlogLog(u8);
bool8 MetatileBehaviour_IsTrickHousePuzzleDoor(u8);
bool8 MetatileBehaviour_IsRegionMap(u8);
bool8 MetatileBehaviour_IsClosedSootopolisDoor(u8);
bool8 MetatileBehaviour_IsSkyPillarClosedDoor(u8);
bool8 MetatileBehaviour_IsRoulette(u8);
bool8 MetatileBehaviour_IsPokeblockFeeder(u8);
bool8 MetatileBehaviour_IsSecretBaseJumpMat(u8);
bool8 MetatileBehaviour_IsSecretBaseSpinMat(u8);
bool8 MetatileBehaviour_IsLavaridgeB1FWarp(u8);
bool8 MetatileBehaviour_IsLavaridge1FWarp(u8);
bool8 MetatileBehaviour_IsAquaHideoutWarp(u8);
bool8 MetatileBehaviour_IsUnionRoomWarp(u8);
bool8 MetatileBehaviour_IsMossdeepGymWarp(u8);
bool8 MetatileBehaviour_IsSurfableFishableWater(u8);
bool8 MetatileBehaviour_IsMtPyreHole(u8);
bool8 MetatileBehaviour_IsCrackedFloorHole(u8);
bool8 MetatileBehaviour_IsCrackedFloor(u8);
bool8 MetatileBehaviour_IsMuddySlope(u8);
bool8 MetatileBehaviour_IsBumpySlope(u8);
bool8 MetatileBehaviour_IsIsolatedVerticalRail(u8);
bool8 MetatileBehaviour_IsIsolatedHorizontalRail(u8);
bool8 MetatileBehaviour_IsVerticalRail(u8);
bool8 MetatileBehaviour_IsHorizontalRail(u8);
bool8 MetatileBehaviour_IsSeaweed(u8);
bool8 MetatileBehaviour_IsRunningDisallowed(u8);
bool8 MetatileBehaviour_IsCuttableGrass(u8);
bool8 MetatileBehaviour_IsRunningShoesManual(u8);
bool8 MetatileBehaviour_IsPictureBookShelf(u8);
bool8 MetatileBehaviour_IsBookShelf(u8);
bool8 MetatileBehaviour_IsPokeCentreBookShelf(u8);
bool8 MetatileBehaviour_IsVase(u8);
bool8 MetatileBehaviour_IsTrashCan(u8);
bool8 MetatileBehaviour_IsShopShelf(u8);
bool8 MetatileBehaviour_IsBlueprint(u8);
bool8 MetatileBehaviour_IsBattlePyramidWarp(u8);
bool8 MetatileBehaviour_IsPlayerFacingWirelessBoxResults(u8 tile, u8 playerDir);
bool8 MetatileBehaviour_IsCableBoxResults2(u8 tile, u8 playerDir);
bool8 MetatileBehaviour_IsQuestionnaire(u8);
bool8 MetatileBehaviour_IsLongGrass_Duplicate(u8);
bool8 MetatileBehaviour_IsLongGrassSouthEdge(u8);
bool8 MetatileBehaviour_IsTrainerHillTimer(u8);
bool8 MetatileBehaviour_IsDirectionalUpRightStairWarp(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsDirectionalUpLeftStairWarp(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsDirectionalDownRightStairWarp(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsDirectionalDownLeftStairWarp(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsDirectionalStairWarp(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSignpost(u32);
bool8 MetatileBehaviour_IsPokemonCentreSign(u32);
bool8 MetatileBehaviour_IsPokeMartSign(u32);
bool8 MetatileBehaviour_IsRockStairs(u8);
bool8 MetatileBehaviour_IsSidewaysStairsRightSide(u8);
bool8 MetatileBehaviour_IsSidewaysStairsLeftSide(u8);
bool8 MetatileBehaviour_IsSidewaysStairsRightSideTop(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSidewaysStairsLeftSideTop(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSidewaysStairsRightSideBottom(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSidewaysStairsLeftSideBottom(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSidewaysStairsRightSideAny(u8 metatileBehaviour);
bool8 MetatileBehaviour_IsSidewaysStairsLeftSideAny(u8 metatileBehaviour);

#endif // GUARD_METATILE_BEHAVIOUR_H
