FuchsiaCity_SafariZone_Office_Frlg_MapScripts::
    .byte 0


FuchsiaCity_SafariZone_Office_Frlg_EventScript_Worker1::
    lock
    faceplayer
    msgbox FuchsiaCity_SafariZone_Office_Frlg_Text_Worker1, MSGBOX_DEFAULT
    release
    end


FuchsiaCity_SafariZone_Office_Frlg_EventScript_Worker2::
    lock
    faceplayer
    msgbox FuchsiaCity_SafariZone_Office_Frlg_Text_Worker2, MSGBOX_DEFAULT
    release
    end


FuchsiaCity_SafariZone_Office_Frlg_EventScript_Worker3::
    lock
    faceplayer
    msgbox FuchsiaCity_SafariZone_Office_Frlg_Text_Worker3, MSGBOX_DEFAULT
    release
    end


FuchsiaCity_SafariZone_Office_Frlg_EventScript_Worker4::
    lock
    faceplayer
    msgbox FuchsiaCity_SafariZone_Office_Frlg_Text_Worker4, MSGBOX_DEFAULT
    release
    end


FuchsiaCity_SafariZone_Office_Frlg_Text_Worker1:
    .string "Running a SAFARI ZONE sounds fun\n"
    .string "until you see the paperwork.$"


FuchsiaCity_SafariZone_Office_Frlg_Text_Worker2:
    .string "No, we don't know exactly where\n"
    .string "every POKéMON is at all times.\p"
    .string "They did not receive the schedule.$"


FuchsiaCity_SafariZone_Office_Frlg_Text_Worker3:
    .string "Someone once asked me if the\n"
    .string "KANGASKHAN could babysit.\p"
    .string "...I wish I were joking.$"


FuchsiaCity_SafariZone_Office_Frlg_Text_Worker4:
    .string "The WARDEN calls this place\n"
    .string "organized chaos.\p"
    .string "We mostly focus on “organized.”$"
