#!/usr/bin/env python3
"""Enforce Hoenn Habitat content and image provenance boundaries."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST: Path
TEXT_TARGETS: tuple[Path, Path, Path]
ITEMS: Path
HABITAT_ICON_ROOT: Path
TEMPORARY_FIELDS = (
    "id",
    "repository_path",
    "use_site",
    "owner",
    "provenance",
    "recorded_on",
    "replacement_requirement",
    "release_blocking",
)
RELEASE_FIELDS = (
    "id",
    "item_id",
    "repository_path",
    "icon_symbol",
    "provenance_type",
    "source_record",
    "approval_reference",
)
COPY_RECORD_FIELDS = ("approval_status", "approval_reference", "replacement_reference")
HINT_SPOTS = (
    "Skitty", "Lotad", "Machop", "Vulpix", "Heracross", "Pinsir",
    "FrameTorchic", "FrameTreecko", "FrameMudkip",
)
HINT_STATES = ("Dormant", "Stirring", "Active")
SCRIPT_COPY_SITES = (
    ("HabitatSpot_Text_BoutPrompt", "removed"),
    ("HabitatSpot_Text_BoutStart", "removed"),
    ("HabitatSpot_Text_BoutLost", "removed"),
    ("HabitatSpot_Text_NoBattler", "removed"),
    ("HabitatSpot_Text_OfferRejected", "live"),
    ("HabitatSpot_Text_Befriended", "live"),
    ("HabitatSpot_Text_NothingToPlace", "live"),
    ("HabitatSpot_Text_Placed", "live"),
    ("HabitatSpot_Text_RecruitPrompt", "live"),
    ("HabitatSpot_Text_Recruited", "live"),
    ("HabitatSpot_Text_GroveFull", "live"),
    ("HabitatSpot_Text_CannotCome", "live"),
    ("HabitatSpot_Text_Ambient", "live"),
    ("HabitatSpot_Text_NotASpot", "live"),
)
FALLBACK_COPY_SITE = "src/habitat/spot_interaction.c:sText_NotASpot"
FURNISHINGS = (
    ("hh-campfire-icon", "ITEM_HH_CAMPFIRE", "graphics/items/icons/habitat/campfire.png", "gItemIcon_HH_Campfire"),
    ("hh-potted-plant-icon", "ITEM_HH_POTTED_PLANT", "graphics/items/icons/habitat/potted_plant.png", "gItemIcon_HH_PottedPlant"),
    ("hh-water-basin-icon", "ITEM_HH_WATER_BASIN", "graphics/items/icons/habitat/water_basin.png", "gItemIcon_HH_WaterBasin"),
    ("hh-lab-pc-icon", "ITEM_HH_LAB_PC", "graphics/items/icons/habitat/lab_pc.png", "gItemIcon_HH_LabPc"),
    ("hh-bookshelf-icon", "ITEM_HH_BOOKSHELF", "graphics/items/icons/habitat/bookshelf.png", "gItemIcon_HH_Bookshelf"),
    ("hh-ball-holder-icon", "ITEM_HH_POKEBALL_HOLDER", "graphics/items/icons/habitat/ball_holder.png", "gItemIcon_HH_BallHolder"),
)
FORBIDDEN_DELIVERABLE_PATTERNS = (
    re.compile(r"\b(?:ChatGPT|Claude|Gemini|OpenAI|Anthropic)\b", re.IGNORECASE),
    re.compile(r"\bgenerated by\b", re.IGNORECASE),
    re.compile(r"\bagent[- ](?:workflow|process)\b", re.IGNORECASE),
)


def configure_root(root: Path) -> None:
    global ROOT, MANIFEST, TEXT_TARGETS, ITEMS, HABITAT_ICON_ROOT
    ROOT = root.resolve()
    MANIFEST = ROOT / "docs/assets/placeholder-assets.json"
    TEXT_TARGETS = (
        ROOT / "src/habitat/spot_data.c",
        ROOT / "src/habitat/spot_interaction.c",
        ROOT / "data/scripts/habitat_spot.inc",
    )
    ITEMS = ROOT / "src/data/items.h"
    HABITAT_ICON_ROOT = ROOT / "graphics/items/icons/habitat"


configure_root(ROOT)


def report_player_facing_temporary_text() -> list[str]:
    errors: list[str] = []
    spot_data = TEXT_TARGETS[0].read_text(encoding="utf-8")
    if "PLACEHOLDER" in spot_data:
        hint_invocations = re.findall(r"^PLACEHOLDER_HINTS\([A-Za-z0-9_]+\);$", spot_data, re.MULTILINE)
        if hint_invocations:
            errors.append(
                "player-facing temporary text: "
                f"{len(hint_invocations) * 3} Habitat hint strings in src/habitat/spot_data.c"
            )
        in_hint_macro = False
        for number, line in enumerate(spot_data.splitlines(), start=1):
            if line.startswith("#define PLACEHOLDER_HINTS"):
                in_hint_macro = True
            if not in_hint_macro and "PLACEHOLDER" in line and "_(\"" in line:
                errors.append(f"player-facing temporary text: src/habitat/spot_data.c:{number}")
            if in_hint_macro and not line.endswith("\\"):
                in_hint_macro = False

    for path in TEXT_TARGETS[1:]:
        for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if "PLACEHOLDER" not in line:
                continue
            if "_(\"" in line or ".string" in line:
                errors.append(f"player-facing temporary text: {path.relative_to(ROOT)}:{number}")
    return errors


def report_question_mark_furnishings() -> list[str]:
    text = ITEMS.read_text(encoding="utf-8")
    errors: list[str] = []
    for match in re.finditer(r"^    \[(ITEM_HH_[A-Z_]+)\] =\n    \{(.*?)(?=^    \[|\n\};)", text, re.MULTILINE | re.DOTALL):
        if "gItemIcon_QuestionMark" in match.group(2):
            errors.append(f"temporary furnishing icon: {match.group(1)} uses gItemIcon_QuestionMark")
    return errors


def expected_copy_sites() -> dict[str, str]:
    sites = {
        f"src/habitat/spot_data.c:sHint{state}_{spot}": "live"
        for spot in HINT_SPOTS
        for state in HINT_STATES
    }
    sites.update({f"data/scripts/habitat_spot.inc:{symbol}": status for symbol, status in SCRIPT_COPY_SITES})
    sites[FALLBACK_COPY_SITE] = "live"
    return sites


def copy_source_text(site: str) -> str | None:
    path_text, symbol = site.split(":", 1)
    path = ROOT / path_text
    text = path.read_text(encoding="utf-8")
    if path_text == "src/habitat/spot_data.c":
        match = re.search(r"#define PLACEHOLDER_HINTS.*?(?=\n\nPLACEHOLDER_HINTS)", text, re.DOTALL)
        return match.group(0) if match else None
    if path_text == "data/scripts/habitat_spot.inc":
        match = re.search(
            rf"^{re.escape(symbol)}:\n((?:\t\.string .*\n)+)", text, re.MULTILINE
        )
        return match.group(1) if match else None
    match = re.search(
        rf"static const u8 {re.escape(symbol)}\[\] = _\((.*?);\n",
        text,
        re.DOTALL,
    )
    return match.group(0) if match else None


def validate_copy_records(data: dict[str, object]) -> list[str]:
    errors: list[str] = []
    records = data.get("copy_records")
    if not isinstance(records, dict):
        return ["placeholder asset manifest: copy_records must be an object keyed by source use-site"]
    expected = expected_copy_sites()
    actual = set(records)
    if actual != set(expected):
        missing = sorted(set(expected) - actual)
        unexpected = sorted(actual - set(expected))
        if missing:
            errors.append(f"placeholder asset manifest: missing copy records: {', '.join(missing)}")
        if unexpected:
            errors.append(f"placeholder asset manifest: unexpected copy records: {', '.join(unexpected)}")
    for site, expected_status in expected.items():
        record = records.get(site)
        if not isinstance(record, dict):
            continue
        missing = [field for field in COPY_RECORD_FIELDS if not record.get(field)]
        if missing:
            errors.append(f"copy record {site}: missing required fields: {', '.join(missing)}")
            continue
        status = record["approval_status"]
        source = copy_source_text(site)
        if status not in ("pending", "approved", "removed"):
            errors.append(f"copy record {site}: approval_status must be pending, approved, or removed")
            continue
        if expected_status == "removed" and status != "removed":
            errors.append(f"copy record {site}: expected approval_status 'removed', got {status!r}")
            continue
        if expected_status == "live" and status == "removed":
            errors.append(f"copy record {site}: a live use-site cannot be marked removed")
            continue
        if status == "removed":
            if source is not None:
                errors.append(f"removed copy record has live source text: {site}")
            continue
        if source is None:
            errors.append(f"copy record source is missing: {site}")
            continue
        if status == "pending":
            if "PLACEHOLDER" not in source:
                errors.append(f"pending copy record has non-temporary source text: {site}")
            else:
                errors.append(f"copy record awaits narrative approval: {site}")
            continue
        approval = ROOT / str(record["approval_reference"])
        if not is_reviewable_file(approval):
            errors.append(f"approved copy record lacks reviewable approval reference: {site}")
            continue
        expected_hash = record.get("approved_text_sha256")
        actual_hash = hashlib.sha256(source.encode("utf-8")).hexdigest()
        if expected_hash != actual_hash:
            errors.append(f"approved copy record content hash does not match source: {site}")
    return errors


def read_manifest() -> tuple[dict[str, object] | None, list[str]]:
    if not MANIFEST.is_file():
        return None, ["missing docs/assets/placeholder-assets.json"]
    try:
        data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        return None, [f"invalid placeholder asset manifest: {error}"]
    if not isinstance(data, dict):
        return None, ["placeholder asset manifest must be a JSON object"]
    return data, []


def is_reviewable_file(path: Path) -> bool:
    return path.is_file() and bool(path.read_text(encoding="utf-8", errors="replace").strip())


def validate_manifest(mode: str) -> list[str]:
    data, errors = read_manifest()
    if data is None:
        return errors
    temporary_assets = data.get("temporary_assets")
    release_assets = data.get("release_assets")
    if not isinstance(temporary_assets, list):
        errors.append("placeholder asset manifest: temporary_assets must be a list")
        temporary_assets = []
    if not isinstance(release_assets, list):
        errors.append("placeholder asset manifest: release_assets must be a list")
        release_assets = []

    required_assets = data.get("required_furnishing_assets")
    if not isinstance(required_assets, list):
        errors.append("placeholder asset manifest: required_furnishing_assets must be a list")
        required_assets = []
    expected_required = {item_id: (asset_id, path, icon_symbol) for asset_id, item_id, path, icon_symbol in FURNISHINGS}
    required_by_item: dict[str, dict[str, object]] = {}
    for index, asset in enumerate(required_assets):
        label = f"placeholder asset manifest: required_furnishing_assets[{index}]"
        if not isinstance(asset, dict):
            errors.append(f"{label} must be an object")
            continue
        item_id = str(asset.get("item_id", ""))
        required_by_item[item_id] = asset
        expected_asset = expected_required.get(item_id)
        if expected_asset is None:
            errors.append(f"{label} has an unexpected item_id {item_id!r}")
            continue
        asset_id, path, icon_symbol = expected_asset
        if asset.get("id") != asset_id or asset.get("repository_path") != path or asset.get("icon_symbol") != icon_symbol:
            errors.append(f"{label} must bind {item_id} to exact id, path, and icon symbol")
        if asset.get("accepted_provenance_types") != ["commissioned", "hand_made"]:
            errors.append(f"{label} must require commissioned or hand_made provenance")
        if not asset.get("source_record_requirement") or not asset.get("approval_reference_requirement"):
            errors.append(f"{label} must require source and approval records")
    for item_id in expected_required:
        if item_id not in required_by_item:
            errors.append(f"missing required furnishing asset record: {item_id}")

    seen_ids: set[str] = set()
    temporary_paths: set[str] = set()
    temporary_by_item: dict[str, dict[str, object]] = {}
    for index, asset in enumerate(temporary_assets):
        label = f"placeholder asset manifest: temporary_assets[{index}]"
        if not isinstance(asset, dict):
            errors.append(f"{label} must be an object")
            continue
        missing = [field for field in TEMPORARY_FIELDS if field not in asset or not asset[field]]
        if missing:
            errors.append(f"{label} missing required fields: {', '.join(missing)}")
            continue
        if asset["id"] in seen_ids:
            errors.append(f"{label} duplicates temporary asset id {asset['id']!r}")
        seen_ids.add(str(asset["id"]))
        if asset["release_blocking"] is not True:
            errors.append(f"{label} must be release_blocking: true")
        try:
            str(asset["recorded_on"])
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(asset["recorded_on"])):
                raise ValueError
        except ValueError:
            errors.append(f"{label} recorded_on must use YYYY-MM-DD")
        repository_path = str(asset["repository_path"])
        temporary_paths.add(repository_path)
        use_site = str(asset["use_site"])
        if use_site.startswith("src/data/items.h:"):
            temporary_by_item[use_site.rsplit(":", 1)[1]] = asset
        if not (ROOT / repository_path).is_file():
            errors.append(f"{label} repository_path is not a file: {repository_path}")

    release_paths: set[str] = set()
    release_by_item: dict[str, dict[str, object]] = {}
    for index, asset in enumerate(release_assets):
        label = f"placeholder asset manifest: release_assets[{index}]"
        if not isinstance(asset, dict):
            errors.append(f"{label} must be an object")
            continue
        release_by_item[str(asset["item_id"])] = asset
        missing = [field for field in RELEASE_FIELDS if field not in asset or not asset[field]]
        if missing:
            errors.append(f"{label} missing required fields: {', '.join(missing)}")
            continue
        if asset["provenance_type"] not in ("commissioned", "hand_made"):
            errors.append(f"{label} provenance_type must be commissioned or hand_made")
        repository_path = str(asset["repository_path"])
        release_paths.add(repository_path)
        if not (ROOT / repository_path).is_file():
            errors.append(f"{label} repository_path is not a file: {repository_path}")
        if not is_reviewable_file(ROOT / str(asset["source_record"])):
            errors.append(f"{label} source_record must be a nonempty reviewable file: {asset['source_record']}")
        if not is_reviewable_file(ROOT / str(asset["approval_reference"])):
            errors.append(f"{label} approval_reference must be a nonempty reviewable file: {asset['approval_reference']}")

    habitat_icons = set()
    if HABITAT_ICON_ROOT.is_dir():
        habitat_icons = {
            path.relative_to(ROOT).as_posix()
            for path in HABITAT_ICON_ROOT.rglob("*")
            if path.is_file()
        }
    unrecorded = habitat_icons - temporary_paths - release_paths
    for path in sorted(unrecorded):
        errors.append(f"unmanifested habitat image: {path}")
    if mode == "release" and temporary_assets:
        errors.append("temporary asset manifest is not empty; release requires every temporary asset to be replaced")
    item_text = ITEMS.read_text(encoding="utf-8")
    for item_id, (asset_id, path, icon_symbol) in expected_required.items():
        match = re.search(
            rf"^    \[{re.escape(item_id)}\] =\n    \{{(.*?)(?=^    \[|\n\}};)",
            item_text,
            re.MULTILINE | re.DOTALL,
        )
        icon_match = re.search(r"\.iconPic = ([A-Za-z0-9_]+)", match.group(1)) if match else None
        actual_icon = icon_match.group(1) if icon_match else None
        temporary_asset = temporary_by_item.get(item_id)
        if actual_icon == "gItemIcon_QuestionMark":
            if (
                temporary_asset is None
                or temporary_asset.get("id") != asset_id
                or temporary_asset.get("repository_path") != "graphics/items/icons/question_mark.png"
            ):
                errors.append(f"temporary furnishing icon lacks exact manifest record: {item_id}")
        else:
            release_asset = release_by_item.get(item_id)
            if (
                release_asset is None
                or release_asset.get("id") != asset_id
                or release_asset.get("repository_path") != path
                or release_asset.get("icon_symbol") != icon_symbol
                or actual_icon != icon_symbol
            ):
                errors.append(
                    f"furnishing item lacks manifested temporary or approved release record: {item_id}"
                )
            elif (
                release_asset.get("source_record") != required_by_item[item_id].get("source_record_requirement")
                or release_asset.get("approval_reference") != required_by_item[item_id].get("approval_reference_requirement")
            ):
                errors.append(f"furnishing release record must use required source and approval references: {item_id}")
    if mode == "release":
        for item_id, (asset_id, path, icon_symbol) in expected_required.items():
            release_asset = release_by_item.get(item_id)
            if release_asset is None:
                errors.append(f"missing required furnishing release record: {item_id}")
            elif (
                release_asset.get("id") != asset_id
                or release_asset.get("repository_path") != path
                or release_asset.get("icon_symbol") != icon_symbol
            ):
                errors.append(f"furnishing release record must exactly match required asset: {item_id}")
            match = re.search(
                rf"^    \[{re.escape(item_id)}\] =\n    \{{(.*?)(?=^    \[|\n\}};)",
                item_text,
                re.MULTILINE | re.DOTALL,
            )
            if match is None or icon_symbol not in match.group(1):
                errors.append(f"furnishing item does not use required approved icon symbol: {item_id}")
    return errors


def report_forbidden_deliverable_markers() -> list[str]:
    errors: list[str] = []
    candidates: list[Path] = []
    for directory in (ROOT / "Story", ROOT / "docs/content", ROOT / "docs/assets"):
        if directory.is_dir():
            candidates.extend(path for path in directory.rglob("*") if path.is_file())
    candidates.extend(TEXT_TARGETS)
    candidates.append(ITEMS)
    for path in candidates:
        text = path.read_text(encoding="utf-8", errors="replace")
        for pattern in FORBIDDEN_DELIVERABLE_PATTERNS:
            match = pattern.search(text)
            if match:
                errors.append(
                    f"forbidden deliverable marker: {path.relative_to(ROOT)}: {match.group(0)!r}"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--development", action="store_true")
    mode.add_argument("--release", action="store_true")
    args = parser.parse_args()
    configure_root(args.root)
    selected_mode = "development" if args.development else "release"
    manifest, manifest_errors = read_manifest()
    errors = (
        report_player_facing_temporary_text()
        + report_question_mark_furnishings()
        + manifest_errors
        + (validate_copy_records(manifest) if manifest is not None else [])
        + (validate_manifest(selected_mode) if manifest is not None else [])
        + report_forbidden_deliverable_markers()
    )
    if errors:
        for error in errors:
            print(f"validate_provenance: {error}", file=sys.stderr)
        return 1
    print(f"validate_provenance: {selected_mode} provenance gate passes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
