/* Autogenerated FRLG classic egg move learnsets for S30.
 * Source: tools/learnset_helpers/porymoves_files/frlg.json
 * 389 species. Sorted by species id for binary search.
 * Regenerate: python3 tools/mf/gen_classic_movepools.py
 */

static const u16 sMfClassicBulbasaurEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_GRASS_WHISTLE,
    MOVE_LIGHT_SCREEN,
    MOVE_MAGICAL_LEAF,
    MOVE_PETAL_DANCE,
    MOVE_SAFEGUARD,
    MOVE_SKULL_BASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicIvysaurEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_GRASS_WHISTLE,
    MOVE_LIGHT_SCREEN,
    MOVE_MAGICAL_LEAF,
    MOVE_PETAL_DANCE,
    MOVE_SAFEGUARD,
    MOVE_SKULL_BASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVenusaurEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_GRASS_WHISTLE,
    MOVE_LIGHT_SCREEN,
    MOVE_MAGICAL_LEAF,
    MOVE_PETAL_DANCE,
    MOVE_SAFEGUARD,
    MOVE_SKULL_BASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCharmanderEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BEAT_UP,
    MOVE_BELLY_DRUM,
    MOVE_BITE,
    MOVE_DRAGON_DANCE,
    MOVE_OUTRAGE,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCharmeleonEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BEAT_UP,
    MOVE_BELLY_DRUM,
    MOVE_BITE,
    MOVE_DRAGON_DANCE,
    MOVE_OUTRAGE,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCharizardEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BEAT_UP,
    MOVE_BELLY_DRUM,
    MOVE_BITE,
    MOVE_DRAGON_DANCE,
    MOVE_OUTRAGE,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSquirtleEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_FORESIGHT,
    MOVE_HAZE,
    MOVE_MIRROR_COAT,
    MOVE_MIST,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWartortleEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_FORESIGHT,
    MOVE_HAZE,
    MOVE_MIRROR_COAT,
    MOVE_MIST,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBlastoiseEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_FORESIGHT,
    MOVE_HAZE,
    MOVE_MIRROR_COAT,
    MOVE_MIST,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCaterpieEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMetapodEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicButterfreeEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWeedleEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKakunaEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBeedrillEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPidgeyEggMoveLearnset[] = {
    MOVE_AIR_CUTTER,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_PURSUIT,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPidgeottoEggMoveLearnset[] = {
    MOVE_AIR_CUTTER,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_PURSUIT,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPidgeotEggMoveLearnset[] = {
    MOVE_AIR_CUTTER,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_PURSUIT,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRattataEggMoveLearnset[] = {
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_FLAME_WHEEL,
    MOVE_FURY_SWIPES,
    MOVE_REVERSAL,
    MOVE_SCREECH,
    MOVE_SWAGGER,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRaticateEggMoveLearnset[] = {
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_FLAME_WHEEL,
    MOVE_FURY_SWIPES,
    MOVE_REVERSAL,
    MOVE_SCREECH,
    MOVE_SWAGGER,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSpearowEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_FALSE_SWIPE,
    MOVE_FAINT_ATTACK,
    MOVE_QUICK_ATTACK,
    MOVE_SCARY_FACE,
    MOVE_SKY_ATTACK,
    MOVE_TRI_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFearowEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_FALSE_SWIPE,
    MOVE_FAINT_ATTACK,
    MOVE_QUICK_ATTACK,
    MOVE_SCARY_FACE,
    MOVE_SKY_ATTACK,
    MOVE_TRI_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicEkansEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_POISON_FANG,
    MOVE_PURSUIT,
    MOVE_SLAM,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicArbokEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_POISON_FANG,
    MOVE_PURSUIT,
    MOVE_SLAM,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPikachuEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_CHARGE,
    MOVE_DOUBLE_SLAP,
    MOVE_ENCORE,
    MOVE_PRESENT,
    MOVE_REVERSAL,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRaichuEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_CHARGE,
    MOVE_DOUBLE_SLAP,
    MOVE_ENCORE,
    MOVE_PRESENT,
    MOVE_REVERSAL,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSandshrewEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_FLAIL,
    MOVE_METAL_CLAW,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_SAFEGUARD,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSandslashEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_FLAIL,
    MOVE_METAL_CLAW,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_SAFEGUARD,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidoranFEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_CHARM,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_FOCUS_ENERGY,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidorinaEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_CHARM,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_FOCUS_ENERGY,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidoqueenEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_CHARM,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_FOCUS_ENERGY,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidoranMEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BEAT_UP,
    MOVE_CONFUSION,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidorinoEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BEAT_UP,
    MOVE_CONFUSION,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNidokingEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BEAT_UP,
    MOVE_CONFUSION,
    MOVE_COUNTER,
    MOVE_DISABLE,
    MOVE_SUPERSONIC,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicClefairyEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_METRONOME,
    MOVE_MIMIC,
    MOVE_PRESENT,
    MOVE_SPLASH,
    MOVE_SUBSTITUTE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicClefableEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_METRONOME,
    MOVE_MIMIC,
    MOVE_PRESENT,
    MOVE_SPLASH,
    MOVE_SUBSTITUTE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVulpixEggMoveLearnset[] = {
    MOVE_DISABLE,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_HEAT_WAVE,
    MOVE_HOWL,
    MOVE_HYPNOSIS,
    MOVE_PSYCH_UP,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNinetalesEggMoveLearnset[] = {
    MOVE_DISABLE,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_HEAT_WAVE,
    MOVE_HOWL,
    MOVE_HYPNOSIS,
    MOVE_PSYCH_UP,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicJigglypuffEggMoveLearnset[] = {
    MOVE_FAKE_TEARS,
    MOVE_FAINT_ATTACK,
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWigglytuffEggMoveLearnset[] = {
    MOVE_FAKE_TEARS,
    MOVE_FAINT_ATTACK,
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicZubatEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_PURSUIT,
    MOVE_QUICK_ATTACK,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGolbatEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_PURSUIT,
    MOVE_QUICK_ATTACK,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicOddishEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_INGRAIN,
    MOVE_RAZOR_LEAF,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGloomEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_INGRAIN,
    MOVE_RAZOR_LEAF,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVileplumeEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_INGRAIN,
    MOVE_RAZOR_LEAF,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicParasEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_FALSE_SWIPE,
    MOVE_FLAIL,
    MOVE_LIGHT_SCREEN,
    MOVE_PSYBEAM,
    MOVE_PURSUIT,
    MOVE_SCREECH,
    MOVE_SWEET_SCENT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicParasectEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_FALSE_SWIPE,
    MOVE_FLAIL,
    MOVE_LIGHT_SCREEN,
    MOVE_PSYBEAM,
    MOVE_PURSUIT,
    MOVE_SCREECH,
    MOVE_SWEET_SCENT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVenonatEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_GIGA_DRAIN,
    MOVE_SCREECH,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVenomothEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_GIGA_DRAIN,
    MOVE_SCREECH,
    MOVE_SIGNAL_BEAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDiglettEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BEAT_UP,
    MOVE_FAINT_ATTACK,
    MOVE_PURSUIT,
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDugtrioEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BEAT_UP,
    MOVE_FAINT_ATTACK,
    MOVE_PURSUIT,
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMeowthEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_ASSIST,
    MOVE_CHARM,
    MOVE_HYPNOSIS,
    MOVE_PSYCH_UP,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPersianEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_ASSIST,
    MOVE_CHARM,
    MOVE_HYPNOSIS,
    MOVE_PSYCH_UP,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPsyduckEggMoveLearnset[] = {
    MOVE_CROSS_CHOP,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_PSYBEAM,
    MOVE_PSYCHIC,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGolduckEggMoveLearnset[] = {
    MOVE_CROSS_CHOP,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_PSYBEAM,
    MOVE_PSYCHIC,
    MOVE_REFRESH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMankeyEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_COUNTER,
    MOVE_FORESIGHT,
    MOVE_MEDITATE,
    MOVE_REVENGE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPrimeapeEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_COUNTER,
    MOVE_FORESIGHT,
    MOVE_MEDITATE,
    MOVE_REVENGE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGrowlitheEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CRUNCH,
    MOVE_FIRE_SPIN,
    MOVE_HEAT_WAVE,
    MOVE_HOWL,
    MOVE_SAFEGUARD,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicArcanineEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CRUNCH,
    MOVE_FIRE_SPIN,
    MOVE_HEAT_WAVE,
    MOVE_HOWL,
    MOVE_SAFEGUARD,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPoliwagEggMoveLearnset[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ICE_BALL,
    MOVE_MIND_READER,
    MOVE_MIST,
    MOVE_SPLASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPoliwhirlEggMoveLearnset[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ICE_BALL,
    MOVE_MIND_READER,
    MOVE_MIST,
    MOVE_SPLASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPoliwrathEggMoveLearnset[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ICE_BALL,
    MOVE_MIND_READER,
    MOVE_MIST,
    MOVE_SPLASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAbraEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_ENCORE,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_KNOCK_OFF,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKadabraEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_ENCORE,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_KNOCK_OFF,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAlakazamEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_ENCORE,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_KNOCK_OFF,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMachopEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENCORE,
    MOVE_LIGHT_SCREEN,
    MOVE_MEDITATE,
    MOVE_ROCK_SLIDE,
    MOVE_ROLLING_KICK,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMachokeEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENCORE,
    MOVE_LIGHT_SCREEN,
    MOVE_MEDITATE,
    MOVE_ROCK_SLIDE,
    MOVE_ROLLING_KICK,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMachampEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENCORE,
    MOVE_LIGHT_SCREEN,
    MOVE_MEDITATE,
    MOVE_ROCK_SLIDE,
    MOVE_ROLLING_KICK,
    MOVE_SMELLING_SALTS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBellsproutEggMoveLearnset[] = {
    MOVE_ENCORE,
    MOVE_INGRAIN,
    MOVE_LEECH_LIFE,
    MOVE_MAGICAL_LEAF,
    MOVE_REFLECT,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWeepinbellEggMoveLearnset[] = {
    MOVE_ENCORE,
    MOVE_INGRAIN,
    MOVE_LEECH_LIFE,
    MOVE_MAGICAL_LEAF,
    MOVE_REFLECT,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVictreebelEggMoveLearnset[] = {
    MOVE_ENCORE,
    MOVE_INGRAIN,
    MOVE_LEECH_LIFE,
    MOVE_MAGICAL_LEAF,
    MOVE_REFLECT,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTentacoolEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_CONFUSE_RAY,
    MOVE_HAZE,
    MOVE_MIRROR_COAT,
    MOVE_RAPID_SPIN,
    MOVE_SAFEGUARD,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTentacruelEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_CONFUSE_RAY,
    MOVE_HAZE,
    MOVE_MIRROR_COAT,
    MOVE_RAPID_SPIN,
    MOVE_SAFEGUARD,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGeodudeEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_MEGA_PUNCH,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGravelerEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_MEGA_PUNCH,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGolemEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_MEGA_PUNCH,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPonytaEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_DOUBLE_KICK,
    MOVE_FLAME_WHEEL,
    MOVE_HYPNOSIS,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRapidashEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_DOUBLE_EDGE,
    MOVE_DOUBLE_KICK,
    MOVE_FLAME_WHEEL,
    MOVE_HYPNOSIS,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlowpokeEggMoveLearnset[] = {
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_MUD_SPORT,
    MOVE_SAFEGUARD,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlowbroEggMoveLearnset[] = {
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_MUD_SPORT,
    MOVE_SAFEGUARD,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagnemiteEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagnetonEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFarfetchdEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FEATHER_DANCE,
    MOVE_FLAIL,
    MOVE_FORESIGHT,
    MOVE_GUST,
    MOVE_MIRROR_MOVE,
    MOVE_QUICK_ATTACK,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDoduoEggMoveLearnset[] = {
    MOVE_ENDEAVOR,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_QUICK_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDodrioEggMoveLearnset[] = {
    MOVE_ENDEAVOR,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_QUICK_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSeelEggMoveLearnset[] = {
    MOVE_DISABLE,
    MOVE_ENCORE,
    MOVE_FAKE_OUT,
    MOVE_HORN_DRILL,
    MOVE_ICICLE_SPEAR,
    MOVE_LICK,
    MOVE_PERISH_SONG,
    MOVE_SLAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDewgongEggMoveLearnset[] = {
    MOVE_DISABLE,
    MOVE_ENCORE,
    MOVE_FAKE_OUT,
    MOVE_HORN_DRILL,
    MOVE_ICICLE_SPEAR,
    MOVE_LICK,
    MOVE_PERISH_SONG,
    MOVE_SLAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGrimerEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_EXPLOSION,
    MOVE_HAZE,
    MOVE_IMPRISON,
    MOVE_LICK,
    MOVE_MEAN_LOOK,
    MOVE_SHADOW_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMukEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_EXPLOSION,
    MOVE_HAZE,
    MOVE_IMPRISON,
    MOVE_LICK,
    MOVE_MEAN_LOOK,
    MOVE_SHADOW_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShellderEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_BUBBLE_BEAM,
    MOVE_ICICLE_SPEAR,
    MOVE_RAPID_SPIN,
    MOVE_SCREECH,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCloysterEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_BUBBLE_BEAM,
    MOVE_ICICLE_SPEAR,
    MOVE_RAPID_SPIN,
    MOVE_SCREECH,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGastlyEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_EXPLOSION,
    MOVE_GRUDGE,
    MOVE_HAZE,
    MOVE_PERISH_SONG,
    MOVE_PSYWAVE,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHaunterEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_EXPLOSION,
    MOVE_GRUDGE,
    MOVE_HAZE,
    MOVE_PERISH_SONG,
    MOVE_PSYWAVE,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGengarEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_EXPLOSION,
    MOVE_GRUDGE,
    MOVE_HAZE,
    MOVE_PERISH_SONG,
    MOVE_PSYWAVE,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicOnixEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_EXPLOSION,
    MOVE_FLAIL,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDrowzeeEggMoveLearnset[] = {
    MOVE_ASSIST,
    MOVE_BARRIER,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_ROLE_PLAY,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHypnoEggMoveLearnset[] = {
    MOVE_ASSIST,
    MOVE_BARRIER,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_ROLE_PLAY,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKrabbyEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_KNOCK_OFF,
    MOVE_SLAM,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKinglerEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_KNOCK_OFF,
    MOVE_SLAM,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVoltorbEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicElectrodeEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicExeggcuteEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CURSE,
    MOVE_INGRAIN,
    MOVE_MOONLIGHT,
    MOVE_PSYCH_UP,
    MOVE_REFLECT,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicExeggutorEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CURSE,
    MOVE_INGRAIN,
    MOVE_MOONLIGHT,
    MOVE_PSYCH_UP,
    MOVE_REFLECT,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCuboneEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BELLY_DRUM,
    MOVE_PERISH_SONG,
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_SKULL_BASH,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMarowakEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BELLY_DRUM,
    MOVE_PERISH_SONG,
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_SKULL_BASH,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHitmonleeEggMoveLearnset[] = {
    MOVE_HELPING_HAND,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHitmonchanEggMoveLearnset[] = {
    MOVE_HELPING_HAND,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLickitungEggMoveLearnset[] = {
    MOVE_BELLY_DRUM,
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_MAGNITUDE,
    MOVE_SLEEP_TALK,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKoffingEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_PSYBEAM,
    MOVE_PSYWAVE,
    MOVE_SCREECH,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWeezingEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_PAIN_SPLIT,
    MOVE_PSYBEAM,
    MOVE_PSYWAVE,
    MOVE_SCREECH,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRhyhornEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_MAGNITUDE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRhydonEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_MAGNITUDE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicChanseyEggMoveLearnset[] = {
    MOVE_AROMATHERAPY,
    MOVE_HEAL_BELL,
    MOVE_METRONOME,
    MOVE_PRESENT,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTangelaEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_FLAIL,
    MOVE_LEECH_SEED,
    MOVE_MEGA_DRAIN,
    MOVE_NATURE_POWER,
    MOVE_REFLECT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKangaskhanEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_DISABLE,
    MOVE_FOCUS_ENERGY,
    MOVE_FORESIGHT,
    MOVE_SAFEGUARD,
    MOVE_STOMP,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHorseaEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_DISABLE,
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_RAGE,
    MOVE_FLAIL,
    MOVE_OCTAZOOKA,
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSeadraEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_DISABLE,
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_RAGE,
    MOVE_FLAIL,
    MOVE_OCTAZOOKA,
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGoldeenEggMoveLearnset[] = {
    MOVE_HAZE,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_PSYBEAM,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSeakingEggMoveLearnset[] = {
    MOVE_HAZE,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_PSYBEAM,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicStaryuEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicStarmieEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMrMimeEggMoveLearnset[] = {
    MOVE_FAKE_OUT,
    MOVE_FUTURE_SIGHT,
    MOVE_HYPNOSIS,
    MOVE_MIMIC,
    MOVE_PSYCH_UP,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicScytherEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_COUNTER,
    MOVE_ENDURE,
    MOVE_LIGHT_SCREEN,
    MOVE_RAZOR_WIND,
    MOVE_REVERSAL,
    MOVE_SAFEGUARD,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicJynxEggMoveLearnset[] = {
    MOVE_FAKE_OUT,
    MOVE_ICE_PUNCH,
    MOVE_MEDITATE,
    MOVE_PSYCH_UP,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicElectabuzzEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_CROSS_CHOP,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_KARATE_CHOP,
    MOVE_MEDITATE,
    MOVE_ROLLING_KICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagmarEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_CROSS_CHOP,
    MOVE_KARATE_CHOP,
    MOVE_MEGA_PUNCH,
    MOVE_SCREECH,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPinsirEggMoveLearnset[] = {
    MOVE_FALSE_SWIPE,
    MOVE_FAINT_ATTACK,
    MOVE_FLAIL,
    MOVE_FURY_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTaurosEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagikarpEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGyaradosEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLaprasEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DRAGON_DANCE,
    MOVE_FORESIGHT,
    MOVE_HORN_DRILL,
    MOVE_REFRESH,
    MOVE_SLEEP_TALK,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDittoEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicEeveeEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVaporeonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicJolteonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFlareonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPorygonEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicOmanyteEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ROCK_SLIDE,
    MOVE_SLAM,
    MOVE_SPIKES,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicOmastarEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ROCK_SLIDE,
    MOVE_SLAM,
    MOVE_SPIKES,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKabutoEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_BUBBLE_BEAM,
    MOVE_CONFUSE_RAY,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_KNOCK_OFF,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKabutopsEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_BUBBLE_BEAM,
    MOVE_CONFUSE_RAY,
    MOVE_DIG,
    MOVE_FLAIL,
    MOVE_KNOCK_OFF,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAerodactylEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DRAGON_BREATH,
    MOVE_FORESIGHT,
    MOVE_PURSUIT,
    MOVE_STEEL_WING,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSnorlaxEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_DOUBLE_EDGE,
    MOVE_FISSURE,
    MOVE_LICK,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicArticunoEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicZapdosEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMoltresEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDratiniEggMoveLearnset[] = {
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_DANCE,
    MOVE_HAZE,
    MOVE_LIGHT_SCREEN,
    MOVE_MIST,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDragonairEggMoveLearnset[] = {
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_DANCE,
    MOVE_HAZE,
    MOVE_LIGHT_SCREEN,
    MOVE_MIST,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDragoniteEggMoveLearnset[] = {
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_DANCE,
    MOVE_HAZE,
    MOVE_LIGHT_SCREEN,
    MOVE_MIST,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMewtwoEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMewEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicChikoritaEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_GRASS_WHISTLE,
    MOVE_INGRAIN,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_VINE_WHIP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBayleefEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_GRASS_WHISTLE,
    MOVE_INGRAIN,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_VINE_WHIP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMeganiumEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_GRASS_WHISTLE,
    MOVE_INGRAIN,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_VINE_WHIP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCyndaquilEggMoveLearnset[] = {
    MOVE_COVET,
    MOVE_CRUSH_CLAW,
    MOVE_FORESIGHT,
    MOVE_FURY_SWIPES,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_REVERSAL,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicQuilavaEggMoveLearnset[] = {
    MOVE_COVET,
    MOVE_CRUSH_CLAW,
    MOVE_FORESIGHT,
    MOVE_FURY_SWIPES,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_REVERSAL,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTyphlosionEggMoveLearnset[] = {
    MOVE_COVET,
    MOVE_CRUSH_CLAW,
    MOVE_FORESIGHT,
    MOVE_FURY_SWIPES,
    MOVE_HOWL,
    MOVE_QUICK_ATTACK,
    MOVE_REVERSAL,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTotodileEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CRUNCH,
    MOVE_DRAGON_CLAW,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_THRASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCroconawEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CRUNCH,
    MOVE_DRAGON_CLAW,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_THRASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFeraligatrEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CRUNCH,
    MOVE_DRAGON_CLAW,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_THRASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSentretEggMoveLearnset[] = {
    MOVE_ASSIST,
    MOVE_DOUBLE_EDGE,
    MOVE_FOCUS_ENERGY,
    MOVE_PURSUIT,
    MOVE_REVERSAL,
    MOVE_SLASH,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFurretEggMoveLearnset[] = {
    MOVE_ASSIST,
    MOVE_DOUBLE_EDGE,
    MOVE_FOCUS_ENERGY,
    MOVE_PURSUIT,
    MOVE_REVERSAL,
    MOVE_SLASH,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHoothootEggMoveLearnset[] = {
    MOVE_FEATHER_DANCE,
    MOVE_FAINT_ATTACK,
    MOVE_MIRROR_MOVE,
    MOVE_SKY_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_WHIRLWIND,
    MOVE_WING_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNoctowlEggMoveLearnset[] = {
    MOVE_FEATHER_DANCE,
    MOVE_FAINT_ATTACK,
    MOVE_MIRROR_MOVE,
    MOVE_SKY_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_WHIRLWIND,
    MOVE_WING_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLedybaEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_PSYBEAM,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLedianEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_PSYBEAM,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSpinarakEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_DISABLE,
    MOVE_PSYBEAM,
    MOVE_PURSUIT,
    MOVE_SIGNAL_BEAM,
    MOVE_SONIC_BOOM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAriadosEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_DISABLE,
    MOVE_PSYBEAM,
    MOVE_PURSUIT,
    MOVE_SIGNAL_BEAM,
    MOVE_SONIC_BOOM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCrobatEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_PURSUIT,
    MOVE_QUICK_ATTACK,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicChinchouEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_FLAIL,
    MOVE_SCREECH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLanturnEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_FLAIL,
    MOVE_SCREECH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPichuEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_CHARGE,
    MOVE_DOUBLE_SLAP,
    MOVE_ENCORE,
    MOVE_PRESENT,
    MOVE_REVERSAL,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCleffaEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_METRONOME,
    MOVE_MIMIC,
    MOVE_PRESENT,
    MOVE_SPLASH,
    MOVE_SUBSTITUTE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicIgglybuffEggMoveLearnset[] = {
    MOVE_FAKE_TEARS,
    MOVE_FAINT_ATTACK,
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTogepiEggMoveLearnset[] = {
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_MIRROR_MOVE,
    MOVE_PECK,
    MOVE_PRESENT,
    MOVE_PSYCH_UP,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTogeticEggMoveLearnset[] = {
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_MIRROR_MOVE,
    MOVE_PECK,
    MOVE_PRESENT,
    MOVE_PSYCH_UP,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNatuEggMoveLearnset[] = {
    MOVE_DRILL_PECK,
    MOVE_FEATHER_DANCE,
    MOVE_FAINT_ATTACK,
    MOVE_HAZE,
    MOVE_PSYCH_UP,
    MOVE_QUICK_ATTACK,
    MOVE_REFRESH,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicXatuEggMoveLearnset[] = {
    MOVE_DRILL_PECK,
    MOVE_FEATHER_DANCE,
    MOVE_FAINT_ATTACK,
    MOVE_HAZE,
    MOVE_PSYCH_UP,
    MOVE_QUICK_ATTACK,
    MOVE_REFRESH,
    MOVE_STEEL_WING,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMareepEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CHARGE,
    MOVE_ODOR_SLEUTH,
    MOVE_REFLECT,
    MOVE_SAFEGUARD,
    MOVE_SCREECH,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFlaaffyEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CHARGE,
    MOVE_ODOR_SLEUTH,
    MOVE_REFLECT,
    MOVE_SAFEGUARD,
    MOVE_SCREECH,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAmpharosEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CHARGE,
    MOVE_ODOR_SLEUTH,
    MOVE_REFLECT,
    MOVE_SAFEGUARD,
    MOVE_SCREECH,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBellossomEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FLAIL,
    MOVE_INGRAIN,
    MOVE_RAZOR_LEAF,
    MOVE_SWORDS_DANCE,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMarillEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_LIGHT_SCREEN,
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_SUBSTITUTE,
    MOVE_SUPERSONIC,
    MOVE_ENCORE,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SLAM,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAzumarillEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BELLY_DRUM,
    MOVE_ENCORE,
    MOVE_FUTURE_SIGHT,
    MOVE_LIGHT_SCREEN,
    MOVE_PERISH_SONG,
    MOVE_PRESENT,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SLAM,
    MOVE_SUBSTITUTE,
    MOVE_SUPERSONIC,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSudowoodoEggMoveLearnset[] = {
    MOVE_SELF_DESTRUCT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPolitoedEggMoveLearnset[] = {
    MOVE_BUBBLE_BEAM,
    MOVE_HAZE,
    MOVE_ICE_BALL,
    MOVE_MIND_READER,
    MOVE_MIST,
    MOVE_SPLASH,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHoppipEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_DOUBLE_EDGE,
    MOVE_ENCORE,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_REFLECT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSkiploomEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_DOUBLE_EDGE,
    MOVE_ENCORE,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_REFLECT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicJumpluffEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_CONFUSION,
    MOVE_DOUBLE_EDGE,
    MOVE_ENCORE,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_REFLECT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAipomEggMoveLearnset[] = {
    MOVE_AGILITY,
    MOVE_BEAT_UP,
    MOVE_COUNTER,
    MOVE_DOUBLE_SLAP,
    MOVE_PURSUIT,
    MOVE_SCREECH,
    MOVE_SLAM,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSunkernEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ENCORE,
    MOVE_GRASS_WHISTLE,
    MOVE_HELPING_HAND,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSunfloraEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ENCORE,
    MOVE_GRASS_WHISTLE,
    MOVE_HELPING_HAND,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicYanmaEggMoveLearnset[] = {
    MOVE_LEECH_LIFE,
    MOVE_REVERSAL,
    MOVE_SIGNAL_BEAM,
    MOVE_SILVER_WIND,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWooperEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_MUD_SPORT,
    MOVE_SAFEGUARD,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicQuagsireEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_CURSE,
    MOVE_MUD_SPORT,
    MOVE_SAFEGUARD,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicEspeonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicUmbreonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_FLAIL,
    MOVE_TICKLE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMurkrowEggMoveLearnset[] = {
    MOVE_CONFUSE_RAY,
    MOVE_DRILL_PECK,
    MOVE_FEATHER_DANCE,
    MOVE_MIRROR_MOVE,
    MOVE_PERISH_SONG,
    MOVE_SKY_ATTACK,
    MOVE_WHIRLWIND,
    MOVE_WING_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlowkingEggMoveLearnset[] = {
    MOVE_BELLY_DRUM,
    MOVE_FUTURE_SIGHT,
    MOVE_MUD_SPORT,
    MOVE_SAFEGUARD,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMisdreavusEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_IMPRISON,
    MOVE_PSYCH_UP,
    MOVE_SCREECH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicUnownEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWobbuffetEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGirafarigEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BEAT_UP,
    MOVE_FORESIGHT,
    MOVE_FUTURE_SIGHT,
    MOVE_MAGIC_COAT,
    MOVE_PSYCH_UP,
    MOVE_TAKE_DOWN,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPinecoEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_PIN_MISSILE,
    MOVE_REFLECT,
    MOVE_SAND_TOMB,
    MOVE_SWIFT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicForretressEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_FLAIL,
    MOVE_PIN_MISSILE,
    MOVE_REFLECT,
    MOVE_SAND_TOMB,
    MOVE_SWIFT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDunsparceEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_ASTONISH,
    MOVE_BIDE,
    MOVE_BITE,
    MOVE_CURSE,
    MOVE_HEADBUTT,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGligarEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_METAL_CLAW,
    MOVE_RAZOR_WIND,
    MOVE_SAND_TOMB,
    MOVE_WING_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSteelixEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_EXPLOSION,
    MOVE_FLAIL,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSnubbullEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_FAINT_ATTACK,
    MOVE_HEAL_BELL,
    MOVE_METRONOME,
    MOVE_PRESENT,
    MOVE_REFLECT,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGranbullEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_FAINT_ATTACK,
    MOVE_HEAL_BELL,
    MOVE_METRONOME,
    MOVE_PRESENT,
    MOVE_REFLECT,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicQwilfishEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_BUBBLE_BEAM,
    MOVE_FLAIL,
    MOVE_HAZE,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicScizorEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_COUNTER,
    MOVE_ENDURE,
    MOVE_LIGHT_SCREEN,
    MOVE_RAZOR_WIND,
    MOVE_REVERSAL,
    MOVE_SAFEGUARD,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShuckleEggMoveLearnset[] = {
    MOVE_SWEET_SCENT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHeracrossEggMoveLearnset[] = {
    MOVE_BIDE,
    MOVE_FALSE_SWIPE,
    MOVE_FLAIL,
    MOVE_HARDEN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSneaselEggMoveLearnset[] = {
    MOVE_BITE,
    MOVE_COUNTER,
    MOVE_CRUSH_CLAW,
    MOVE_FAKE_OUT,
    MOVE_FORESIGHT,
    MOVE_REFLECT,
    MOVE_SPITE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTeddiursaEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_FAKE_TEARS,
    MOVE_METAL_CLAW,
    MOVE_SEISMIC_TOSS,
    MOVE_SLEEP_TALK,
    MOVE_TAKE_DOWN,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicUrsaringEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CRUNCH,
    MOVE_FAKE_TEARS,
    MOVE_METAL_CLAW,
    MOVE_SEISMIC_TOSS,
    MOVE_SLEEP_TALK,
    MOVE_TAKE_DOWN,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlugmaEggMoveLearnset[] = {
    MOVE_ACID_ARMOR,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagcargoEggMoveLearnset[] = {
    MOVE_ACID_ARMOR,
    MOVE_HEAT_WAVE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSwinubEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BITE,
    MOVE_BODY_SLAM,
    MOVE_DOUBLE_EDGE,
    MOVE_ICICLE_SPEAR,
    MOVE_MUD_SHOT,
    MOVE_ROCK_SLIDE,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPiloswineEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BITE,
    MOVE_BODY_SLAM,
    MOVE_DOUBLE_EDGE,
    MOVE_ICICLE_SPEAR,
    MOVE_MUD_SHOT,
    MOVE_ROCK_SLIDE,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCorsolaEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_BARRIER,
    MOVE_CONFUSE_RAY,
    MOVE_ICICLE_SPEAR,
    MOVE_INGRAIN,
    MOVE_MIST,
    MOVE_ROCK_SLIDE,
    MOVE_SCREECH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRemoraidEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_HAZE,
    MOVE_OCTAZOOKA,
    MOVE_ROCK_BLAST,
    MOVE_SCREECH,
    MOVE_SUPERSONIC,
    MOVE_THUNDER_WAVE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicOctilleryEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_HAZE,
    MOVE_OCTAZOOKA,
    MOVE_ROCK_BLAST,
    MOVE_SCREECH,
    MOVE_SUPERSONIC,
    MOVE_THUNDER_WAVE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDelibirdEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_FUTURE_SIGHT,
    MOVE_ICE_BALL,
    MOVE_QUICK_ATTACK,
    MOVE_RAPID_SPIN,
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMantineEggMoveLearnset[] = {
    MOVE_HAZE,
    MOVE_HYDRO_PUMP,
    MOVE_MUD_SPORT,
    MOVE_ROCK_SLIDE,
    MOVE_SLAM,
    MOVE_TWISTER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSkarmoryEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DRILL_PECK,
    MOVE_PURSUIT,
    MOVE_SKY_ATTACK,
    MOVE_WHIRLWIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHoundourEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_COUNTER,
    MOVE_FIRE_SPIN,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_REVERSAL,
    MOVE_SPITE,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHoundoomEggMoveLearnset[] = {
    MOVE_BEAT_UP,
    MOVE_COUNTER,
    MOVE_FIRE_SPIN,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_REVERSAL,
    MOVE_SPITE,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKingdraEggMoveLearnset[] = {
    MOVE_AURORA_BEAM,
    MOVE_DISABLE,
    MOVE_DRAGON_BREATH,
    MOVE_DRAGON_RAGE,
    MOVE_FLAIL,
    MOVE_OCTAZOOKA,
    MOVE_SPLASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPhanpyEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_COUNTER,
    MOVE_FISSURE,
    MOVE_FOCUS_ENERGY,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDonphanEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_COUNTER,
    MOVE_FISSURE,
    MOVE_FOCUS_ENERGY,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPorygon2EggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicStantlerEggMoveLearnset[] = {
    MOVE_BITE,
    MOVE_DISABLE,
    MOVE_EXTRASENSORY,
    MOVE_PSYCH_UP,
    MOVE_SPITE,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSmeargleEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTyrogueEggMoveLearnset[] = {
    MOVE_HELPING_HAND,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHitmontopEggMoveLearnset[] = {
    MOVE_HELPING_HAND,
    MOVE_HI_JUMP_KICK,
    MOVE_MACH_PUNCH,
    MOVE_MIND_READER,
    MOVE_RAPID_SPIN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSmoochumEggMoveLearnset[] = {
    MOVE_FAKE_OUT,
    MOVE_ICE_PUNCH,
    MOVE_MEDITATE,
    MOVE_PSYCH_UP,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicElekidEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_CROSS_CHOP,
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_KARATE_CHOP,
    MOVE_MEDITATE,
    MOVE_ROLLING_KICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMagbyEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_CROSS_CHOP,
    MOVE_KARATE_CHOP,
    MOVE_MEGA_PUNCH,
    MOVE_SCREECH,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMiltankEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ENDURE,
    MOVE_HELPING_HAND,
    MOVE_PRESENT,
    MOVE_PSYCH_UP,
    MOVE_REVERSAL,
    MOVE_SEISMIC_TOSS,
    MOVE_SLEEP_TALK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBlisseyEggMoveLearnset[] = {
    MOVE_AROMATHERAPY,
    MOVE_HEAL_BELL,
    MOVE_METRONOME,
    MOVE_PRESENT,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRaikouEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicEnteiEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSuicuneEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLarvitarEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CURSE,
    MOVE_DRAGON_DANCE,
    MOVE_FOCUS_ENERGY,
    MOVE_OUTRAGE,
    MOVE_PURSUIT,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPupitarEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CURSE,
    MOVE_DRAGON_DANCE,
    MOVE_FOCUS_ENERGY,
    MOVE_OUTRAGE,
    MOVE_PURSUIT,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTyranitarEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_CURSE,
    MOVE_DRAGON_DANCE,
    MOVE_FOCUS_ENERGY,
    MOVE_OUTRAGE,
    MOVE_PURSUIT,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLugiaEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHoOhEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCelebiEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTreeckoEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_CRUSH_CLAW,
    MOVE_DRAGON_BREATH,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGrovyleEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_CRUSH_CLAW,
    MOVE_DRAGON_BREATH,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSceptileEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_CRUSH_CLAW,
    MOVE_DRAGON_BREATH,
    MOVE_ENDEAVOR,
    MOVE_LEECH_SEED,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTorchicEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENDURE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCombuskenEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENDURE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBlazikenEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_ENDURE,
    MOVE_REVERSAL,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMudkipEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ICE_BALL,
    MOVE_MIRROR_COAT,
    MOVE_REFRESH,
    MOVE_STOMP,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMarshtompEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ICE_BALL,
    MOVE_MIRROR_COAT,
    MOVE_REFRESH,
    MOVE_STOMP,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSwampertEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_ICE_BALL,
    MOVE_MIRROR_COAT,
    MOVE_REFRESH,
    MOVE_STOMP,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPoochyenaEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_COVET,
    MOVE_LEER,
    MOVE_POISON_FANG,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMightyenaEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_COVET,
    MOVE_LEER,
    MOVE_POISON_FANG,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicZigzagoonEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_PURSUIT,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLinooneEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_PURSUIT,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWurmpleEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSilcoonEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBeautiflyEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCascoonEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDustoxEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLotadEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_LEECH_SEED,
    MOVE_RAZOR_LEAF,
    MOVE_SWEET_SCENT,
    MOVE_SYNTHESIS,
    MOVE_WATER_GUN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLombreEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_LEECH_SEED,
    MOVE_RAZOR_LEAF,
    MOVE_SWEET_SCENT,
    MOVE_SYNTHESIS,
    MOVE_WATER_GUN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLudicoloEggMoveLearnset[] = {
    MOVE_FLAIL,
    MOVE_LEECH_SEED,
    MOVE_RAZOR_LEAF,
    MOVE_SWEET_SCENT,
    MOVE_SYNTHESIS,
    MOVE_WATER_GUN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSeedotEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_FALSE_SWIPE,
    MOVE_LEECH_SEED,
    MOVE_QUICK_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNuzleafEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_FALSE_SWIPE,
    MOVE_LEECH_SEED,
    MOVE_QUICK_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShiftryEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_FALSE_SWIPE,
    MOVE_LEECH_SEED,
    MOVE_QUICK_ATTACK,
    MOVE_RAZOR_WIND,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTaillowEggMoveLearnset[] = {
    MOVE_MIRROR_MOVE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_REFRESH,
    MOVE_SKY_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSwellowEggMoveLearnset[] = {
    MOVE_MIRROR_MOVE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_REFRESH,
    MOVE_SKY_ATTACK,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWingullEggMoveLearnset[] = {
    MOVE_AGILITY,
    MOVE_GUST,
    MOVE_MIST,
    MOVE_TWISTER,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPelipperEggMoveLearnset[] = {
    MOVE_AGILITY,
    MOVE_GUST,
    MOVE_MIST,
    MOVE_TWISTER,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRaltsEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_DISABLE,
    MOVE_MEAN_LOOK,
    MOVE_MEMENTO,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKirliaEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_DISABLE,
    MOVE_MEAN_LOOK,
    MOVE_MEMENTO,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGardevoirEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_DISABLE,
    MOVE_MEAN_LOOK,
    MOVE_MEMENTO,
    MOVE_WILL_O_WISP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSurskitEggMoveLearnset[] = {
    MOVE_FORESIGHT,
    MOVE_HYDRO_PUMP,
    MOVE_MIND_READER,
    MOVE_MUD_SHOT,
    MOVE_PSYBEAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMasquerainEggMoveLearnset[] = {
    MOVE_FORESIGHT,
    MOVE_HYDRO_PUMP,
    MOVE_MIND_READER,
    MOVE_MUD_SHOT,
    MOVE_PSYBEAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShroomishEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FAKE_TEARS,
    MOVE_FALSE_SWIPE,
    MOVE_HELPING_HAND,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBreloomEggMoveLearnset[] = {
    MOVE_CHARM,
    MOVE_FAKE_TEARS,
    MOVE_FALSE_SWIPE,
    MOVE_HELPING_HAND,
    MOVE_SWAGGER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlakothEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVigorothEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSlakingEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_CRUSH_CLAW,
    MOVE_CURSE,
    MOVE_PURSUIT,
    MOVE_SLASH,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNincadaEggMoveLearnset[] = {
    MOVE_ENDURE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNinjaskEggMoveLearnset[] = {
    MOVE_ENDURE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShedinjaEggMoveLearnset[] = {
    MOVE_ENDURE,
    MOVE_FAINT_ATTACK,
    MOVE_GUST,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWhismurEggMoveLearnset[] = {
    MOVE_EXTRASENSORY,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLoudredEggMoveLearnset[] = {
    MOVE_EXTRASENSORY,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicExploudEggMoveLearnset[] = {
    MOVE_EXTRASENSORY,
    MOVE_SMELLING_SALTS,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_TAKE_DOWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMakuhitaEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CROSS_CHOP,
    MOVE_DETECT,
    MOVE_DYNAMIC_PUNCH,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_HELPING_HAND,
    MOVE_REVENGE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHariyamaEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CROSS_CHOP,
    MOVE_DETECT,
    MOVE_DYNAMIC_PUNCH,
    MOVE_FAINT_ATTACK,
    MOVE_FORESIGHT,
    MOVE_HELPING_HAND,
    MOVE_REVENGE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAzurillEggMoveLearnset[] = {
    MOVE_ENCORE,
    MOVE_REFRESH,
    MOVE_SING,
    MOVE_SLAM,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNosepassEggMoveLearnset[] = {
    MOVE_EXPLOSION,
    MOVE_MAGNITUDE,
    MOVE_ROLLOUT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSkittyEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_FAKE_TEARS,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_UPROAR,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDelcattyEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_FAKE_TEARS,
    MOVE_HELPING_HAND,
    MOVE_PSYCH_UP,
    MOVE_SUBSTITUTE,
    MOVE_TICKLE,
    MOVE_UPROAR,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSableyeEggMoveLearnset[] = {
    MOVE_MOONLIGHT,
    MOVE_PSYCH_UP,
    MOVE_RECOVER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMawileEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_FALSE_SWIPE,
    MOVE_POISON_FANG,
    MOVE_PSYCH_UP,
    MOVE_SWORDS_DANCE,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAronEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_ENDEAVOR,
    MOVE_SMELLING_SALTS,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLaironEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_ENDEAVOR,
    MOVE_SMELLING_SALTS,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAggronEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_ENDEAVOR,
    MOVE_SMELLING_SALTS,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMedititeEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_DYNAMIC_PUNCH,
    MOVE_FAKE_OUT,
    MOVE_FIRE_PUNCH,
    MOVE_FORESIGHT,
    MOVE_ICE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMedichamEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_DYNAMIC_PUNCH,
    MOVE_FAKE_OUT,
    MOVE_FIRE_PUNCH,
    MOVE_FORESIGHT,
    MOVE_ICE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicElectrikeEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_CURSE,
    MOVE_HEADBUTT,
    MOVE_SWIFT,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicManectricEggMoveLearnset[] = {
    MOVE_CRUNCH,
    MOVE_CURSE,
    MOVE_HEADBUTT,
    MOVE_SWIFT,
    MOVE_UPROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicPlusleEggMoveLearnset[] = {
    MOVE_SUBSTITUTE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMinunEggMoveLearnset[] = {
    MOVE_SUBSTITUTE,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVolbeatEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_SILVER_WIND,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicIllumiseEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_GROWTH,
    MOVE_SILVER_WIND,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRoseliaEggMoveLearnset[] = {
    MOVE_COTTON_SPORE,
    MOVE_PIN_MISSILE,
    MOVE_SPIKES,
    MOVE_SYNTHESIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGulpinEggMoveLearnset[] = {
    MOVE_ACID_ARMOR,
    MOVE_DREAM_EATER,
    MOVE_PAIN_SPLIT,
    MOVE_SMOG,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSwalotEggMoveLearnset[] = {
    MOVE_ACID_ARMOR,
    MOVE_DREAM_EATER,
    MOVE_PAIN_SPLIT,
    MOVE_SMOG,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCarvanhaEggMoveLearnset[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSharpedoEggMoveLearnset[] = {
    MOVE_DOUBLE_EDGE,
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWailmerEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DOUBLE_EDGE,
    MOVE_FISSURE,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_THRASH,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWailordEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DOUBLE_EDGE,
    MOVE_FISSURE,
    MOVE_SLEEP_TALK,
    MOVE_SNORE,
    MOVE_SWAGGER,
    MOVE_THRASH,
    MOVE_TICKLE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicNumelEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_DEFENSE_CURL,
    MOVE_HOWL,
    MOVE_ROLLOUT,
    MOVE_SCARY_FACE,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCameruptEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_DEFENSE_CURL,
    MOVE_HOWL,
    MOVE_ROLLOUT,
    MOVE_SCARY_FACE,
    MOVE_STOMP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTorkoalEggMoveLearnset[] = {
    MOVE_ENDURE,
    MOVE_ERUPTION,
    MOVE_SLEEP_TALK,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSpoinkEggMoveLearnset[] = {
    MOVE_EXTRASENSORY,
    MOVE_FUTURE_SIGHT,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGrumpigEggMoveLearnset[] = {
    MOVE_EXTRASENSORY,
    MOVE_FUTURE_SIGHT,
    MOVE_SUBSTITUTE,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSpindaEggMoveLearnset[] = {
    MOVE_ASSIST,
    MOVE_BATON_PASS,
    MOVE_DISABLE,
    MOVE_ENCORE,
    MOVE_ROCK_SLIDE,
    MOVE_SMELLING_SALTS,
    MOVE_TRICK,
    MOVE_WISH,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTrapinchEggMoveLearnset[] = {
    MOVE_FOCUS_ENERGY,
    MOVE_GUST,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicVibravaEggMoveLearnset[] = {
    MOVE_FOCUS_ENERGY,
    MOVE_GUST,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFlygonEggMoveLearnset[] = {
    MOVE_FOCUS_ENERGY,
    MOVE_GUST,
    MOVE_QUICK_ATTACK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCacneaEggMoveLearnset[] = {
    MOVE_ACID,
    MOVE_COUNTER,
    MOVE_DYNAMIC_PUNCH,
    MOVE_GRASS_WHISTLE,
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCacturneEggMoveLearnset[] = {
    MOVE_ACID,
    MOVE_COUNTER,
    MOVE_DYNAMIC_PUNCH,
    MOVE_GRASS_WHISTLE,
    MOVE_TEETER_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSwabluEggMoveLearnset[] = {
    MOVE_AGILITY,
    MOVE_HAZE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAltariaEggMoveLearnset[] = {
    MOVE_AGILITY,
    MOVE_HAZE,
    MOVE_PURSUIT,
    MOVE_RAGE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicZangooseEggMoveLearnset[] = {
    MOVE_COUNTER,
    MOVE_CURSE,
    MOVE_DOUBLE_KICK,
    MOVE_FLAIL,
    MOVE_RAZOR_WIND,
    MOVE_ROAR,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSeviperEggMoveLearnset[] = {
    MOVE_BODY_SLAM,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLunatoneEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSolrockEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBarboachEggMoveLearnset[] = {
    MOVE_SPARK,
    MOVE_THRASH,
    MOVE_WHIRLPOOL,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWhiscashEggMoveLearnset[] = {
    MOVE_SPARK,
    MOVE_THRASH,
    MOVE_WHIRLPOOL,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCorphishEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_ENDEAVOR,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCrawdauntEggMoveLearnset[] = {
    MOVE_ANCIENT_POWER,
    MOVE_BODY_SLAM,
    MOVE_ENDEAVOR,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBaltoyEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicClaydolEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLileepEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_MIRROR_COAT,
    MOVE_RECOVER,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCradilyEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_MIRROR_COAT,
    MOVE_RECOVER,
    MOVE_ROCK_SLIDE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAnorithEggMoveLearnset[] = {
    MOVE_KNOCK_OFF,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicArmaldoEggMoveLearnset[] = {
    MOVE_KNOCK_OFF,
    MOVE_RAPID_SPIN,
    MOVE_ROCK_SLIDE,
    MOVE_SWORDS_DANCE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicFeebasEggMoveLearnset[] = {
    MOVE_CONFUSE_RAY,
    MOVE_DRAGON_BREATH,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_MIRROR_COAT,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMiloticEggMoveLearnset[] = {
    MOVE_CONFUSE_RAY,
    MOVE_DRAGON_BREATH,
    MOVE_HYPNOSIS,
    MOVE_LIGHT_SCREEN,
    MOVE_MIRROR_COAT,
    MOVE_MUD_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicCastformEggMoveLearnset[] = {
    MOVE_FUTURE_SIGHT,
    MOVE_PSYCH_UP,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKecleonEggMoveLearnset[] = {
    MOVE_DISABLE,
    MOVE_MAGIC_COAT,
    MOVE_TRICK,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShuppetEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_DESTINY_BOND,
    MOVE_DISABLE,
    MOVE_FORESIGHT,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBanetteEggMoveLearnset[] = {
    MOVE_ASTONISH,
    MOVE_DESTINY_BOND,
    MOVE_DISABLE,
    MOVE_FORESIGHT,
    MOVE_IMPRISON,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDuskullEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_FAINT_ATTACK,
    MOVE_GRUDGE,
    MOVE_IMPRISON,
    MOVE_MEMENTO,
    MOVE_PAIN_SPLIT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDusclopsEggMoveLearnset[] = {
    MOVE_DESTINY_BOND,
    MOVE_FAINT_ATTACK,
    MOVE_GRUDGE,
    MOVE_IMPRISON,
    MOVE_MEMENTO,
    MOVE_PAIN_SPLIT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicTropiusEggMoveLearnset[] = {
    MOVE_HEADBUTT,
    MOVE_LEECH_SEED,
    MOVE_NATURE_POWER,
    MOVE_RAZOR_WIND,
    MOVE_SLAM,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicChimechoEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_DISABLE,
    MOVE_DREAM_EATER,
    MOVE_HYPNOSIS,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicAbsolEggMoveLearnset[] = {
    MOVE_BATON_PASS,
    MOVE_CURSE,
    MOVE_DOUBLE_EDGE,
    MOVE_FAINT_ATTACK,
    MOVE_MAGIC_COAT,
    MOVE_SUBSTITUTE,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWynautEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSnoruntEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGlalieEggMoveLearnset[] = {
    MOVE_BLOCK,
    MOVE_SPIKES,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSphealEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_ROCK_SLIDE,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_WATER_SPORT,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSealeoEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_ROCK_SLIDE,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_WATER_SPORT,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicWalreinEggMoveLearnset[] = {
    MOVE_CURSE,
    MOVE_FISSURE,
    MOVE_ROCK_SLIDE,
    MOVE_SPIT_UP,
    MOVE_STOCKPILE,
    MOVE_SWALLOW,
    MOVE_WATER_SPORT,
    MOVE_YAWN,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicClamperlEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_BODY_SLAM,
    MOVE_CONFUSE_RAY,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicHuntailEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_BODY_SLAM,
    MOVE_CONFUSE_RAY,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGorebyssEggMoveLearnset[] = {
    MOVE_BARRIER,
    MOVE_BODY_SLAM,
    MOVE_CONFUSE_RAY,
    MOVE_MUD_SPORT,
    MOVE_REFRESH,
    MOVE_SUPERSONIC,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRelicanthEggMoveLearnset[] = {
    MOVE_AMNESIA,
    MOVE_MAGNITUDE,
    MOVE_ROCK_SLIDE,
    MOVE_SKULL_BASH,
    MOVE_SLEEP_TALK,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLuvdiscEggMoveLearnset[] = {
    MOVE_MUD_SPORT,
    MOVE_SPLASH,
    MOVE_SUPERSONIC,
    MOVE_WATER_SPORT,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBagonEggMoveLearnset[] = {
    MOVE_DRAGON_DANCE,
    MOVE_DRAGON_RAGE,
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_TWISTER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicShelgonEggMoveLearnset[] = {
    MOVE_DRAGON_DANCE,
    MOVE_DRAGON_RAGE,
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_TWISTER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicSalamenceEggMoveLearnset[] = {
    MOVE_DRAGON_DANCE,
    MOVE_DRAGON_RAGE,
    MOVE_HYDRO_PUMP,
    MOVE_THRASH,
    MOVE_TWISTER,
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicBeldumEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMetangEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicMetagrossEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRegirockEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRegiceEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRegisteelEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLatiasEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicLatiosEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicKyogreEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicGroudonEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicRayquazaEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicJirachiEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDeoxysNormalEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDeoxysAttackEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDeoxysDefenseEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const u16 sMfClassicDeoxysSpeedEggMoveLearnset[] = {
    MOVE_UNAVAILABLE,
};

static const struct MfClassicU16LearnsetPtr sClassicEggMoveLearnsets[] = {
    { SPECIES_BULBASAUR, sMfClassicBulbasaurEggMoveLearnset },
    { SPECIES_IVYSAUR, sMfClassicIvysaurEggMoveLearnset },
    { SPECIES_VENUSAUR, sMfClassicVenusaurEggMoveLearnset },
    { SPECIES_CHARMANDER, sMfClassicCharmanderEggMoveLearnset },
    { SPECIES_CHARMELEON, sMfClassicCharmeleonEggMoveLearnset },
    { SPECIES_CHARIZARD, sMfClassicCharizardEggMoveLearnset },
    { SPECIES_SQUIRTLE, sMfClassicSquirtleEggMoveLearnset },
    { SPECIES_WARTORTLE, sMfClassicWartortleEggMoveLearnset },
    { SPECIES_BLASTOISE, sMfClassicBlastoiseEggMoveLearnset },
    { SPECIES_CATERPIE, sMfClassicCaterpieEggMoveLearnset },
    { SPECIES_METAPOD, sMfClassicMetapodEggMoveLearnset },
    { SPECIES_BUTTERFREE, sMfClassicButterfreeEggMoveLearnset },
    { SPECIES_WEEDLE, sMfClassicWeedleEggMoveLearnset },
    { SPECIES_KAKUNA, sMfClassicKakunaEggMoveLearnset },
    { SPECIES_BEEDRILL, sMfClassicBeedrillEggMoveLearnset },
    { SPECIES_PIDGEY, sMfClassicPidgeyEggMoveLearnset },
    { SPECIES_PIDGEOTTO, sMfClassicPidgeottoEggMoveLearnset },
    { SPECIES_PIDGEOT, sMfClassicPidgeotEggMoveLearnset },
    { SPECIES_RATTATA, sMfClassicRattataEggMoveLearnset },
    { SPECIES_RATICATE, sMfClassicRaticateEggMoveLearnset },
    { SPECIES_SPEAROW, sMfClassicSpearowEggMoveLearnset },
    { SPECIES_FEAROW, sMfClassicFearowEggMoveLearnset },
    { SPECIES_EKANS, sMfClassicEkansEggMoveLearnset },
    { SPECIES_ARBOK, sMfClassicArbokEggMoveLearnset },
    { SPECIES_PIKACHU, sMfClassicPikachuEggMoveLearnset },
    { SPECIES_RAICHU, sMfClassicRaichuEggMoveLearnset },
    { SPECIES_SANDSHREW, sMfClassicSandshrewEggMoveLearnset },
    { SPECIES_SANDSLASH, sMfClassicSandslashEggMoveLearnset },
    { SPECIES_NIDORAN_F, sMfClassicNidoranFEggMoveLearnset },
    { SPECIES_NIDORINA, sMfClassicNidorinaEggMoveLearnset },
    { SPECIES_NIDOQUEEN, sMfClassicNidoqueenEggMoveLearnset },
    { SPECIES_NIDORAN_M, sMfClassicNidoranMEggMoveLearnset },
    { SPECIES_NIDORINO, sMfClassicNidorinoEggMoveLearnset },
    { SPECIES_NIDOKING, sMfClassicNidokingEggMoveLearnset },
    { SPECIES_CLEFAIRY, sMfClassicClefairyEggMoveLearnset },
    { SPECIES_CLEFABLE, sMfClassicClefableEggMoveLearnset },
    { SPECIES_VULPIX, sMfClassicVulpixEggMoveLearnset },
    { SPECIES_NINETALES, sMfClassicNinetalesEggMoveLearnset },
    { SPECIES_JIGGLYPUFF, sMfClassicJigglypuffEggMoveLearnset },
    { SPECIES_WIGGLYTUFF, sMfClassicWigglytuffEggMoveLearnset },
    { SPECIES_ZUBAT, sMfClassicZubatEggMoveLearnset },
    { SPECIES_GOLBAT, sMfClassicGolbatEggMoveLearnset },
    { SPECIES_ODDISH, sMfClassicOddishEggMoveLearnset },
    { SPECIES_GLOOM, sMfClassicGloomEggMoveLearnset },
    { SPECIES_VILEPLUME, sMfClassicVileplumeEggMoveLearnset },
    { SPECIES_PARAS, sMfClassicParasEggMoveLearnset },
    { SPECIES_PARASECT, sMfClassicParasectEggMoveLearnset },
    { SPECIES_VENONAT, sMfClassicVenonatEggMoveLearnset },
    { SPECIES_VENOMOTH, sMfClassicVenomothEggMoveLearnset },
    { SPECIES_DIGLETT, sMfClassicDiglettEggMoveLearnset },
    { SPECIES_DUGTRIO, sMfClassicDugtrioEggMoveLearnset },
    { SPECIES_MEOWTH, sMfClassicMeowthEggMoveLearnset },
    { SPECIES_PERSIAN, sMfClassicPersianEggMoveLearnset },
    { SPECIES_PSYDUCK, sMfClassicPsyduckEggMoveLearnset },
    { SPECIES_GOLDUCK, sMfClassicGolduckEggMoveLearnset },
    { SPECIES_MANKEY, sMfClassicMankeyEggMoveLearnset },
    { SPECIES_PRIMEAPE, sMfClassicPrimeapeEggMoveLearnset },
    { SPECIES_GROWLITHE, sMfClassicGrowlitheEggMoveLearnset },
    { SPECIES_ARCANINE, sMfClassicArcanineEggMoveLearnset },
    { SPECIES_POLIWAG, sMfClassicPoliwagEggMoveLearnset },
    { SPECIES_POLIWHIRL, sMfClassicPoliwhirlEggMoveLearnset },
    { SPECIES_POLIWRATH, sMfClassicPoliwrathEggMoveLearnset },
    { SPECIES_ABRA, sMfClassicAbraEggMoveLearnset },
    { SPECIES_KADABRA, sMfClassicKadabraEggMoveLearnset },
    { SPECIES_ALAKAZAM, sMfClassicAlakazamEggMoveLearnset },
    { SPECIES_MACHOP, sMfClassicMachopEggMoveLearnset },
    { SPECIES_MACHOKE, sMfClassicMachokeEggMoveLearnset },
    { SPECIES_MACHAMP, sMfClassicMachampEggMoveLearnset },
    { SPECIES_BELLSPROUT, sMfClassicBellsproutEggMoveLearnset },
    { SPECIES_WEEPINBELL, sMfClassicWeepinbellEggMoveLearnset },
    { SPECIES_VICTREEBEL, sMfClassicVictreebelEggMoveLearnset },
    { SPECIES_TENTACOOL, sMfClassicTentacoolEggMoveLearnset },
    { SPECIES_TENTACRUEL, sMfClassicTentacruelEggMoveLearnset },
    { SPECIES_GEODUDE, sMfClassicGeodudeEggMoveLearnset },
    { SPECIES_GRAVELER, sMfClassicGravelerEggMoveLearnset },
    { SPECIES_GOLEM, sMfClassicGolemEggMoveLearnset },
    { SPECIES_PONYTA, sMfClassicPonytaEggMoveLearnset },
    { SPECIES_RAPIDASH, sMfClassicRapidashEggMoveLearnset },
    { SPECIES_SLOWPOKE, sMfClassicSlowpokeEggMoveLearnset },
    { SPECIES_SLOWBRO, sMfClassicSlowbroEggMoveLearnset },
    { SPECIES_MAGNEMITE, sMfClassicMagnemiteEggMoveLearnset },
    { SPECIES_MAGNETON, sMfClassicMagnetonEggMoveLearnset },
    { SPECIES_FARFETCHD, sMfClassicFarfetchdEggMoveLearnset },
    { SPECIES_DODUO, sMfClassicDoduoEggMoveLearnset },
    { SPECIES_DODRIO, sMfClassicDodrioEggMoveLearnset },
    { SPECIES_SEEL, sMfClassicSeelEggMoveLearnset },
    { SPECIES_DEWGONG, sMfClassicDewgongEggMoveLearnset },
    { SPECIES_GRIMER, sMfClassicGrimerEggMoveLearnset },
    { SPECIES_MUK, sMfClassicMukEggMoveLearnset },
    { SPECIES_SHELLDER, sMfClassicShellderEggMoveLearnset },
    { SPECIES_CLOYSTER, sMfClassicCloysterEggMoveLearnset },
    { SPECIES_GASTLY, sMfClassicGastlyEggMoveLearnset },
    { SPECIES_HAUNTER, sMfClassicHaunterEggMoveLearnset },
    { SPECIES_GENGAR, sMfClassicGengarEggMoveLearnset },
    { SPECIES_ONIX, sMfClassicOnixEggMoveLearnset },
    { SPECIES_DROWZEE, sMfClassicDrowzeeEggMoveLearnset },
    { SPECIES_HYPNO, sMfClassicHypnoEggMoveLearnset },
    { SPECIES_KRABBY, sMfClassicKrabbyEggMoveLearnset },
    { SPECIES_KINGLER, sMfClassicKinglerEggMoveLearnset },
    { SPECIES_VOLTORB, sMfClassicVoltorbEggMoveLearnset },
    { SPECIES_ELECTRODE, sMfClassicElectrodeEggMoveLearnset },
    { SPECIES_EXEGGCUTE, sMfClassicExeggcuteEggMoveLearnset },
    { SPECIES_EXEGGUTOR, sMfClassicExeggutorEggMoveLearnset },
    { SPECIES_CUBONE, sMfClassicCuboneEggMoveLearnset },
    { SPECIES_MAROWAK, sMfClassicMarowakEggMoveLearnset },
    { SPECIES_HITMONLEE, sMfClassicHitmonleeEggMoveLearnset },
    { SPECIES_HITMONCHAN, sMfClassicHitmonchanEggMoveLearnset },
    { SPECIES_LICKITUNG, sMfClassicLickitungEggMoveLearnset },
    { SPECIES_KOFFING, sMfClassicKoffingEggMoveLearnset },
    { SPECIES_WEEZING, sMfClassicWeezingEggMoveLearnset },
    { SPECIES_RHYHORN, sMfClassicRhyhornEggMoveLearnset },
    { SPECIES_RHYDON, sMfClassicRhydonEggMoveLearnset },
    { SPECIES_CHANSEY, sMfClassicChanseyEggMoveLearnset },
    { SPECIES_TANGELA, sMfClassicTangelaEggMoveLearnset },
    { SPECIES_KANGASKHAN, sMfClassicKangaskhanEggMoveLearnset },
    { SPECIES_HORSEA, sMfClassicHorseaEggMoveLearnset },
    { SPECIES_SEADRA, sMfClassicSeadraEggMoveLearnset },
    { SPECIES_GOLDEEN, sMfClassicGoldeenEggMoveLearnset },
    { SPECIES_SEAKING, sMfClassicSeakingEggMoveLearnset },
    { SPECIES_STARYU, sMfClassicStaryuEggMoveLearnset },
    { SPECIES_STARMIE, sMfClassicStarmieEggMoveLearnset },
    { SPECIES_MR_MIME, sMfClassicMrMimeEggMoveLearnset },
    { SPECIES_SCYTHER, sMfClassicScytherEggMoveLearnset },
    { SPECIES_JYNX, sMfClassicJynxEggMoveLearnset },
    { SPECIES_ELECTABUZZ, sMfClassicElectabuzzEggMoveLearnset },
    { SPECIES_MAGMAR, sMfClassicMagmarEggMoveLearnset },
    { SPECIES_PINSIR, sMfClassicPinsirEggMoveLearnset },
    { SPECIES_TAUROS, sMfClassicTaurosEggMoveLearnset },
    { SPECIES_MAGIKARP, sMfClassicMagikarpEggMoveLearnset },
    { SPECIES_GYARADOS, sMfClassicGyaradosEggMoveLearnset },
    { SPECIES_LAPRAS, sMfClassicLaprasEggMoveLearnset },
    { SPECIES_DITTO, sMfClassicDittoEggMoveLearnset },
    { SPECIES_EEVEE, sMfClassicEeveeEggMoveLearnset },
    { SPECIES_VAPOREON, sMfClassicVaporeonEggMoveLearnset },
    { SPECIES_JOLTEON, sMfClassicJolteonEggMoveLearnset },
    { SPECIES_FLAREON, sMfClassicFlareonEggMoveLearnset },
    { SPECIES_PORYGON, sMfClassicPorygonEggMoveLearnset },
    { SPECIES_OMANYTE, sMfClassicOmanyteEggMoveLearnset },
    { SPECIES_OMASTAR, sMfClassicOmastarEggMoveLearnset },
    { SPECIES_KABUTO, sMfClassicKabutoEggMoveLearnset },
    { SPECIES_KABUTOPS, sMfClassicKabutopsEggMoveLearnset },
    { SPECIES_AERODACTYL, sMfClassicAerodactylEggMoveLearnset },
    { SPECIES_SNORLAX, sMfClassicSnorlaxEggMoveLearnset },
    { SPECIES_ARTICUNO, sMfClassicArticunoEggMoveLearnset },
    { SPECIES_ZAPDOS, sMfClassicZapdosEggMoveLearnset },
    { SPECIES_MOLTRES, sMfClassicMoltresEggMoveLearnset },
    { SPECIES_DRATINI, sMfClassicDratiniEggMoveLearnset },
    { SPECIES_DRAGONAIR, sMfClassicDragonairEggMoveLearnset },
    { SPECIES_DRAGONITE, sMfClassicDragoniteEggMoveLearnset },
    { SPECIES_MEWTWO, sMfClassicMewtwoEggMoveLearnset },
    { SPECIES_MEW, sMfClassicMewEggMoveLearnset },
    { SPECIES_CHIKORITA, sMfClassicChikoritaEggMoveLearnset },
    { SPECIES_BAYLEEF, sMfClassicBayleefEggMoveLearnset },
    { SPECIES_MEGANIUM, sMfClassicMeganiumEggMoveLearnset },
    { SPECIES_CYNDAQUIL, sMfClassicCyndaquilEggMoveLearnset },
    { SPECIES_QUILAVA, sMfClassicQuilavaEggMoveLearnset },
    { SPECIES_TYPHLOSION, sMfClassicTyphlosionEggMoveLearnset },
    { SPECIES_TOTODILE, sMfClassicTotodileEggMoveLearnset },
    { SPECIES_CROCONAW, sMfClassicCroconawEggMoveLearnset },
    { SPECIES_FERALIGATR, sMfClassicFeraligatrEggMoveLearnset },
    { SPECIES_SENTRET, sMfClassicSentretEggMoveLearnset },
    { SPECIES_FURRET, sMfClassicFurretEggMoveLearnset },
    { SPECIES_HOOTHOOT, sMfClassicHoothootEggMoveLearnset },
    { SPECIES_NOCTOWL, sMfClassicNoctowlEggMoveLearnset },
    { SPECIES_LEDYBA, sMfClassicLedybaEggMoveLearnset },
    { SPECIES_LEDIAN, sMfClassicLedianEggMoveLearnset },
    { SPECIES_SPINARAK, sMfClassicSpinarakEggMoveLearnset },
    { SPECIES_ARIADOS, sMfClassicAriadosEggMoveLearnset },
    { SPECIES_CROBAT, sMfClassicCrobatEggMoveLearnset },
    { SPECIES_CHINCHOU, sMfClassicChinchouEggMoveLearnset },
    { SPECIES_LANTURN, sMfClassicLanturnEggMoveLearnset },
    { SPECIES_PICHU, sMfClassicPichuEggMoveLearnset },
    { SPECIES_CLEFFA, sMfClassicCleffaEggMoveLearnset },
    { SPECIES_IGGLYBUFF, sMfClassicIgglybuffEggMoveLearnset },
    { SPECIES_TOGEPI, sMfClassicTogepiEggMoveLearnset },
    { SPECIES_TOGETIC, sMfClassicTogeticEggMoveLearnset },
    { SPECIES_NATU, sMfClassicNatuEggMoveLearnset },
    { SPECIES_XATU, sMfClassicXatuEggMoveLearnset },
    { SPECIES_MAREEP, sMfClassicMareepEggMoveLearnset },
    { SPECIES_FLAAFFY, sMfClassicFlaaffyEggMoveLearnset },
    { SPECIES_AMPHAROS, sMfClassicAmpharosEggMoveLearnset },
    { SPECIES_BELLOSSOM, sMfClassicBellossomEggMoveLearnset },
    { SPECIES_MARILL, sMfClassicMarillEggMoveLearnset },
    { SPECIES_AZUMARILL, sMfClassicAzumarillEggMoveLearnset },
    { SPECIES_SUDOWOODO, sMfClassicSudowoodoEggMoveLearnset },
    { SPECIES_POLITOED, sMfClassicPolitoedEggMoveLearnset },
    { SPECIES_HOPPIP, sMfClassicHoppipEggMoveLearnset },
    { SPECIES_SKIPLOOM, sMfClassicSkiploomEggMoveLearnset },
    { SPECIES_JUMPLUFF, sMfClassicJumpluffEggMoveLearnset },
    { SPECIES_AIPOM, sMfClassicAipomEggMoveLearnset },
    { SPECIES_SUNKERN, sMfClassicSunkernEggMoveLearnset },
    { SPECIES_SUNFLORA, sMfClassicSunfloraEggMoveLearnset },
    { SPECIES_YANMA, sMfClassicYanmaEggMoveLearnset },
    { SPECIES_WOOPER, sMfClassicWooperEggMoveLearnset },
    { SPECIES_QUAGSIRE, sMfClassicQuagsireEggMoveLearnset },
    { SPECIES_ESPEON, sMfClassicEspeonEggMoveLearnset },
    { SPECIES_UMBREON, sMfClassicUmbreonEggMoveLearnset },
    { SPECIES_MURKROW, sMfClassicMurkrowEggMoveLearnset },
    { SPECIES_SLOWKING, sMfClassicSlowkingEggMoveLearnset },
    { SPECIES_MISDREAVUS, sMfClassicMisdreavusEggMoveLearnset },
    { SPECIES_UNOWN, sMfClassicUnownEggMoveLearnset },
    { SPECIES_WOBBUFFET, sMfClassicWobbuffetEggMoveLearnset },
    { SPECIES_GIRAFARIG, sMfClassicGirafarigEggMoveLearnset },
    { SPECIES_PINECO, sMfClassicPinecoEggMoveLearnset },
    { SPECIES_FORRETRESS, sMfClassicForretressEggMoveLearnset },
    { SPECIES_DUNSPARCE, sMfClassicDunsparceEggMoveLearnset },
    { SPECIES_GLIGAR, sMfClassicGligarEggMoveLearnset },
    { SPECIES_STEELIX, sMfClassicSteelixEggMoveLearnset },
    { SPECIES_SNUBBULL, sMfClassicSnubbullEggMoveLearnset },
    { SPECIES_GRANBULL, sMfClassicGranbullEggMoveLearnset },
    { SPECIES_QWILFISH, sMfClassicQwilfishEggMoveLearnset },
    { SPECIES_SCIZOR, sMfClassicScizorEggMoveLearnset },
    { SPECIES_SHUCKLE, sMfClassicShuckleEggMoveLearnset },
    { SPECIES_HERACROSS, sMfClassicHeracrossEggMoveLearnset },
    { SPECIES_SNEASEL, sMfClassicSneaselEggMoveLearnset },
    { SPECIES_TEDDIURSA, sMfClassicTeddiursaEggMoveLearnset },
    { SPECIES_URSARING, sMfClassicUrsaringEggMoveLearnset },
    { SPECIES_SLUGMA, sMfClassicSlugmaEggMoveLearnset },
    { SPECIES_MAGCARGO, sMfClassicMagcargoEggMoveLearnset },
    { SPECIES_SWINUB, sMfClassicSwinubEggMoveLearnset },
    { SPECIES_PILOSWINE, sMfClassicPiloswineEggMoveLearnset },
    { SPECIES_CORSOLA, sMfClassicCorsolaEggMoveLearnset },
    { SPECIES_REMORAID, sMfClassicRemoraidEggMoveLearnset },
    { SPECIES_OCTILLERY, sMfClassicOctilleryEggMoveLearnset },
    { SPECIES_DELIBIRD, sMfClassicDelibirdEggMoveLearnset },
    { SPECIES_MANTINE, sMfClassicMantineEggMoveLearnset },
    { SPECIES_SKARMORY, sMfClassicSkarmoryEggMoveLearnset },
    { SPECIES_HOUNDOUR, sMfClassicHoundourEggMoveLearnset },
    { SPECIES_HOUNDOOM, sMfClassicHoundoomEggMoveLearnset },
    { SPECIES_KINGDRA, sMfClassicKingdraEggMoveLearnset },
    { SPECIES_PHANPY, sMfClassicPhanpyEggMoveLearnset },
    { SPECIES_DONPHAN, sMfClassicDonphanEggMoveLearnset },
    { SPECIES_PORYGON2, sMfClassicPorygon2EggMoveLearnset },
    { SPECIES_STANTLER, sMfClassicStantlerEggMoveLearnset },
    { SPECIES_SMEARGLE, sMfClassicSmeargleEggMoveLearnset },
    { SPECIES_TYROGUE, sMfClassicTyrogueEggMoveLearnset },
    { SPECIES_HITMONTOP, sMfClassicHitmontopEggMoveLearnset },
    { SPECIES_SMOOCHUM, sMfClassicSmoochumEggMoveLearnset },
    { SPECIES_ELEKID, sMfClassicElekidEggMoveLearnset },
    { SPECIES_MAGBY, sMfClassicMagbyEggMoveLearnset },
    { SPECIES_MILTANK, sMfClassicMiltankEggMoveLearnset },
    { SPECIES_BLISSEY, sMfClassicBlisseyEggMoveLearnset },
    { SPECIES_RAIKOU, sMfClassicRaikouEggMoveLearnset },
    { SPECIES_ENTEI, sMfClassicEnteiEggMoveLearnset },
    { SPECIES_SUICUNE, sMfClassicSuicuneEggMoveLearnset },
    { SPECIES_LARVITAR, sMfClassicLarvitarEggMoveLearnset },
    { SPECIES_PUPITAR, sMfClassicPupitarEggMoveLearnset },
    { SPECIES_TYRANITAR, sMfClassicTyranitarEggMoveLearnset },
    { SPECIES_LUGIA, sMfClassicLugiaEggMoveLearnset },
    { SPECIES_HO_OH, sMfClassicHoOhEggMoveLearnset },
    { SPECIES_CELEBI, sMfClassicCelebiEggMoveLearnset },
    { SPECIES_TREECKO, sMfClassicTreeckoEggMoveLearnset },
    { SPECIES_GROVYLE, sMfClassicGrovyleEggMoveLearnset },
    { SPECIES_SCEPTILE, sMfClassicSceptileEggMoveLearnset },
    { SPECIES_TORCHIC, sMfClassicTorchicEggMoveLearnset },
    { SPECIES_COMBUSKEN, sMfClassicCombuskenEggMoveLearnset },
    { SPECIES_BLAZIKEN, sMfClassicBlazikenEggMoveLearnset },
    { SPECIES_MUDKIP, sMfClassicMudkipEggMoveLearnset },
    { SPECIES_MARSHTOMP, sMfClassicMarshtompEggMoveLearnset },
    { SPECIES_SWAMPERT, sMfClassicSwampertEggMoveLearnset },
    { SPECIES_POOCHYENA, sMfClassicPoochyenaEggMoveLearnset },
    { SPECIES_MIGHTYENA, sMfClassicMightyenaEggMoveLearnset },
    { SPECIES_ZIGZAGOON, sMfClassicZigzagoonEggMoveLearnset },
    { SPECIES_LINOONE, sMfClassicLinooneEggMoveLearnset },
    { SPECIES_WURMPLE, sMfClassicWurmpleEggMoveLearnset },
    { SPECIES_SILCOON, sMfClassicSilcoonEggMoveLearnset },
    { SPECIES_BEAUTIFLY, sMfClassicBeautiflyEggMoveLearnset },
    { SPECIES_CASCOON, sMfClassicCascoonEggMoveLearnset },
    { SPECIES_DUSTOX, sMfClassicDustoxEggMoveLearnset },
    { SPECIES_LOTAD, sMfClassicLotadEggMoveLearnset },
    { SPECIES_LOMBRE, sMfClassicLombreEggMoveLearnset },
    { SPECIES_LUDICOLO, sMfClassicLudicoloEggMoveLearnset },
    { SPECIES_SEEDOT, sMfClassicSeedotEggMoveLearnset },
    { SPECIES_NUZLEAF, sMfClassicNuzleafEggMoveLearnset },
    { SPECIES_SHIFTRY, sMfClassicShiftryEggMoveLearnset },
    { SPECIES_TAILLOW, sMfClassicTaillowEggMoveLearnset },
    { SPECIES_SWELLOW, sMfClassicSwellowEggMoveLearnset },
    { SPECIES_WINGULL, sMfClassicWingullEggMoveLearnset },
    { SPECIES_PELIPPER, sMfClassicPelipperEggMoveLearnset },
    { SPECIES_RALTS, sMfClassicRaltsEggMoveLearnset },
    { SPECIES_KIRLIA, sMfClassicKirliaEggMoveLearnset },
    { SPECIES_GARDEVOIR, sMfClassicGardevoirEggMoveLearnset },
    { SPECIES_SURSKIT, sMfClassicSurskitEggMoveLearnset },
    { SPECIES_MASQUERAIN, sMfClassicMasquerainEggMoveLearnset },
    { SPECIES_SHROOMISH, sMfClassicShroomishEggMoveLearnset },
    { SPECIES_BRELOOM, sMfClassicBreloomEggMoveLearnset },
    { SPECIES_SLAKOTH, sMfClassicSlakothEggMoveLearnset },
    { SPECIES_VIGOROTH, sMfClassicVigorothEggMoveLearnset },
    { SPECIES_SLAKING, sMfClassicSlakingEggMoveLearnset },
    { SPECIES_NINCADA, sMfClassicNincadaEggMoveLearnset },
    { SPECIES_NINJASK, sMfClassicNinjaskEggMoveLearnset },
    { SPECIES_SHEDINJA, sMfClassicShedinjaEggMoveLearnset },
    { SPECIES_WHISMUR, sMfClassicWhismurEggMoveLearnset },
    { SPECIES_LOUDRED, sMfClassicLoudredEggMoveLearnset },
    { SPECIES_EXPLOUD, sMfClassicExploudEggMoveLearnset },
    { SPECIES_MAKUHITA, sMfClassicMakuhitaEggMoveLearnset },
    { SPECIES_HARIYAMA, sMfClassicHariyamaEggMoveLearnset },
    { SPECIES_AZURILL, sMfClassicAzurillEggMoveLearnset },
    { SPECIES_NOSEPASS, sMfClassicNosepassEggMoveLearnset },
    { SPECIES_SKITTY, sMfClassicSkittyEggMoveLearnset },
    { SPECIES_DELCATTY, sMfClassicDelcattyEggMoveLearnset },
    { SPECIES_SABLEYE, sMfClassicSableyeEggMoveLearnset },
    { SPECIES_MAWILE, sMfClassicMawileEggMoveLearnset },
    { SPECIES_ARON, sMfClassicAronEggMoveLearnset },
    { SPECIES_LAIRON, sMfClassicLaironEggMoveLearnset },
    { SPECIES_AGGRON, sMfClassicAggronEggMoveLearnset },
    { SPECIES_MEDITITE, sMfClassicMedititeEggMoveLearnset },
    { SPECIES_MEDICHAM, sMfClassicMedichamEggMoveLearnset },
    { SPECIES_ELECTRIKE, sMfClassicElectrikeEggMoveLearnset },
    { SPECIES_MANECTRIC, sMfClassicManectricEggMoveLearnset },
    { SPECIES_PLUSLE, sMfClassicPlusleEggMoveLearnset },
    { SPECIES_MINUN, sMfClassicMinunEggMoveLearnset },
    { SPECIES_VOLBEAT, sMfClassicVolbeatEggMoveLearnset },
    { SPECIES_ILLUMISE, sMfClassicIllumiseEggMoveLearnset },
    { SPECIES_ROSELIA, sMfClassicRoseliaEggMoveLearnset },
    { SPECIES_GULPIN, sMfClassicGulpinEggMoveLearnset },
    { SPECIES_SWALOT, sMfClassicSwalotEggMoveLearnset },
    { SPECIES_CARVANHA, sMfClassicCarvanhaEggMoveLearnset },
    { SPECIES_SHARPEDO, sMfClassicSharpedoEggMoveLearnset },
    { SPECIES_WAILMER, sMfClassicWailmerEggMoveLearnset },
    { SPECIES_WAILORD, sMfClassicWailordEggMoveLearnset },
    { SPECIES_NUMEL, sMfClassicNumelEggMoveLearnset },
    { SPECIES_CAMERUPT, sMfClassicCameruptEggMoveLearnset },
    { SPECIES_TORKOAL, sMfClassicTorkoalEggMoveLearnset },
    { SPECIES_SPOINK, sMfClassicSpoinkEggMoveLearnset },
    { SPECIES_GRUMPIG, sMfClassicGrumpigEggMoveLearnset },
    { SPECIES_SPINDA, sMfClassicSpindaEggMoveLearnset },
    { SPECIES_TRAPINCH, sMfClassicTrapinchEggMoveLearnset },
    { SPECIES_VIBRAVA, sMfClassicVibravaEggMoveLearnset },
    { SPECIES_FLYGON, sMfClassicFlygonEggMoveLearnset },
    { SPECIES_CACNEA, sMfClassicCacneaEggMoveLearnset },
    { SPECIES_CACTURNE, sMfClassicCacturneEggMoveLearnset },
    { SPECIES_SWABLU, sMfClassicSwabluEggMoveLearnset },
    { SPECIES_ALTARIA, sMfClassicAltariaEggMoveLearnset },
    { SPECIES_ZANGOOSE, sMfClassicZangooseEggMoveLearnset },
    { SPECIES_SEVIPER, sMfClassicSeviperEggMoveLearnset },
    { SPECIES_LUNATONE, sMfClassicLunatoneEggMoveLearnset },
    { SPECIES_SOLROCK, sMfClassicSolrockEggMoveLearnset },
    { SPECIES_BARBOACH, sMfClassicBarboachEggMoveLearnset },
    { SPECIES_WHISCASH, sMfClassicWhiscashEggMoveLearnset },
    { SPECIES_CORPHISH, sMfClassicCorphishEggMoveLearnset },
    { SPECIES_CRAWDAUNT, sMfClassicCrawdauntEggMoveLearnset },
    { SPECIES_BALTOY, sMfClassicBaltoyEggMoveLearnset },
    { SPECIES_CLAYDOL, sMfClassicClaydolEggMoveLearnset },
    { SPECIES_LILEEP, sMfClassicLileepEggMoveLearnset },
    { SPECIES_CRADILY, sMfClassicCradilyEggMoveLearnset },
    { SPECIES_ANORITH, sMfClassicAnorithEggMoveLearnset },
    { SPECIES_ARMALDO, sMfClassicArmaldoEggMoveLearnset },
    { SPECIES_FEEBAS, sMfClassicFeebasEggMoveLearnset },
    { SPECIES_MILOTIC, sMfClassicMiloticEggMoveLearnset },
    { SPECIES_CASTFORM, sMfClassicCastformEggMoveLearnset },
    { SPECIES_KECLEON, sMfClassicKecleonEggMoveLearnset },
    { SPECIES_SHUPPET, sMfClassicShuppetEggMoveLearnset },
    { SPECIES_BANETTE, sMfClassicBanetteEggMoveLearnset },
    { SPECIES_DUSKULL, sMfClassicDuskullEggMoveLearnset },
    { SPECIES_DUSCLOPS, sMfClassicDusclopsEggMoveLearnset },
    { SPECIES_TROPIUS, sMfClassicTropiusEggMoveLearnset },
    { SPECIES_CHIMECHO, sMfClassicChimechoEggMoveLearnset },
    { SPECIES_ABSOL, sMfClassicAbsolEggMoveLearnset },
    { SPECIES_WYNAUT, sMfClassicWynautEggMoveLearnset },
    { SPECIES_SNORUNT, sMfClassicSnoruntEggMoveLearnset },
    { SPECIES_GLALIE, sMfClassicGlalieEggMoveLearnset },
    { SPECIES_SPHEAL, sMfClassicSphealEggMoveLearnset },
    { SPECIES_SEALEO, sMfClassicSealeoEggMoveLearnset },
    { SPECIES_WALREIN, sMfClassicWalreinEggMoveLearnset },
    { SPECIES_CLAMPERL, sMfClassicClamperlEggMoveLearnset },
    { SPECIES_HUNTAIL, sMfClassicHuntailEggMoveLearnset },
    { SPECIES_GOREBYSS, sMfClassicGorebyssEggMoveLearnset },
    { SPECIES_RELICANTH, sMfClassicRelicanthEggMoveLearnset },
    { SPECIES_LUVDISC, sMfClassicLuvdiscEggMoveLearnset },
    { SPECIES_BAGON, sMfClassicBagonEggMoveLearnset },
    { SPECIES_SHELGON, sMfClassicShelgonEggMoveLearnset },
    { SPECIES_SALAMENCE, sMfClassicSalamenceEggMoveLearnset },
    { SPECIES_BELDUM, sMfClassicBeldumEggMoveLearnset },
    { SPECIES_METANG, sMfClassicMetangEggMoveLearnset },
    { SPECIES_METAGROSS, sMfClassicMetagrossEggMoveLearnset },
    { SPECIES_REGIROCK, sMfClassicRegirockEggMoveLearnset },
    { SPECIES_REGICE, sMfClassicRegiceEggMoveLearnset },
    { SPECIES_REGISTEEL, sMfClassicRegisteelEggMoveLearnset },
    { SPECIES_LATIAS, sMfClassicLatiasEggMoveLearnset },
    { SPECIES_LATIOS, sMfClassicLatiosEggMoveLearnset },
    { SPECIES_KYOGRE, sMfClassicKyogreEggMoveLearnset },
    { SPECIES_GROUDON, sMfClassicGroudonEggMoveLearnset },
    { SPECIES_RAYQUAZA, sMfClassicRayquazaEggMoveLearnset },
    { SPECIES_JIRACHI, sMfClassicJirachiEggMoveLearnset },
    { SPECIES_DEOXYS_NORMAL, sMfClassicDeoxysNormalEggMoveLearnset },
    { SPECIES_DEOXYS_ATTACK, sMfClassicDeoxysAttackEggMoveLearnset },
    { SPECIES_DEOXYS_DEFENSE, sMfClassicDeoxysDefenseEggMoveLearnset },
    { SPECIES_DEOXYS_SPEED, sMfClassicDeoxysSpeedEggMoveLearnset },
};
