/* Autogenerated classic (Gen-3 / intro-gen) base stats for S29.
 * Modern values live in gSpeciesInfo (P_UPDATED_STATS == GEN_LATEST).
 * Sorted by species id for binary search. Regenerate if upstream
 * species_info P_UPDATED_STATS branches change.
 * 64 species. */

static const struct MfClassicBaseStats sClassicBaseStats[] =
{
    { SPECIES_BUTTERFREE, { 60, 45, 50, 70, 80, 80 } }, // spa 80->90
    { SPECIES_BEEDRILL, { 65, 80, 40, 75, 45, 80 } }, // atk 80->90
    { SPECIES_PIDGEOT, { 83, 80, 75, 91, 70, 70 } }, // spe 91->101
    { SPECIES_ARBOK, { 60, 85, 69, 80, 65, 79 } }, // atk 85->95
    { SPECIES_PIKACHU, { 35, 55, 30, 90, 50, 40 } }, // def 30->40, spd 40->50
    { SPECIES_RAICHU, { 60, 90, 55, 100, 90, 80 } }, // spe 100->110
    { SPECIES_NIDOQUEEN, { 90, 82, 87, 76, 75, 85 } }, // atk 82->92
    { SPECIES_NIDOKING, { 81, 92, 77, 85, 85, 75 } }, // atk 92->102
    { SPECIES_CLEFABLE, { 95, 70, 73, 60, 85, 90 } }, // spa 85->95
    { SPECIES_WIGGLYTUFF, { 140, 70, 45, 45, 75, 50 } }, // spa 75->85
    { SPECIES_VILEPLUME, { 75, 80, 85, 50, 100, 90 } }, // spa 100->110
    { SPECIES_DUGTRIO, { 35, 80, 50, 120, 50, 70 } }, // atk 80->100
    { SPECIES_POLIWRATH, { 90, 85, 95, 70, 70, 90 } }, // atk 85->95
    { SPECIES_ALAKAZAM, { 55, 50, 45, 120, 135, 85 } }, // spd 85->95
    { SPECIES_VICTREEBEL, { 80, 105, 65, 70, 100, 60 } }, // spd 60->70
    { SPECIES_GOLEM, { 80, 110, 130, 45, 55, 65 } }, // atk 110->120
    { SPECIES_FARFETCHD, { 52, 65, 55, 60, 58, 62 } }, // atk 65->90
    { SPECIES_DODRIO, { 60, 110, 70, 100, 60, 60 } }, // spe 100->110
    { SPECIES_ELECTRODE, { 60, 50, 70, 140, 80, 80 } }, // spe 140->150
    { SPECIES_EXEGGUTOR, { 95, 95, 85, 55, 125, 65 } }, // spd 65->75
    { SPECIES_NOCTOWL, { 100, 50, 50, 70, 76, 96 } }, // spa 76->86
    { SPECIES_ARIADOS, { 70, 90, 70, 40, 60, 60 } }, // spd 60->70
    { SPECIES_AMPHAROS, { 90, 75, 75, 55, 115, 90 } }, // def 75->85
    { SPECIES_BELLOSSOM, { 75, 80, 85, 50, 90, 100 } }, // def 85->95
    { SPECIES_AZUMARILL, { 100, 50, 80, 50, 50, 80 } }, // spa 50->60
    { SPECIES_JUMPLUFF, { 75, 55, 70, 110, 55, 85 } }, // spd 85->95
    { SPECIES_QWILFISH, { 65, 95, 75, 85, 55, 55 } }, // def 75->85
    { SPECIES_MAGCARGO, { 50, 50, 120, 30, 80, 80 } }, // hp 50->60, spa 80->90
    { SPECIES_CORSOLA, { 55, 55, 85, 35, 65, 85 } }, // hp 55->65, def 85->95, spd 85->95
    { SPECIES_MANTINE, { 65, 40, 70, 70, 80, 140 } }, // hp 65->85
    { SPECIES_BEAUTIFLY, { 60, 70, 50, 65, 90, 50 } }, // spa 90->100
    { SPECIES_SWELLOW, { 60, 85, 60, 125, 50, 50 } }, // spa 50->75
    { SPECIES_PELIPPER, { 60, 50, 100, 65, 85, 70 } }, // spa 85->95
    { SPECIES_MASQUERAIN, { 70, 60, 62, 60, 80, 82 } }, // spe 60->80, spa 80->100
    { SPECIES_EXPLOUD, { 104, 91, 63, 68, 91, 63 } }, // spd 63->73
    { SPECIES_DELCATTY, { 70, 65, 65, 70, 55, 55 } }, // spe 70->90
    { SPECIES_VOLBEAT, { 65, 73, 55, 85, 47, 75 } }, // def 55->75, spd 75->85
    { SPECIES_ILLUMISE, { 65, 47, 55, 85, 73, 75 } }, // def 55->75, spd 75->85
    { SPECIES_LUNATONE, { 70, 55, 65, 70, 95, 85 } }, // hp 70->90
    { SPECIES_SOLROCK, { 70, 95, 85, 70, 55, 65 } }, // hp 70->90
    { SPECIES_CHIMECHO, { 65, 50, 70, 65, 95, 80 } }, // hp 65->75, def 70->80, spd 80->90
    { SPECIES_STARAPTOR, { 85, 120, 70, 100, 50, 50 } }, // spd 50->60
    { SPECIES_ROSERADE, { 60, 70, 55, 90, 125, 105 } }, // def 55->65
    { SPECIES_CRESSELIA, { 120, 70, 120, 85, 75, 130 } }, // def 120->110, spd 130->120
    { SPECIES_STOUTLAND, { 85, 100, 90, 80, 45, 90 } }, // atk 100->110
    { SPECIES_UNFEZANT, { 80, 105, 80, 93, 65, 55 } }, // atk 105->115
    { SPECIES_GIGALITH, { 85, 135, 130, 25, 60, 70 } }, // spd 70->80
    { SPECIES_WOOBAT, { 55, 45, 43, 72, 55, 43 } }, // hp 55->65
    { SPECIES_SEISMITOAD, { 105, 85, 75, 74, 85, 75 } }, // atk 85->95
    { SPECIES_LEAVANNY, { 75, 103, 80, 92, 70, 70 } }, // spd 70->80
    { SPECIES_SCOLIPEDE, { 60, 90, 89, 112, 55, 69 } }, // atk 90->100
    { SPECIES_KROOKODILE, { 95, 117, 70, 92, 65, 70 } }, // def 70->80
    { SPECIES_CRUSTLE, { 70, 95, 125, 45, 65, 75 } }, // atk 95->105
    { SPECIES_BEARTIC, { 95, 110, 80, 50, 70, 80 } }, // atk 110->130
    { SPECIES_CRYOGONAL, { 70, 50, 30, 105, 95, 135 } }, // hp 70->80, def 30->50
    { SPECIES_AEGISLASH_SHIELD, { 60, 50, 150, 60, 50, 150 } }, // def 150->140, spd 150->140
    { SPECIES_ZACIAN_HERO, { 92, 130, 115, 138, 80, 115 } }, // atk 130->120
    { SPECIES_ZAMAZENTA_HERO, { 92, 130, 115, 138, 80, 115 } }, // atk 130->120
    { SPECIES_ALAKAZAM_MEGA, { 55, 50, 65, 150, 175, 95 } }, // spd 95->105
    { SPECIES_AEGISLASH_BLADE, { 60, 150, 50, 60, 150, 50 } }, // atk 150->140, spa 150->140
    { SPECIES_ZACIAN_CROWNED, { 92, 170, 115, 148, 80, 115 } }, // atk 170->150
    { SPECIES_ZAMAZENTA_CROWNED, { 92, 130, 145, 128, 80, 145 } }, // atk 130->120, def 145->140, spd 145->140
    { SPECIES_BUTTERFREE_GMAX, { 60, 45, 50, 70, 80, 80 } }, // spa 80->90
    { SPECIES_PIKACHU_GMAX, { 35, 55, 30, 90, 50, 40 } }, // def 30->40, spd 40->50
};
