// Generated by pentara/tools/world.py: Pentara Guide entries.

static const u16 sGuideSpecies_SproutHollow[] = {SPECIES_NONE};
static const u16 sGuideSpecies_MeadowLane[] = {SPECIES_PIDGEY, SPECIES_SENTRET, SPECIES_RATTATA, SPECIES_HOOTHOOT, SPECIES_CATERPIE, SPECIES_WEEDLE, SPECIES_HOPPIP, SPECIES_PICHU, SPECIES_IGGLYBUFF, SPECIES_NONE};
static const u16 sGuideSpecies_Brambleton[] = {SPECIES_NONE};
static const u16 sGuideSpecies_Whisperwood[] = {SPECIES_CATERPIE, SPECIES_WEEDLE, SPECIES_ODDISH, SPECIES_SPINARAK, SPECIES_LEDYBA, SPECIES_PARAS, SPECIES_METAPOD, SPECIES_KAKUNA, SPECIES_PIKACHU, SPECIES_PINECO, SPECIES_SCYTHER, SPECIES_PINSIR, SPECIES_NONE};
static const u16 sGuideSpecies_OldMillRoad[] = {SPECIES_SPEAROW, SPECIES_NIDORAN_F, SPECIES_NIDORAN_M, SPECIES_MAREEP, SPECIES_EKANS, SPECIES_SANDSHREW, SPECIES_PONYTA, SPECIES_DODUO, SPECIES_GROWLITHE, SPECIES_SUNKERN, SPECIES_SNUBBULL, SPECIES_GIRAFARIG, SPECIES_NONE};
static const u16 sGuideSpecies_Cobblecross[] = {SPECIES_NONE};

static const struct PentaraGuideEntry sPentaraGuide[] =
{
    {.region = 1, .mapsec = MAPSEC_SPROUT_HOLLOW, .name = COMPOUND_STRING("SPROUT HOLLOW"), .species = sGuideSpecies_SproutHollow, .minLevel = 0, .maxLevel = 0, .habitat = COMPOUND_STRING("-"), .items = NULL, .legends = NULL},
    {.region = 1, .mapsec = MAPSEC_MEADOW_LANE, .name = COMPOUND_STRING("MEADOW LANE"), .species = sGuideSpecies_MeadowLane, .minLevel = 3, .maxLevel = 6, .habitat = COMPOUND_STRING("Grass"), .items = COMPOUND_STRING("Found here: Potion, Poké\n" "Ball"), .legends = NULL},
    {.region = 1, .mapsec = MAPSEC_BRAMBLETON, .name = COMPOUND_STRING("BRAMBLETON"), .species = sGuideSpecies_Brambleton, .minLevel = 0, .maxLevel = 0, .habitat = COMPOUND_STRING("-"), .items = COMPOUND_STRING("Mart:\n" "Poké Ball, Great Ball,\n" "Potion, Antidote, Paralyze\n" "Heal, Awakening, Repel,\n" "Escape Rope\n" "TM01 Protect, TM02 Rest,\n" "TM16 Flame Charge, TM15\n" "Water Pulse, TM17 Magical\n" "Leaf, TM21 Aerial Ace, TM20\n" "Rock Tomb, TM25 Bug Bite"), .legends = NULL},
    {.region = 1, .mapsec = MAPSEC_WHISPERWOOD, .name = COMPOUND_STRING("WHISPERWOOD"), .species = sGuideSpecies_Whisperwood, .minLevel = 7, .maxLevel = 10, .habitat = COMPOUND_STRING("Grass"), .items = COMPOUND_STRING("Found here: Antidote,\n" "Miracle Seed"), .legends = NULL},
    {.region = 1, .mapsec = MAPSEC_OLD_MILL_ROAD, .name = COMPOUND_STRING("OLD MILL ROAD"), .species = sGuideSpecies_OldMillRoad, .minLevel = 8, .maxLevel = 10, .habitat = COMPOUND_STRING("Grass"), .items = NULL, .legends = NULL},
    {.region = 1, .mapsec = MAPSEC_COBBLECROSS, .name = COMPOUND_STRING("COBBLECROSS"), .species = sGuideSpecies_Cobblecross, .minLevel = 0, .maxLevel = 0, .habitat = COMPOUND_STRING("-"), .items = COMPOUND_STRING("Mart:\n" "Poké Ball, Great Ball,\n" "Master Ball, Potion, Super\n" "Potion, Full Heal, Repel,\n" "Escape Rope, Fire Stone,\n" "Water Stone, Thunder Stone,\n" "Leaf Stone, Moon Stone\n" "TM01 Protect, TM02 Rest,\n" "TM20 Rock Tomb, TM23\n" "Bulldoze, TM22 Brick Break,\n" "TM30 Metal Claw, TM10\n" "Sandstorm, TM08 Sunny Day,\n" "TM09 Rain Dance, TM12\n" "Swords Dance, TM13 Calm\n" "Mind, TM14 Bulk Up"), .legends = NULL},
};
