

DEXNAV_ENABLED                = false # Whether or not DexNav is enabled. If TRUE, flags/vars below must all be non-zero
USE_DEXNAV_SEARCH_LEVELS      = false


#  Flag/var defines
DN_FLAG_SEARCHING             = 0 # Searching for mon
DN_FLAG_DEXNAV_GET            = 0 # DexNav shows in start menu
DN_FLAG_DETECTOR_MODE         = 0 # Allow player to find hidden mons
DN_VAR_SPECIES                = 0 # Registered DexNav species
DN_VAR_STEP_COUNTER           = 0 # Steps for finding hidden pokemon


#  Search parameters
DEXNAV_TIMEOUT                  = 15 # 15 seconds is the time out. Max of 1092 seconds allowed
SNEAKING_PROXIMITY              = 4 # Tile amount
CREEPING_PROXIMITY              = 2
MAX_PROXIMITY                   = 20


DEXNAV_CHAIN_MAX                = 100 # maximum chain value


#  hidden pokemon options - an approximation of values due to lack of available data
HIDDEN_MON_STEP_COUNT       = 100 # Look for hidden pokemon every x steps
HIDDEN_MON_SEARCH_RATE      = 25 # x% chance of finding hidden pokemon every x steps
HIDDEN_MON_PROBABILTY       = 15 # x% chance of finding hidden mon compared to regular encounter data


# // SEARCH PROBABILITIES
#  See https://bulbapedia.bulbagarden.net/wiki/DexNav#Benefits
#  Chance of encountering egg move at search levels
SEARCHLEVEL0_MOVECHANCE         = 0
SEARCHLEVEL5_MOVECHANCE         = 21
SEARCHLEVEL10_MOVECHANCE        = 46
SEARCHLEVEL25_MOVECHANCE        = 58
SEARCHLEVEL50_MOVECHANCE        = 63
SEARCHLEVEL100_MOVECHANCE       = 83
#  Chance of encountering Hidden Abilities at search levels
SEARCHLEVEL0_ABILITYCHANCE      = 0
SEARCHLEVEL5_ABILITYCHANCE      = 0
SEARCHLEVEL10_ABILITYCHANCE     = 5
SEARCHLEVEL25_ABILITYCHANCE     = 15
SEARCHLEVEL50_ABILITYCHANCE     = 20
SEARCHLEVEL100_ABILITYCHANCE    = 23
#  Chance of encountering held item
SEARCHLEVEL0_ITEM               = 0
SEARCHLEVEL5_ITEM               = 0
SEARCHLEVEL10_ITEM              = 1
SEARCHLEVEL25_ITEM              = 7
SEARCHLEVEL50_ITEM              = 6
SEARCHLEVEL100_ITEM             = 12
#  Chance of encountering one star potential
SEARCHLEVEL0_ONESTAR            = 0
SEARCHLEVEL5_ONESTAR            = 14
SEARCHLEVEL10_ONESTAR           = 17
SEARCHLEVEL25_ONESTAR           = 17
SEARCHLEVEL50_ONESTAR           = 15
SEARCHLEVEL100_ONESTAR          = 8
#  Chance of encountering two star potential
SEARCHLEVEL0_TWOSTAR            = 0
SEARCHLEVEL5_TWOSTAR            = 1
SEARCHLEVEL10_TWOSTAR           = 9
SEARCHLEVEL25_TWOSTAR           = 16
SEARCHLEVEL50_TWOSTAR           = 17
SEARCHLEVEL100_TWOSTAR          = 24
#  Chance of encountering three star potential
SEARCHLEVEL0_THREESTAR          = 0
SEARCHLEVEL5_THREESTAR          = 0
SEARCHLEVEL10_THREESTAR         = 1
SEARCHLEVEL25_THREESTAR         = 7
SEARCHLEVEL50_THREESTAR         = 6
SEARCHLEVEL100_THREESTAR        = 12


