

#  In the Generation 3 games, Asserts were used in various debug builds.
#  Ruby/Sapphire and Emerald do not have these asserts while Fire Red
#  still has them in the ROM. This is because the developers forgot
#  to define NDEBUG before release, however this has been changed as
#  Ruby's actual debug build does not use the AGBPrint features.
//

#  Use `make release` to automatically enable NDEBUG.
#ifdef RELEASE

#define NDEBUG

#endif



#  printf debugging is now enabled by default. This allows
#  the various AGBPrint functions to be used. (See include/gba/isagbprint.h).
#  See below for enabling different pretty printing versions.
#  To disable printf debugging, build a release build using `make release`.


#ifndef NDEBUG



#define PRETTY_PRINT_MINI_PRINTF (0)

#define PRETTY_PRINT_LIBC (1)



#define LOG_HANDLER_AGB_PRINT (0)

#define LOG_HANDLER_NOCASH_PRINT (1)

#define LOG_HANDLER_MGBA_PRINT (2)



#  Use this switch to choose a handler for pretty printing.
#  NOTE: mini_printf supports a custom pretty printing formatter to display preproc encoded strings. (%S)
#        some libc distributions (especially dkp arm-libc) will fail to link pretty printing.
#define PRETTY_PRINT_HANDLER (PRETTY_PRINT_MINI_PRINTF)



#  Use this switch to choose a handler for printf output.
#  NOTE: These will only work on the respective emulators and should not be used in a productive environment.
#        Some emulators or real hardware might (and is allowed to) crash if they are used.
#        AGB_PRINT is supported on respective debug units.


#define LOG_HANDLER (LOG_HANDLER_MGBA_PRINT)

#endif



#  Uncomment to fix some identified minor bugs
#define BUGFIX



#  Various undefined behavior bugs may or may not prevent compilation with
#  newer compilers. So always fix them when using a modern compiler.
#if MODERN || defined(BUGFIX)

#ifndef UBFIX

#define UBFIX

#endif

#endif



#  Compatibility definition for other projects to detect pokeemerald-expansion
#define RHH_EXPANSION



#  Legacy branch-based defines included for backwards compatibility
#define BATTLE_ENGINE

#define POKEMON_EXPANSION

#define ITEM_EXPANSION



#  Generation constants used in configs to define behavior.
GEN_1 = 0
GEN_2 = 1
GEN_3 = 2
GEN_4 = 3
GEN_5 = 4
GEN_6 = 5
GEN_7 = 6
GEN_8 = 7
GEN_9 = 8
#  Changing GEN_LATEST's value to a different Generation will change every default setting that uses it at once.
GEN_LATEST = "GEN_9"


#  General settings
EXPANSION_INTRO              = true # If TRUE, a custom RHH intro will play after the vanilla copyright screen.
HQ_RANDOM                    = true # If TRUE, replaces the default RNG with an implementation of SFC32 RNG. May break code that relies on RNG.
AUTO_SCROLL_TEXT             = false # If TRUE, text will automatically scroll to the next line after NUM_FRAMES_AUTO_SCROLL_DELAY. Players can still press A_BUTTON or B_BUTTON to scroll on their own.
NUM_FRAMES_AUTO_SCROLL_DELAY = 49
PHONEMES_SHARED              = false # If TRUE, bard phonemes all reference the same sound (sound/direct_sound_samples/phonemes/shared.bin) to save ROM space.


#  Measurement system constants to be used for UNITS
UNITS_IMPERIAL               = 0 # Inches, feet, pounds
UNITS_METRIC                 = 1 # meters, kilograms


UNITS                        = "UNITS_IMPERIAL"
CHAR_DEC_SEPARATOR           = "CHAR_PERIOD" # CHAR_PERIOD is used as a decimal separator only in the UK and the US. The rest of the world uses CHAR_COMMA.


#  Naming Screen
AUTO_LOWERCASE_KEYBOARD      = "GEN_LATEST" # Starting in GEN_6, after entering the first uppercase character, the keyboard switches to lowercase letters.


