

#  Item config
I_SHINY_CHARM_ADDITIONAL_ROLLS  = 2 # Amount of additional shiny rolls if the player has the Shiny Charm. Set it to 0 to disable Shiny Charm's effects.
I_KEY_FOSSILS                   = "GEN_LATEST" # In Gen4+, all Gen 3 fossils became regular items.
I_KEY_ESCAPE_ROPE               = "GEN_LATEST" # In Gen8, Escape Rope became a Key Item. Keep in mind, this will make it free to buy in marts.
I_HEALTH_RECOVERY               = "GEN_LATEST" # In Gen7+, certain healing items recover a different amount of HP than they used to.
I_SITRUS_BERRY_HEAL             = "GEN_LATEST" # In Gen4+, Sitrus Berry was changed from healing 30 HP to healing 25% of Max HP.
I_VITAMIN_EV_CAP                = "GEN_LATEST" # In Gen8+, the Vitamins no longer have a cap of 100 EV per stat.
I_BERRY_EV_JUMP                 = "GEN_LATEST" # In Gen4 only, EV-lowering Berries lower a stat's EV to 100 if it is above 100.
I_GRISEOUS_ORB_FORM_CHANGE      = "GEN_LATEST" # In Gen9+, the Griseous Orb no longer changes Giratina's form when held.
I_GEM_BOOST_POWER               = "GEN_LATEST" # In Gen6+, the Gem boost power was reduced from 50% to 30%.
I_USE_EVO_HELD_ITEMS_FROM_BAG   = false # If TRUE, items such as Razor Claw or Electirizer will be usable from the bag to evolve a Pokémon just like in LA.
I_TYPE_BOOST_POWER              = "GEN_LATEST" # In Gen4+, all regular type boosting held items had their power increased from 10% to 20%. eg. Charcoal
I_SELL_VALUE_FRACTION           = "GEN_LATEST" # In Gen9+, items sell for 1/4 of their value instead of 1/2.
I_PRICE                         = "GEN_LATEST" # Some items have varied in value across generations.
I_BERRY_PRICE                   = "GEN_7" # Since Berries have become unplantable (Gen8+), their price has gone up.
I_POWER_ITEM_BOOST              = "GEN_LATEST" # In Gen7+, Power Items grant 8 EVs instead of 4 EVs.
I_PREMIER_BALL_BONUS            = "GEN_LATEST" # In LGPE onwards (Gen8+ here), you are given a Premier Ball for every 10 Poké Balls of any type and in the same purchase. Previously, it only applied to regular Poké Balls and only 1 could be obtained per purchase.
I_ROTOM_CATALOG_THUNDER_SHOCK   = "GEN_LATEST" # In Gen9+, reverting Rotom to its base form will teach it Thunder Shock even if it knows another move.
I_REPEL_INCLUDE_FAINTED         = "GEN_LATEST" # In Gen1 and Gen6+, Repels always use the level of the first member of the party to check which wild Pokémon to prevent encounters with, even if that member is fainted. In Gen2-5, it only uses the level of the first non-fainted Pokémon.


#  TM config
I_REUSABLE_TMS          = false # In Gen5-8, TMs are reusable. Setting this to TRUE will make all vanilla TMs reusable, though they can also be cherry-picked by setting their importance to 1.


#  Exp. Share config
#  To use this feature, replace the 0 with the flag ID you're assigning it to.
#  Eg: Replace with FLAG_UNUSED_0x264 so you can use that flag to toggle the feature.
I_EXP_SHARE_FLAG        = 0 # If this flag is set, every Pokémon in the party will gain experience, regardless if they participated in the battle or not.
I_EXP_SHARE_ITEM        = "GEN_5" # In Gen6+, the Exp. Share was changed from a held item to a Key item that toggles the effect described above.


#  Repel/Lure config
#  These two settings are both independent and complementary.
VAR_LAST_REPEL_LURE_USED    = 0 # If this var has been assigned, last Repel/Lure used will be saved and the player will get prompted with the vanilla repel YES/NO option, unless I_REPEL_LURE_MENU is set to TRUE.
I_REPEL_LURE_MENU           = true # If TRUE, the player is able to choose which Repel/Lure to use once the previous one runs out. Cursor position is saved by VAR_LAST_REPEL_LURE_USED if not 0.


#  Vs. Seeker
I_VS_SEEKER_CHARGING        = 0 # If this flag is assigned, the Vs Seeker functionality will be enabled. When the player has the Vs. Seeker, Match Call rematch functions will stop working.


#  ORAS Dowsing Machine
I_ORAS_DOWSING_FLAG         = 0 # Replace 0 with an unused flag to enable the Dowsing Machine mechanic from ORAS.
I_ORAS_DOWSING_SOUNDS       = true # If TRUE, the Dowsing Machine will make sounds based on how far away the hidden item is.
I_ORAS_DOWSING_COLOR_PAL    = 15 # The color within the palette that will change based on proximity to the item.
#  Color values for the ORAS dowsing distances/anims
I_ORAS_DOWSING_COLOR_NONE   = "RGB_GRAY"
I_ORAS_DOWSING_COLOR_SLOW   = "RGB2GBA"
I_ORAS_DOWSING_COLOR_NORMAL = "RGB2GBA"
I_ORAS_DOWSING_COLOR_FAST   = "RGB2GBA"
I_ORAS_DOWSING_COLOR_FASTER = "RGB_RED"


